### ISSUE TITLE
ArrayField with nested SingleFieldList broken in version 3.6.0

### ISSUE THREAD

**Issue by sebitoelcheater** [marmelab/react-admin#4916] opened 2020-06-08 15:49 UTC
**What you were expecting:**
`SingleFieldList` to work properly inside `ArrayField`, as in version 3.5.5.
```
<ArrayField source="statements">
  <SingleFieldList>
    <ChipField source="name"/>
  </SingleFieldList>
</ArrayField>
```

**What happened instead:**
It throws
```
TypeError: Cannot read property 'map' of undefined
```

**Steps to reproduce:**
Visit `list` in any resource view with `List` component containing `ArrayField` with a nested `SingleFieldList`:
```
<ArrayField source="statements">
  <SingleFieldList>
    <ChipField source="name"/>
  </SingleFieldList>
</ArrayField>
```

**Related code:**
```
export const CompanyList = props => (
  <List {...props}>
    <Datagrid rowClick="edit">
      <ArrayField source="statements">
        <SingleFieldList>
          <ChipField source="name"/>
        </SingleFieldList>
      </ArrayField>
    </Datagrid>
  </List>
);
```

**Other information:**
[This PR](https://github.com/marmelab/react-admin/pull/4536) seems to be causing the error.

**Environment**

* React-admin version: 3.6.0
* Last version that did not exhibit the issue (if applicable): 3.5.5
* React version: ^16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error): TypeError: Cannot read property 'map' of undefined

**Comment by djhi** [comment] 2020-06-09 06:29
Fixed by #4918

**Closed by djhi** 2020-06-09 06:29 UTC

**Comment by DeciusAntiochus** [comment] 2020-06-11 14:38
Just had the same issue since I went on the 3.6.0 version, but with different error

```
Uncaught TypeError: Cannot read property 'map' of undefined
    at SingleFieldList (0.chunk.js:138755)
```

My list component:
```
export const AbonnementList = (props) => (
  <List {...props} filters={<FullFilter />}>
    <Datagrid rowClick='edit'>
      <TextField source='id' />
      <TextField source='name' />
      <TextField source='price' />
      <TextField label='Période de facturation' source='pricePeriod' />
      <TextField label="Période d'octroi des crédits" source='offeredPeriod' />

      <ArrayField source='descriptions'>
        <SingleFieldList linkType={false}>
          <TextField source='description'></TextField>
        </SingleFieldList>
      </ArrayField>
      <EditButton />
    </Datagrid>
  </List>
);```

And of course, the fix proposed in the PR didn't work.

**Comment by fzaninotto** [comment] 2020-06-11 16:15
@DeciusAntiochus I can't reproduce the problem you describe. Please provide a CodeSandbox reproducing your error, and open a new issue with its link.
