### ISSUE TITLE
Page number out of boundaries

### ISSUE THREAD

**Issue by vdieulesaint** [marmelab/react-admin#2366] opened 2018-09-28 08:38 UTC
react-admin : 2.3.2

Steps to reproduce :
1. Go to https://marmelab.com/react-admin-demo/#/customers
2. Change "Rows per page" to 10
3. Select Page "90"
4. Change "Rows per page" to 25

You will get "The page number 90 is out of boundaries"

Playing with pagination size should also reset the page number.

**Comment by fzaninotto** [comment] 2018-10-01 06:42
Duplicate of #2350

**Closed by fzaninotto** 2018-10-01 06:42 UTC
Labels: Hacktoberfest, bug, good first issue
