### ISSUE TITLE
Is there any breaking changes blocking Material UI upgrade?

### ISSUE THREAD

**Issue by adamlukaszczyk** [marmelab/react-admin#2437] opened 2018-10-16 10:28 UTC
Current version of Material UI points to 3.2.2 and React-admin use 1.4.0 at the moment
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/package.json#L44

I've did a really quick test of upgrading and looks promising.

Is there a reason why it is not upgraded along new versions of React-admin?

**Comment by djhi** [comment] 2018-10-16 11:14
Duplicate of #2399

**Closed** 2018-10-16 11:15 UTC
