### ISSUE TITLE
FormWithRedirect with custom mutators stops working after v3.13.2

### ISSUE THREAD

**Issue by Vgor07** [marmelab/react-admin#6057] opened 2021-03-18 13:02 UTC
After upgrading to v3.13.2 I am getting the following error

```
TypeError: form.mutators.resetSubmitErrors is not a function

    in ReactFinalForm (created by FormWithRedirect)
    in FormContextProvider (created by FormWithRedirect)
    in FormWithRedirect
```
The error is caused by FormWithRedirect where I am using custom mutators. I believe that there was a change introduced in 3.13.2 which is causing these issues.

**Comment by fzaninotto** [comment] 2021-03-18 13:27
Duplicate of #6049

**Closed by fzaninotto** 2021-03-18 13:27 UTC
