### ISSUE TITLE
[SimpleFormIterator] Support default fields value when click add button

### ISSUE THREAD

**Issue by scq000** [marmelab/react-admin#3590] opened 2019-08-23 06:38 UTC
I have the following code:
```
{
  id: 123
  backlinks: [
        {
            date: '2012-08-10T00:00:00.000Z',
            url: 'http://example.com/foo/bar.html',
        },
        {
            date: '2012-08-14T00:00:00.000Z',
            url: 'https://blog.johndoe.com/2012/08/12/foobar.html',
        }
   ]
}
```

```
import { ArrayInput, SimpleFormIterator, DateInput, TextInput } from 'react-admin';

<ArrayInput source="backlinks">
    <SimpleFormIterator>
        <DateInput source="date" />
        <TextInput source="url" />
    </SimpleFormIterator>
</ArrayInput>
```

![image](https://user-images.githubusercontent.com/12999391/63571480-e9456300-c5b2-11e9-988f-158085427ab3.png)

When I click add button, a new record will be rendered in the `Backlinks` field, but the default value is undefined. After clicking the add button, the data structure will be like this:
```
{
  id: 123
  backlinks: [
        {
            date: '2012-08-10T00:00:00.000Z',
            url: 'http://example.com/foo/bar.html',
        },
        {
            date: '2012-08-14T00:00:00.000Z',
            url: 'https://blog.johndoe.com/2012/08/12/foobar.html',
        },
       {}
   ]
}
```
But I would like to set the default value when I click the add button.

**Comment by djhi** [comment] 2019-08-23 07:32
Duplicate of #2489.
Also, please follow the issue template

**Closed by djhi** 2019-08-23 07:32 UTC
