### ISSUE TITLE
3.0.0-beta.5: AutocompleteInput and allowEmpty issue

### ISSUE THREAD

**Issue by MiMo42** [marmelab/react-admin#3920] opened 2019-11-03 17:03 UTC
**What you were expecting:**
AutocompleteInput shows suggestion for empty value to clear a current selection.

**What happened instead:**
The empty value suggestion item is shown if there is no matching value selected yet. Thats OK.
But:
If a matching value _is_ selected, there is no empty suggestion item in list of suggestions.
So you can't change selection from previously selected value back to null (empty).

**Steps to reproduce:**
AutocompleteInput with allowEmpty set

**Related code:**
see useSuggestion hook: In getSuggestionsFactory the emptySuggestion is _not_ added when limiting choices because of a currently selected item.
An emptySuggestion item will only be added to list of suggestions if no item has been selected yet.
This is why you cannot clear a current selection.

BTW: it would be more intuitive if the emptySelection would be inserted on top. 
Currently the emptySelection item is appended and you have to scroll to reach it.

And: Clearing out the input field manually (backspace) and pressing Enter performs nothing although allowEmpty should cause a cleared input to select the matching emptySuggestion.

**Environment**

* React-admin version: 3.0.0-beta.5
* React version: 16.10
* Browser: Chrome

**Comment by Kmaschta** [comment] 2019-11-04 14:35
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by Kon0pelka** [comment] 2019-11-05 07:23
In my case it looks like this.
`https://codesandbox.io/s/simple-vc7gl`
There is an empty field:
![image](https://user-images.githubusercontent.com/22622216/68186580-84948480-ffb5-11e9-83a6-6f9f68a108ff.png)
But after selection the empty field disappears:
![image](https://user-images.githubusercontent.com/22622216/68186835-1f8d5e80-ffb6-11e9-83b6-eb62605f4a2b.png)

**Comment by Kon0pelka** [comment] 2019-11-05 07:28
oh I accidentally repeated question #3909

**Comment by MiMo42** [comment] 2019-11-05 10:19
https://codesandbox.io/s/simple-rzpk0?fontsize=14
EditComment: I just added allowEmpty to ReferenceInput for post_id for demonstration purpose.
->No empty item is added to list of matches
I described the reason for that in my original post.

**Comment by Kmaschta** [comment] 2019-11-07 09:02
Confirmed, thanks for reporting!

**Comment by fzaninotto** [comment] 2019-11-08 13:17
Fixed by #3953

**Closed by fzaninotto** 2019-11-08 13:17 UTC
Labels: bug, v3-beta

**Comment by MoonSeeing** [comment] 2019-11-11 03:16
> Fixed by #3953

this fix did not publish in beta.6?

**Comment by MoonSeeing** [comment] 2019-11-13 08:25
@fzaninotto this fix did not publish in beta.6?it seem did not on effect on beta.6

**Comment by fzaninotto** [comment] 2019-11-14 09:53
!yes it did, but you must set the `allowEmpty` prop on the `ReferenceInput`, not the `AutocompleteInput`.
