### ISSUE TITLE
Dynamic Theme colour/file isn't being used in Create/Show/Edit for Resource that has a Custom Layout (while be correct for Listing page).

### ISSUE THREAD

**Issue by cordial** [marmelab/react-admin#6225] opened 2021-04-29 21:21 UTC
**What you were expecting:**
When you dynamically pick a theme object in a custom layout based on the URL/history in react-admin resource, the correct theme is only used on the list page. 

**What happened instead:**
When you go to the resource listing page, the correct theme is used. But when you then navigate to any of the create/show or edit pages, the theme seems to default back to the base / primary one. 

**Steps to reproduce:**
1. Create Custom Layout file. Overwrite the Appbar and List component (with Listbase) with custom ones too. Although I'm not sure the appbar/listbase steps are necessary. 
2. Use the custom Layout in the Admin component.
3. Create some resources. 
4. Dynamically pick a theme based on the name of the Resouce (using history).
5. Navigate to the listing page of the resources. They display the specific theme correctly. 
6. Navigate to the create/show/edit pages of the resources. These, for some reason, default back to the primary theme (or primary default colours). 

**Related code:**

At the root level code..
```
<Admin
      authProvider={AuthProvider({ awsConfig })}
      dashboard={Dashboard}
      dataProvider={graphQLProvider}
      history={history}
      layout={Layout}
      title="Home"
      loginPage={CustomLogin}
     // logoutButton={LogoutButton}
    >
 <LMSResource projection={["details"]} name="Assigment" options={{label: 'Assignments'}} create={AssignmentCreate} list={AssignmentList}
                   title="Generic" show={AssignmentShow} edit={AssignmentEdit} icon={AssignmentIcon}/>
```

In the custom Layout file (I have an array of themes to choose from that is imported from another file)

```
const Layout = ({
    children,
    dashboard,
    logout,
}) => {
    const [resource, setResource] = useState('');
    const history = useHistory();
    useEffect(() => {
          const newResource = history.location.pathname.replace(/^\/|\/$/g, '').toLowerCase(); 
          if(newResource===''){
             setResource('primary');
          } else if (newResource !== resource) {
              setResource(newResource);
          }
    }, [history.location.pathname]);

    function getTheme(themes){
        let result = ''
        var i=0;

        for(i = 0; i < themes.length; i++){
            if(Object.keys(themes[i])[0] === resource){
                result = themes[i][resource];
            }
        }
        return (!result ? themes[0].primary : result );
    }

    const theme = createMuiTheme(getTheme(themes));
    const useStyles = makeStyles(() => ({
  ...
    }));

    const classes = useStyles(theme);
    const dispatch = useDispatch();
    const open = useSelector(state => state.admin.ui.sidebarOpen);

    return (
        <ThemeProvider theme={theme}>
            <CssBaseline /> 
            <Grid container>
                <Box className={classes.sidebar} color="grey.200" borderRight={1} item md={3} lg={2} component={Grid} display={{ xs: 'none', md: 'block' }}>
                    <Grid>
                         <Logo/>
                         <SchoolText  color='textPrimary'/>
                    </Grid>
                    <TextField className={[classes.search,classes['search' + resource]]} id="outlined-basic" label="Search" variant="outlined" />
                    <Sidebar open={open} className={classes.sidebar}>               
                        <Menu logout={logout} hasDashboard={!!dashboard} />
                    </Sidebar>

                </Box>
                <Box item component={Grid} xs={12} md={9} lg={10}>
                   <AppBar title={resource} logout={logout} />
                   <Box component={Grid} className={classes.breadcrumb} display={{ xs: 'none', md: 'block' }} borderTop={1}>
                       <Breadcrumbs/>
                   </Box>
                   <main>    
                    <div className={classes.content}>
                        {children}
                    </div>
                    </main>
                </Box>    
                <Notification />
            </Grid>
        </ThemeProvider>
    );
}; export default Layout
```

I can post the List, Show, Create and Edit components if necessary, but I presume if one of resource components is receiving the right theme variables, then they all should?

**Environment**

* React-admin version: 3.7.1
* Last version that did not exhibit the issue (if applicable): n/a
* React version: 17.0.2
* Browser: all
* Stack trace (in case of a JS error): n/a

**Comment by fzaninotto** [comment] 2021-04-29 22:08
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have two options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.

If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Closed by fzaninotto** 2021-04-29 22:08 UTC

**Comment by cordial** [comment] 2021-04-29 22:35
Perhaps I haven't explained myself correctly, because I think this is possibly a bug (admittedly I may be wrong). 

You have a custom Layout component. This provides the components for which the List View, Edit, Create and Show sit in i.e. a custom appbar, sidebar and menu. I have provided the custom Layout component with an individual theme which is specific to each Resource component. In the list view, this theme is used correctly. In the Edit, Create and Show views it is not. 

To be clear, I mean the layout colours outside of the List, Edit, Create and Show components and in the actual Layout components i.e. the appbar background is the wrong colour, as is the sidebar etc. So how can they be right for List but wrong for Edit, Create and Show pages when it uses the same layout component for each in the resource? I don't think I have any way of controlling this?

**Comment by cordial** [comment] 2021-04-30 00:32
Regexs. tsk.

**Comment by fzaninotto** [comment] 2021-04-30 07:07
Changing the layout depending on the view isn't a feature that react-admin provides. So there might be a bug that prevents it, but we won't spend time looking into it. We can't troubleshoot every possible use case. 

I doubt that the problem is on the react-admin side, though. The Edit view does nothing special with the theme. 

If you happen to discover the cause and find a fix, we'll gladly accept a PR.

**Comment by cordial** [comment] 2021-04-30 23:05
Sorry, was an issue in the regex above

          const newResource = history.location.pathname.replace(/^\/|\/$/g, '').toLowerCase(); 

List has a different url structure than Create, Show, Edit...
