### ISSUE TITLE
ChipField inside a ReferenceField shows as empty when the source value is 'undefined'

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2694] opened 2018-12-23 19:54 UTC
**What you were expecting:**

`<ChipField />` to show nothing

**What happened instead:**

![image](https://user-images.githubusercontent.com/7850073/50387087-247a5400-06fd-11e9-80bf-04b3da0e4261.png)

**Steps to reproduce:**

See code below (Note: `groupId` comes from the data provider as `undefined` in the record)

**Related code:**

```
<ReferenceField
        label="Restaurant Group"
        source="groupId"
        reference="restaurantGroups"
        allowEmpty
      >
        <ChipField
          linkType="show"
          source="name"
          style={{cursor: 'pointer'}}
        />
      </ReferenceField>
```

P.S. Irrelevant to this issue but I had to use `style={{cursor: 'pointer'}}` in order for the link to show a pointer. Shouldn't this be automatic?

**Other information:**

**Environment**

* React-admin version: 2.5.1

**Comment by pftsao** [comment] 2018-12-24 11:46
This has nothing to do with ReferenceField. It is just the designed behavior of ChipField.
You can write a component to achieve your goals:
`const MyChip =  ({record,source, ...props})=>(record && (record[source]!==undefined)?<ChipField {...{record, source, ...props}}:null)`

**Comment by pftsao** [comment] 2018-12-24 12:19
For the 'pointer' matter:
It is also the designed behavior of Chip.
There are several kinds of Chip. The ChipField itself do not know it's in a link or not. 
You may need a 'clickable' attribute:
`const MyChip = ({record,source, ...props})=>(record && (record[source]!==undefined)?<ChipField clickable {...{record, source, ...props}}:null)`

**Comment by afilp** [comment] 2018-12-24 22:52
@pftsao Thanks for your tip, this is exactly what I did to circumvent the problem. But I think a custom component should not be the case for `undefined`. This should be taken care by the `ChipField` itself.

In other fields, `undefined` shows nothing (like in `<TextField />`).

I saw the code and we could do the condition there:

```
export const ChipField = ({
    className,
    classes = {},
    source,
    record = {},
    ...rest
}) => {
    return (
        <Chip
            className={classnames(classes.chip, className)}
            label={get(record, source)}
            {...sanitizeRestProps(rest)}
        />
    );
};
```

If we do not want this to be default, we could add a new prop, called `allowEmpty`, with default being `true`, so that the behavior is exactly as before. And we could add `allowEmpty={false}` if we want the behavior that me and @zohaib-zix wants (and I believe others too). The behavior being no `chipField` apeearing at all.

What do you all think?

**Comment by pftsao** [comment] 2018-12-25 10:01
Hi. In fact a TextField do shows something when it is 'undefined'. Incidently what it shows is invisible with the default styles.  If someone puts a grey border with his TextField, he will get a similar 'undefined' Text as Chip.

I think the real problem is the RefferenceField wraps a  '~~/undefined' link to the 'undefined' Chip. In most cases we do not want that link, but I do not know how to prevent RefferenceField to do this.

**Comment by mnlbox** [comment] 2019-02-20 10:11
@fzaninotto, @djhi Guys I have same problem. Any plan to fix this?

**Comment by djhi** [comment] 2019-02-20 11:01
> In most cases we do not want that link, but I do not know how to prevent ReferenceField to do this.

Not sure I understand but if you don't want a link, follow the [documentation](https://marmelab.com/react-admin/Fields.html#referencefield):

> You can also prevent `<ReferenceField>` from adding link to children by setting `linkType` to `false`.

**Comment by mnlbox** [comment] 2019-02-20 11:41
@djhi I set `linkType={false}` but still it render empty `ChipField` rather than nothing.

**Comment by fzaninotto** [comment] 2020-10-14 21:03
Cannot reproduce on master anymore, closing.

**Closed by fzaninotto** 2020-10-14 21:03 UTC
Labels: enhancement
