### ISSUE TITLE
Table Pagination is not working for Datagrid inside List component

### ISSUE THREAD

**Issue by manisuec** [marmelab/react-admin#4206] opened 2019-12-24 05:49 UTC
Expected behaviour: Pagination to work seamlessly. Choosing different values for rows per page like 5, 10, 25 etc. should work as expected. 

Current Behaviour: The list view is displaying all the records despite pagination enabled. Changing value of rows per page has no effect.

Steps to reproduce: Create a List view with Datagrid and pagination enabled. Add some records and play with different values of rows per page.

```
<List
				{...props}
				filters={<BoMFilter />}
				filter={{ projectId }}
				sort={{ field: 'id', order: 'ASC' }}
				basePath="/bomitems"
				resource="bomitems"
				bulkActionButtons={false}
				exporter={false}
				actions={<BoMActions projectId={projectId} location={location} />}
				perPage={25}
			>
				<Datagrid>
					<TextField source="name" label={'Name'} />
					<TextField source="description" label={'BoM Item'} />
					<TextField source="brand" label={'Brand'} />
					{permissions === 'admin' ? <EditButton /> : null}
					<CloneButton />
				</Datagrid>
			</List>
```
**Environment**

* React-admin version: 3.1.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Chrome/Opera
* Stack trace (in case of a JS error):

**Comment by ThieryMichel** [comment] 2020-01-02 14:31
Could not reproduce even when adding a permanent filter like in your snippet.
Please add more information, or even better add a codesandbox link.

**Comment by fzaninotto** [comment] 2020-01-20 20:50
No news for some time, closing. If you give us a way to reproduce the problem, we'll reopen the issue.

**Closed by fzaninotto** 2020-01-20 20:50 UTC
Labels: needs more info

**Comment by mdawezkhan3** [comment] 2020-11-20 04:22
Do we have to make changes in backend code also for pagination to work ?
