### ISSUE TITLE
Material UI 4.12.1 warnings

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#6451] opened 2021-07-20 14:12 UTC
**What you were expecting:**
No warnings

**What happened instead:**
Receive the following warnings after upgrading to MUI 4.12.1

- Warning: Failed prop type: The prop `onExited` of `ForwardRef(Snackbar)` is deprecated. Use the `TransitionProps` prop instead.
  - This warning is triggered by Notification.tsx
- Warning: Failed prop type: The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated. Use the `onPageChange` prop instead. -AND- Warning: Failed prop type: The prop `onChangeRowsPerPage` of `ForwardRef(TablePagination)` is deprecated. Use the `onRowsPerPageChange` prop instead.
  - This warning is triggered by Pagination.tsx

**Comment by fzaninotto** [comment] 2021-07-20 15:24
Hi, and thanks for the report. 

These are deprecation warnings that can be ignored as long as you don't use the next major version of material-ui, which is still in beta and has many, many breaking changes. So we're not in a hurry to fix them. We'll probably do that in the next major version of react-admin (v4, not yet started).

The second issue was already reported in https://github.com/marmelab/react-admin/issues/6421

**Comment by cprater** [comment] 2021-07-23 19:59
@fzaninotto Excuse my ignorance I've done a bit of googling and still found no answer. How are we able to ignore the deprecation warnings?

**Comment by herndlm** [comment] 2021-08-11 09:18
@fzaninotto would you consider accepting PRs fixing the deprecation warnings?

**Comment by fzaninotto** [comment] 2021-08-13 08:53
For the deprecation warning discussion, please comment on #6490

**Comment by fzaninotto** [comment] 2021-09-14 09:39
Note that this warning only occurs in development. The warning tells that that this feature will be removed in MUI 5.0. Version 5.0 has many breaking changes and is only in beta, and we don't intend to support before react-admin 4.x. In other words, we don't intend to care about MUI 5.x in react-admin 3.x

If they put a deprecation warning for all breaking changes in 4.x, it'll be hell to fix on our side.

As the peerDependency on material-ui is "^4.11.2", fixing this warning this implies that we bump the minimal mui version in our next minor (3.18)

**Comment by fzaninotto** [comment] 2021-09-14 12:58
The funny think is that there is no documentation for version 4.12...

https://material-ui.com/versions/

**Comment by davidhenley** [comment] 2021-09-14 20:28
> Note that this warning only occurs in development

Well that's where we do all our work and when we are looking at the console. They are piling up quickly and are very annoying to search through.

Do you have any suggestions for ignoring these?

> As the peerDependency on material-ui is "^4.11.2", fixing this warning this implies that we bump the minimal mui version in our next minor (3.18)

So are you saying that this will be fixed in 3.18.2?

**Comment by whg517** [comment] 2021-09-15 10:17
I hope this problem can be fixed as soon as possible, this annoying warning always makes it difficult for me to debug the program. If the Material-UI doesn't provide a good way to control it, I think react-admin should be able to control the version that uses dependencies, rather than having this problem exposed to the user.

**Comment by fzaninotto** [comment] 2021-09-15 10:55
If you don't want the warnings, downgrade the material-ui version you're using, or ask them to allow a global setting to turn the warnings off.

As for react-admin, the next version (3.19) will have these warnings cleared. Release schedules for early October.

**Comment by davidhenley** [comment] 2021-09-21 15:11
@fzaninotto Can you give instructions on how to downgrade the material-ui for those of us that only take on the dependency of react-admin??

```
"dependencies": {
    "react": "^17.0.2",
    "react-admin": "^3.18.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
  },
```

**Comment by fzaninotto** [comment] 2021-09-22 16:33
@davidhenley To force a sub-dependency, you have 2 ways:

1. add it as a direct dependency. normally, npm/yarn should deduplicate it, and force react-admin to use your version

```diff
"dependencies": {
    "react": "^17.0.2",
    "react-admin": "^3.18.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
+   "@material-ui/core": "^4.11.2"
  },
```

2. If you're using yarn, you can add a [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) entry to force a particular version:

```diff
"dependencies": {
    "react": "^17.0.2",
    "react-admin": "^3.18.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
},
+"resolutions": {
+   "@material-ui/core": "4.11.2"
+},
```

**Comment by davidhenley** [comment] 2021-09-22 17:12
@fzaninotto I added the first way, deleted node_modules and package.lock and still the same issues.

**Comment by herndlm** [comment] 2021-09-22 18:45
@davidhenley AFAIK you need to stay on 4.11.x to get rid of the warnings right now. As the caret ^ is allowing 4.12.x as well here, smth like `~4.11.0` should work.

**Comment by davidhenley** [comment] 2021-09-22 19:31
@herndlm hmm...that didn't seem to work. still getting the same errors:

```
"dependencies": {
    "react": "^17.0.2",
    "react-admin": "3.18.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "@material-ui/core": "~4.11.0",
    "@material-ui/icons": "^4.11.2",
  },
```

**Comment by whg517** [comment] 2021-09-23 02:10
@davidhenley 

I use `npm`. In my experience, first you need to check the dependent version of `@material-ui/core` in ` package-lock.json` . If not 4.11.2, uninstall and reinstall `npm i @material-ui/core@4.11.2` . And check `package-lock.json` again. If this still doesn't work, try deleting the `node_modules` directory and re-running 'npm install'. Only if the version in `package-lock.json` is confirmed can you confirm that you have installed version 4.11.2.

I know it's an annoying question, but it's the only thing I can do. Recently I saw that Material 5.0 has been released. I hope react-admin will follow suit soon.

Thanks to the community developers for their efforts.

**Comment by fzaninotto** [comment] 2021-09-23 08:27
Since react-admin 3.18 was published and removes these warnings, our fix for this problem is simply to upgrade to the latest react-admin version. 

You can avoid it if you know how to fork yarn/npm dependencies, but in that case it's your responsibility to do it.

**Comment by davidhenley** [comment] 2021-09-23 19:43
@fzaninotto Do you mean 3.19? The warnings are still there in 3.18.2

**Comment by davidhenley** [comment] 2021-09-23 19:45
@whg517 I did wipe node_modules and reinstalled as stated earlier. They are still there. Hopefully 3.19 will come out soon.

**Comment by fzaninotto** [comment] 2021-09-24 06:02
My bad, these warnings will go away in 3.19.

**Closed** 2021-10-04 09:03 UTC
Labels: bug
