### ISSUE TITLE
Page Not Rendered When Used Array Input

### ISSUE THREAD

**Issue by berviantoleo** [marmelab/react-admin#1767] opened 2018-04-22 14:20 UTC
**What you were expecting:**
The page completely rendered and show

**What happened instead:**

The page not shown and console shown an error for a Tab with ArrayInput.

**Steps to reproduce:**
1. Using React Admin 2.0.0-beta4
2. Create TabbedForm with one Form using ArrayInput
3. Try Custom Field
4. If error, try another field

**Related code:**
```
<FormTab label="Pages">
                <ArrayInput source="pages">
                    <SimpleFormIterator>
                        <Field name="image" component={CustomComponentInput} />
                        <TextInput source="page" />
                    </SimpleFormIterator>
                </ArrayInput>
  </FormTab>
```

**Other information:**
I also followed the code in Documentation, but not work.

**Environment**

* React-admin version: 2.0.0-beta4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.2
* Browser: Firefox 59.0.2
* Stack trace (in case of a JS error):

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CatalogCreate`. invariant.js:42
	invariant invariant.js:42
	throwOnInvalidElementType react-dom.development.js:5393
	createFiberFromElement react-dom.development.js:5364
	reconcileSingleElement react-dom.development.js:8054
	reconcileChildFibers react-dom.development.js:8110
	reconcileChildrenAtExpirationTime react-dom.development.js:8240
	reconcileChildren react-dom.development.js:8231
	updateHostComponent react-dom.development.js:8539
	beginWork react-dom.development.js:8986
	performUnitOfWork react-dom.development.js:11814
	workLoop react-dom.development.js:11843
	renderRoot react-dom.development.js:11874
	performWorkOnRoot react-dom.development.js:12449
	performWork react-dom.development.js:12370
	performSyncWork react-dom.development.js:12347
	interactiveUpdates react-dom.development.js:12597
	interactiveUpdates react-dom.development.js:1958
	dispatchInteractiveEvent react-dom.development.js:4259
	dispatchInteractiveEvent self-hosted:1035:17
```

**Comment by fzaninotto** [comment] 2018-04-23 11:30
If works on the simple example, so I can't reproduce the issue. Your stack trace is impossible to use, can you paste a non-bundled stack trace instead (using source maps)? Also, try removing the line

`<Field name="image" component={CustomComponentInput} />`

And see if it fixes the bug - that's the only special thing that I see in your code.

**Comment by fzaninotto** [comment] 2018-05-09 15:28
No news for some time, closing.

**Closed by fzaninotto** 2018-05-09 15:28 UTC
