### ISSUE TITLE
List component custom props are ignored when you get to buildQuery

### ISSUE THREAD

**Issue by cordial** [marmelab/react-admin#6162] opened 2021-04-13 15:42 UTC
**What you were expecting:**
We want to be able to write custom graphQL queries and pass a projection where the UI specifies what fields it wants by passing it in a custom prop to the buildQuery function - for example via the list component. In our example...

``export const UserList = props => {
  return (
    <List projections={USER_LIST_PROJECTIONS} filter={{roles: ["ADMIN"]}}>
      <Datagrid rowClick="show">
       ...
  )
}``

We want to use a custom property to be available inside the params argument in the buildQuery method here -

`const buildQuery = (jsonIntrospectionResults) => (raFetchType, resourceName, params) => {`

**What happened instead:**
The property is ignored and the params only contains the existing List properties. 

**Steps to reproduce:**
1. Try and use a custom prop on a component to specify what data this particular component wants (our example above uses List)
2. New prop will be ignored and not passed to the buildQuery. 

**current workaround**

If we pass it as part of the filter prop, then this works fine. But this seems really wrong. e.g. 
`export const UserList = props => {
  return (
    <List {...props} filter={{selections: USER_LIST_SELECTIONS, roles: ["ADMIN"]}}>
      <Datagrid rowClick="show">
        <TextFiel`

and in the buildQuery method - 
`const buildQuery = (jsonIntrospectionResults) => (raFetchType, resourceName, params) => {
   let selections = params.filter.selections
`

**Environment**

* React-admin version: 3.7.1
* Last version that did not exhibit the issue (if applicable): n/a
* React version: 17.0.2
* Browser: n/a
* Stack trace (in case of a JS error): n/a

**Comment by fzaninotto** [comment] 2021-04-13 20:06
Duplicate of #6155

**Closed by fzaninotto** 2021-04-13 20:06 UTC
