### ISSUE TITLE
Pagination is misused in ReferenceManyField in a Edit

### ISSUE THREAD

**Issue by TheBlusky** [marmelab/react-admin#5495] opened 2020-11-06 11:43 UTC
**What you were expecting:**

When using `rowsPerPageOptions={[10]}` within `ReferenceManyField` in a `Edit`, pagination should be 10 by 10

**What happened instead:**

Pagination is 25 by 25

**Steps to reproduce:**

I am using a `ReferenceManyField` within a `FormTab` within a `TabbedForm` within a `Edit`.

**Related code:**

```
export default (props) => (
  <Edit
    {...props}
  >
    <TabbedForm>
      [...]
      <FormTab [...]>
        <ReferenceManyField
          reference='foo'
          pagination={<Pagination rowsPerPageOptions={[10]} />}  // <-- Here
          target=':some_id'
        >
          <Datagrid>
            <Fields />
            <Fields />
            <Fields />
          </Datagrid>
        </ReferenceManyField>
      </FormTab>
  </Edit>
)
```

It's working fine, but the pagination is used as 25 by 25 instead of 10 by 10.

**Screenshot:**

![tIn9ZsgC5T](https://user-images.githubusercontent.com/441709/98364009-4995b880-2030-11eb-9594-7a9d6691f848.png)

(Note, only 10 items are displayed, because the server does not handle pagination, and use a hard coded value of 10)

**Other information:**

**Environment**

* React-admin version: 3.7.1
* React version: 16.13.1
* Browser: Chrome

**Comment by MicroJackson** [comment] 2020-11-06 12:58
This is not a bug I think, but I might be wrong.
You are giving specific options, in this case you can select the option 10 only. Normally its something like: `rowsPerPageOptions={[10, 25, 50, 100]}`
As stated, this is giving options to the pagination to use in the dropdown, not setting them.
You also need to set: `perPage={100}`

All documented here: https://marmelab.com/react-admin/List.html#the-pagination-component
Also: https://marmelab.com/react-admin/Fields.html#referencemanyfield has an example with PerPage.

**Comment by TheBlusky** [comment] 2020-11-06 13:49
Awesome ! Your suggestion fixed the widget.

However, it's strange, because the behavior is different than `List` where something like

```
<List
    pagination={
      <Pagination rowsPerPageOptions={[10]} />
    }
    {...props}
  >
```

Will set a `perPage` to 10 by default.

**Comment by MicroJackson** [comment] 2020-11-06 14:02
Awesome that it worked.

A List Pagination by default is set to 10. 
If you do `rowsPerPageOptions={[20]}` I think the dropdown will either be empty or 10.

**Comment by djhi** [comment] 2020-11-06 14:09
Thx @MicroJackson. Can we close this then ?

**Closed** 2020-11-06 14:12 UTC
