### ISSUE TITLE
Filter changes the focus of TextInput after few words and does not allow to enter long words

### ISSUE THREAD

**Issue by arjunk** [marmelab/react-admin#3149] opened 2019-04-19 10:50 UTC
Focus changes in middle of typing when filtering by text.

**What you were expecting:**
Filter should allow user to input full text and should not change the focus of the textbox.

**What happened instead:**
Everytime I type a text for filtering the focus of Text-box changes after entering some characters.

 **Steps to reproduce:**

Create a Filter with TextInput and use it in List

```
import { Filter, ReferenceInput, SelectInput, TextInput, List } from 'react-admin';
const PostFilter = (props) => (
    <Filter {...props}>
        <TextInput label="Search" source="q" resettable alwaysOn />
    </Filter>
);

export const PostList = (props) => (
    <List filters={<PostFilter />} {...props}>
        // ...
    </List>
);
```

In above code react-admin doesn't allow you to type a long text and changes focus of the text box after entering some characters.

**Environment**
React-admin version: 2.8.2

**Comment by Kmaschta** [comment] 2019-04-19 15:51
I have hard time reproducing this issue. Using a `TextInput` or a `SearchInput`, the debounce triggers the save long after I typed the last character.

Mind you reproduce the issue by forking [this CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or provide a gif for example?
Can it be related to a different browser?

**Comment by fzaninotto** [comment] 2019-04-23 09:04
This was normally fixed in 2.8.6 (see #3099). Can you upgrade and confirm that you no longer have the issue?

**Comment by vindeolal** [comment] 2019-04-25 11:09
Duplicate of [https://github.com/marmelab/react-admin/issues/3142](https://github.com/marmelab/react-admin/issues/3142)
I was not able to reproduce my issue on the above sandbox, even tried changing the version. 
Below is the GIF of the issue. You can see that focus of textbox changes when I stop typing.
 
![FilterError](https://user-images.githubusercontent.com/24850487/56731395-0179b280-6778-11e9-8edd-37e54fd38d7d.gif)

**Comment by fzaninotto** [comment] 2019-04-25 11:54
If we can't reproduce it, we won't be able to fix it... It may be a problem with your code rather than react-admin's code. So I'm closing this issue, feel free to reopen if you manage to reproduce it.

**Closed by fzaninotto** 2019-04-25 11:54 UTC
Labels: awaiting more info

**Comment by fzaninotto** [comment] 2019-04-25 15:23
Just a quick question: would you, by any chance, use a custom material ui theme that depends on the state?

**Comment by first-developer-com** [comment] 2020-07-23 12:39
I do it like this 
<Filter {...props}>
        {props.filterValues._id? <TextInput autoFocus source="_id" alwaysOn /> : <TextInput source="_id" alwaysOn />}
        {props.filterValues.name? <TextInput autoFocus source="name" alwaysOn /> : <TextInput source="name" alwaysOn />}
</Filter>
Add a autoFocus attribute if props.filterValues.something is
it is not the best issue, but it works.

**Comment by yaarchee** [comment] 2021-12-08 09:29
@vindeolal hi, sorry, tell me please, did you manage to solve this problem? I just ran into the same one. After typing in the search field, the List component unmounts and mounts and because of this the focus is lost, but why does it behave this way until I figured out
