### ISSUE TITLE
Beta 3 to Beta 5 issue: convertLegacyDataProvider.js import of constants set to undefined

### ISSUE THREAD

**Issue by qpointsystems** [marmelab/react-admin#3937] opened 2019-11-05 19:02 UTC
**What you were expecting:**
After moving from Beta 3 to Beta 5 convertLegacyDataProvider should be able to use fetchMap object to crosswalk fetch verbs like 'create' to constants (e.g., create: CREATE, ...), thereby allowing legacy data providers to function properly in 3.0.

**What happened instead:**
After seeing "unsupported fetch action type" exceptions in my DataProvider, I traced root cause to convertLegacyDataProvider and its import of action types from "../core".  Stepping through the code in Chrome Inspect, the import does not fail, but all constants imported (e.g., CREATE, DELETE, etc) have values of 'undefined'. This results in all translations via the fetchMap object to result in X -> undefined.  That root issue then cascades later to usages of the DataProvider as the observed "unsupported fetch action" exception.

**Steps to reproduce:**
Updated my projects react-admin dependencies in package.json.
From:
    "ra-core": "^3.0.0-beta.3",
    "react-admin": "^3.0.0-beta.3",
To:
    "ra-core": "^3.0.0-beta.4",
    "react-admin": "^3.0.0-beta.5",

Deleted node_modules directory and package-lock.json and ran 'npm install' to install project dependencies. 

Downgrading from Beta 5 back to Beta3, following the same npm pattern results in the project working fine.  All Beta's and Alpha's up to latest Beta 5 worked fine.

NOTE: Using yarn versus npm gives same results.

**Related code:**
Not quite sure what to include.

**Other information:**
I'm really hoping that this is some obscure npm side effect that I'm causing myself. That said, I did notice that in Beta4 this area of the ra-core project did change structure a bit, so maybe this is a regression from that work.

**Environment**

* React-admin version: 3.0.0-beta.5
* Last version that did not exhibit the issue (if applicable): 3.0.0-beta.3
* React version: ^16.9.0
* Browser: 
Chrome Version 78.0.3904.87 (Official Build) (64-bit)
Safari Version 13.0.2 (15608.2.30.1.1)
* OS: OSX 10.15 (19A583)

* Stack trace (in case of a JS error): 
Stacktrace is too far removed from root cause but have provided a stacktrace just after the import of constants from '../core' in the convertLegacyDataProvider file.

[convertLegacyDataProvider trace.txt](https://github.com/marmelab/react-admin/files/3810748/convertLegacyDataProvider.trace.txt)

![Post import debug](https://user-images.githubusercontent.com/44985224/68237101-6467c400-ffbb-11e9-96aa-88ee6ac10580.png)
![FetchMap](https://user-images.githubusercontent.com/44985224/68237265-aa248c80-ffbb-11e9-8136-b62c86a4cd5b.png)

**Comment by qpointsystems** [comment] 2019-11-06 18:13
FYI: I'm taking a crack at refactoring my PostGRESt DataProvider to the nouveau style DataProvider as of 3.0. That said, i'd like to be able to use my current provider a bit longer.

**Comment by fzaninotto** [comment] 2019-11-07 18:01
Duplicate of #3924

**Closed by fzaninotto** 2019-11-07 18:01 UTC
