### ISSUE TITLE
On save, Old record still exist in list

### ISSUE THREAD

**Issue by thatshailesh** [marmelab/react-admin#4197] opened 2019-12-19 14:52 UTC
Whenever I edit any record and save, the old version is being shown in my list and its only getting deleted when API is responded successfully

Please see the attached screencast [click here](http://somup.com/cqlq27fkXi)

**Comment by djhi** [comment] 2019-12-19 15:27
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by thatshailesh** [comment] 2019-12-20 03:03
@djhi  I have pushed repo, please check

[https://github.com/thatshailesh/sample-react-admin](https://github.com/thatshailesh/sample-react-admin)

**Comment by fzaninotto** [comment] 2019-12-20 08:07
Hi, your repository depends on a local API, so we can't test it. Please fork the react-admin codesandbox instead, which depends on a mocked API in the browser. 

Also, as the bug doesn't appear on master, the problem is likely on your side.

**Comment by thatshailesh** [comment] 2019-12-20 08:17
Hi Guys,

It has been fixed, it was `id` issue so i was sending `id` in all APIs except `getOne`

**Comment by thatshailesh** [comment] 2019-12-20 08:36
@fzaninotto is there any component in `react-admin` that can help in uploading `csv` or `files?

**Comment by fzaninotto** [comment] 2020-01-20 20:49
@thatshailesh No, you'll have to write it yourself.

I'm closing this issue as the problem was on your side.

**Closed by fzaninotto** 2020-01-20 20:49 UTC
Labels: needs more info
