### ISSUE TITLE
logoutOnFailure for useCheckAuth is always false

### ISSUE THREAD

**Issue by rhubarbselleven** [marmelab/react-admin#5196] opened 2020-08-27 11:07 UTC
**What you were expecting:**
As per: <https://marmelab.com/react-admin/Authentication.html#checking-credentials-during-navigation>

> If the promise is rejected, react-admin redirects by default to the /login page. You can override where to redirect the user in checkAuth(), by rejecting an object with a redirectTo property

**What happened instead:**

When using the sample code provided, the page does not redirect when rejecting the promise:

```
// in src/authProvider.js
export default {
    login: ({ username, password }) => { /* ... */ },
    logout: () => { /* ... */ },
    checkError: (error) => { /* ... */ },
    checkAuth: () => localStorage.getItem('token')
        ? Promise.resolve()
        : Promise.reject(),
    // ...
};
```

A rejected promise in `checkAuth` does not logout, nor redirect the user.

**Steps to reproduce:**

In [useAuthState](https://github.com/marmelab/react-admin/blob/04c4b0d22e860f3c36e92df922edc6ee5e276c64/packages/ra-core/src/auth/useAuthState.ts#L59), `checkAuth` is invoked with `params, false`. 

When handling the [thrown error from the authProvider](https://github.com/marmelab/react-admin/blob/04c4b0d22e860f3c36e92df922edc6ee5e276c64/packages/ra-core/src/auth/useCheckAuth.ts#L55) the `false` value is tested and so the resultant `logout` and `redirectTo` fragments are never reached.

**Other information:**

**Environment**

* React-admin version: 3.8.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.13.1
* Browser: Chrome 84.0.4147.125
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-08-27 14:18
`useAuthState` doesn't log out - it just returns the auth state. If you want a hook that redirects to the login when not authenticated, use `useCheckAuth`, or, even better, [`useAuthenticated`](https://marmelab.com/react-admin/Authentication.html#useauthenticated-hook).

It seems to me the documentation of the `useAuthenticated` and `useAuthState` hooks is pretty explicit on that point. Or am I missing something?

**Comment by rhubarbselleven** [comment] 2020-08-28 00:06
Hey @fzaninotto, thanks for checking this out. I can see where I've led you wrong in my description.

As a user, I expect to reject a promise in my `autProvider.checkAuth` when I determine believe the browser authentication state is invalid. I may decribe where to redirect the user as a part of the promise rejection. This is documented by <https://marmelab.com/react-admin/Authentication.html#checking-credentials-during-navigation>. 

The cause for this seems to be that `logoutOnFailure` is always false and thereby the redirection statement is never reached.

Does that help clarify?

**Comment by fzaninotto** [comment] 2020-08-28 06:52
No, I still don't understand. 

React-admin uses the `useAuthenticated` hook for all its routes (via `<WithPermisisons>` in `<Resource>`). This hook in turn calls `useCheckAuth` with only one parameter, leaving the second parameter, `logoutOnFailure`, to its default value, which is `true`. So *by default*, when using `useAuthenticated`, a rejected Promise from `authProvider.checkAuth()` with a `redirectTo` argument will be taken into account.

The case of `useAuthState` is different: *by design* it doesn't log out on failure. Because otherwise, what's the point of knowing that the user is logged out while your hook can't do anything about that information?

In your case, you should use `useAuthenticated` and not `useAuthState`.

Now if you disagree, please provide a CodeSandbox with your code, because I can't understand where a bug can be without proper code.

**Comment by fzaninotto** [comment] 2020-10-29 16:26
No news for some time, closing.

**Closed by fzaninotto** 2020-10-29 16:26 UTC
Labels: needs more info
