### ISSUE TITLE
`useLocaleState` returns different locale than one provided in `i18nProvider` prop on `<Admin/>` component

### ISSUE THREAD

**Issue by dominikboniecki** [marmelab/react-admin#8828] opened 2023-04-12 11:27 UTC
**What you were expecting:**
`useLocaleState` hook should return locale provided in `i18nProvider` prop of `<Admin/>` component

**What happened instead:**
`useLocaleState` returns probably browser locale instead of provided in above prop. Problem occured on 4.9.2, when I downgrade react-admin to 4.9.1, everything seems fine

**Steps to reproduce:**
1. Provide `i18nProvider` in `<Admin/>` component with custom locale
2. Use `useLocaleState` somewhere in the app and check `[locale, ...]` value from hook

```
<HydraAdmin
      entrypoint={VITE_CORE_API}
      authProvider={epAuthProvider}
      dataProvider={epDataProvider}
      dashboard={dashboard}
      layout={EpLayout}
      store={memoryStore()}
      theme={appTheme}
      i18nProvider={i18nProvider}>
      {(permissions: string[]) => <>{getResourcesAndCustomRoutes(permissions)}</>}
    </HydraAdmin>
```

```
export const i18nProvider = polyglotI18nProvider(
  (locale) => messages[locale as LocaleKey],
  initialLocale,
  availableLanguages,
);
```
`i18nProvider.getLocale()` is `en-GB`

` const [locale, setLocale] = useLocaleState();`
`locale` is `pl-PL`

**Environment**

* React-admin version: 4.9.2
* Last version that did not exhibit the issue (if applicable): 4.9.1
* React version: 18
* Browser: latest Chrome

**Comment by fzaninotto** [comment] 2023-04-12 11:51
Thanks for your feedback.

That's weird, because bothing has changed concerning the locale and that hook between react-admin 4.9.1 and 4.9.2

https://github.com/marmelab/react-admin/compare/v4.9.1...v4.9.2

I see you're using HydraAdmin - I suspect something changed on their side, or the problem comes from elsewhere. 

In any case, we need a reproduction to investigate further - please fork the simple example codesandbox and tweak it to reproduce the bug, then post the link here. 

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by fzaninotto** [comment] 2023-08-01 13:57
No news for some time, closing.

**Closed by fzaninotto** 2023-08-01 13:57 UTC
Labels: needs more info
