### ISSUE TITLE
Nextjs - page refresh on prev and next explorer history button with app folder

### ISSUE THREAD

**Issue by groomain** [marmelab/react-admin#9442] opened 2023-11-13 11:49 UTC
**What you were expecting:**
When you press the next or prev button of my explorer I expect to not reload react-admin.
I'm not expecting a full page refresh.

**What happened instead:**
The page is fully refreshed instead of handled with reat-router.

**Steps to reproduce:**
Follow the nextjs app folder example on react-admin documentation. Click on a link, then click on the prev button.
I don't know if it's possible to not perform a hard refresh like with the page folder.

**Other information:**
* React-admin version: 4.15.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18
* Browser: Chrome 116
* Stack trace (in case of a JS error):

**Comment by erwanMarmelab** [comment] 2023-11-14 10:00
Hi Romain,

I can't reproduce the problem you describe with the nextJs tutorial. There could be something else in your settings, or a step you did that causes the bug.

Can you please try and reproduce your issue on a [codesandbox](https://codesandbox.io/)?

Cheers,

Erwan

**Comment by fzaninotto** [comment] 2023-12-12 18:45
No news for some time, closing.

**Closed by fzaninotto** 2023-12-12 18:45 UTC
Labels: needs more info
