### ISSUE TITLE
In Tab view, Data is not displayed

### ISSUE THREAD

**Issue by vahidqo** [marmelab/react-admin#5484] opened 2020-11-04 08:43 UTC
in Tab show, I have 2 tabs but one of them that related to other tables doesn't show the content, also the filter is correct ( I mean there is 2 data ) but records have not been shown.

**this is my code:**
```
import * as React from "react";
import {
    Datagrid,
    TextField,
    ReferenceField,
    ShowButton,
    Show,
    TabbedShowLayout,
    ReferenceManyField,
    Tab
}
from 'react-admin';
import AssetClassTitle from './AssetClassTitle';


const AssetClassShow = props => (
    <Show {...props} title={<AssetClassTitle />}>
        <TabbedShowLayout>
            <Tab label="مشخصات">
                <TextField label="کد کلاس تجهیز" textAlgin="right" source="AssetClassCode" />
                <TextField label="نام کلاس تجهیز" textAlgin="right" source="AssetClassName" />
                <ReferenceField label="خانواده تجهیز" textAlgin="right" source="AssetCategoryID" reference="PMWorks/AssetCategory">
                    <TextField source="AssetCategoryName" />
                </ReferenceField>
            </Tab>
            <Tab label="ویژگی ها" path="PMWorks/AssetClassSpecificData">
                <ReferenceManyField
                    addLabel={false}
                    reference="PMWorks/AssetClassSpecificData"
                    target="AssetClassID"
                    sort={{ field: 'SpecificDataID', order: 'DESC' }}
                >
                    <Datagrid>
                        <TextField label="نام کلاس تجهیز" textAlgin="right" source="SpecificDataID" />
                        <ShowButton />
                    </Datagrid>
                </ReferenceManyField>
            </Tab>
        </TabbedShowLayout>
    </Show>
);


export default AssetClassShow;
```

**this is what have been shown:**
![image](https://user-images.githubusercontent.com/69747871/98088002-2afbba00-1e96-11eb-8b1b-6c6fe2219f76.png)

as you can see there are 2 records - which is correct - but it doesn't show.

**and this is components in the console:**
{
  "addLabel": false,
  "reference": "PMWorks/AssetClassSpecificData",
  "target": "AssetClassID",
  "sort": {
    "field": "SpecificDataID",
    "order": "DESC"
  },
  "children": "<ForwardRef />",
  "filter": {},
  "perPage": 25,
  "source": "id",
  "basePath": "/PMWorks/AssetClassSpecificData",
  "record": {
    "id": 1,
    "AssetClassCode": "T11",
    "AssetClassName": "Oil Storage Tank",
    "AssetCategoryID": 2
  },
  "resource": "PMWorks/AssetClassSpecificData",
  "currentSort": {
    "field": "SpecificDataID",
    "order": "DESC"
  },
  "data": {},
  "defaultTitle": null,
  "displayedFilters": {},
  "error": null,
  "filterValues": {},
  "hasCreate": false,
  "hideFilter": "ƒ () {}",
  "ids": [
    2,
    1
  ],
  "loaded": true,
  "loading": false,
  "onSelect": "ƒ () {}",
  "onToggleItem": "ƒ () {}",
  "onUnselectItems": "ƒ () {}",
  "page": 1,
  "selectedIds": [],
  "setFilters": "ƒ () {}",
  "setPage": "ƒ () {}",
  "setPerPage": "ƒ () {}",
  "setSort": "ƒ () {}",
  "showFilter": "ƒ () {}",
  "total": 2
}

**Comment by djhi** [comment] 2020-11-04 09:09
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by vahidqo** [comment] 2020-11-04 09:24
I'm not very good with Codesandbox but I made changes and this is the link:
https://codesandbox.io/s/relaxed-hooks-6r9xk?file=/src/posts/PostShow.js
is that ok or you need more?
thanks

**Comment by djhi** [comment] 2020-11-04 09:53
The codesandbox is broken on the post show view

**Comment by vahidqo** [comment] 2020-11-04 10:00
> The codesandbox is broken on the post show view

https://codesandbox.io/s/floral-waterfall-k03zp

I think now you have access to it

**Comment by djhi** [comment] 2020-11-04 10:17
That's not what I meant, the post show view does not work at all so I cannot reproduce your issue

**Comment by vahidqo** [comment] 2020-11-04 14:38
> That's not what I meant, the post show view does not work at all so I cannot reproduce your issue

Sorry.
that's my problem working with Codesandbox

**Comment by fzaninotto** [comment] 2020-12-11 15:19
this issue has gone silent. Without any way to reproduce the issue, we have to close it. Feel free to comment with new info if you want it ropened.

**Closed by fzaninotto** 2020-12-11 15:19 UTC
Labels: needs more info
