### ISSUE TITLE
Failed to minify on build

### ISSUE THREAD

**Issue by FbPalmabit** [marmelab/react-admin#1762] opened 2018-04-19 12:34 UTC
I followed the tutorial and created app with create-react-app.
But when I build with `npm run build` i have this error:
```
Failed to minify the code from this file:

        ./node_modules/query-string/index.js:42

Read more here: http://bit.ly/2tRViJ9
```
**Environment**

* React-admin version: 2.0.0-RC1
* React version: 16.3.2

**Comment by fzaninotto** [comment] 2018-04-19 12:37
Fixed by 4ee71dc56d7b257a8ba49cd3a03e11307cfddc50

**Comment by FbPalmabit** [comment] 2018-04-19 12:40
thanks!

**Comment by christiaanwesterbeek** [comment] 2018-04-23 14:06
My build is failing too, and the commit https://github.com/marmelab/react-admin/commit/4ee71dc56d7b257a8ba49cd3a03e11307cfddc50 is probably fixing it.

Since that commit is not in RC1, I need to add the `master` branch as my dependency for now, because I need my build to not fail. However `yarn add -D https://github.com/marmelab/react-admin#master ` results in 

> yarn add v1.5.1
> [1/5] 🔍  Validating package.json...
> [2/5] 🔍  Resolving packages...
> error An unexpected error occurred: "Can't add \"react-admin-lerna\": invalid package version undefined.".

The problem is probably due to the fact that the name is "react-admin-lerna" instead of "react-admin".

How can I add `react-admin#master` now to my project?

**Comment by onka13** [comment] 2019-12-15 22:22
I've same problem. 

```
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/ra-core/node_modules/query-string/index.js:9
```

"react-admin": "^3.0.4"

**Comment by fzaninotto** [comment] 2019-12-16 09:00
It seems #4081 reverted the fix. Reopening.

**Closed** 2019-12-16 09:21 UTC
