### ISSUE TITLE
useGetRecordRepresentation not exported from ra-core

### ISSUE THREAD

**Issue by btbenedi** [marmelab/react-admin#8168] opened 2022-09-15 08:31 UTC
Updating from 4.2.6 to 4.3.2

**What you were expecting:**
Both local dev and build success

**What happened instead:**
On both dev and build, receiving ```Attempted import error: 'useGetRecordRepresentation' is not exported from 'ra-core' (imported as 'useGetRecordRepresentation').```

In local dev, I get additional info that this attempted import is occurring on ```ReferenceField```, ```AutocompleteInput```, and ```SelectInput``` in ```ra-ui-materialui```

**Steps to reproduce:**
I do not see the issue on codesandbox.io fork, the main difference for us is we're using ```craco start``` and ```craco build``` as we utilize an alias feature for our importing. I am attempting a standalone sample app with ```craco``` to see if it's related to that or more global. Will update if I get that up and running with same error.

**Environment**

* React-admin version: 4.3 (tested all 4.3.0, 4.3.1, and 4.3.2, all exhibit same behavior)
* Last version that did not exhibit the issue (if applicable): 4.2.6
* React version: 17.0.2
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2022-09-15 08:39
Hi, 

Looking at the source, `useGetRecordRepresentation` is indeed exported since 4.3.0

* https://github.com/marmelab/react-admin/blame/master/packages/ra-core/src/core/index.ts
* https://github.com/marmelab/react-admin/pull/8011

The problem you meed may be caused by a duplicate `ra-core` in your node_modules. Could you check your `yarn.lock` for multiple versions of `ra-core`?

**Comment by btbenedi** [comment] 2022-09-15 08:47
Ahh dangit, I had version 4.2.7 of ```ra-data-json-server``` still in ```package.json```, so ```package-lock.json``` still had ```ra-core``` 4.2.7

Reminder kids to update all your sibling packages 😂 all looks good now, thanks.

Side note, thanks for #7999, this is why we're updating.

**Comment by WiXSL** [comment] 2022-09-15 10:54
Closing this issue since it has been resolved

**Closed by WiXSL** 2022-09-15 10:54 UTC
Labels: needs more info
