### ISSUE TITLE
Unauthenticated custom routes not working when using a function for the App's children

### ISSUE THREAD

**Issue by razdvapoka** [marmelab/react-admin#5036] opened 2020-07-11 13:45 UTC
**What you were expecting:**
Custom route renders without authentication.

**What happened instead:**
It gets redirected to /login page.

**Steps to reproduce:**
1) Make the App's children a function that accepts permissions
2) Go to any custom route unauthenticated
3) You'll be redirected to the login page

**Other information:**
I think it happens because the `CoreAdminRouter` tries to [initialize resources](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L44) even when you are not authenticated. The attempt to get permissions is rejected and the app [logs out](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/core/CoreAdminRouter.tsx#L78) which redirects you to the login page.

[Related closed issue](https://github.com/marmelab/react-admin/issues/4821)

**Environment**

* React-admin version: 3.6.2
* React version: 16.13.1
* Browser: Firefox 77.0.1

**Comment by Luwangel** [comment] 2020-07-15 12:15
Hi,

Thank you for opening this issue :pray:

Unfortunately, I cannot reproduce your bug. Maybe it's because it has been fixed in newer versions but I'm not sure.

Please follow the instructions explained in the bug report template so that I can reproduce your issue:
1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by vudaysai** [comment] 2020-07-29 07:24
Hi,

I have reproduced the issue here [Sandbox](https://codesandbox.io/s/react-admin-custom-page-redirect-issue-08kdm?file=/src/authProvider.js) with the mistake i made.

Issue is in **getPermissions()** of **authProvider** if it returns `Promise.reject()` it will redirect to login page.

@razdvapoka you might also be doing same thing too, so this might helps

**Comment by jdemangeon** [comment] 2020-08-24 14:36
Hello @razdvapoka ! Do you have fixed your issue? If so, please inform us so that we can close the issue.

**Comment by alextaymx** [comment] 2020-11-11 11:25
I am having the same issue

**Comment by fzaninotto** [comment] 2021-01-14 22:18
No news for some time, closing.

**Closed by fzaninotto** 2021-01-14 22:18 UTC
Labels: needs more info

**Comment by TCM5** [comment] 2021-05-18 23:50
We also noticed this behaviour. Because custom routes are based on the current resolved permissions.
If the `getPermissions` method from `AuthProvider` returns `Promise.reject()` public custom resources will fail to show, and a redirect to login page is allways triggered.

It makes sense this behaviour because `getPermissions ` should allways `resolve`, even if not permissions are assigned, but for public resources (no authentication needed) it makes no sense.

In order to solve this, instead of change the core behaviour that expects the permissions resolved, a new wrapper like a `PublicRoute ` or `StandaloneRoute` should make the trick in order that all routings that defined using this wrapper should be ignored by getPermissions.
