### ISSUE TITLE
UNDO logic not working when doing multiple deletions one by one

### ISSUE THREAD

**Issue by IliaIdakiev** [marmelab/react-admin#10269] opened 2024-10-10 07:46 UTC
**What you were expecting:**
The "UNDO" (cancel action) functionality is not working correctly. The issue caused by the so called undoableEventEmitter. This event emitter emits only the "end" event without any additional info about the action that will be performed. This causes an issue when I do multiple fast deletions. The issue is that the **second deletion triggers the emittion of "end" event which cases the first deletion action to get triggered even though the "UNDO" toast is still present on the UI and users can click the button but nothing will happen.** One possible solution for resolving the issue would be adding a unique identifier for the given action and passing this unique id to the undoable event emitter so undoable actions can be indipendently recognised.

**What happened instead:**
Each click of "UNDO" should be canceling the action that this "UNDO" is meant for.

**Steps to reproduce:**
Increase the "UNDO" default timeout so it doesn't hide the notification after 5 seconds so it's easier to reproduce. Open dev tools - network tab. Click two times the delete button inside of a list and click the first "UNDO" button. This will trigger the fist deletion instead of canceling it. From what I remember while testing I even think that it triggers both deletions and makes both "UNDO" toasts useless. 

**Related code:**
I'm posting links directly to the source code because the issue can be seen directly:

The event emitter that is shared:

https://github.com/marmelab/react-admin/blob/3a463d3a73455cc65a37c61852e35a26f7f3a2b2/packages/ra-core/src/dataProvider/undoableEventEmitter.ts#L3

The place where react admin is listening for the given event:

https://github.com/marmelab/react-admin/blob/3a463d3a73455cc65a37c61852e35a26f7f3a2b2/packages/ra-core/src/dataProvider/useDelete.ts#L415

One of the places (in my case the place) where the event is fired (upon clicking the second delete):

https://github.com/marmelab/react-admin/blob/3a463d3a73455cc65a37c61852e35a26f7f3a2b2/packages/ra-ui-materialui/src/layout/Notification.tsx#L87

**Other information:**
I think I provided the correct links and files but I was debugging the issue yesterday and by mistake I closed the files but I'm pretty sure that the links that I've shared are the correct ones.

**Environment**

* React-admin version: Latest
* Last version that did not exhibit the issue (if applicable): -
* React version: -
* Browser: -
* Stack trace (in case of a JS error): -

**Comment by erwanMarmelab** [comment] 2024-10-11 15:37
Reproduced thanks, here is a screencast showing this bug:
https://github.com/user-attachments/assets/0bbc4cd0-abda-4d92-b5d8-1336e94259a6

**Comment by fzaninotto** [comment] 2024-10-23 07:51
I have understood the cause of the bug, but the resolution isn't straightforward. Here is my analysis. 

The notifications use a FIFO stack. Whenever a function calls `notify()`, this adds a notification to the `NotificationContext` stack. Whenever this context changes, the `Notification` takes a notification from the stack and displays it. 

On the other hand, the side effects of undoable mutations use an even emitter logic. For example, `DeleteButtton` registers a listener for the next 'end' event. When the user clicks several of these in a row, they all register a callback for the next `end` event. And this event is triggered when the notification hides - to let the time for the user to cancel it. 

These two logics (stack and event listeners) work well together when there is only one side effect. As soon as there is more than one, it fails. Here is a typical failing sequence of events (tested by adding console.log everywhere):

1. The user clicks on a DeleteButton in a list
2. The useDeleteWithUndoController registers a listener L1 to execute the mutation on `end`
3. The useDeleteWithUndoController calls notify, which adds an element to the NotificationContext stack
4. The Notification component sees that there is a new notification, so displays it
5. The user clicks on a second DeleteButton in a list 
6. The useDeleteWithUndoController registers a second listener L2 to execute the mutation on `end`
7. The useDeleteWithUndoController calls notify, which adds an element to the NotificationContext stack
8. The Notification component sees that there is a new notification, so it hides the first one
9. Once the notification hides, it triggers the end event, and executes both listeners. Both L1 and L2 mutations are executed. 
10. The second notification shows
11. Once the second notification hides (for any reason: clickaway, timeout, or click on undo), it triggers the end event, and but there are no more listener to execute because both were already executed in 8One side note: why does Notification trigger the `end` event when the notification hides? Because we have no other way to detect all cases (clickaway, timeout, or click on undo). MUI doesn't call the `<Notification onClose>` callback when the notification is closed programatically. 

So the heart of the problem is that we use two incompatible systems to manage two side effects: notification and mutations. 

Now, how do we solve this? There are a few options:

### Solution A

All the undoable mutations should trigger an `end` event to execute remaining listeners before adding their own. This means that the L1 listener will execute at step 6 instead of step 9. That isn't enough to fix the problem: we also need to prevent L2 from being executed on 9 instead of 11. For that, we have to add a new state to Notification so that it doesn't emit the `end` event when it's closing *programatically*. 

```diff
diff --git packages/ra-core/src/dataProvider/useDelete.ts packages/ra-core/src/dataProvider/useDelete.ts
index fa618bb57..efde2d070 100644
--- packages/ra-core/src/dataProvider/useDelete.ts
+++ packages/ra-core/src/dataProvider/useDelete.ts
@@ -411,6 +411,9 @@ export const useDelete = <
                 }
             );
         } else {
+            // complete pending mutation
+            undoableEventEmitter.emit('end', { isUndo: false });
+
             // undoable mutation: register the mutation for later
             undoableEventEmitter.once('end', ({ isUndo }) => {
                 if (isUndo) {
diff --git packages/ra-ui-materialui/src/layout/Notification.tsx packages/ra-ui-materialui/src/layout/Notification.tsx
index bbd53f35b..3d6c6bc11 100644
--- packages/ra-ui-materialui/src/layout/Notification.tsx
+++ packages/ra-ui-materialui/src/layout/Notification.tsx
@@ -42,37 +42,39 @@ export const Notification = (props: NotificationProps) => {
     const [currentNotification, setCurrentNotification] = React.useState<
         NotificationPayload | undefined
     >(undefined);
+    const [closingForNewNotification, setClosingForNewNotification] =
+        React.useState(false);
     const translate = useTranslate();
 
     useEffect(() => {
-        const beforeunload = (e: BeforeUnloadEvent) => {
-            e.preventDefault();
-            const confirmationMessage = '';
-            e.returnValue = confirmationMessage;
-            return confirmationMessage;
-        };
-
-        if (currentNotification?.notificationOptions?.undoable) {
-            window.addEventListener('beforeunload', beforeunload);
-        }
-
         if (notifications.length && !currentNotification) {
             // Set a new snack when we don't have an active one
             const notification = takeNotification();
             if (notification) {
                 setCurrentNotification(notification);
                 setOpen(true);
+                setClosingForNewNotification(false);
             }
         } else if (notifications.length && currentNotification && open) {
             // Close an active snack when a new one is added
             setOpen(false);
+            setClosingForNewNotification(true);
         }
 
-        return () => {
-            if (currentNotification?.notificationOptions?.undoable) {
-                window.removeEventListener('beforeunload', beforeunload);
-            }
+        // warn about ongoing mutation not being triggered on unload
+        const beforeunload = (e: BeforeUnloadEvent) => {
+            e.preventDefault();
+            const confirmationMessage = '';
+            e.returnValue = confirmationMessage;
+            return confirmationMessage;
         };
+
+        if (currentNotification?.notificationOptions?.undoable) {
+            window.addEventListener('beforeunload', beforeunload);
+            return () => {
+                window.removeEventListener('beforeunload', beforeunload);
+            };
+        }
     }, [notifications, currentNotification, open, takeNotification]);
 
     const handleRequestClose = useCallback(() => {
@@ -84,10 +86,14 @@ export const Notification = (props: NotificationProps) => {
             currentNotification &&
             currentNotification.notificationOptions?.undoable
         ) {
-            undoableEventEmitter.emit('end', { isUndo: false });
+            if (closingForNewNotification) {
+                setClosingForNewNotification(false);
+            } else {
+                undoableEventEmitter.emit('end', { isUndo: false });
+            }
         }
         setCurrentNotification(undefined);
-    }, [currentNotification]);
+    }, [currentNotification, closingForNewNotification]);
 
     const handleUndo = useCallback(() => {
         undoableEventEmitter.emit('end', { isUndo: true });
@@ -125,7 +131,7 @@ export const Notification = (props: NotificationProps) => {
                     : autoHideDurationFromMessage ?? undefined
             }
             disableWindowBlurListener={undoable}
-            TransitionProps={{ onExited: handleExited }}
+            TransitionProps={{ onExit: handleExited }}
             onClose={handleRequestClose}
             ContentProps={{
                 className: clsx(NotificationClasses[typeFromMessage || type], {

```

This works, but it's not robust. We need to modify all optimistic mutations to trigger and `end` before registering a listener. The mutation will run *before* the Notification disappears, leaving a fraction of a second to press the UNDO button without effect. Also, any userr land button that registers an `end` listener will have to also trigger the event beforehand. Finally, this won't work when the second mutation is optimistic instead of undoable (as is won't trigger the `end` event in that case). 

I'm -1 for this solution

### Solution B

We modify all undoable mutations to add their callback to a new stack instead of registering an event emitter. That way, both side effects (mutation and notification) use the same data structure and can be synchronized. The "take" of the mutation stack will be triggered by the "close" of a Notification. We need to build a new utility for this, and to modify the `undoableEventEmitter` object to become a proxy for that stack to keep backwards compatibility. 

I haven't yet tested this approach.

It's a major change because we somehow deprecate the `undoableEventEmitter`, and it should probably wait for a minor release. But I think it's the most robust. 

Maybe there is also a third solution?

**Comment by fzaninotto** [comment] 2024-10-24 06:55
The second approach works like a charm. PR incoming.

**Closed** 2024-10-29 08:33 UTC
