### ISSUE TITLE
Resource search results are not updated when URL is changed in browser address bar

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#5299] opened 2020-09-24 15:53 UTC
**What you were expecting:**
Changing URL string to exclude filter parameters in resource list page should change search criteria and find new records

**What happened instead:**
Removing "filter" parameters in URL bar and hitting "Enter" does not change the search criteria

-------------------------------------

**Steps to reproduce - example 1:**
**Step 1:** Click on the following link to open application in a browser (or manually paste into a new browser tab):
https://marmelab.com/react-admin-demo/#/commands?filter=%7B%22status%22%3A%22ordered%22%2C%22q%22%3A%22asdasdasdasdasd%22%7D&order=DESC&page=1&perPage=25&sort=date

**Step 2:** Remove all url parameters (only leave https://marmelab.com/react-admin-demo/#/commands in the URL bar) and click "Enter"

Observe that no results are displayed. Also notice that filter input still shows "asdasdasdasdasd" even though URL parameters has changed

![image](https://user-images.githubusercontent.com/48455289/94167969-becb7680-fe52-11ea-8429-d545d1738a4e.png)

-------------------------------------

**Steps to reproduce - example 2:**

This example is different from previous example since step 1 also has a problem.

**Step 1:** Click on the following link to open application in a browser (or manually paste into a new browser tab):
https://marmelab.com/react-admin-demo/#/customers?filter=%7B%22q%22%3A%2212345%22%7D&order=DESC&page=1&perPage=25&sort=last_seen

This step should not produce any results.

Note an issue here: search box is empty; it should have 12345

![image](https://user-images.githubusercontent.com/48455289/94168591-69439980-fe53-11ea-8a8f-9b1e6bcbfc59.png)

**Step 2:** Edit URL to exclude parameters (the url should be https://marmelab.com/react-admin-demo/#/customers) and hit enter

Notice that no results are displayed; however, if I click "F5" to refresh the application, everything is displayed again. 

![image](https://user-images.githubusercontent.com/48455289/94168661-795b7900-fe53-11ea-9956-a5378613a923.png)

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

**Environment**

* React-admin version: latest included into the demo site
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Chrome 85.0.4183.102
* Stack trace (in case of a JS error):

**Comment by wattry** [comment] 2020-09-25 21:02
@panfiva with regards to the first issue I believe the browser behaviour is causing the confusion as that works when I press return. If you don't select the autofill and then press enter/return it will work.

**Comment by panfiva** [comment] 2020-09-28 13:57
@wattry , that's strange. I tried both chrome and IE, and I am experiencing the same issue. After editing URL, I press "enter" which normally triggers navigation event in browsers.

**Comment by djhi** [comment] 2020-09-28 14:23
Reproduced. Thanks.

**Comment by wattry** [comment] 2020-09-28 15:31
@panfiva yeah I can modify the url in chrome and press enter and it works fine.

**Comment by wattry** [comment] 2020-09-28 15:35
https://media.giphy.com/media/NWivmlYNVs1zjnlv9S/giphy.gif

**Comment by WiXSL** [comment] 2021-12-24 11:43
I cannot reproduce this anymore with the latest version of react-admin (3.19.5).
So I'm closing this issue, but please fell free to re-open it if you find the way to reproduce it.

**Closed by WiXSL** 2021-12-24 11:43 UTC
