### ISSUE TITLE
parse and format props are not triggered when using options props

### ISSUE THREAD

**Issue by tamir61** [marmelab/react-admin#5151] opened 2020-08-13 06:50 UTC
Hey i'm trying to use ImageInput as example below but i noticed that the parse and format props are not triggered when i'm dropping a file into the input.

I found out that if i'm removing `options={{onDrop:this.handleImageChange}}`  they are triggered each time i'm switching image file.. 

```     
      <Edit {...props}>
        <SimpleForm defautValue={{ supportedCountries: this.state.defaultCountries }} >
          <ImageInput
            options={{onDrop:this.handleImageChange}}
            label="Logo"
            source="logo"
            accept="image/*"
            parse={helpers.parseS3Url.bind(null, 'ico')}
            format={ImageFormatter}
            allowEmpty
          >
            <ImageField source="url" />
          </ImageInput>
        </SimpleForm>
      </Edit>
```

Any ideas?
Thanks!

**Comment by fzaninotto** [comment] 2020-08-13 07:32
Looking at the FileInput code, I see no reason for that. Maybe the problem is on your side? To demonstrate this is a react-admin bug, please create a minimal CodeSandbox based on the simple example reproducing the bug, as explained in the issue template. Also, please specify your react-admin version and browser (again, as required by the issue template).

**Comment by tamir61** [comment] 2020-08-16 11:48
@fzaninotto i'm running react-admin version 2.9.9 with chrome Version 84.0.4147.125 (Official Build) (64-bit)
i created [CodeSandbox](https://codesandbox.io/s/react-admin-advanced-recipes-quick-createpreview-forked-hwbtd?file=/src/comments/CommentCreate.js) example with the problem

i inserted those lines 
```
                 <ImageInput
                    // options={{ onDrop: () => console.log('onDrop') }}
                    onChange={() => console.log('onChange')}
                    label="test"
                    source="logo"
                    accept="image/*"
                    parse={() => console.log('parse')}
                    format={() => console.log('format')}
                    allowEmpty
                >
                    <ImageField />
                </ImageInput>
```
![image](https://user-images.githubusercontent.com/43725711/90333528-43fb7a00-dfcf-11ea-9137-131ebedc97e4.png)

after choosing file i expected that console.log('onChange') will be triggered. 
when i comentting `onChange={() => console.log('onChange')}` and uncomment `// options={{ onDrop: () => console.log('onDrop') }}` format and parsing are not being triggered

**Comment by fzaninotto** [comment] 2020-08-16 15:27
> i'm running react-admin version 2.9.9

That's the important bit. This component was partially rewritten in react-admin 3.x, which doesn't show the bug you're describing. 

I encourage you to upgrade to version 3 - version 2 is feature-freeze and the core team doesn't maintain it anymore. So even if I'm marking this issue as a bug, you'll have to wait for a member of the community to publish a PR with a bugfix.

**Comment by jayanth-2** [comment] 2020-12-24 05:39
@fzaninotto I think we can close this issue. It's working fine.

**Closed** 2021-01-03 15:32 UTC
Labels: bug, v2
