### ISSUE TITLE
Infinite loop when ReferenceInput refers to a deleted resource

### ISSUE THREAD

**Issue by despatates** [marmelab/react-admin#2058] opened 2018-07-20 19:41 UTC
**Context:**
I have a form to edit `company` resource.
A company can have a parent company.

In the edit form, I'm using a `ReferenceInput` with an `AutocompleteInput` to select the parent company to set for the current one.

When I try to edit a company, the edit form is reloading indefinitely if the parent company has been deleted (a `404` error is returned by the server).

**What you were expecting:**

When a `ReferenceInput` refers to a deleted resource, do not try to load it again and again.

**What happened instead:**

The edit form seems to reload indefinitely.
When I look the network tab in chrome inspector, I can see the following requests looping:
- the request loading the main resource, request ok.
- the request loading possible values for the `ReferenceInput`/`AutocompleteInput`, request ok.
- the request loading the current related object (deleted), raising a `404`.

**Steps to reproduce:**

- Build a form to edit a resource.
- In this form, include a `ReferenceInput` referencing another resource.
- Try to edit a resource having a related resource no more existing (so your server raise a `404`).

**Related code:**

My form is:
```js
const CompanyEdit = props => (
  <Edit {...props}>
    <SimpleForm>
      <TextInput source="name" />
      <ReferenceInput
        source="parent_id"
        reference="company"
        filterToQuery={searchText => ({ name: searchText })}
        sort={{ field: 'name', order: 'ASC' }}
        allowEmpty
      >
        <AutocompleteInput optionText="name" />
      </ReferenceInput>
    </SimpleForm>
  </Edit>
);
```

My main resource:
```json
{
  "id": 5,
  "name": "My company",
  "parent_id": 1
}
```

The request done by the `ReferenceInput` to load the related resource (attribute `parent_id`):
```
GET /api/model/company/1
```
This request raise a `404` error because this resource doesn't exist anymore.

**Other information:**

I tried with `ReferenceField` in place of `ReferenceInput`, all is working correctly. The text field is not displaying the parent company field, and the form is not reloading indefinitely.

**Environment**

* React-admin version: 2.1.2
* React version: 16.4.1
* Browser: Chrome 67.0.3396.99

**Comment by djhi** [comment] 2018-07-20 19:49
Thanks for reporting. Closing it as a duplicate of #2014 though

**Closed by djhi** 2018-07-20 19:49 UTC
