### ISSUE TITLE
Missing dependency history

### ISSUE THREAD

**Issue by numediaweb** [marmelab/react-admin#7471] opened 2022-04-01 13:13 UTC
The `CoreAdminContext` uses `history` package but this package is not required on the `package.json`. 

This leads to this error when I run my react app `npm run start`:
```
/node_modules/ra-core/esm/core/CoreAdminContext.js
Module not found: Can't resolve 'history' in '/Users/aidrissi/apps/myapp/node_modules/ra-core/esm/core'
```

When I check why this package is needed I get:
```
npm ls ra-core
app@0.1.0 /Users/me/apps/app
`-- @api-platform/admin@2.7.2
  `-- react-admin@3.19.6
    +-- ra-core@3.19.6
    +-- ra-i18n-polyglot@3.19.6
    | `-- ra-core@3.19.6  deduped
    `-- ra-language-english@3.19.6
      `-- ra-core@3.19.6  deduped
```

**Comment by fzaninotto** [comment] 2022-04-01 15:04
I can't reproduce this problem. 

what package manage & version are you using? What node version? Can you please join a repro?

**Comment by numediaweb** [comment] 2022-04-01 18:10
I am using NPM, default setup nothing fancy:
```
npm -v
6.14.7

node -v
v14.7.0
```

My package.json:

```
{
.... trimmed ....
  "dependencies": {
    "@api-platform/admin": "^2.7.2",
    "@api-platform/api-doc-parser": "^0.13.2",
    "@fortawesome/fontawesome-svg-core": "1.2.27",
    "@fortawesome/free-brands-svg-icons": "5.12.1",
    "@fortawesome/free-regular-svg-icons": "5.12.1",
    "@fortawesome/free-solid-svg-icons": "5.12.1",
    "@fortawesome/react-fontawesome": "0.1.8",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "4.0.0-alpha.42",
    "apexcharts": "^3.33.0",
    "clsx": "^1.1.1",
    "crypto-js": "^4.1.1",
    "framer-motion": "1.8.4",
    "history": "^5.3.0",
    "lodash": "^4.17.21",
    "pe7-icon": "1.0.4",
    "plotly.js": "^1.58.4",
    "prop-types": "^15.7.2",
    "query-string": "^7.1.1",
    "react": "^16.14.0",
    "react-apexcharts": "1.3.6",
    "react-circle": "1.1.1",
    "react-countup": "4.3.3",
    "react-dom": "^16.14.0",
    "react-feather": "2.0.3",
    "react-perfect-scrollbar": "1.5.8",
    "react-plotly.js": "^2.5.1",
    "react-redux": "7.2.0",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "react-scripts": "3.4.0",
    "react-scroll": "^1.8.2",
    "react-spinners": "0.8.0",
    "redux": "^4.1.2",
    "source-map-explorer": "^2.5.2",
    "states-us": "^1.0.1"
  },
  "scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "start": "react-scripts start",
    "build": "GENERATE_SOURCEMAP=false react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "format": "./node_modules/.bin/eslint --fix --ignore-path .gitignore ."
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-react": "7.18.3",
    "eslint-plugin-unused-imports": "0.1.2",
    "node-sass": "4.13.1",
    "prettier": "1.19.1",
    "prettier-eslint": "9.0.1",
    "prettier-eslint-cli": "5.0.0",
    "sass-vars-to-js-loader": "2.1.1"
  }
}

```

**Comment by fzaninotto** [comment] 2022-04-03 07:00
Thanks for the feedback.

So it seems your package manager doesn't make the `history` package available, even though it's required by `react-router`. `history` is marked as a `devDependency` in `ra-core`, it should probably be marked as a `dependency` instead. 

I'm marking this as a bug.

**Closed** 2022-04-04 11:45 UTC
Labels: bug
