### ISSUE TITLE
CSS display bug in production

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#1927] opened 2018-06-19 13:36 UTC
Hello, 
i encounter a bug.
when I refresh my page by emptying my cache I'm having big display problems.
For example, no input : 

![capture d ecran 2018-06-19 a 15 21 01](https://user-images.githubusercontent.com/9990521/41600435-383af522-73d6-11e8-9fb7-951f87701776.png)

And after login (the size of the site is 1em)
![capture d ecran 2018-06-19 a 15 20 40](https://user-images.githubusercontent.com/9990521/41600445-40736490-73d6-11e8-8180-16ad00aa32ee.png)

Also, I only encounter this problem in production.

**Environment**

* React-admin version: 2.0.3
* React version: 16.4.1
* Browser: Chrome 67

**Comment by Kmaschta** [comment] 2018-06-19 13:38
Is this related to https://github.com/marmelab/react-admin/issues/1782 ?

Check your minified classes. Do you have a different Material-UI version installed from your dependencies ?

**Comment by nacimgoura** [comment] 2018-06-19 13:42
In my dependencies, I have
```
"@material-ui/core": "~1.2.2",
"@material-ui/icons": "~1.1.0"
```

yes, it seems to be the same problem. When I return to the 1st page I do not encounter the bug until I empty my cache.

**Comment by Kmaschta** [comment] 2018-06-19 13:47
I close this issue since it's a duplicate of #1782 (I re-opened it)

There is a workaround to make it work on production: use a custom JssProvider with a global `generateClassName` function (example: https://github.com/marmelab/react-admin/issues/1782#issue-317565973)

Thanks for reporting this bug, feel free to add any details you have on the other issue!

**Closed by Kmaschta** 2018-06-19 13:47 UTC
Labels: duplicate
