### ISSUE TITLE
AuthorizationProvider checkAuth is not awaited

### ISSUE THREAD

**Issue by crtl** [marmelab/react-admin#8420] opened 2022-11-21 19:51 UTC
**What you were expecting:**
The promise returned by `checkAuth` should be awaited correctly and pages should only be displayed after it is resolved.

**What happened instead:**
Page is displayed empty and requests are executed.

**Steps to reproduce:**
Create authProvider with checkAuth that never resolves.

```jsx
const AuthProvider = {
  checkAuth(params) => new Promise(() => {}),
  ...
}

const App = () => <Admin dataProvider={simpleRestProvider("http://localhost")} authProvider={AuthProvider}>
   <Resource name="users" list={ListGuesser} />
   <Resource name="feedback" list={ListGuesser} />
   <Resource name="reports" list={ListGuesser} />
</Admin>

```

Even though the promise never resolves the page is still displayed and the request to load `users` is executed.

**Related code:**
https://codesandbox.io/s/affectionate-torvalds-gnwfur?file=/src/authProvider.tsx Line 53

**Other information:**
I have a custom auth flow which first awaits firebase authentication and then uses the id token to authenticate against a backend.
I am not able to get it to work without the page first displaying the home list view, redirecting to login, then redirect back to overview where im now authenticated.

**Environment**

* React-admin version: 4.5.2
* React version: 17.0.2
* Browser: Chrome

**Comment by fzaninotto** [comment] 2022-11-21 21:29
Yep, @zenflow got it right. This is not a bug. So I'm closing the issue.

**Closed by fzaninotto** 2022-11-21 21:29 UTC
