### ISSUE TITLE
Document how to override notifications messages

### ISSUE THREAD

**Issue by dimitrovs** [marmelab/react-admin#1193] opened 2017-11-01 03:52 UTC
This has already been asked before: #180 but the answer provided was to basically not use the Admin component. I believe this could be a useful feature. Can we discuss some alternative approaches to provide an easier to use and user friendly server messaging?

I propose to add support for a mapping file, similar to the way Translation messages are implemented, such that every error (or even every response) received from the server will be looked up in this server messages mapping file by the Admin on rest saga.

**Comment by fzaninotto** [comment] 2017-11-02 08:05
And do what? That means baking in the saga some predefined behaviors. Which ones?

**Comment by dimitrovs** [comment] 2017-11-03 05:54
The saga already shows the error message as a notification. What I am proposing is to support a map of resource + error code to a custom error message instead of the default one. This will allow us to give more meaningful notification messages instead of generic "Internal Server Error".

**Comment by fzaninotto** [comment] 2017-11-03 10:02
I think the solution for that is that you provide a custom saga. But we need to provide a way to disable aor's default error messages. So marking this as an enhancement.

**Comment by dimitrovs** [comment] 2017-11-10 03:59
For anybody else who needs this: if you are in control of your backend you can just return {message:'Text'} and Admin-on-rest will show the message text in the notification.

**Comment by alauper** [comment] 2018-01-19 02:18
@dimitrovs thaaaaank you.  I was scratching my head for hours trying to figure out how to override the generic error.

**Comment by djhi** [comment] 2018-02-16 17:17
@dimitrovs, can we close this then ?

**Comment by djhi** [comment] 2018-02-20 07:45
This is documented actually: See https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client (at the end, `Error format`).

How can we make this easier to find ?

**Comment by joe-at-startupmedia** [comment] 2018-04-03 12:13
Just stumbled into this issue today. It's documented in this issue as well.
https://github.com/marmelab/admin-on-rest/issues/843

**Comment by MROFerreiro** [comment] 2019-02-08 12:30
Even with the possibility to show a custom error message, translation of it is not possible. React-Admin assumes the message coming in `{error.message}` from server. If the server message is *"Couldn't find resource"* it's that message that will be shown in notification.

I think it would be better to error message be based on a code number/string. Something like, if server returns error object like the following `{error: {code: 405}}` it goes to `dictionary.error[*code from server error*]` and show that message in notification. If server has no code number/string show a default error message.

**Comment by djhi** [comment] 2019-02-08 12:35
Yes we can do a better job on documenting this. In the mean time, you should know that the notifications will always try to translate their texts (https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/layout/Notification.js#L83).

So, in order to translate your API errors, just make the error's message a translation key.

**Comment by wmwart** [comment] 2019-04-03 12:52
@djhi , how do you translate your Errors?

**Comment by djhi** [comment] 2019-04-03 13:04
Please ask this on StackOverflow

**Comment by wmwart** [comment] 2019-04-04 05:58
@djhi , OK. 
[https://stackoverflow.com/questions/55508741/how-to-handle-server-error-in-react-admin](https://stackoverflow.com/questions/55508741/how-to-handle-server-error-in-react-admin)

**Comment by imekinox** [comment] 2019-04-13 14:53
I just posted an answer on your stackoverflow question @wmwart

**Comment by jesseshieh** [comment] 2019-11-24 16:31
As @fzaninotto mentioned in a comment above, are there any plans to support disabling notifications? Should I open a new issue?

I see that **overriding** the error message is possible, but in my case, I'm looking for a way to **disable** the notification entirely. I posted a [stackoverflow question](https://stackoverflow.com/questions/58945845/react-admin-how-to-suppress-multiple-401-notifications) and looked at the source code, but I can't seem to find a way to do this. Anybody know a way to disable the notification?

The relevant part of the source I found is the [notification saga](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/notification.ts#L34) which always shows either the error, the error.message or the notification.body with no option to skip or ignore. Thanks for an awesome framework, btw!

**Comment by fzaninotto** [comment] 2019-11-24 17:59
No, we have no such plans. But you can achieve it in userland by overriding the Notification component in the layout.

**Comment by jesseshieh** [comment] 2019-11-24 18:05
Thanks @fzaninotto! I'll give that a try.

**Comment by pashaworks** [comment] 2019-12-18 10:53
> {message: 'Text'}
Can you give an example of what the error from the server should look like?
![2019-12-18_13-54](https://user-images.githubusercontent.com/49949779/71080212-c5c7a900-219d-11ea-9eba-4ef56a67e813.png)

**Comment by JulienMattiussi** [comment] 2020-03-05 17:28
@pavel-nano Can you give more detail of the situation illustrated by your screenshot ?
Like which kind of button have been clicked ? is it custom or not ? maybe the type of APi call and the error code ?

I tried to reproduce your notifcation "failing" message but without succes.
The network preview displayed is exactely what you need set a custom notification from the API. And for now, I don't understand why it didn't.

Note : Only way of possible bug I founded is in the Exporter if your csv export fails.

**Comment by JulienMattiussi** [comment] 2020-04-03 09:10
As we have no more information to progress on this issue since a long, I close it.

**Closed by JulienMattiussi** 2020-04-03 09:10 UTC
Labels: documentation, enhancement, needs more info, old
