### ISSUE TITLE
ArrayField cannot take in a source property with name of "items"

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6521] opened 2021-08-19 20:07 UTC
If I change the source property name from "items" to anything else (and change the API side) everything works as expected.

Works on refresh but not on navigation from List

![Screen Shot 2021-08-19 at 3 11 33 PM](https://user-images.githubusercontent.com/15056748/130137236-0ea0ac42-ddcb-4bbb-af5c-aca65f603147.png)

```
<Show {...props}>
    <SimpleShowLayout>
      <TextField source="id"/>
      <DateField source="invoiceDate"/>
      <ArrayField source="items" fullWidth>
        <Datagrid>
          <TextField source="productId"/>
          <TextField source="productName"/>
          <TextField source="productSize"/>
        </Datagrid>
      </ArrayField>
    </SimpleShowLayout>
  </Show>
```

```
    at http://localhost:3000/static/js/vendors~main.chunk.js:113837:24
    at div
    at div
    at FormControl (http://localhost:3000/static/js/vendors~main.chunk.js:10810:24)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:41532:31)
    at Labeled (http://localhost:3000/static/js/vendors~main.chunk.js:121830:24)
    at div
    at div
    at CardContent (http://localhost:3000/static/js/vendors~main.chunk.js:5297:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:41532:31)
    at CardContentInner (http://localhost:3000/static/js/vendors~main.chunk.js:125867:25)
    at SimpleShowLayout (http://localhost:3000/static/js/vendors~main.chunk.js:112777:21)
    at div
    at Paper (http://localhost:3000/static/js/vendors~main.chunk.js:20120:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:41532:31)
    at Card (http://localhost:3000/static/js/vendors~main.chunk.js:4976:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:41532:31)
    at div
    at div
    at ShowView (http://localhost:3000/static/js/vendors~main.chunk.js:112552:23)
    at RecordContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:84115:21)
    at ShowContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:85231:21)
    at ResourceContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:91043:21)
    at Show (http://localhost:3000/static/js/vendors~main.chunk.js:112283:79)
    at InvoiceShow
    at WithPermissions (http://localhost:3000/static/js/vendors~main.chunk.js:82121:23)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169136:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:169338:29)
    at ResourceContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:91043:21)
    at ResourceRoutes (http://localhost:3000/static/js/vendors~main.chunk.js:90909:17)
    at Resource (http://localhost:3000/static/js/vendors~main.chunk.js:90981:15)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169136:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:169338:29)
    at RoutesWithLayout (http://localhost:3000/static/js/vendors~main.chunk.js:91170:21)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3000/static/js/vendors~main.chunk.js:126561:24)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:41532:31)
    at C (http://localhost:3000/static/js/vendors~main.chunk.js:169393:37)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:166243:75)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:40234:24)
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:126679:26)
    at MyLayout
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169136:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:169338:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/vendors~main.chunk.js:90545:87)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169136:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:169338:29)
    at CoreAdminUI (http://localhost:3000/static/js/vendors~main.chunk.js:90761:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:168771:30)
    at ConnectedRouter (http://localhost:3000/static/js/vendors~main.chunk.js:49525:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/vendors~main.chunk.js:49648:25)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:166243:75)
    at TranslationProvider (http://localhost:3000/static/js/vendors~main.chunk.js:99553:28)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:165956:20)
    at CoreAdminContext (http://localhost:3000/static/js/vendors~main.chunk.js:90308:25)
    at AdminContext
    at Admin (http://localhost:3000/static/js/vendors~main.chunk.js:133713:22)
    at App
```

**Comment by davidhenley** [comment] 2021-08-19 20:16
LOL, this only breaks if the ArrayField source name is "items".

**Comment by fzaninotto** [comment] 2021-08-23 16:37
Hi, and thanks for your report.

Is it possible that the error comes from your data? If the `items` value isn't an array, this could cause the error you're describing. 

To dig further, we need a way to reproduce the error. Please fork the simple example codesandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak it to trigger the bug. If you can't reproduce it, it means the problem is on your side.

**Comment by WiXSL** [comment] 2022-01-28 11:10
No news for some time, I'm closing this issue.
Please, feel free to re-open it if you find a way to reproduce it.

**Closed by WiXSL** 2022-01-28 11:10 UTC
Labels: needs more info
