### ISSUE TITLE
Delete confirm dialog message is not compatible with german translations

### ISSUE THREAD

**Issue by iamstiil** [marmelab/react-admin#4946] opened 2020-06-16 10:06 UTC
**What you were expecting:**
The title inside of the confirm dialog should be `Lösche Machine #1` for resource `machine` if name is defined as `Machine |||| Machinen` for the german language.

**What happened instead:**
The actual title is `Lösche machine #1`

**Steps to reproduce:**
- Add german translations from `ra-language-german`.
- Create any resource.
- Create an item for that resource
- Switch to german (if not already done).
- Click `Löschen` to delete.

**Related code:**
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/button/DeleteWithConfirmButton.tsx#L76

The issue is in this line. `humanize` expects a second argument which determines if the string should not be uppercased. In german you need to uppercase the translation. We might need to move to lowercasing the english translation for the `name` key and uppercasing it manually in places we want it to be uppercase, rather than making it lowercase here. In german you would leave it uppercase in `name`.

**Environment**

* React-admin version: `3.6.1`
* Last version that did not exhibit the issue (if applicable):
* React version: `16.13.0`
* Browser: `Chrome`
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-06-16 12:47
Duplicate of #4783

**Closed by fzaninotto** 2020-06-16 12:47 UTC
