### ISSUE TITLE
expose react-hook-form hooks that are bundled with react-admin

### ISSUE THREAD

**Issue by bartvanremortele** [marmelab/react-admin#8393] opened 2022-11-15 12:07 UTC
**What you were expecting:**
I want to make use of certain react-hook-form hooks such as `useFormContext` and `useWatch`. If I want to do that with PNPM I need to install react-hook-form as a dependency on my project which causes major issues in combination with react-admin as the dependency is resolved to a different npm module. 

I assume the default intent is that users can import react-hook-form from the subdependency that comes with react-admin. That's quite bad practice and can [lead to a lot of bugs ](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html).

It would be better if react-admin would encapsulate react-hook-form and re-exports the enabled features from it's core package.

**What happened instead:**
If you do not install react-hook-form the dependency cannot be resolved. If you do the entire project breaks. Filters stop working and the form providers/context stops working.

**Steps to reproduce:**
Set-up a project with PNPM or with NPM using `npm c set global-style true`

**Related code:**
-

**Environment**

* React-admin version: 4.5.1
* Last version that did not exhibit the issue (if applicable): /
* React version: 18
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment] 2022-11-15 15:58
Thanks for submitting this.

React Admin should be compatible with any RHF version, provided that it respects the constraint on the version declared as [peerDependency](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/package.json#L54).
- If you do not add RHF to your project, then it is still available in the node_modules because RA needs it, so you **can** import  the hooks from it (tested successfully with yarn and npm)
- If you add RHF to your project, and it meets the minimum version required in peerDependencies (^7.34.2 at the time of writing), it should work too, unless RHF made a BC in a recent version

However, I must admit I have not tested with pnpm, and I shall do so.

Could you also please provide the detail of the resolved RHF versions for your workspace, that cause the application to break?

Thanks.

**Comment by bartvanremortele** [comment] 2022-11-15 16:14
Hi, thanks for following up. 

The module isolation that PNPM introduces makes it impossible to import the version that RA uses. What I tried next was add react-hook-form as a dependency on our RA app. However that resulted in most things breaking.

In our case we have a monorepo set-up with PNPM which includes a react-app and a react-admin app. Both of them use react-hook-form but our main app uses a different version. Installing react-hook-form inside the react-admin app resulted in yet another version of react-hook-form and still broke the admin app.

After a lot of different attempts, I've managed to find a workaround by utilizing PNPM's `hoist-pattern` in .npmrc. Documentation can be found [here](https://pnpm.io/npmrc#hoist-pattern).

```
hoist-pattern[]=*
hoist-pattern[]=!react-hook-form
hoist-pattern[]=!react-admin
```

The above does require me to install react-hook-form in the react-admin app and re-using the exact same version that was resolved by the lock file for the RA dependency which is worries me that as soon as the lockfile changes and ra-core defines a new version of react-hook-form it will break again.

**Comment by fzaninotto** [comment] 2022-11-16 08:31
I disagree, this is not a bug with react-admin, but a strong limitation of pnpm. This limitation will create many other bugs as you won't be able to wrap react-admin with a custom Router from react-router, or a ThemeProvider from mui.

Also, re-exporting the hooks of third-party library sounds very weird to me - I've never seen that in any library. It would force us to document the fact that users should use our hooks instead of the ones from the third-party libraries... This is not something we want to do. 

I prefer to say that we don't support pnpm rather than force all users to learn a new way to use dependencies. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2022-11-16 08:31 UTC
Labels: bug

**Comment by osseonews** [comment] 2022-12-22 02:22
Interesting, I just ran across this same issue. I am surprised you won't fix this to work with pnpm. pnpm is becoming increasingly popular for whatever reason. Actually, nearly all the main repos we use have now upgraded to pnpm, and now we are trying to use react-admin inside those apps, and we simply can't. pnpm won't install the peer dependencies properly.  I don't like pnpm either, but nothing you can do, if other major repos start using exclusively (btw, I think they use it b/c it allows for an easy way to manage a monorepo with workspaces). So now we are stuck with either abandoning react-admin or somehow hacking away at another repo to replace pnpm with yarn. Both bad choices. What is the reason for not supporting pnpm in react-admin?

**Comment by slax57** [comment] 2022-12-22 14:26
@osseonews it's simply because we couldn't figure out a way to make our packages work with pnpm without breaking the peer dependencies.
To us, it is very surprising that pnpm does not to support them, and we believe the fix should rather come from pnpm than react-admin, because it affects many other libraries, not only us.
Still, if you think you know a way to change our packages manifests to make them compatible with pnpm, without breaking the compatibility with npm and yarn, then we would gladly accept your help! Feel free to open a PR!

**Comment by osseonews** [comment] 2022-12-22 14:29
Thanks. I actually just decided to refactor our current repo to get rid of pnpm :0). Honestly, I'm not sure why pnpm is gaining so much in popularity. Yarn seems fine to me.

**Comment by TimKraemer** [comment] 2023-08-18 14:25
Sorry for potentially hijacking this thread...
I might have misunderstood something here, but I'm using `yarn` as my package-manger. `yarn add react-admin` gets me a working setup in which I can use something like this simplified example using `useFormContext()` according to [the react-admin documentation of `Form`](https://marmelab.com/react-admin/Form.html)
```jsx
import { TextInput, useInput } from "react-admin"
import { useFormContext } from "react-hook-form"

export default function CustomNameInput() {
  const { setValue } = useFormContext()
  const nameInput = useInput({ source: "name" })

  const handleGeneratedName = () => {
    if (nameInput.field.value) {
      setValue("generatedName", nameInput.field.value.toLowerCase())
    }
  }
 
  return (
    <>
      <TextInput source="name" />
      <TextInput source="generatedName" />
    </>
  )
}
``` 

the problem now is, that eslint is now bugging me that ['react-hook-form' should be listed in the project's dependencies.](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md).
If I install it with `yarn add react-hook-form` it stops working and throwing errors that `setValue` doesn't exist.

In general it feels weird to me to use old or modified versions of a named package and then introducing compatibility issues. How would I ever use the actual `react-hook-form` package if needed in the same project?

**Comment by djhi** [comment] 2023-08-18 15:03
That's probably because yarn installed two versions of the `react-hook-form` package. Check your `yarn.lock` file for duplicates.

**Comment by TimKraemer** [comment] 2023-08-18 17:28
> That's probably because yarn installed two versions of the `react-hook-form` package. Check your `yarn.lock` file for duplicates.

You are absolutely right! Manually removing the duplicate from `yarn.lock` file and calling `yarn install` and `yarn add react-hook-form` fixed my issue. Thank you very much!
