### ISSUE TITLE
Doubled calls to REST api in AutocompleteArrayInput

### ISSUE THREAD

**Issue by instantlinux** [marmelab/react-admin#4509] opened 2020-03-11 16:11 UTC
**What you were expecting:**
When I type each character into an autocomplete field under ReferenceArrayInput, I expect to see a single call to getList for the backend API.

**What happened instead:**
Upon each character typed, I see two dataProvider API calls with the same filter settings. Example:
```
{
  "filter": {"name": "d%"},
  "limit": 40,
  "offset": 0,
  "sort": "name:asc",
  "status": "active"
}
```
Then when I type the next character, I see two more (example as above but with filter: {name: "da%"}. (The latter calls may not even need to happen at all, because if the previous call returned fewer than the limit, all the data is already in memory.)

**Steps to reproduce:**
This happens for any case within my codebase that follows the [AutocompleteArrayInput doc](https://marmelab.com/react-admin/Inputs.html#autocompletearrayinput) example for use with ReferenceArrayInput. The case I'm reporting here that generates the above query params uses a source endpoint that has about 50 _person_ records indexed by a _name_ field:
```
            <ReferenceArrayInput label='Members' source='members'
                    sort={{ field: 'name', order: 'ASC' }}
                    reference='person' optionText='name' perPage={40} >
                <AutocompleteArrayInput />
            </ReferenceArrayInput>
```

**Other information:**
This was previously reported and apparently fixed in issue #3108; this may be a regression or another aspect of the same underlying problem.

My code in dataProvider is:
```
    getList: (resource, params) => {
        const query = {
            limit: params.pagination.perPage,
            offset: (params.pagination.page - 1) * params.pagination.perPage,
            status: ['active'],
        };
        if (params.sort) {
            query.sort = params.sort.field + ':' + params.sort.order.toLowerCase();
        }
        if (params.filter.hasOwnProperty('q')) {
            params.filter.name = params.filter.q + '%';
            delete params.filter.q;
        }
        if (Object.keys(params.filter).length > 0) {
            query.filter = JSON.stringify(params.filter);
        }
        return httpClient(`${urlPrefix(resource)}?${stringify(query)}`).then((
            { json }) => ({data: json.items, total: json.count})) },
```
**Environment**

* React-admin version: 3.2.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.12.0
* Browser: Chrome 80.0.3987.116
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-03-18 22:13
I can't reproduce it on master. The simple example contains such an AutocompleteArrayInput in the Post edit page, misc tab, tag edition. it makes only oneAPI call per keystroke (as seen in the console logs). 

Please fork [the simple example codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and try and reproduce your issue. When you're done, please paste the code to your codesandbox here.

**Comment by instantlinux** [comment] 2020-03-23 05:53
I upgraded to 3.3.1 hoping that'd fix it, but alas I still see it in my setup. Will have to see if I can repro it in the sandbox.

**Comment by jdemangeon** [comment] 2020-04-14 08:02
Hello @instantlinux :) Have you been able to reproduce the problem in the sandbox?

**Comment by instantlinux** [comment] 2020-04-14 14:43
It's been a lot of effort to split out my code between proprietary and open-source; in the past couple of days I've finally made two new repos [instantlinux/apicrud](/instantlinux/apicrud) with the backend and [instantlinux/apicrud-ui](/instantlinux/apicrud-ui) with the front-end. The problem does reproduce when using docker images built from those. When I find time I'll figure out how to use the sandbox to load that code.

**Comment by fzaninotto** [comment] 2020-06-02 21:42
No news for some time, so I'm closing this issue.

**Closed by fzaninotto** 2020-06-02 21:42 UTC
Labels: needs more info
