### ISSUE TITLE
Can't include in app with connected-react-router v5

### ISSUE THREAD

**Issue by AleBlondin** [marmelab/react-admin#2549] opened 2018-11-20 09:47 UTC
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/react-admin).

**What you were expecting:**
I include React-admin in my app. I expect it to work, it crashes.

**Steps to reproduce:**
Have an App that uses connected-react-router, especially v5. The routing state in redux is stored under a key named "router" and [cannot be changed](https://github.com/supasate/connected-react-router/releases/tag/v5.0.0).
However in react-admin the key is named "routing" and [cannot be changed either](https://marmelab.com/react-admin/CustomApp.html).
For information react-router-redux (used by react-admin) is deprecated, the new library to use is connected-react-router

**Suggested change:**
I suggest changing the routing store key name in react-admin from "routing" to "router". I believe it involves changing these only 3 files:
- packages/ra-core/src/sideEffect/auth.js
- packages/ra-core/src/reducer/index.js
- packages/ra-ui-materialui/src/layout/Menu.js

And documentation:
- docs/CustomApp.md
-  docs/Admin.md

I would glady open a PR.

**Other information:**

**Environment**

* React-admin version: 4.2.4
* Last version that did not exhibit the issue (if applicable): /
* React version: 16.6.0
* Browser: Chrome
* Stack trace (in case of a JS error):
![image](https://user-images.githubusercontent.com/25102531/48764874-29d52080-ecb1-11e8-8959-83dc5bef530b.png)

**Comment by fzaninotto** [comment] 2018-11-20 17:14
Duplicate of #1999.

**Comment by AleBlondin** [comment] 2018-11-20 17:44
@fzaninotto I don't agree it is a duplicate. I am not saying that react-router-redux is deprecated, but that react-admin is not compatible with connected-react-router.
I believe it is possible to make the 2 compatible with each other without any lib upgrade.

**Comment by fzaninotto** [comment] 2018-11-20 17:47
Sorry, I must have misunderstood something. You're saying that connected-react-router doesn't allow to change the routing key in the state, so I don't understanb how your proposed change can be backwards compatible.

**Comment by AleBlondin** [comment] 2018-11-20 19:02
Indeed, connected-react-router doesn't allow to change the routing key in the state, but redux-react-router does. I suggest changing the routing key in react-admin while it still uses redux-react-router.

I hope I made myself clearer :smiley:

**Comment by fzaninotto** [comment] 2018-11-21 01:36
Yes, now I understand, thanks. I'd gladly accept a PR to change the routing key in the react-admin state. Please open it against `next`, because even if this key isn't a public API, I prefer that people using it have their application broken by upgrading to a minor rather than a bugfix.

**Comment by fzaninotto** [comment] 2018-11-21 08:56
Fixed by #2551

**Comment by fzaninotto** [comment] 2018-11-21 09:04
Sorry, wrong issue.

**Comment by djhi** [comment] 2018-11-21 09:04
Make sure we don't use any selectors from `redux-react-router`. I think they can't be configured to use another key than `routing`

**Comment by AleBlondin** [comment] 2018-11-21 11:13
The redux-react-router docs say [here](https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-or-another-state-wrapper-with-my-redux-store) that you can specify a custom routing state selector if needed.
However, it is only if you use the `syncHistoryWithStore` method. It seems it isn't needed since v5 alpha of redux-react-router (the version used by react-admin). Plus this method is not used in react-admin.

I created the PR, the tests pass. Do you think I ought to write documentation about this change ? And where would I write it ?

**Comment by AleBlondin** [comment] 2018-11-21 11:44
Ok thanks. I think my PR is ready, it is [here](https://github.com/marmelab/react-admin/pull/2553)

**Comment by fzaninotto** [comment] 2018-11-21 12:43
Fixed by #2553

**Closed by fzaninotto** 2018-11-21 12:43 UTC
