### ISSUE TITLE
Unable to override SortButton styling

### ISSUE THREAD

**Issue by CleverAtBen** [marmelab/react-admin#9161] opened 2023-08-03 09:10 UTC
**What you were expecting:**
Sort button to use styling props as similar Tool bar action buttons do

**What happened instead:**
styling props have no effect

**Related code:**

With the following code the Sort Button is not styled in the same way as the Export and Create Button

```
        <TopToolbar>
            <SortButton color="inherit" fields={['lastName', 'firstName', 'lastSeen', 'lastBooking', 'createdDate']} />
            <ExportButton color="inherit" />
            <CreateButton color="inherit"/>
        </TopToolbar>

```

**Comment by fzaninotto** [comment] 2023-08-03 13:25
Well, since the support for extra props isn't documented, it's not a bug ;) So I'm marking this as an enhancement. Feel free to open a PR adding the support for extra props.

**Comment by akshayaqburst** [comment] 2023-08-09 20:27
I will work on this

**Comment by slax57** [comment] 2023-08-28 12:53
Implemented via https://github.com/marmelab/react-admin/pull/9223

**Closed by slax57** 2023-08-28 12:53 UTC
Labels: enhancement
