### ISSUE TITLE
unSelectAll not working

### ISSUE THREAD

**Issue by anuraram12345** [marmelab/react-admin#3289] opened 2019-05-30 20:51 UTC
**Related code:**

```
onSuccess: {
            notification: {
                body: 'Republishing versions to existing saved spaces',
                level: 'info',
                messageArgs: {
                    smart_count: ids.length,
                },
            },
            basePath,
            refresh:true,
            redirectTo: "/versions",
            unselectAll:true,
        },
```

I have the above code unSelectAll is not working.The selected items are still selected

**Comment by Kmaschta** [comment] 2019-06-03 06:20
Please use the bug template and provide a bit more context in order to help maintainers found what's wrong.

Also, I see that your code, at `unselectAll` the S of select isn't capitalized. Is this the source of your issue?

**Comment by hamzhi** [comment] 2019-06-14 21:49
HI, I have the same problem. I tried to use 'Mutation' for bulk buttons, data are updating, but checkboxes are still select. It seems the problem is that the field "selectedIds" in the store is not updating. Below is the code:

`import React, { Fragment } from 'react'
import PropTypes from 'prop-types'
import { Button, Mutation } from 'react-admin'

const sideEffects = {
  onSuccess: {
    notification: {
      body: 'ra.notification.updated',
      level: 'info'
    },
    unselectAll: true,
    refresh: true
  },
  onFailure: {
    notification: {
      body: 'ra.notification.http_error',
      level: 'warning'
    }
  }
}

const BulkActionButtons = props => {
  const { resource, selectedIds } = props
  const path = resource + '/block'

  return (
    <Mutation
      type="UPDATE_MANY"
      resource={path}
      payload={selectedIds.join(',')}
      options={sideEffects}
    >
      {approve => (
          <Button
            label="own.buttons.block"
            color="primary"
            variant="outlined"
            onClick={approve}
            className="user-bulk-button"
          />
      )}
    </Mutation>
  )
}

BulkActionButtons.propTypes = {
  resource: PropTypes.string.isRequired,
  selectedIds: PropTypes.arrayOf(PropTypes.any).isRequired
}

export default BulkActionButtons
`

**Comment by fzaninotto** [comment] 2019-06-17 12:52
I can't reproduce on `next`. Please provide a link to a codeSandbox reproducing the problem.

P.S.: I think your payload is wrong. UPDATE_MANY expects a payload under the shape { ids, data }

**Comment by anuraram12345** [comment] 2019-06-19 18:36
import { Identifier, Record } from 'react-admin';
import { UPDATE_MANY } from 'react-admin';
import { CRUD_UPDATE_MANY } from 'react-admin';
import {  RefreshSideEffect } from 'react-admin';

export const republishMultiple = (
    resource: string,
    ids: Identifier[],
    data: any,
    basePath: string,
    redirectTo: RedirectionSideEffect = 'list',
    refresh: RefreshSideEffect = true
): CrudUpdateManyAction => ({
    type: CRUD_UPDATE_MANY,
    payload: { ids, data },
    meta: {
        resource:"versions/republish",
        fetch: UPDATE_MANY,
        undoable: true,
        onSuccess: {
            notification: {
                body: 'Republishing versions to existing saved spaces',
                level: 'info',
                messageArgs: {
                    smart_count: ids.length,
                },
            },
            basePath,
            refresh:true,
            redirectTo: "/versions",
            unSelectAll:true,
        },
        onFailure: {
            notification: {
                body: 'ra.notification.http_error',
                level: 'warning',
            },
        },
    },
});


const PostBulkButtons = props => (
  <Fragment>
      <RepublishMultipleButton label="RePublish" {...props} />
  </Fragment>
);

**Comment by anuraram12345** [comment] 2019-06-19 19:24
Please look at the above code I have unSelectAll true not working

**Comment by fzaninotto** [comment] 2019-06-20 06:27
again, since the bug may come from other parts in your code, please fork the react-admin codesandbox and add the minimum code to reproduce your issue.

**Comment by hamzhi** [comment] 2019-06-21 08:59
I cannot reproduce the problem in the codeandbox, in my opinion, this is because fake dataProvider is used there. I noticed a difference in the action CUSTOM_FETCH_SUCCESS, in my case this action does not change the state: list-> selectedIds

**Comment by anuraram12345** [comment] 2019-07-02 16:49
I have the below button and below Code

But the Select box is still shows clicked.I am using the crudUpdateMany of react admin.
I reduced my code

const PostBulkButtons = props => (
  <Fragment>
      <RepublishMultipleButton label="RePublish" {...props} />
  </Fragment>
);

// in ./ResetViewsButton.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { SaveButton} from 'react-admin'; 
import { crudUpdateMany } from 'ra-core';

class PromoteMultipleButton extends Component {
    handleClick = () => {
        const { basePath, promoteMultiple, resource, selectedIds } = this.props;
        crudUpdateMany(resource, selectedIds, { views: 0 }, basePath);
    };

    render() {
        const { handleSubmitWithRedirect, promote, ...props } = this.props;
        return (
          <SaveButton undoable={false} handleSubmitWithRedirect={this.handleClick} {...props} />
        );
      }
}

export default connect(undefined, { crudUpdateMany })(PromoteMultipleButton);

**Comment by fzaninotto** [comment] 2019-07-07 21:09
I don't know why you use a `SaveButton` - a simple `Button` should do the trick.

I don't think that the problem comes from the dataProvider in CodeSandbox - we've managed to use `crudUpdateMany` with success with other data providers, and it unselects the lines correctly. 

Again, please try to isolate the bug in a CodeSandbox - we can't use your code to reproduce the bug.

**Comment by anuraram12345** [comment] 2019-07-17 17:01
I kept the Simple Button.The Selection in Checkbok is not going away at all.This issue is easily reprodusable.Please fix

const PostBulkButtons = props => (
  <Fragment>
      <RepublishMultipleButton label="RePublish" {...props} />
  </Fragment>
);

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Button, crudUpdateMany } from 'react-admin';

class RepublishMultipleButton extends Component {
    handleClick = () => {
        const { basePath, crudUpdateMany, resource, selectedIds } = this.props;
        crudUpdateMany("versions/republish", selectedIds, { views: 0 }, basePath);
    };

    render() {
        return (
            <Button label="Reset Views" onClick={this.handleClick} />
        );
    }
}

export default connect(undefined, { crudUpdateMany })(RepublishMultipleButton);

**Comment by anuraram12345** [comment] 2019-07-17 17:03
The above code is using react-admin's data Provider.

**Comment by Kmaschta** [comment] 2019-07-18 11:22
I read three times this issue, and I'm still not sure what is going on.

@anuraram12345 No, if you don't come with the full context or with a minimal example with the bug, it is not easily reprodusable.

On the demo, we have a example of `crudUpdateMany` usage, that works just fine, running on the latest React Admin version.

See : https://marmelab.com/react-admin-demo/#/reviews
Code : https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/ReviewList.js

Please, fork the demo, make it work on CodeSandbox, or somewhere so that we can see the bug by ourselves.

My assumption is that if something goes wrong with the API / GraphQL server while doing the change, the data isn't refreshed.

But if we can't reproduce, we will not be able to fix it and we'll have to close this issue.

**Comment by gladium-software** [comment] 2019-07-23 08:18
This has been driving me crazy for months, so thought I'd spend a bit of time running through it today.

The issue occurs when you pass in a resource with an extra path. For example, if you have:

<Resource name='myawesomeresource' />

These work: 
`crudUpdateMany(resource, selectedIds, { status: 'accepted' }, basePath)`
or
`crudUpdateMany('myawesomeresource', selectedIds, { status: 'accepted' }, basePath)`

However this doesn't:
`crudUpdateMany('myawesomeresource/with/a/path', selectedIds, { status: 'accepted' }, basePath)`

I've not started looking at the underlying code in crudUpdateMany yet, but wanted to share this ASAP.

@anuraram12345  - looks like you're trying to do what I am.

**Comment by anuraram12345** [comment] 2019-07-23 17:18
I copied the Burtton Code from the repo Url that you provided
https://github.com/marmelab/react-admin/blob/master/examples/demo/src/reviews/ReviewList.js

This works fine
The select checkbox is getting cleared when i come back to page.so i am good
Thanks

**Comment by hamzhi** [comment] 2019-07-23 17:56
@gladium-software 
Your solution solved my problem too. Thank you

In my code above:
...
const path = resource + '/block'  // this change to  const path = resource
...
and made some changing in my dataProvider

**Comment by gladium-software** [comment] 2019-07-23 18:04
@hamzhi - could you share the changes for the dataProvider?

**Comment by hamzhi** [comment] 2019-07-23 18:08
`
...
  const payload = { ids: selectedIds, data: { **action: action** } }

  return (
    <Mutation
      type="UPDATE_MANY"
      resource={resource}
      payload={payload}
      options={sideEffects}
    >
      {approve => (
        <Button
          label={`own.buttons.${action}`}
          color="primary"
          variant="outlined"
          onClick={approve}
          className="user-bulk-button"
        />
      )}
    </Mutation>
  )
}
`
And changes in dataProvider

`
...
case UPDATE_MANY: {
      **if (params.data && params.data.action) {
        resource = `${resource}/${params.data.action}`
      }**
      url = `${apiUrl}/${resource}?${stringify({ ids: params.ids.join(',') })}`
      options.method = 'PUT'
      break
    }
...
`

**Comment by gladium-software** [comment] 2019-07-23 18:11
@hamzhi  Ah ha, nice. Thanks.

**Comment by Kmaschta** [comment] 2019-09-23 13:04
I'll close this one since a workaround has been found and there is no news from two months on this issue.

Feel free to comment with more details or open a new issue with a reproducable Code Sandbox.

**Closed by Kmaschta** 2019-09-23 13:04 UTC
Labels: awaiting more info
