### ISSUE TITLE
Bug on ressource GetList

### ISSUE THREAD

**Issue by kyo06** [marmelab/react-admin#2497] opened 2018-11-03 21:25 UTC
**What you were expecting:**
I would like to get a list of ressources (it is empty) getting from Loopback (I use loopback-component-react-admin on the server side).

**What happened instead:**
I get an error when it connects on the REST api and get an empty list (it is normal there are no data) and gets this warning 
 "Warning: Missing translation for key: "Cannot read property 'has' of undefined""
and after it logoff (because there is en Error)

**Related code:**
```
export const NeedsList = (props) => (
<List {...props}>
        <Datagrid>
        <TextField source="id" />
                        <TextField source="name"  />                  
        </Datagrid>
    </List>
);
```
**Environment**

* React-admin version: 2.4.1
* React version: 16.6.0
* Browser: Google Chrome
* Stack trace (in case of a JS error):
function.console.(anonymous function) (index.js:1452)
warning (browser.js:43)
warn (index.js:28)
push../node_modules/node-polyglot/index.js.Polyglot.t (index.js:335)
Notification.render (Notification.js:145)
finishClassComponent (react-dom.development.js:8747)
updateClassComponent (react-dom.development.js:8715)
beginWork (react-dom.development.js:9364)
performUnitOfWork (react-dom.development.js:12372)
workLoop (react-dom.development.js:12402)
renderRoot (react-dom.development.js:12431)
performWorkOnRoot (react-dom.development.js:13028)
performWork (react-dom.development.js:12949)
performSyncWork (react-dom.development.js:12927)
requestWork (react-dom.development.js:12817)
scheduleWorkImpl (react-dom.development.js:12691)
scheduleWork (react-dom.development.js:12650)
enqueueSetState (react-dom.development.js:6920)
push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:386)
(anonymous) (Router.js:102)
listener (createTransitionManager.js:55)
(anonymous) (createTransitionManager.js:73)
notifyListeners (createTransitionManager.js:72)
setState (createHashHistory.js:107)
(anonymous) (createHashHistory.js:199)
confirmTransitionTo (createTransitionManager.js:45)
push (createHashHistory.js:183)
(anonymous) (middleware.js:19)
(anonymous) (formMiddleware.js:22)
(anonymous) (middleware.js:72)
dispatch (applyMiddleware.js:46)
(anonymous) (utils.js:282)
(anonymous) (proc.js:557)
exec (scheduler.js:20)
flush (scheduler.js:63)
asap (scheduler.js:35)
runPutEffect (proc.js:553)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
Promise.then (async)
resolvePromise (proc.js:515)
runCallEffect (proc.js:584)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
runSelectEffect (proc.js:784)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
(anonymous) (proc.js:516)
Promise.then (async)
resolvePromise (proc.js:515)
runCallEffect (proc.js:584)
runEffect (proc.js:496)
next (proc.js:366)
proc (proc.js:314)
runForkEffect (proc.js:625)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
takeCb (proc.js:531)
put (channel.js:88)
(anonymous) (channel.js:190)
(anonymous) (channel.js:211)
emit (channel.js:39)
(anonymous) (middleware.js:74)
dispatch (applyMiddleware.js:46)
(anonymous) (utils.js:282)
(anonymous) (proc.js:557)
exec (scheduler.js:20)
flush (scheduler.js:63)
asap (scheduler.js:35)
runPutEffect (proc.js:553)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
(anonymous) (proc.js:516)
Promise.then (async)
resolvePromise (proc.js:515)
runCallEffect (proc.js:584)
runEffect (proc.js:496)
next (proc.js:366)
currCb (proc.js:449)
checkEffectEnd (proc.js:689)
chCbAtKey (proc.js:707)
currCb (proc.js:449)
(anonymous) (proc.js:567)
exec (scheduler.js:20)
flush (scheduler.js:63)
asap (scheduler.js:35)
(anonymous) (channel.js:215)
emit (channel.js:39)
(anonymous) (middleware.js:74)
(anonymous) (bindActionCreators.js:3)
ListController.updateData (ListController.js:265)
ListController.componentDidMount (ListController.js:194)
commitLifeCycles (react-dom.development.js:10251)
commitAllLifeCycles (react-dom.development.js:11994)
callCallback (react-dom.development.js:107)
invokeGuardedCallbackDev (react-dom.development.js:144)
invokeGuardedCallback (react-dom.development.js:191)
commitRoot (react-dom.development.js:12138)
completeRoot (react-dom.development.js:13086)
performWorkOnRoot (react-dom.development.js:13032)
performWork (react-dom.development.js:12949)
performSyncWork (react-dom.development.js:12927)
interactiveUpdates (react-dom.development.js:13193)
interactiveUpdates (react-dom.development.js:2057)
dispatchInteractiveEvent (react-dom.development.js:4474)

**Comment by fzaninotto** [comment] 2018-11-05 22:09
Hi kyo06, and thanks for the report. 

This is probably a bug in your data provider, as I can't reproduce it on the demo (where I added a filter on a list to return zero results, e.g. https://marmelab.com/react-admin-demo/#/customers?filter=%7B%22last_seen_gte%22%3A%222019-05-29%22%7D&order=DESC&page=1&perPage=25&sort=last_seen).

So I'm closing this issue as it's not a bug we can fix. Feel free to reopen it if you can provide a CodeSandbox showing a failure with one of react-admin core data providers.

**Closed by fzaninotto** 2018-11-05 22:09 UTC
