### ISSUE TITLE
Empty List Component is only visible without any live filters

### ISSUE THREAD

**Issue by UtsavEuler** [marmelab/react-admin#10239] opened 2024-09-25 06:30 UTC
**Is your feature request related to a problem? Please describe.**
I want to display a custom component when the user tries to filter something in the list and there were no results.
I used the empty prop for the List component but looking at the code it only works when there are no live filters.

```
    const shouldRenderEmptyPage =
        !isLoading &&
        data?.length === 0 &&
        !Object.keys(filterValues).length &&
        empty !== false;
```

**Describe the solution you'd like**
Either remove the filters length check or have a separate prop like emptyWithFilters.

**Additional context**
In my case i have a bunch of tickets, the user might not have access to the ticket based on locations they have been given access to or they might be filtering and getting no results, so I want to have a custom component for empty list describing steps in detail.

**Comment by fzaninotto** [comment] 2024-09-27 17:32
The `<List empty>` prop is indeed designed for resources for which there is no record at all (usually to display an invitation to create a new record). In that case, it doesn't make sense to render the filters or the pagination. 

Your use case is different, as you should render the applied filters.

You can implement your used case in user land without modifying the framework. For example, you can create a custom component that renders either the Datagrid or your custom component based on the condition you need. Something like:

```jsx
const TicketList = () => (
   <List>
      <TicketListContent />
   </List>
);

const TicketListContent = () => {
   const { isPending, total, filterValues } = useListContext();
   return (/* your own condition *) ? <DescribeSteps /> : <TicketDatagrid />;
};
```

Does that solve your problem?

**Comment by UtsavEuler** [comment] 2024-09-28 08:56
Thanks for help makes sense.

**Comment by fzaninotto** [comment] 2024-09-30 11:58
Good, so I'm closing your issue as it's not a bug.

**Closed by fzaninotto** 2024-09-30 11:58 UTC
Labels: needs more info
