### ISSUE TITLE
Failed to start development server

### ISSUE THREAD

**Issue by quangthe** [marmelab/react-admin#5140] opened 2020-08-12 07:54 UTC
**What you were expecting:**

Can setup the project, according to the tutorial https://marmelab.com/react-admin/Tutorial.html 
```
yarn create react-app test-admin
cd test-admin/
yarn add react-admin ra-data-json-server prop-types
yarn start
```

**What happened instead:**

`yarn start`
```
./node_modules/ra-ui-materialui/esm/list/index.js
Cannot find file: 'filter.js' does not match the corresponding name on disk: './node_modules/ra-ui-materialui/esm/list/Filter.js'.
```

**Steps to reproduce:**

Follow the tutorial (https://marmelab.com/react-admin/Tutorial.html) steps: 
```
yarn create react-app test-admin
cd test-admin/
yarn add react-admin ra-data-json-server prop-types
```
Edit the App.js
```
import React from 'react';
import { Admin } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
const App = () => <Admin dataProvider={dataProvider} />;

export default App;
```

Then start development server
```
yarn start
```

**Related code:**

**Other information:**

However if I run `yarn run build` and serve build on port 5000 then it has no issue. Look like issue happens on development mode.

**Environment**

* React-admin version: 3.8.0
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error):
```
Uncaught Error: Cannot find module './filter'
    at webpackMissingModule (index.js:1)
    at Module../node_modules/ra-ui-materialui/esm/list/index.js (index.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/ra-ui-materialui/esm/index.js (index.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/react-admin/esm/AdminUI.js (AdminUI.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/react-admin/esm/Admin.js (Admin.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/react-admin/esm/index.js (index.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/App.js (index.css:7)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/index.js (index.css?f3f6:45)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (serviceWorker.js:141)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
index.js:1 ./node_modules/ra-ui-materialui/esm/list/index.js
Cannot find file: 'filter.js' does not match the corresponding name on disk: './node_modules/ra-ui-materialui/esm/list/Filter.js'.
console.<computed> @ index.js:1
```

**Comment by djhi** [comment] 2020-08-12 08:27
Thanks for taking the time to open this issue. It's a duplicate of #5135 though so I'll close it

**Closed by djhi** 2020-08-12 08:27 UTC
