### ISSUE TITLE
[BUG] AutocompleteInput suggestion panel in wrong position

### ISSUE THREAD

**Issue by ronfogel** [marmelab/react-admin#2847] opened 2019-02-01 16:08 UTC
**What you were expecting:**
When suggestions are filtered (you wrote something in the autocomplete to get less or better results) and the autocomplete panel opens to the top, the panel position should be relative to the autocomplete input.

**What happened instead:**
It filtered the suggestions from 25 to less and the initial position as same as it was at the beginning. It fix the position after scroll or any interaction with the window.

**Steps to reproduce:**
1. Go to the sandbox provided below
2. Go to the comments tab
3. Click on edit on one of the comments
4. Click on the posts autocomplete input (it will open the suggestions panel)
5.  Scroll a little bit down when the autocomplete's panel is open (it will change the position of the panel - might also be a bug?)
6. Write something in the autocomplete to filter, for example: "qui tempore rerum et volup" (It will result in two suggestions)

**Related code:**
https://codesandbox.io/s/pyxyq9wrkj
(note that I overrided the inputValueMatcher so it wont auto select value)

**Other information:**
<img width="668" alt="screen shot 2019-02-01 at 18 05 20" src="https://user-images.githubusercontent.com/16741829/52134371-1c8ec780-264c-11e9-8866-e61a4db53f1f.png">

**Environment**

* React-admin version: 2.3.2 and above.
* Last version that did not exhibit the issue (if applicable): might be less, didnt check..
* React version: 16.3.1 and above
* Browser: Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2019-02-04 13:55
Duplicate of #2259

**Closed by fzaninotto** 2019-02-04 13:55 UTC
