### ISSUE TITLE
DateInput decrease the day by 1 when you change its value and trigger a form validation function

### ISSUE THREAD

**Issue by gabe-o-fetchly** [marmelab/react-admin#10197] opened 2024-09-12 00:14 UTC
**What you were expecting:**
DateInput to always have the value sent to the validation function exactly as it displays on the component

**What happened instead:**
see below

**Steps to reproduce:**
The DateInput day value decrease by 1 when you log its value on a validation function, but only if you change the date initial value, for example if the initial value is today, when the issue happens, the day of the date is decreased by 1...
How to reproduce: 
- Add a validation prop to your form like so: `validate={validateCreate}`
- Set the forms validation modes to submit: `mode='onSubmit' reValidateMode='onSubmit'`
- Insert a default value on the DateInput, as a prop like this:
`defaultValue={new Date().toISOString().split('T')[0]}`
- Add a simple log to the validation form value for the DateInput (my DateInput source is called start_date): `console.log(values.start_date)`
- Open the page where you have your DateInput and press the save button
- You will see that the date is correct, since it has the initial value
- Change your Date to something else and press Save again, you will see the date has decreased by 1 day, and if you keep testing, you can see that it only happens if you change the date to something else other than the initial value

**Related code:**
Dont have a codesandbox, its very easy to reproduce this

**Environment**

* React-admin version:
`from package-lock: "node_modules/react-admin": { "version": "5.1.3", ... }`
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

I would love to get some idea how to work around this issue

**Comment by gabe-o-fetchly** [comment] 2024-09-13 13:10
> Thanks for reporting this. Please provide a sample application showing the issue by forking the following Stackblitz (https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple).

Thanks for your reply, here is the stackblitz fork: https://stackblitz.com/edit/github-burcyy?file=src%2Fposts%2FCreatePost.tsx
Just navigate to posts, then create, to see my example

I have made the exact same scenario as I'm facing, but with reduced code, and in this example (not my own project) there is even a weirder behavior where the date is being decreased by one day every time you press the save button, where in my case you don't see the date change in the component displaying the value, just the validation function receives whatever value is there -1 day, and stays with that value instead of keeping decreasing it every time you save.

**Comment by djhi** [comment] 2024-09-16 10:22
I can't reproduce your issue in the stackblitz you provided, at least not in a chromium browser. What browser are you using?
![image](https://github.com/user-attachments/assets/415afff9-b8d9-442e-9aec-e9281c458419)

**Comment by richarpw** [comment] 2024-09-30 15:04
I am seeing this also in my application. You can replicate the stackblitz bug by the following steps:

1. Click the Plus button to create a new post
2. Select any part of the date (not the date picker but the text input date itself, so MM DD or YYYY)
3. Click outside of the box in empty space, the date will decrease by a day.

**Comment by fzaninotto** [comment] 2024-10-01 06:55
I still can't replicate the bug in the provided Stackblitz.

It may be linked to a timezone setting (and the bug may only be replicable at certain times of the day). Please narrow down the reproduction so we can work on a fix.

**Comment by gabe-o-fetchly** [comment] 2024-10-01 14:02
> I still can't replicate the bug in the provided Stackblitz.
> 
> It may be linked to a timezone setting (and the bug may only be replicable at certain times of the day). Please narrow down the reproduction so we can work on a fix.

@djhi 
Interesting theory about timezone, i'm at GMT-3, são paulo time, what about you?

> I am seeing this also in my application. You can replicate the stackblitz bug by the following steps:
> 
> 1. Click the Plus button to create a new post
> 2. Select any part of the date (not the date picker but the text input date itself, so MM DD or YYYY)
> 3. Click outside of the box in empty space, the date will decrease by a day.
@richarpw what timezone are you at?

**Comment by WiXSL** [comment] 2024-10-01 14:13
I can reproduce the issue with your Stackblitz, and I'm on GMT-03:00 as well

**Comment by richarpw** [comment] 2024-10-01 14:32
I am EDT (GMT-4).

**Comment by gabe-o-fetchly** [comment] 2024-10-01 18:07
> @gabe-o-fetchly,
> 
> I can confirm that this is a timezone related issue. Using your StackBlitz, and changing the location in Chrome's console (More Tool / Sensor / Location) to "London", I can't reproduce it, but I can with "São Pablo"

Very nice Anibal, do you have any suggestion for a workaround?
I also wonder if we can consider this to be a bug, from the looks of it this is a bug, if you take a quick look at the internal code that saves and retrieves the data, it seems like timezone is not well handled

**Comment by WiXSL** [comment] 2024-10-02 13:14
> > @gabe-o-fetchly,
> > I can confirm that this is a timezone related issue. Using your StackBlitz, and changing the location in Chrome's console (More Tool / Sensor / Location) to "London", I can't reproduce it, but I can with "São Pablo"
> 
> Very nice Anibal, do you have any suggestion for a workaround? I also wonder if we can consider this to be a bug, from the looks of it this is a bug, if you take a quick look at the internal code that saves and retrieves the data, it seems like timezone is not well handled

I dig into the project's code and, if you change `test-global-setup.js` like this:

```diff
module.exports = async () => {
-  process.env.TZ = 'Europe/Paris';
+  process.env.TZ = 'America/Los_Angeles';
};
```

And then run all tests in `packages/ra-ui-materialui/src/input/DateInput.spec.tsx`, most will fail with the problem described in this issue.

**Comment by gabe-o-fetchly** [comment] 2024-10-02 20:21
@djhi do you have any suggestion for a temporary fix for this? Seems like the code was expecting that the timezone were based on GMT0+ based on the last reply from Anibal

**Comment by fzaninotto** [comment] 2024-10-03 09:45
@WiXSL Thanks, that's a valid repro! marking this as a bug.

**Comment by fzaninotto** [comment] 2024-10-03 10:03
This version of `convertDateToString` seems to fix the problem:

```tsx
/**
 * Convert Date object to String
 *
 * @param {Date} value value to convert
 * @returns {String} A standardized date (yyyy-MM-dd), to be passed to an <input type="date" />
 */
const convertDateToString = (value: Date) => {
    if (!(value instanceof Date) || isNaN(value.getDate())) return '';
    let UTCDate = new Date(value.getTime() + value.getTimezoneOffset() * 60000);
    const pad = '00';
    const yyyy = UTCDate.getFullYear().toString();
    const MM = (UTCDate.getMonth() + 1).toString();
    const dd = UTCDate.getDate().toString();
    return `${yyyy}-${(pad + MM).slice(-2)}-${(pad + dd).slice(-2)}`;
};
```

**Comment by Dmytro-Uchkin** [comment] 2024-10-20 17:52
@fzaninotto When can we expect a patch for the bug?

**Closed** 2024-10-28 07:41 UTC
