### ISSUE TITLE
Bug select in AutocompleteInput

### ISSUE THREAD

**Issue by sorcer1** [marmelab/react-admin#2768] opened 2019-01-14 14:17 UTC
Hi, 

In found this bug in the demo : 
[https://marmelab.com/react-admin-demo/#/commands/468](https://marmelab.com/react-admin-demo/#/commands/468)

How to reproduce :

In the customer Select, clear th customer
Type the first letters of an existing customer, it will auto select the customer
Clear the customer and try to type again another name.
The name was wrong because the last letters of the customer was added to the customer in select.

**Comment by fzaninotto** [comment] 2019-01-15 08:13
Duplicate of #2428

**Closed by fzaninotto** 2019-01-15 08:13 UTC
