### ISSUE TITLE
Attempted import error: 'ListProps' is not exported from 'react-admin'. (RA latest version)

### ISSUE THREAD

**Issue by francoisruty** [marmelab/react-admin#6227] opened 2021-04-30 10:36 UTC
**What you were expecting:**
No error when attempting to import ListProps from react-admin

**What happened instead:**
Import error

**Steps to reproduce:**
Any .ts file importing ListProps from react-admin

**Related code:**
```
import { FC } from "react";
import { List, ListProps, Datagrid, NumberField, TextField } from "react-admin";

console.log(ListProps);
```

**Other information:**

**Environment**

* React-admin version: 3.14.5
* React version: 17.0.1
* Browser: chrome

**Comment by francoisruty** [comment] 2021-04-30 10:45
Same with import { ListProps } from "ra-ui-materialui";

(I can't find documentation for react-admin and typescript so I looked in github repo, some pieces (ex: Poster Galore demo) import ListProps from react-admin, some other pieces import ListProps from ra-ui-materialui, but neither work with latest packages versions

**Comment by francoisruty** [comment] 2021-04-30 11:11
Precision: both react-admin and ra-ui-materialui are at latest version, I deleted packages-lock.json, node_modules etc, then fresh npm install and still the problem persists

**Comment by fzaninotto** [comment] 2021-05-01 21:06
I can't reproduce the problem on master. Please post a link to a fork of the simple example codesandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) that reproduces the issue.

**Comment by fzaninotto** [comment] 2021-05-31 21:55
No news for some time, closing.

**Closed by fzaninotto** 2021-05-31 21:55 UTC
Labels: needs more info
