### ISSUE TITLE
ReferenceInput allow to disable request to selected reference

### ISSUE THREAD

**Issue by ihrigb** [marmelab/react-admin#2719] opened 2019-01-03 13:06 UTC
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
When a resource is selected in a `ReferenceInput` (e.g. via `SelectInput`), a request is fired to update the selected resource. I my case, the value, I pick is not the ID, but some other property. Thereby the request will fail, as it is not done to a valid ID. It would be cool, if that request can be disabled.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by djhi** [comment] 2019-01-03 13:22
Duplicate of #2570

**Closed by djhi** 2019-01-03 13:22 UTC

**Comment by kopax** [comment] 2024-07-07 02:34
I have the same issue. Where is the link on stackoverflow for the workaround. The validation request can be very disturbing
