### ISSUE TITLE
onChange doesn't work if you include the (event)

### ISSUE THREAD

**Issue by dylanh724** [marmelab/react-admin#6298] opened 2021-05-23 11:24 UTC
**What you were expecting:**
`onChange` events only seem to trigger if they don't include the `(event)` as a function. In my example, I specifically used a `<TextInput>`, but others likely have issues too.

**What happened instead:**
Nothing happened when you used onChange as a func with event param.

**Steps to reproduce:**
```js
<TextInput
    [...]
    onChange={event => alert('This alert, as a placeholder, should show, but does not')}
/>
```

**Related code:**
```js
<TextInput
    [...]
    onChange={alert('This placeholder alert DOES work, however')}
/>
```

**Environment**

* React-admin version: `3.15.1`

**Comment by fzaninotto** [comment] 2021-05-24 14:18
I can't reproduce your issue. Please link to a CodeSandbox reproducing the problem, based on https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by fzaninotto** [comment] 2021-06-21 12:01
No news for some time, closing.

**Closed by fzaninotto** 2021-06-21 12:01 UTC
Labels: needs more info
