### ISSUE TITLE
ReferenceInput make new request only when the optionValue exists on SelectInput?

### ISSUE THREAD

**Issue by Iliyass** [marmelab/react-admin#3205] opened 2019-05-09 09:58 UTC
(Note: I know there are a duplicate issue #2585 or [Stackoverflow](https://stackoverflow.com/q/51993131/2100974) but I found no help) 
**What you were expecting:**
No new request after selecting from SelectInput

**What happened instead:**
Once you selected an item from SelectInput a new Request issued

**Steps to reproduce:**
Here I created a codesandbox example, where I changed the tags AutocompleteArrayInput to SelectInput and ReferenceArrayInput to ReferenceInput to reproduce my issue, you will see that no request will be issued because the data provider only get the data from the data.js file, but you can see the helper text under SelectInput https://codesandbox.io/s/jvvq0y0095?fontsize=14

**Environment**

* React-admin version: ^2.9.0
* Last version that did not exhibit the issue (if applicable):
* React version:16.8.6
* Browser: Chrome

**Comment by fzaninotto** [comment] 2019-05-13 08:39
Duplicate of #3108

**Closed by fzaninotto** 2019-05-13 08:39 UTC
