### ISSUE TITLE
Notification component does not disappear correctly.

### ISSUE THREAD

**Issue by wbojaume** [marmelab/react-admin#6928] opened 2021-12-02 13:29 UTC
**What you were expecting:**
The notification component will disappear when there are no notifications to display, preventing the Snakbar component from covering a part of the interface.
When a form is saved correctly, all notifications will be output, not just the first one.

**What happened instead:**
The Notification component remains with visibility: hidden when there is no notification to display covering a part of the interface.
When you save a form correctly several times, the notification only appears the first time.

**Steps to reproduce:**
For example, if you successfully save an edit form, the notification will appear. When the notification is hidden, the Notification component will remain covering the interface.
If we successfully save the form a second time, the notification will not appear.

**Related code:**

In this example, using react-admin version 3.12.4, the problem can be reproduced, and it occurs up to the latest version.
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Other information:**
![ezgif-2-b11ffbeb7661](https://user-images.githubusercontent.com/83648361/144430320-64bef759-711f-4d8d-8ad9-30a19af118df.gif)

**Environment**
* React-admin version: 3.19.2
* Last version that did not exhibit the issue (if applicable): not found
* React version: 17.0
* Browser: Firefox 95.0b8
* Stack trace (in case of a JS error): no

**Comment by WiXSL** [comment] 2021-12-04 22:30
Reproduced. Thanks

**Comment by fzaninotto** [comment] 2021-12-05 20:57
Duplicate of #6901

**Closed** 2021-12-05 20:57 UTC
Labels: bug
