### ISSUE TITLE
is there a way to disable cache duration (getFetchedAt)

### ISSUE THREAD

**Issue by aitboudad** [marmelab/react-admin#2886] opened 2019-02-14 13:09 UTC
Hi, 
I'm using WebSockets to track data changes and force fetching data when necessary, so the cache duration ([ten minutes](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/util/getFetchedAt.ts)) feature is useless to me and introduce undesired side-effects in my app, so is there any way to entirely disable this feature?

Thanks!

**Comment by fzaninotto** [comment] 2019-02-21 15:13
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Closed by fzaninotto** 2019-02-21 15:13 UTC

**Comment by aitboudad** [comment] 2019-02-21 15:21
well I would consider it as a feature since there is no way to disable cache duration

**Comment by fzaninotto** [comment] 2019-02-21 16:29
Ah, sorry, I read your issue as a How To question, but it seems it was not one. 

> the cache duration [...] feature [...] introduce undesired side-effects in my app

Can you be more specific? What bug exactly is it causing?

**Comment by michalpierzchlewicz** [comment] 2019-06-13 12:30
Same here. Having the same issues. Would be great to be able to configure the cacheDuration and have the possibility of disabling it in total.

Have the same use case and issue:
1. I have a resource `clients` for which I have a List view.
2. I'm listening on `clients` resource for update events to my data from my API through WebSockets. When I receive a new event, I dispatch the following event:
```javascript
props.dispatch({
  type: UPDATE,
  payload: {
    data: {
      id: client._id,
      ...client
     }
  },
  meta: {
    resource: constants.resources.clients,
    fetchResponse: UPDATE,
    fetchStatus: FETCH_END
  }
})
```
3. If I go to this view and wait for longer than 10 min (longer than `const defaultCacheDuration = 10 * 60 * 1000;`) and after that time I will receive the update event from my API, the event that I disaptch will cause all the "old" data to be removed because their 'fetchedAt' values are older than defaultCacheDuration.

The issue is that you have no option of modifying the defaultCacheDuration value or disabling it in total.
