### ISSUE TITLE
Responsive class isn't responsive

### ISSUE THREAD

**Issue by JacquesBonet** [marmelab/react-admin#2145] opened 2018-08-09 00:32 UTC
I have a datagrid.

According the screen resolution, I want to display 2 columns or 5 column

I use Responsive class with code like that

 ```
<Responsive
                small={
                    <SDataGrid style={{ height: containerListHeight() }}>
                        <TextField source="name" />
                        <TextField source="surname" />
                    </SDataGrid>
                }
                medium={
                    <SDataGrid style={{ height: containerListHeight() }}>
                        <TextField source="name" />
                        <TextField source="surname" />
                        <TextField source="address" />
                         <TextField source="age" />
                }     
/>   
```            

Unfortunately this code doesn't works when I redimension the window.

If I debug Responsive code, I see width props is always at the initial value,the value don't change when the windows width change

The problem is this code withWidth(Responsive) doesn't works

    

**What you were expecting:**
I want the width props value change when the window width change

**What happened instead:**
The with props stay always on the same value, the initial value which is 'lg' in my case

**Related code:**
I modified the Responsive code in order to works

```
const withWidth = () => {
    const width = window.innerWidth

    if (width < 576) return 'xs'

    if (width < 768) return 'sm'

    if (width < 992) return 'md'

    if (width < 1200) return 'lg'

    return 'xl'
}

export const Responsive = ({ xsmall, small, medium, large, ...rest }) => {
    let element
    const width = withWidth()

    switch (width) {
...
```

**Comment by JacquesBonet** [comment] 2018-08-09 02:27
There is the same problem with Sidebar class.

When we redimension the windows, the sidebar doesn't adapt to the new screen dimension

**Comment by lihop** [comment] 2018-08-10 04:11
> There is 3 modes for the sidemenu :
>
> 1. full width view, (medium)
> 2. icons views, (small)
> 3. hidden (xsmall)

While there are three breakpoints for the sidebar (medium, small and xsmall), the sidebar can also be open/closed at each breakpoint. This means that there are 6 possible states total:

#### 1. medium/sidebar open
<img width="571.33" alt="screen shot 2018-08-10 at 8 49 18 am" src="https://user-images.githubusercontent.com/3696783/43934642-80ca7fb6-9c7a-11e8-8c3e-8e0129bd3c13.png">

#### 2. medium/sidebar closed
<img height="228.88" alt="screen shot 2018-08-10 at 9 17 10 am" src="https://user-images.githubusercontent.com/3696783/43935501-7e3dfbde-9c7e-11e8-8f50-313a0322d450.png">

#### 3. small/sidebar open
<img width="340.92" alt="screen shot 2018-08-10 at 9 18 01 am" src="https://user-images.githubusercontent.com/3696783/43935500-7dfc13a4-9c7e-11e8-90b7-8389b24c20b6.png">

#### 4. small/sidebar closed
<img height="228.88" alt="screen shot 2018-08-10 at 8 49 01 am" src="https://user-images.githubusercontent.com/3696783/43934643-80fa6640-9c7a-11e8-8308-0cb7c39e1371.png">

#### 5. xsmall/sidebar open
<img width="222.06" alt="screen shot 2018-08-10 at 8 49 54 am" src="https://user-images.githubusercontent.com/3696783/43934641-80978a20-9c7a-11e8-97a2-184e7775c334.png">

#### 6. xsmall/sidebar closed
<img height="300" alt="screen shot 2018-08-10 at 8 48 48 am" src="https://user-images.githubusercontent.com/3696783/43934644-812bae26-9c7a-11e8-92e6-c281ad28eb48.png">

When changing the resolution, the open/closed state of the sidebar *does not change*, so if the sidebar is open it will go between states 1, 3, 5. Whereas if the sidebar is closed it will go between states 2, 4, 6. I think this is the correct and intended behaviour and personally I don't think it needs to change.

> View 2 happen with a window in small resolution only when we enter refresh key (F5)

This is because the visibility of the SideBar component is set when the component mounts: https://github.com/marmelab/react-admin/blob/6015670a863bef868a0cafcfb1706187609a6369/packages/ra-ui-materialui/src/layout/Sidebar.js#L47-L52

If you really want this behaviour you can create a custom Sidebar component (or any component that connects `width` and `setSidebarVisibility` for that matter) and implement `componentDidUpdate()` like this:
```js
  componentDidUpdate({ width: prevWidth }) {
    const { width, setSidebarVisibility } = this.props

    switch (width) {
      case 'md':
      case 'lg':
      case 'xl':
        if (prevWidth === 'sm' || prevWidth === 'xs') setSidebarVisibility(true)
        return
      case 'sm':
        if (prevWidth !== 'sm') setSidebarVisibility(false)
        return
      case 'xs':
        if (prevWidth !== 'xs') setSidebarVisibility(false)
        return
    }
  }
```

See the `<SidebarAutoToggle>` component in [this sandbox](https://codesandbox.io/s/9y6j29vw94?view=preview) for an example.

**Comment by fzaninotto** [comment] 2018-08-10 06:49
@lihop Thanks a lot for the clarification. Yes, it is the intended behavior, and yes, the right way to tweak it is to use a custom Sidebar. So I’m closing this issue as there is no bug.

**Closed by fzaninotto** 2018-08-10 06:49 UTC

**Comment by JacquesBonet** [comment] 2018-08-11 21:54
You  totally right lihop, thanks for your nice explanation.

**Comment by aislanmaia** [comment] 2019-03-16 16:40
I'm following the tutorial and at the [Support Mobile Devices](https://marmelab.com/react-admin/Tutorial.html#supporting-mobile-devices) the Responsive component simply doesn't work at all. that is it. I'm using Google Chrome version `73.0.3683.75`

**Comment by fzaninotto** [comment] 2019-03-17 17:43
@aislanmaia it works on the demo, so I suspect there is something wrong on your side. If you can create a CodeSandbox demonstrating the problem on a simple example, please open a new issue.
