### ISSUE TITLE
Documentation example for "Not Using the `<Admin>` Components" is not working

### ISSUE THREAD

**Issue by srosset81** [marmelab/react-admin#5026] opened 2020-07-09 11:13 UTC
**What you were expecting:**
I followed the guide to [include React Admin in another app](https://marmelab.com/react-admin/CustomApp.html).

**What happened instead:**
The first part of the guide ("Using an Existing Redux Provider") worked fine, but when I tried to do the second part ("Not Using the `<Admin>` Components"), I encountered several problems:

- The example `authProvider` did not work (`const authProvider = () => Promise.resolve();`), because `authProvider` is now supposed to be an object instead of a function. I used instead my own provider.
- No `locale` variable was defined, so I set it to `"en"`.
- No `theme` was provided to the `<ThemeProvider>`, so I had to create one.
- `PropTypes` did not exist so I had to import the `prop-types` package.
- The `withContext` expected `authProvider` to be a `PropTypes.object` instead of a `PropTypes.func`

I would gladly submit a PR to fix these few documentation problems, but **I also encountered a severe bug** that I was not able to fix: when I try to edit a resource, the client is redirected to the list, but the data are not updated.

**Steps to reproduce:**
Here's a codesandbox: https://codesandbox.io/s/naughty-snowflake-l2pe2
To reproduce:
- Select a post on the list
- Edit the title and click `Save`
- The optimistic update works and the title is changed, but the data are not updated

How do I know that "the data are not updated" ?
- In my own data provider, I can see the `update` method is never called.
- In the Redux DevTools, I see it stops at `@@router/LOCATION_CHANGE` while on [working examples](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple), the `RA/COMPLETE` action is called a little bit later.
- If I try to reload the page, I get a warning from my browser that data have not been submitted. I don't have this warning when I try working examples.
- If I try to edit or create another post, I get errors. I suspect that React-Admin thinks I'm still in "optimistic update" mode.

**Related code:**
https://codesandbox.io/s/naughty-snowflake-l2pe2

**Other information:**
I wonder if it is a problem with the redux-saga ?

**Environment**
- React-admin version: 3.6.3 on the codesandbox (but it also doesn't work with the latest 3.7.0 version)
- React version: 16.9.0 on the codesandbox
- Browser: latest version of Chrome

Thanks !

**Comment by srosset81** [comment] 2020-07-16 10:57
Sorry the file `createAdminStore.js` was missing from the codesandbox, I don't know where it went.

... but I have **good news** ! I've added the `<Notification />` inside the `<ThemeProvider>` and now everything seems to work fine ! (Visible in the codesandbox)

Is it normal that the application hangs if this Notification component is missing ? Is it something that should be added to the documentation ?

**Comment by Luwangel** [comment] 2020-07-16 13:15
Hello,

Not using the <Admin> is not a common use case, so the documentation is probably outdated. We would appreciate a pull request fixing all the issues you have encountered 😊.

I tested your CodeSandbox with and without the `<Notification>` component and it works in both cases. Maybe it's something else. But I cannot reproduce any crash...

Thanks again,
Adrien

**Comment by srosset81** [comment] 2020-07-16 15:22
> Not using the is not a common use case, so the documentation is probably outdated. We would appreciate a pull request fixing all the issues you have encountered .

Sure, I'll do that ! :-)

> I tested your CodeSandbox with and without the `<Notification>` component and it works in both cases. Maybe it's something else. But I cannot reproduce any crash...

It's not crashing, but the data are not really updated (only optimistically, but the data provider is not called).
With the Redux DevTools, you can see that it gets stuck at the `@@router/LOCATION_CHANGE` action. When you add the `<Notification>` component, the `RA/COMPLETE` action is sent a few seconds later, and then there are more actions.

**Comment by fzaninotto** [comment] 2020-08-09 14:21
Fixed by #5058

**Closed by fzaninotto** 2020-08-09 14:21 UTC
Labels: bug, documentation
