### ISSUE TITLE
Reintroduce useVersion for refreshing custom things

### ISSUE THREAD

**Issue by archfz** [marmelab/react-admin#8748] opened 2023-03-21 21:59 UTC
**Is your feature request related to a problem? Please describe.**
In v4 `useVersion` was removed without providing full backwards compatibility or alternative.

**Describe the solution you'd like**
`useVersion` could be reintroduced and still exposing a version counter, and the refresh button could increment this. This is useful as there could be non query related hooks, or non react query http client libraries in those hooks, which would be nice to also update once the refresh button is pressed.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fzaninotto** [comment] 2023-03-22 07:41
> There could be non query related hooks, or non react query http client libraries in those hooks, which would be nice to also update once the refresh button is pressed.

Could you give an example? 

Note that you can reproduce a global refresh in user land by using a custom layout where you track the version using a simple `useState`, increment it using a custom `RefreshButton`, and force a remount of the app by using the version as the `key` for the root component.

**Comment by archfz** [comment] 2023-03-23 20:13
Yeah, I am forced to do that and I was thinking that this might be a common thing, but indeed would need community feedback. I will have to replicate the `LoadingIndicator`  since it is not exposing an onClick. Also as you said one also needs custom layout and custom app bar, I would expect many users have these as the default builtin ones.

**Comment by archfz** [comment] 2023-03-23 21:38
Another inconvenience is that I would also need to wrap the `useRefresh` hook, since when that is triggered the version should also be incremented.

**Comment by fzaninotto** [comment] 2023-08-01 14:00
We had no community feedback on this one and, since it's doable in user land, we won't move forward with it. So I'm closing the issue. Thanks for raising the idea anyway!

**Closed by fzaninotto** 2023-08-01 14:00 UTC
Labels: needs more info
