### ISSUE TITLE
Type 'ListProps' is not assignable to type 'ListControllerProps'

### ISSUE THREAD

**Issue by olegcherr** [marmelab/react-admin#7110] opened 2022-01-19 18:35 UTC
**React-Admin v4.0.0-alpha.1**

TypeScript complains about wrong prop type for List/Edit/Show components:
```
Type '(props: ListProps<Record>) => Element' is not assignable to type 'ComponentType<ListControllerProps<Record>> | undefined'
Type '(props: ShowProps<Record>) => Element' is not assignable to type 'ComponentType<ShowControllerProps<Record>> | undefined'.
```
```
<Resource name="positions" list={PositionList} show={PositionShow} />

function PositionList(props: ListProps) {
...

function PositionShow(props: ShowProps) {
...
```

![image](https://user-images.githubusercontent.com/3730074/150192858-47df3cc9-73f7-41ae-a566-e568eafc94e0.png)

Related, I guess: https://github.com/marmelab/react-admin/issues/7109

UPD:
https://codesandbox.io/s/demo--ra-list-show-props-type-bug-0o4jt?file=/src/App.tsx

**Comment by WiXSL** [comment] 2022-01-20 14:35
I cannot reproduce this error in simple example in next branch

**Comment by olegcherr** [comment] 2022-01-21 10:19
I reproduced it on codepen:
https://codesandbox.io/s/demo--ra-list-show-props-type-bug-0o4jt?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/3730074/150510238-ae0594b4-23f1-4771-8093-08ec47b39f5c.png)

**Comment by WiXSL** [comment] 2022-01-21 12:12
I don't know why it doesn't show in the simple example, but its seems you are right.

**Comment by fzaninotto** [comment] 2022-01-21 13:21
Fixed by #7121

**Closed by fzaninotto** 2022-01-21 13:21 UTC
Labels: bug
