### ISSUE TITLE
Remove items from ArrayInput and re-add new ones, data of previous items would be shown

### ISSUE THREAD

**Issue by ddhp** [marmelab/react-admin#7788] opened 2022-06-06 14:11 UTC
**What you were expecting:**

append to an `ArrayInput` would show empty items

**What happened instead:**

if the ArrayInput is initialized with items, after removing them and click "ADD" button, the new items will hold the info of previously removed ones

**Steps to reproduce:**

1. start demo `simple` by `make run-simple`
2. visit `http://localhost:8080/#/posts/create`
3. remove the default backlinks
4. press `ADD`
5. Date & Url is the default one

**Related code:**
N/A

**Other information:**

N/A

**Environment**

* React-admin version: lastest(4.1.2)
* Last version that did not exhibit the issue (if applicable): N/A
* React version: N/A
* Browser: Chrome 102.0.5005.61
* Stack trace (in case of a JS error): N/A

**Comment by septentrion-730n** [comment] 2022-06-07 22:33
Thanks for the report. We have been able to reproduce the bug.

**Comment by slax57** [comment] 2022-06-08 08:22
Possible duplicate of https://github.com/marmelab/react-admin/issues/7385

**Comment by septentrion-730n** [comment] 2022-08-03 08:26
Djhi is working on the issue mentionned above. I'll close this one as a duplicate.

**Closed by septentrion-730n** 2022-08-03 08:26 UTC
Labels: bug, good first issue
