### ISSUE TITLE
Infinite loading view when declaring resource at runtime with no authProvider

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#3239] opened 2019-05-17 07:20 UTC
**What you were expecting:**

When I try to declare the Resource at runtime, I expect the Resource would be rendered even without authProvider
According to the documentation https://marmelab.com/react-admin/Admin.html#declaring-resources-at-runtime the authProvider is completely optional

**What happened instead:**

It shows an infinite loading page when authProvider is omitted. The last dispatched action in Redux Dev Tool is RA/USER_LOGOUT and it is trying to use the none existing authProvider.

**Steps to reproduce:**

In the simple demo application
1. Remove all Resources except posts in Admin
2. Remove authProvider of Admin, then it will show an infinite loading view.

If we put authProvider back the page will render normally. If we simply have an authProvider that return Promise.resolve() for all cases, the page will also render normally. (I use this as a temporary workaround in my code.)

**Related code:**

```
https://codesandbox.io/s/simple-p6ej7
```

**Other information:**

The reason might be related with #1650. Because authProvider is not defined, it will definitely throw on AUTH_GET_PERMISSIONS. Then it's trying to log the user out with the not defined authProvider?

**Environment**

* React-admin version: 2.9.1
* Last version that did not exhibit the issue (if applicable): Not sure
* React version: 16.9 alpha 0
* Browser: Latest Chrome and Latest Firefox
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment] 2019-07-23 16:55
You might be right, when the children of the `<Admin>` component is a function, we should assume that the `authProvider` must be set.
I don't know if it's an expected behavior nor if it's documented.

https://github.com/marmelab/react-admin/blob/f4ad22c222611ed2b8a7b0145c46ed792345d94a/packages/ra-core/src/CoreAdminRouter.tsx#L175-L176

I'll let the core maintainers decide on what to do about it.
One workaround would be to not use a a function as children when you don't have an auth provider.

**Comment by fzaninotto** [comment] 2019-07-23 20:24
If you use a function as child of `Admin`, and this function doesn't receive the permissions (because you don't have any `authProvider`, how does your function select which resources to include or not?

**Comment by smeng9** [comment] 2019-07-23 21:59
Hi @fzaninotto, sorry for the confusion here. The codesandbox is used to illustrate the problem, but our use case is different than selecting which resources to include or not.

Our use case generates all `<Resource />` on the fly from a schemas json fetched from backend:
```
    fetchResources = async (permissions) => {
        let response = await fetch(`${apiUrl}/schemas`);
        let schemas = await response.json();
        return schemas.map(schema => {
            return <Resource 
                  key={schema.id}
                  name={schema.resource}
                  list={schemaToListView(schema)} 
                  show={schemaToShowView(schema)}
                  edit={schemaToEditView(schema)} 
                  create={schemaToCreateView(schema)}/>;});
    };
```
In this use case, the number of entries in schemas and how many field each schema has is not known beforehand.

We have to use schemaToListView/ShowView/EditView/CreateView HOC to create Views and Resources dynamically and this is the only way.

Our use case does not need auth.
But as I have said before, 

>  If we simply have an authProvider that return Promise.resolve() for all cases, the page will also render normally

I think the simplest solution to close this issue is: mention in documentation we need to add an empty authProvider for this edge case. I brought up this issue here hope that it can help someone encountered this issue in the future.

**Comment by fzaninotto** [comment] 2019-07-24 06:20
Now I understand your use case, which is not something we had in mind. The dynamic children was really designed for authorization. 

However, your use case seems pretty common, and the fix to call the authProvider only if it's defined is straightforward. So instead of adding yet another gotcha to the documentation, let's make the framework more fault tolerant. 

I'm marking it as a bug.

**Closed** 2019-08-12 15:50 UTC
Labels: bug, good first issue
