### ISSUE TITLE
ReferenceInput with AutocompleteInput

### ISSUE THREAD

**Issue by seaver-choy** [marmelab/react-admin#2624] opened 2018-12-05 14:25 UTC
**What you were expecting:**
Receive a list of 500 items with item_name as optionText

**What happened instead:**
AutocompleteInput.js:195 Uncaught TypeError: Cannot read property 'toString' of undefined

**Steps to reproduce:**
Have a list of 500 items in the database and fetch perPage with 500 items

**Related code:**

```
<ReferenceInput label="item 1" source="item1" reference="tblitem" validate={required()} perPage={500}>
            <AutocompleteInput optionText="item_name"/>
          </ReferenceInput>
```

**Other information:**

**Environment**

* React-admin version: "^2.4.1"
* Last version that did not exhibit the issue (if applicable):
* React version: "^16.6.0"
* Browser: Google Chrome
* Stack trace (in case of a JS error):
Uncaught TypeError: Cannot read property 'toString' of undefined
    at AutocompleteInput._this.getSuggestionText (AutocompleteInput.js:195)
    at AutocompleteInput._this.renderSuggestion (AutocompleteInput.js:382)
    at Item.render (Item.js:194)
    at finishClassComponent (react-dom.development.js:14306)
    at updateClassComponent (react-dom.development.js:14270)
    at beginWork (react-dom.development.js:15106)
    at performUnitOfWork (react-dom.development.js:17903)
    at workLoop (react-dom.development.js:17944)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:17224)
    at renderRoot (react-dom.development.js:18037)
    at performWorkOnRoot (react-dom.development.js:18919)
    at performWork (react-dom.development.js:18826)
    at performSyncWork (react-dom.development.js:18799)
    at interactiveUpdates$1 (react-dom.development.js:19109)
    at interactiveUpdates (react-dom.development.js:2328)
    at dispatchInteractiveEvent (react-dom.development.js:5134)

The above error occurred in the <Item> component:
    in Item (created by ItemsList)
    in ul (created by ItemsList)
    in ItemsList (created by Autowhatever)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Autowhatever)
    in div (created by Popper)
    in Portal (created by Popper)
    in Popper (created by WithTheme(Popper))
    in WithTheme(Popper) (created by Autowhatever)
    in div (created by Autowhatever)
    in Autowhatever (created by Autosuggest)
    in Autosuggest (created by AutocompleteInput)
    in AutocompleteInput (created by WithStyles(AutocompleteInput))
    in WithStyles(AutocompleteInput) (created by translate(WithStyles(AutocompleteInput)))
    in translate(WithStyles(AutocompleteInput)) (created by FormFieldView)
    in FormFieldView (created by DefaultValue)
    in DefaultValue (created by Connect(DefaultValue))
    in Connect(DefaultValue) (created by WithFormField)
    in WithFormField (at Card/index.js:73)
    in ReferenceInputView (created by ReferenceInputController)
    in ReferenceInputController (created by Connect(ReferenceInputController))
    in Connect(ReferenceInputController) (created by translate(Connect(ReferenceInputController)))
    in translate(Connect(ReferenceInputController)) (created by ReferenceInput)
    in ReferenceInput (created by translate(ReferenceInput))
    in translate(ReferenceInput) (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by FormFieldView)
    in FormFieldView (created by DefaultValue)
    in DefaultValue (created by Connect(DefaultValue))
    in Connect(DefaultValue) (created by WithFormField)
    in WithFormField (at Card/index.js:72)
    in div (created by FormInput)
    in FormInput (created by WithStyles(FormInput))
    in WithStyles(FormInput) (created by FormTab)
    in span (created by FormTab)
    in FormTab (created by translate(FormTab))
    in translate(FormTab) (at Card/index.js:71)
    in Route (created by TabbedForm)
    in div (created by CardContent)
    in CardContent (created by WithStyles(CardContent))
    in WithStyles(CardContent) (created by CardContentInner)
    in CardContentInner (created by WithStyles(CardContentInner))
    in WithStyles(CardContentInner) (created by TabbedForm)
    in form (created by TabbedForm)
    in TabbedForm (created by WithStyles(TabbedForm))
    in WithStyles(TabbedForm) (created by Form(WithStyles(TabbedForm)))
    in Form(WithStyles(TabbedForm)) (created by Connect(Form(WithStyles(TabbedForm))))
    in Connect(Form(WithStyles(TabbedForm))) (created by ReduxForm)
    in ReduxForm (created by translate(ReduxForm))
    in translate(ReduxForm) (created by Connect(translate(ReduxForm)))
    in Connect(translate(ReduxForm)) (created by Route)
    in Route (created by withRouter(Connect(translate(ReduxForm))))
    in withRouter(Connect(translate(ReduxForm))) (at Card/index.js:70)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by WithStyles(Card))
    in WithStyles(Card) (created by CreateView)
    in div (created by CreateView)
    in CreateView (created by CreateController)
    in CreateController (created by translate(CreateController))
    in translate(CreateController) (created by Connect(translate(CreateController)))
    in Connect(translate(CreateController)) (created by Create)
    in Create (created by WithStyles(Create))
    in WithStyles(Create) (at Card/index.js:69)
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by Route)
    in Route (created by Resource)
    in Switch (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (at src/index.js:55)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Route)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Route)
    in Route (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
    in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdmin)
    in Switch (created by CoreAdmin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdmin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by CoreAdmin)
    in Provider (created by CoreAdmin)
    in CoreAdmin (created by withContext(CoreAdmin))
    in withContext(CoreAdmin) (at src/index.js:47)

React will try to recreate this component tree from scratch using the error boundary you provided, Layout.

**Comment by pftsao** [comment] 2018-12-06 15:55
This is because some of your items have no item_name.
The 'getSuggestionText()' in Autocomplete(Array)Input.js calls 'toString()' before checks it.

If you do not want to edit Autocomplete(Array)Input.js you can change your optionText like this:
        optionText = choice => {
          let _c = choice.item_name
          if (_c === null || _c === undefined) _c = ''
          return _c
        }

**Comment by fzaninotto** [comment] 2018-12-13 20:31
Closing as it's not a bug in react-admin.

**Closed by fzaninotto** 2018-12-13 20:31 UTC
