### ISSUE TITLE
[Bug] ReferenceInput/ReferenceArrayInput sometimes doesn't show the selected values

### ISSUE THREAD

**Issue by ngocketit** [marmelab/react-admin#2790] opened 2019-01-19 13:37 UTC
![react-admin-bug](https://user-images.githubusercontent.com/1885269/51427367-eab74300-1bff-11e9-9b3d-235840692c66.gif)

**What you were expecting:**
`ReferenceInput/ReferenceyArrayInput` should always show the selected values that come from the REST API.

**What happened instead:**
Selected values sometimes don't always show up. They instead show up for about a second and suddenly disappear. If I use Refresh button, sometimes the values show up, sometimes not. According to my finding, this seems to happen when there is another usage of `ReferenceInput` or `ReferenceArrayInput` that refers to the same resource type as that of the one being created/edited (check the `Parent category` reference in the example below).

**Steps to reproduce (and the code):**
I have an example where I have resources for products, product categories and product attributes. Each product category can have 1 or more attributes and 0 or 1 parent category. Following is the code:
```
<ReferenceInput label='Parent category' source='parentId' reference='Category'>
    <SelectInput label='Parent category' optionText='title' />
</ReferenceInput>

<ReferenceArrayInput label='Attributes' source='attributeIds' reference='Attribute'>
    <SelectArrayInput label='Attributes' optionText='title' />
</ReferenceArrayInput>
```

The transform from `attributes` and `category` properties of a Category is done via response mapping in data provider like so:

```
'GET_ONE': {
      query: gql`query getCategory($id: ID!) {
        item: getCategory(id: $id) {
          ${returnedFields}
        }
      }`,
      variables: params,
      parseResponse: response => {
        const category = response.data.item;

        if (category.parent) {
          category.parentId = category.parent.id;
        }
        if (category.attributes) {
          category.attributeIds = category.attributes.map(a => a.id);
        }
        return { data: category };
      }
},
```

**Environment**

* React-admin version: 2.6.1
* React version: 16.7.0
* Browser: Chrome
* Stack trace (in case of a JS error): No errors

**Comment by ngocketit** [comment] 2019-01-25 22:21
Any ideas about how to fix this, anyone?

**Comment by ngocketit** [comment] 2019-01-26 23:47
More specifically, it happens when there is reference of the same resource type as that of the one currently being created/edited. I found a workaround by relying on the data provider to load the list of items and use `<SelectInput/>` instead.

**Comment by fzaninotto** [comment] 2019-01-28 13:22
Can you please update the bug title and description to reflect the actual bug case? I'm confused with the current description.

**Comment by fzaninotto** [comment] 2019-01-28 15:25
Now the title and description don't match anymore...

**Comment by ngocketit** [comment] 2019-01-28 19:39
@fzaninotto Sorry if something is not clear to you but does the title or description matter more than the bug itself? To me, both title & description are very descriptive and I didn't want to put a long title since all the details can be found in the description.

**Comment by rhenriques78** [comment] 2019-01-29 13:57
Currently i'm going though the same problem. I've noticed that the id is ok but the selected description is empty (line break - &#8203):

**Comment by fzaninotto** [comment] 2019-02-07 11:21
"sometimes fails" makes it hard to reproduce. If you could narrow down the cause of the bug and provide a minimal CodeSandbox allowing to reproduce the bug, it would help us fix it.

**Comment by ngocketit** [comment] 2019-02-07 13:51
@fzaninotto Currently I have a workaround but I'll double check and see if there is anything wrong on my side and possibly post some code. By "sometimes" I mean sometimes it works, some other time not for the exact same code.

**Comment by kopax** [comment] 2019-02-20 18:43
Hi @ngocketit, we also have the same issue randomlu, what is the workaround that you have? Thanks!

**Comment by ngocketit** [comment] 2019-02-20 19:46
@kopax The workaround I'm using is not using `ReferenceInput` or `ReferenceArrayInput` but instead, I used data provider to load all the referenced objects and use `SelectInput` instead.

**Comment by tunglt1810** [comment] 2019-04-06 10:07
> @kopax The workaround I'm using is not using `ReferenceInput` or `ReferenceArrayInput` but instead, I used data provider to load all the referenced objects and use `SelectInput` instead.

@ngocketit : field data của record gốc cần là 1 mảng id, tuy nhiên mình lại gặp trường hợp ấn save thì các field đã select bị biến mất, nhận response về mới update

**Comment by kopax** [comment] 2019-04-07 18:03
> @ngocketit : field data của record gốc cần là 1 mảng id, tuy nhiên mình lại gặp trường hợp ấn save thì các field đã select bị biến mất, nhận response về mới update

Hay quá! Tai sao việc tiẻng việt?

**Comment by tunglt1810** [comment] 2019-04-08 09:58
Sorry @kopax , my mistake.

This is my experience when using ReferenceInput. When i click save, some checked box disappear and showing after update active success.

![SaveRole](https://user-images.githubusercontent.com/19906349/55715649-61095b80-5a1f-11e9-813b-bfc07276636c.gif)

**Comment by Kmaschta** [comment] 2019-07-23 17:05
Can someone reproduce the issue on [this CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by Kmaschta** [comment] 2019-09-23 13:00
Any news on this one?

**Comment by fzaninotto** [comment] 2019-11-08 13:22
No news for too long, closing.

**Closed by fzaninotto** 2019-11-08 13:22 UTC
Labels: needs more info
