### ISSUE TITLE
NumberInput is not set as dirty

### ISSUE THREAD

**Issue by bladx** [marmelab/react-admin#8028] opened 2022-08-02 17:34 UTC
**What you were expecting:**
NumberInput is not set as dirty (touched) when using the arrow buttons to update value.

**What happened instead:**
NumberInput should be set as dirty (touched) so that we can save the form.

**Steps to reproduce:**

1. Run the simple application from next branch
2. Go to post edition
3. Go to Misc 3rd tab (http://localhost:8080/#/posts/13/2)
4. Increment and/or decrement Average note field using arrow buttons
5. See that save button is still disabled (you can make the input dirty by focus it)

**Other information:**

![Capture d’écran 2022-08-02 à 19 32 54](https://user-images.githubusercontent.com/4518629/182437980-a134f3ee-e268-4820-a344-6bf831ad930e.png)
![Capture d’écran 2022-08-02 à 19 33 01](https://user-images.githubusercontent.com/4518629/182437984-f3962a9c-5d1e-415b-becd-e6efc87f3075.png)

**Environment**

* React-admin version: 4.2.4
* Last version that did not exhibit the issue (if applicable): not the case on https://marmelab.com/react-admin-demo/#/products/create/details
* React version: 17.0.0
* Browser: Firefox 103.0 (64-bit), Google Chrome Version 103.0.5060.134 (Build officiel) (x86_64)
* OS: macOS Monterey 12.2.1
* Stack trace (in case of a JS error):

**Comment by septentrion-730n** [comment] 2022-08-03 08:17
Thanks for your report! 
Duplicate of #7919

**Closed by septentrion-730n** 2022-08-03 08:17 UTC
