### ISSUE TITLE
ReferenceInput label uses the wrong resource for translation message

### ISSUE THREAD

**Issue by atcg01** [marmelab/react-admin#7646] opened 2022-05-05 15:26 UTC
ReferenceInput in react-admin@4.02 traduct field in the same way of react-admin@3.19

When editing a resource posts with the following field
`<ReferenceInput source="idUser" reference="users"><AutoComplete /></ReferenceInput>`
The ReferenceInput label will be traduct with the key resources.**users**.fields.idUser in react-admin@4, while react-admin@3.19 use resources.**posts**.fields.idUser

The ReferenceField use resources.**posts**.fields.idUser in react-admin@3.19 and react-admin@4.02

**Comment by djhi** [comment] 2022-05-05 15:36
Please follow the issue template

**Comment by atcg01** [comment] 2022-05-05 15:43
**What you were expecting:**
ReferenceInput in react-admin@4.02 traduct field in the same way of react-admin@3.19

**What happened instead:**
ReferenceInput use resources.{resource in reference prop}.fields.field_name instead of resources.{current edited resource}.fields.field_name

**Steps to reproduce:**
When editing a resource **posts** with the following field
`<ReferenceInput source="idUser" reference="**users**"><AutoComplete /></ReferenceInput>`
The ReferenceInput label will be traduct with the key resources.**users**.fields.idUser in react-admin@4.02, while react-admin@3.19 use resources.**posts**.fields.idUser

**Other information:**
The ReferenceField use resources.**posts**.fields.idUser in react-admin@3.19 and react-admin@4.02

**Environment**

* React-admin version: 4.02
* React version: 17.0.2
* Browser: Chrome

**Comment by fzaninotto** [comment] 2022-05-05 16:03
Reproduced, thanks!

**Comment by fzaninotto** [comment] 2022-05-05 16:24
The problem is that, since we removed prop injection, the child of ReferenceInput has no way to access the original resource... That's a tough one. 

One solution would be to augment the ChoicesContext to store the original resource, but it's a bit hacky... The other solution would be to create a new context. But why would children of ReferenceInput read that context? Not a good one either.

**Comment by fzaninotto** [comment] 2022-05-05 17:20
I may have a good solution. The idea is to invert the control of `FieldTitle`. Instead of *pushing* props to it, let it *pull* data from a context...

So `SimpleForm`, `ArrayInput`, `ReferenceInput`, and many other components, should create a `<FieldTitlePrefixContext>`. They have the means to build a value for it. 

Individual inputs would just pass the props they receive to `FieldTitle`: `label`, and `source`. `<FieldTitle>` would use the `FieldTitlePrefixContext` value to prefix the `source` it receives in case it has no `label`.

This is a pretty large change, but I think it's the right way - it's, in fact, the continuation of what we've done in the 3.0 -> 4.0 migration. 

And it's backwards compatible.

**Comment by fzaninotto** [comment] 2022-05-18 16:48
After thinking a bit about it, the previous version didn't make sense. It generated translation messages like `resources.users.fields.idUser`, which doesn't exist, as `users` doesn't have an `idUser` field (but an `id` field).

**Comment by atcg01** [comment] 2022-05-18 16:51
The key use for translation is not `resources.users.fields.idUser` but `resources.posts.fields.idUser` in 3.19

**Comment by fzaninotto** [comment] 2022-05-18 16:51
right, I mixed it up, sorry.

**Comment by atcg01** [comment] 2022-05-18 18:34
no it generate `resources.posts.fields.idUser` for posts resource with foreign key idUser reference key id is resource user

**Comment by fzaninotto** [comment] 2022-05-19 13:07
Fixed by #7110

**Closed by fzaninotto** 2022-05-19 13:07 UTC
Labels: bug
