### ISSUE TITLE
SubmissionValidation shows error message only on the next submit

### ISSUE THREAD

**Issue by wayheyha** [marmelab/react-admin#7154] opened 2022-01-28 12:12 UTC
**What you were expecting:**
see: https://marmelab.com/react-admin/CreateEdit.html#submission-validation

**What happened instead:**
If you use the code you provided following happens: If i cause a 422-Response first no error message is shown in the form. If i now cause a 200-Response the error from the previos false attempt will be displayed.

**Steps to reproduce:**
see: https://marmelab.com/react-admin/CreateEdit.html#submission-validation 

**Related code:**
see: https://marmelab.com/react-admin/CreateEdit.html#submission-validation

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.19.7
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* React-Final-Form version: 6.5.7
* Browser: Any
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2022-01-28 12:17
Please fill the missing infiormation in the template, provide a link to a codesandbox demonstrating the issue, and keep your temper.

Remember, you got this for free, and we've been working on it for years.

**Comment by wayheyha** [comment] 2022-01-28 12:58
@fzaninotto Again sorry for my harsh tone. It seems that i am an angry developer theese days ;-)

I updated the message and also i noticed that the per-field-validation imediatly response, but the notification box at the bottom of the app displays the n-1 message on the current submit.

**Comment by fzaninotto** [comment] 2022-01-28 13:41
We can't reproduce the problem you describe with the elements of your issue. If you want us to take a look at it, please provide a link to a codesandbox demonstrating the issue. 

I think I said that already.

**Comment by fzaninotto** [comment] 2022-07-21 16:54
No news for some time, closing.

**Closed by fzaninotto** 2022-07-21 16:54 UTC
Labels: needs more info
