### ISSUE TITLE
[demo] "dense" prop on submenu headers makes root menu items not consistent

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#3437] opened 2019-07-21 17:37 UTC
The `dense` prop used here https://github.com/marmelab/react-admin/blob/0fa6ee5005d0db740f53aeac95d7fbc281d747a9/examples/demo/src/layout/SubMenu.js#L38 

produces a "compact" version of the root menu items:

![Screenshot from 2019-07-21 18-48-06](https://user-images.githubusercontent.com/869693/61594596-dd4e3600-abed-11e9-9d29-132521dc62cf.png)

while the root menu items without submenus keep the "non compact" aspect:

![Screenshot from 2019-07-21 18-49-57](https://user-images.githubusercontent.com/869693/61594607-f5be5080-abed-11e9-8cb8-7c901d523078.png)

This is the same root menu without the `dense` prop:

![Screenshot from 2019-07-21 18-48-59](https://user-images.githubusercontent.com/869693/61594611-15557900-abee-11e9-9cca-20221ad441c5.png)

I'm not sure if the desired design is "dense everywhere" (parent and child menus) or if the the `dense` prop should be used only on child menus.

Please note: as you can see this is based on a local prototype using an extracted version of the demo submenu code so there is a chance the demo doesn't show the same behavior. I tried to do the same tests directly on the demo but encountered some difficulties https://github.com/marmelab/react-admin/issues/3436.

**Comment by esistgut** [comment] 2019-07-21 19:33
After the restoring of the demo (https://github.com/marmelab/react-admin/pull/3440) I did some additional tests: the problem doesn't show up on the demo because it forces an older version of material-ui (4.0.0-beta.2) on its dependencies. On this version the `dense` props don't seem to sort any effect. Upgrading to the current version (4.2.1) makes the problem visible.

**Comment by djhi** [comment] 2019-10-01 12:50
Can't reproduce it on the latest alpha. Can you please confirm it is fixed or provide a codesandbox showing the issue?

**Comment by fzaninotto** [comment] 2019-10-01 12:55
Already fixed in `next` (#3718)

**Closed by fzaninotto** 2019-10-01 12:55 UTC
Labels: v3-alpha
