### ISSUE TITLE
Navigating to edit page when already there causes edit form values to be cleared.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#2901] opened 2019-02-19 18:23 UTC
**What you were expecting:**
Clicking a navigational link to go to the same resource edit page that I'm already on should not clear out the edit form. No navigation should happen at all.

**What happened instead:**
Instead, the edit form values are cleared out. (`form.record-form` is deleted in Redux.)

**Steps to reproduce:**

- Make a normal resource with `list` and `edit` views.
- Create a global `<Link />` or `<MenuItemLink />` that points to the edit views relative URL (e.g. in the sidebar menu, a footer or in the app bar).
- Use the link to navigate to the edit view.
- Wait for the edit view to load completely.
- Use the link again to navigate to the same edit view.
- Observe that the edit form values have now been cleared out.

**Environment**

* React-admin version: 2.7.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.1
* Browser: Chrome 72
* Stack trace (in case of a JS error): none

**Comment by fzaninotto** [comment] 2019-02-21 15:09
What is the use case for providing a link to the current edit page?

**Comment by waynebloss** [comment] 2019-02-21 21:26
My use case is that I have a number of resources that will only have one record to edit. So, when I render their `MenuItemLink` in my custom sidebar, I check for a property that indicates this situation and I link directly to the well-known ID of the resource record.

So, within the realm of my use-case, if you make a mistake and click the sidebar item when you're already on the page, all the form inputs get cleared out. 

However, aside from the particular usefulness of linking directly to an edit page - I imagine that I would want to guard against the behavior of deleting `form.record-form` upon navigation to the self-same page just because of the fact that we're running in a web browser and such navigation could possibly happen in a multitude of ways in a kit that is highly customizable...

It's not a huge problem for me if you don't want to address it. Just letting you know. I'm sure I can come up with an acceptable workaround by implementing my own onClick handler for the menu items where I have this problem.

Thanks!

**Comment by fzaninotto** [comment] 2019-02-22 18:44
@djhi I don't remember where and why the form reset is done, can you point me to the right direction?

**Comment by waynebloss** [comment] 2019-02-22 22:13
@fzaninotto I think it's [here](https://github.com/marmelab/react-admin/blob/f08bf8522fedc74b73fcd4d6470b38f9dcbec9b4/packages/ra-core/src/form/formMiddleware.ts#L38)

**Comment by waynebloss** [comment] 2019-02-22 22:18
@fzaninotto On line 32 in that same file, it looks like an attempt to prevent the exact situation that I'm having the issue with. However, I bet that since payload.state is different, it's not working.

**Comment by waynebloss** [comment] 2019-02-22 22:21
I think comparing just the pathname is a good idea. I use `history.replace()` (or whatever its called) to store temporary state in query parameters all the time, so things are remembered when I refresh, kinda like the list views do.

**Comment by fzaninotto** [comment] 2020-10-14 22:14
Cannot reproduce anymore on master, closing.

**Closed by fzaninotto** 2020-10-14 22:14 UTC
Labels: enhancement
