### ISSUE TITLE
RichTextInput text does not update when the underlying redux-form `source` is changed.

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2832] opened 2019-01-30 10:35 UTC
**What you were expecting:**
`RichTextInput` text to be updated when the underlying redux-form `source` is changed.
(Note: This may be related to the closed PR https://github.com/marmelab/react-admin/pull/2581 I created a new issue because the use case is different that the one noted in that PR)

**What happened instead:**
`RichTextInput` does not update on changes of its REDUX form value, when this change comes from another input that targets the same `source`.

It does seem that something special needs to happen when its input props change, like the proposed `this.quill.pasteHTML(nextProps.input.value);` found at the following closed PR: https://github.com/marmelab/react-admin/pull/2581

**Steps to reproduce:**

This is our case:
We use the same RichTextInput source (eg: title.en) twice in the same form (the 2nd one is in a "translations" dialog, which is part of the form). When we change the title.en rich text in the "translations" dialog and then close the dialog, unfortunately the title.en outside the dialog (but in the same form) still shows the old text.

**Related code:**

* CodeSandbox (https://codesandbox.io/s/n5q09v99xl)
* A sample application via GitHub
-->

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 2.6.3

**Comment by fzaninotto** [comment] 2019-01-31 15:31
Duplicate of #2464

**Closed by fzaninotto** 2019-01-31 15:31 UTC
