### ISSUE TITLE
Issues with react-admin (2.5.3) and ra-ui-materialui dependencies

### ISSUE THREAD

**Issue by activist** [marmelab/react-admin#2942] opened 2019-02-28 10:39 UTC
First I must apologize if this is not the correct channel as this issue is not directly yours. It seems that a new version of react-headroom is breaking our build (which in turn is a dependency of react-admin). 

[Reference issue in react-headroom repo]( https://github.com/KyleAMathews/react-headroom/issues/161)

**What you were expecting:**
Building the application should work as expected.

**What happened instead:**
We have not changed any dependencies, but our build is suddenly breaking with the following error:
Module not found: Error: Can't resolve 'react-headroom' in 'C:\<myapppath>\node_modules\ra-ui-materialui\lib\layout'
 @ ./node_modules/ra-ui-materialui/lib/layout/Headroom.js 8:39-64
 @ ./node_modules/ra-ui-materialui/lib/layout/index.js
 @ ./node_modules/ra-ui-materialui/lib/index.js
 @ ./node_modules/react-admin/lib/Admin.js
 @ ./node_modules/react-admin/lib/index.js

**Other information:**
It seems that react-headroom was updated to version 2.2.5 yesterday. [See this issue](https://github.com/KyleAMathews/react-headroom/issues/161)

Likely there is an issue with the new version. So my question is this:
Should react-headroom (and generally other dependecies) have a caret(^) in the ra-ui-materialui package.json as it in this case causes upstream issues?

I know this could turn into broader discussion regarding package-lock.json etc, but I'm just curious on your point of view on this.

* React-admin version: 2.5.3
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.0
* Browser:
* Stack trace (in case of a JS error):
Module not found: Error: Can't resolve 'react-headroom' in 'C:\<myapppath>\node_modules\ra-ui-materialui\lib\layout'
 @ ./node_modules/ra-ui-materialui/lib/layout/Headroom.js 8:39-64
 @ ./node_modules/ra-ui-materialui/lib/layout/index.js
 @ ./node_modules/ra-ui-materialui/lib/index.js
 @ ./node_modules/react-admin/lib/Admin.js
 @ ./node_modules/react-admin/lib/index.js

**Comment by fzaninotto** [comment] 2019-02-28 13:02
Thanks for the report.

That means that react-headroom didn't follow semver, and introduced a breaking change in a minor version. We assume that packages are semver compliant. Assuming the worst (and falling back to ~ instead of ^ in dependencies) has the drawback of increasing the bundle size as some dependencies get duplicated.

In this particular case, we should either wait for headroom to fix the problem, or publish a new release where the headroom dependency if fixed to an earlier version.

**Comment by fzaninotto** [comment] 2019-02-28 13:02
Can you confirm react-headroom 2.2.6 solves the issue?

**Comment by fzaninotto** [comment] 2019-02-28 13:05
In fact, it's a duplicate of #2941. Continuing the discussion there.

**Closed by fzaninotto** 2019-02-28 13:05 UTC
Labels: bug
