### ISSUE TITLE
Warnings: React does not recognize titleAccess and activeClassName

### ISSUE THREAD

**Issue by RafeSacks** [marmelab/react-admin#2603] opened 2018-12-02 19:51 UTC
I'm getting a couple more warnings similar to  a few other issues. 

- [Warning: React does not recognize the `fullWidth` prop on a DOM element. #1957](https://github.com/marmelab/react-admin/issues/1957) 
- [<ReferenceInput> inside <SimpleFormIterator> throws warnings #1973](https://github.com/marmelab/react-admin/issues/1973)
- [MenuItemLink leftIcon=<img..> #1926](https://github.com/marmelab/react-admin/issues/1926)

[EDIT:] After writing this I believe I found the cause as mentioned in the last link above. I am using icons from mdi-react such as:

    import ShopifyIcon from "mdi-react/ShopifyIcon";

...are these not supposed to be supported?

They render nicely. Functionality wise I have no issues. Is this a warning that should simply be silenced or is there a code path that I'm not hitting so it only appears safe?

If I am supposed to extend something on my end, please advise.

### Details
`Warning: React does not recognize the `titleAccess` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `titleaccess` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

`Warning: React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Environment**

* React-admin version: 2.5.0
* Last version that did not exhibit the issue (if applicable):
* React version: 16.6.3
* Browser: VS Code Debugger launched Chrome
* Warning detail:
```
    in Menu (created by WithStyles(Menu))
    in WithStyles(Menu) (created by Connect(WithStyles(Menu)))
    in Connect(WithStyles(Menu)) (created by Context.Consumer)
    in translate(Connect(WithStyles(Menu))) (created by Layout)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Drawer)
    in div (created by Drawer)
    in Drawer (created by WithStyles(Drawer))
    in WithStyles(Drawer) (created by Sidebar)
    in Responsive (created by WithWidth(Responsive))
    in EventListener (created by WithWidth(Responsive))
    in WithWidth(Responsive) (created by WithTheme(WithWidth(Responsive)))
    in WithTheme(WithWidth(Responsive)) (created by Sidebar)
    in Sidebar (created by WithWidth(Sidebar))
    in EventListener (created by WithWidth(Sidebar))
    in WithWidth(Sidebar) (created by WithTheme(WithWidth(Sidebar)))
    in WithTheme(WithWidth(Sidebar)) (created by WithStyles(WithTheme(WithWidth(Sidebar))))
    in WithStyles(WithTheme(WithWidth(Sidebar))) (created by Connect(WithStyles(WithTheme(WithWidth(Sidebar)))))
    in Connect(WithStyles(WithTheme(WithWidth(Sidebar)))) (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Route)
    in Route (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
    in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (at AppLayout.js:10)
    in AppLayout (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdmin)
    in Switch (created by CoreAdmin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdmin)
    in TranslationProviderView (created by Connect(TranslationProviderView))
    in Connect(TranslationProviderView) (created by CoreAdmin)
    in Provider (created by CoreAdmin)
    in CoreAdmin (created by withContext(CoreAdmin))
    in withContext(CoreAdmin) (at App.js:38)
    in App (at src/index.js:7)
```

**Comment by fzaninotto** [comment] 2018-12-03 10:01
Yep, that's a duplicate of #1926. You'll need to wrap your custom icon into another component to swallow the non-supported props.

**Closed by fzaninotto** 2018-12-03 10:01 UTC

**Comment by RafeSacks** [comment] 2018-12-03 18:35
Hi,

I'll implement the workaround. I suppose I can make a little wrapper that takes any icon as a prop. Perhaps this should this perhaps happen on the react-admin side since there are some pretty large icon libraries that provide react components? ...a low priority suggestion. I won't wait for this, just proposing the idea. Thanks!
