### ISSUE TITLE
3.1.2 has a bug where on launch it ends in an endless loop. 

### ISSUE THREAD

**Issue by heyaj19** [marmelab/react-admin#4307] opened 2020-01-17 04:42 UTC
**What you were expecting:**
I was expecting to see a login page or a the last page I had signed into before upgrading from 3.1.1 to 3.1.2

**What happened instead:**
The localhost launches a browser window and just iterates through all the routes. In firefox it asks to stop or wait. In chorme it just never ends

**Steps to reproduce:**
Upgrade from 3.1.1 to 3.1.2. I can get you access to my private repo - but not sure what else I can do. 

Cant create a sandbox. One of the things I found was the issue showed up on staging after I did npm install --production. Once I did that on my local machine it started doing the same thing. But after that when I deleted my node_module folder the issue was still there. The issue disappeared when I downgraded from 3.1.2 to 3.1.1. 

**Environment**

* React-admin version: 3.1.2
* Last version that did not exhibit the issue (if applicable):3.1.1
* React version:16.12.0
* Browser:Firefox/Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-01-17 10:30
We can't reproduce the issue. You will have to provide a CodeSandbox. If you can't reproduce it on CodeSandbox, the issue is probably on your side.

**Comment by heyaj19** [comment] 2020-01-17 15:08
If you like I can provide you my github repo?

**Comment by Luwangel** [comment] 2020-01-17 15:20
Hi,

Your repo will not be useful, but you can copy the code from your repo in CodeSandbox.

1. Please fork the following template on CodeSandbox : [React Admin Template](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
2. Reproduce your bug. Remember to give us the clearest and simplest example possible.
3. Reply to this issue with the link of your CodeSandbox, and extra information if it's necessary.

Regards,
Adrien

**Comment by fzaninotto** [comment] 2020-01-28 07:08
No news for some time, closing.

**Closed by fzaninotto** 2020-01-28 07:08 UTC
Labels: needs more info

**Comment by kvieira90** [comment] 2020-02-05 20:52
Also having this issue with 3.1.3. If I hide all routes to force all users to login page, it ends in the endless load screen
![Screen Shot 2020-02-05 at 3 51 22 PM](https://user-images.githubusercontent.com/5322549/73882016-60a04380-482f-11ea-84d3-323de52c1b97.png)

source is: `<Admin 
    authProvider={authProvider}
    dataProvider={simpleRestProvider(url, httpClient)}>
      { permissions => [
          permissions === 'user' || permissions === 'admin' ? <Resource name="invoices" create={InvoiceCreate} list={InvoiceList} show={InvoiceView}/> : null,
          permissions === 'admin' ? <Resource name="clients" create={ClientCreate} list={ClientList} edit={ClientEdit}/> : null,
          permissions === 'admin' ? <Resource name="chefs" create={ChefCreate} list={ChefList} edit={ChefEdit}/> : null,
        ]
      }
  </Admin>`

AuthProvider is a direct copy from the docs https://marmelab.com/react-admin/doc/3.1/Authentication.html
