### ISSUE TITLE
Using ArrayInput is causing view to be dirty and save button is enabled even though there have been no changes

### ISSUE THREAD

**Issue by mikemcclaran** [marmelab/react-admin#7043] opened 2021-12-29 15:06 UTC
**What you were expecting:**
I expect that the save button on the edit view will not be enabled until changes are actually made.  Also, when using `warnWhenUnsavedChanges` I would not expect the unsaved changes prompt if no changes have been made.

**What happened instead:**
once I add ArrayInput to my edit view, the save button is enabled prior to any changes being made.

**Steps to reproduce:**
My Edit view was working as expected until I added the ArrayInput

**Related code:**
Here is my Edit view
```
<Edit {...props}>
    <SimpleForm warnWhenUnsavedChanges={true}>
        <TextInput disabled source="id" label="Id"/>
        <TextInput disabled source="dappID" label="Dapp Id"/>
        <NumberInput disabled source="networkID" label="Network Id"/>
        <NumberInput disabled source="chainID" label="Chain Id"/>
        <TextInput source="displayName" label="Display Name" validate={validateDisplayName}/>
        <ArrayInput source="contracts">
            <SimpleFormIterator disableAdd disableRemove disableReordering>
                <TextInput disabled source="contractID" label="Contract Id" fullWidth/>
                <TextInput disabled source="contractName" label="Contract Name" fullWidth/>
                <TextInput disabled source="contractAddress" label="Contract Address" fullWidth/>
            </SimpleFormIterator>
        </ArrayInput>
    </SimpleForm>
</Edit>
```

If I remove the ArrayInput, my view works as expected.

**Other information:**

**Environment**

* React-admin version:  3.19.5
* React version: 17.0.2
* Browser: Chrome, Brave

**Comment by WiXSL** [comment] 2022-01-03 12:40
Please provide a CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) to reproduce the error you are describing

**Comment by mikemcclaran** [comment] 2022-01-03 19:53
I will try to make a simple example.  Is there a way for me to see the initial data and the current data that is being used to determine dirty state?  Maybe there is an issue with my data that I am missing

**Comment by michbert** [comment] 2022-01-12 12:11
I am experiencing the same problem with the latest react-admin version (3.19.6)

The problem is actually present right in your provided example (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple):
1. Edit a post without backlinks added -> Works fine
2. Add backlink and save
3. Edit post again -> form is immediately marked dirty and you get a warning about unsaved changes when navigating away

The issue obviously only appears if there is at least one element already added to an ArrayInput

**Comment by WiXSL** [comment] 2022-01-12 12:57
Yes. You are right.
I'm marking this as a bug.

**Closed** 2022-01-20 07:14 UTC
Labels: bug
