### ISSUE TITLE
DefaultValue is shared with multiple forms containing the same source

### ISSUE THREAD

**Issue by estephan** [marmelab/react-admin#3375] opened 2019-06-29 09:36 UTC
**What you were expecting:**

I expect that if I have a default value set on a `TextInput`, that it is the default value I specified on that `TextInput` and not the value that I have set on another `TextInput`.

**What happened instead:**

Instead, if I have two `TextInputs` with the same `source` on different forms, they share the same default value, no matter what values are set.

**Steps to reproduce:**

Following on from the provided codesandbox, I have made a small change to have a `TextInput` on the `CommentCreate` form with a source of `title` and a defaultValue of "comment title". I have also modified the existing `TextInput` on the `PostQuickCreate` form with a source of `title` and added a defaultValue of "post tile".
When the "create" button is clicked an the `PostQuickCreate` form is rendered the value of the `TextInput` on the `CommentCreate` changes from the expected "comment title" to "post title".

**Related code:**

https://codesandbox.io/s/simple-2vgxe

**Other information:**

I suspect it has to do with how `getDefaultValues` is implemented on `SimpleForm`. That state is shared between forms for default values in `admin.record`.

**Environment**

* React-admin version: 2.0.0
* Last version that did not exhibit the issue (if applicable): n/a
* React version: 16.3.1
* Browser: Chrome
* Stack trace (in case of a JS error): n/a

**Comment by fzaninotto** [comment] 2019-07-02 09:43
Bug reproduced and confirmed, thanks for the report.

**Comment by m4theushw** [comment] 2019-07-04 02:02
After debugging the example I discovered that opening the `PostQuickCreate` form a `RA/INITIALIZE_FORM` action is dispatched by the `withDefaultValue` HOC. That action updates the `admin.record` with values from the modal, which is propagated to the base form. I don't think is possible to use the `defaultValue` in a form opened inside other form because they will share the state.

**Comment by djhi** [comment] 2019-07-04 05:27
This will be fixed in v3 when we'll switch from `redux-form` to `final-forms`

**Comment by fzaninotto** [comment] 2019-08-21 13:12
@djhi can you confirmed it's fixed in `next`?

**Comment by djhi** [comment] 2019-08-21 14:16
Yes, default values can't be shared anymore

**Comment by fzaninotto** [comment] 2019-08-21 14:19
Fixed by #3455

**Closed by fzaninotto** 2019-08-21 14:19 UTC
Labels: bug
