### ISSUE TITLE
Digit grouping does not work for NumberInput

### ISSUE THREAD

**Issue by Nefcanto** [marmelab/react-admin#6412] opened 2021-07-05 08:11 UTC
**What you were expecting:**
I expected to enter my long numbers, and `NumberInput` show them while group them by each three digits, like **2,342,883** for example.

**What happened instead:**
`NumberInput` clears the data after 3 digits.

**Steps to reproduce:**
Create a simple react admin project.
Create a simple form.
Add a `NumberInput`.
Add `format` and `pars` as follow:

        <NumberInput
            props={props}
            format={removeGrouping}
            parse={digitGroup}
        />

Add these functions to your function component:

    const digitGroup = value => {
        if (value === undefined || value === null || /^\s*$/g.test(value)) {
            return '';
        }
        value = value.toString();
        value = value.replace(/,/g, '');
        var str = value.toString().split('.');
        if (str[0].length > 3) {
            str[0] = str[0].replace(/(\d)(?=(\d{3})+$)/g, '$1,');
        }
        var result = str.join('.');
        return result;
    };

    const removeGrouping = value => {
        console.log(value);
        if (value.replace) {
            value = value.replace(',', '');
        }
        return value;
    };

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Environment**

* React-admin version: 3.16.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome 91.0.4472.114
* Stack trace (in case of a JS error): No error

**Comment by fzaninotto** [comment] 2021-07-06 12:24
Hi, and thanks for your report. I don't think this is a problem in the NumberInput, but rather in your custom parse and format functions.

Unless you can show that there is a problem in NumberInput with a simpler reproducible case, I'm going to assume that the problem is on your side, so I'm closing the issue.

**Closed by fzaninotto** 2021-07-06 12:24 UTC

**Comment by Nefcanto** [comment] 2021-07-07 04:45
Thank you @fzaninotto.

I made [this fiddle](http://jsfiddle.net/2o8mn4zy/), and you are right. While it's not a problem of our script (because we're using it for like 5 years now), it's the problem of HTML number input. And since `NumberInput` of react admin uses HTML number input, thus this happened.

Our option is to create a numeric field, but using `TextInput`.

Thank you.
