### ISSUE TITLE
BooleanInput parse and format props don't seem to work

### ISSUE THREAD

**Issue by amhouel** [marmelab/react-admin#4412] opened 2020-02-11 18:40 UTC
**What you were expecting:**

Have the parse and format functions transform our record non-boolean values to boolean values for the input and vice-versa and see the BooleanInput toggle work accordingly on click.

**What happened instead:**

The BooleanInput is always set to true and doesn't change on click.
If the initial value is a true value, the parse and format functions successfully change the value to the false value on the 1st click but then get stuck on that value.
If the initial value is a false value, then the parse and format functions always return that same false value.

**Steps to reproduce:**

In the Posts list, click on any Edit button and inside the Edit form click on the "Title" BooleanInput.

**Related code:**

https://codesandbox.io/s/serverless-pine-dhgem

**Environment**

* React-admin version: 3.2.1
* Last version that did not exhibit the issue (if applicable): 2.9.9
* React version: 16.9
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-02-13 13:48
The `format` and `parse` functions are well called when I try this code:

```jsx
        <BooleanInput
          source="title"
          format={v => {console.log('format', v);return v}}
          parse={v =>{console.log('parse', v);return v}}
        />
```

So in my opinion, the problem is either on your side or in the final-form side.

**Comment by jparkrr** [comment] 2020-02-23 18:27
(I'm working with @amhouel)

Yes, you're right. It looks like react-final-form [doesn't support `format` for checkboxes](https://github.com/final-form/react-final-form/blob/f3c1aea93b520c0620f1b8090f5966e0da94a798/src/useField.js#L213)

**Comment by fzaninotto** [comment] 2020-02-25 07:28
Thanks for looking into it. I'm closing this issue.

**Closed by fzaninotto** 2020-02-25 07:28 UTC
Labels: needs more info

**Comment by pefi1011** [comment] 2020-07-04 11:11
Hi @jparkrr @amhouel how did you solve this? I have the same requirement: transform non-boolean record (array of strings) to boolean values for the input and vice-versa and see the BooleanInput toggle work accordingly on click.

I have tried parse/format as @fzaninotto mentioned, but in the logs I see do not see `parse` logs. The app crashes with `Error: Cannot set a numeric property on an object` before the `parse` function is executed

**Comment by kopax** [comment] 2020-07-04 11:24
I have the same issue with BooleanInput.

**Comment by armellarcier** [comment] 2020-07-17 11:57
I found a workaround. You can use it like `<FormattedBooleanInput trueValue="yes" falseValue="no" source="myfield" />`

```jsx
import React from "react";
import { FormDataConsumer, BooleanInput } from "react-admin";

const FormattedBooleanInput = ({
    falseValue = "N",
    trueValue = "Y",
    source,
    formPassInputRenderer,
    inputProps,
    ...props
}) => (
    <FormDataConsumer {...props}>
        {({ formData, ...rest }) => (
            <BooleanInput
                options={{
                    checked: formData[source] === trueValue,
                }}
                format={(value) => value === trueValue}
                parse={(value) => (value ? trueValue : falseValue)}
                fullWidth
                source={source}
                {...inputProps}
            />
        )}
    </FormDataConsumer>
);

FormattedBooleanInput.defaultProps = {
    inputProps: {},
};

export default FormattedBooleanInput;
```
