### ISSUE TITLE
list id must be a number

### ISSUE THREAD

**Issue by Godman-quake** [marmelab/react-admin#4564] opened 2020-03-21 12:42 UTC
My Posts item is like this:
{id:'aeab001',title:'some title',...}
It can be shown in a list.
But when I selected it and clicked the delete button, an error 'Total from response is not a number.' occurred, although the post actually can be removed at last.
If I change the id to a number like 123, everything is OK!
So, what's the problem?

**Comment by Godman-quake** [comment] 2020-03-22 04:08
I have written a wrapper that can convert origin id(mongodb's objectid, a string) to a number before put into redux, and convert it back before delete or update.
Now everything is OK!

**Comment by Godman-quake** [comment] 2020-03-22 04:09
Do anybody know a better solution? Thanks first!

**Comment by dhstack** [comment] 2020-03-23 03:44
Possible duplicate of https://github.com/marmelab/react-admin/issues/4337

**Comment by JulienMattiussi** [comment] 2020-03-23 09:14
Thanks for reporting this.
As pointed, its a duplicate of #4337.

The bug was introduced in 3.3.0 
It's happens only if `undoable={true]`
We're working on it

As a dupplicate, I close this issue.

**Closed by JulienMattiussi** 2020-03-23 09:14 UTC
