### ISSUE TITLE
Performance issue with form submission with many inputs

### ISSUE THREAD

**Issue by Eddy-Ko** [marmelab/react-admin#9885] opened 2024-05-30 08:19 UTC
**What you were expecting:**

The app doesn't freeze when I submit the form with many inputs.

**What happened instead:**

The app freezes for a few seconds when I submit the form with many inputs. The more inputs there are, the longer the freeze.

**Steps to reproduce:**

Click menu > Custom4 > Edit any field > Click save button

**Related code:**

* Preferably, a sandbox forked from 
  - https://stackblitz.com/edit/github-uqosta?file=src%2FCustom4.tsx

```
import Box from '@mui/material/Box';
import React from 'react';
import { Form, SaveButton, TextInput, useAuthenticated } from 'react-admin';

const inputs = Array.from({ length: 50 }, (v, i) => i);

const Custom = () => {
  useAuthenticated();

  const onSubmit = (formValues: any) => {
    console.log(formValues);
  };

  return (
    <>
      <Box>
        <Form onSubmit={onSubmit}>
          <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
            {inputs.map((i) => (
              <TextInput key={i} source={`text${i}`} />
            ))}
          </Box>
          <SaveButton />
        </Form>
      </Box>
    </>
  );
};

export default Custom;

```

**Other information:**

If I replace TextInput with MyInput in Custom5, the problem is solved. So I think the issue is related to the Input.
```
function MyInput({ source }: { source: string }) {
  const { register } = useFormContext();
  return <input {...register(source)} />;
}
```

**Environment**

* React-admin version: 4.16.15
* react-hook-form: 7.51.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Brave Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (arm64)
* Stack trace (in case of a JS error):

**Comment by djhi** [comment] 2024-05-30 08:56
Reproduced, thanks

**Comment by fzaninotto** [comment] 2024-05-30 09:48
The bug doesn't occur with react-hook-form <= 7.51.0. It starts with [react-hook-form 7.51.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.51.1).

**Comment by fzaninotto** [comment] 2024-05-30 12:52
The bug is triggered by this line

https://github.com/marmelab/react-admin/blob/0d05494446cf7725d62ef9aae893a440485b40bb/packages/ra-core/src/form/useApplyInputDefaultValues.ts#L45

Without it, it disappears. It seems that calling `getFieldState()` creates a rerender loop. I'll try to build a repro.

**Comment by fzaninotto** [comment] 2024-05-30 13:02
I can reproduce the issue in your CodeSandbox by using the following implementation for `MyInput`: 

```diff
function MyInput({ source }: { source: string }) {
-   const { register } = useFormContext();
+   const { getFieldState, formState, register } = useFormContext();
+   getFieldState(source, formState);
    return <input {...register(source)} />;
}
```

The problem is even more apparent when using MUI's `TextField` instead of `input` (as it is much slower). 

So this is definitely a react-hook-form regression. I'll open an issue in their repo. In the meantime, please use react-hook-form <= 7.51.0.

**Comment by fzaninotto** [comment] 2024-05-30 13:31
Created issue in the react-hook-form repo: https://github.com/react-hook-form/react-hook-form/issues/11954

**Comment by fzaninotto** [comment] 2024-06-19 12:18
Confirmed, the bug was fixed in react-hook-form. Thanks for the heads up!

**Closed by fzaninotto** 2024-06-19 12:18 UTC
Labels: bug
