### ISSUE TITLE
Resource not displayed on Refresh.

### ISSUE THREAD

**Issue by MarkLyck** [marmelab/react-admin#4683] opened 2020-04-13 21:34 UTC
**What you were expecting:**
dataProvider getList to be called and displayed the resource the URL points to.

in this case /address_types

<img width="1679" alt="Screen Shot 2020-04-13 at 5 26 43 PM" src="https://user-images.githubusercontent.com/6841110/79163358-ecdd6280-7dac-11ea-8e7c-169a860bafd9.png">

**What happened instead:**
dataProvider not called, displays nothing. (like when you go to the main endpoint for the first. time before navigating to any Resources)

<img width="1675" alt="Screen Shot 2020-04-13 at 5 27 04 PM" src="https://user-images.githubusercontent.com/6841110/79163369-f23aad00-7dac-11ea-909f-9e28d07afb2c.png">

**Steps to reproduce:**
Go to a resource using hashRouter.
Watch getList being called in the dataProvider and react-admin displays the Resource.
Refresh page

**Related code:**
I have no customRoutes and haven't messed with Routing at all.

Using `api-platform/Admin` as my base. HydraAdmin as my Admin component. Everything else is standard.

**Environment**

* React-admin version:  "react-admin": "^3.4.0",
* @api-platform/admin: "^2.1.0",
* React version: "react": "^16.13.1",
* Browser: Google Chrome

**Comment by djhi** [comment] 2020-04-14 06:32
Thanks for reporting this. We can't investigate without a way to reproduce it. Please create a codesandbox showing the issue

**Comment by manohar719** [comment] 2020-05-20 10:41
Same issue with me

**Comment by fzaninotto** [comment] 2020-05-20 11:58
As the initial reporter didn't provide enough details for us to reproduce this issue, we're going to close it. Unless @manohar719 can help?

**Comment by fzaninotto** [comment] 2020-06-02 21:47
No news for some time, closing. I suspect the problem is on the API Platform admin side.

**Closed by fzaninotto** 2020-06-02 21:47 UTC
Labels: needs more info

**Comment by manohar719** [comment] 2020-06-10 06:48
@fzaninotto sorry for late post, I have created a mock example on codesandbox, below is the link
https://codesandbox.io/s/confident-snowflake-u8f03?file=/src/posts.js
for reference click on the first record, and then try to reload the browser.

**Comment by fzaninotto** [comment] 2020-07-29 14:19
I still can't see any problem with your CodeSandbox.
