### ISSUE TITLE
Add ability to customize message notification on successful or unsuccessful delete

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#5337] opened 2020-10-01 20:58 UTC
**Is your feature request related to a problem? Please describe.**
Our create and update messages use the translation hooks to add messageArgs to replace part of messages provided by the useNotify hook. However, we cannot change the "Element" on the delete notification without hard coding the translation messages or customizing several key parts of the ra-core package, we are not opposed to this however, we feel the change might benefit others.

**Describe the solution you'd like**
Allow users to pass in optional onSuccess and onFailure parameters to the [DeleteButton](https://github.com/marmelab/react-admin/blob/3cc19b5ab3b319a9a151c77cdf4d7f21e5acd075/packages/ra-ui-materialui/src/button/DeleteButton.tsx#L47) and pass those onto the respective delete controllers.

**Describe alternatives you've considered**
It would be possible to add an object that handled any type of action at the &lt;Edit&gt; or &lt;Create&gt; level by for example:

```
<Edit
  onSuccess={
    delete:() => {},
    save: () => {}
  }
  onFailure={
    delete:() => {},
    save: () => {}
  }
...rest
>
...
</Edit>

<Create
  onSuccess={
    save: () => {}
  }
  onFailure={
    save: () => {}
  }
...rest
>
...
</Create>
```

**Additional context**

**Comment by djhi** [comment] 2020-10-02 04:24
Thanks for the request. Closing it as a duplicate of #5309 though

**Closed by djhi** 2020-10-02 04:24 UTC

**Comment by wattry** [comment] 2020-10-02 05:06
Whoops, thanks.
