### ISSUE TITLE
Clicking in the confirm delete modal triggers datagrid rowClick

### ISSUE THREAD

**Issue by tdeo** [marmelab/react-admin#3394] opened 2019-07-09 15:34 UTC
**What you were expecting:**
I would expect  clicking in the modal to do nothing.

**What happened instead:**
Clicking within the modal goes to the target specified by the `rowClick` prop of `Datagrid`

**Steps to reproduce:**
Click on a delete button in a list view, and then on the text "Are you sure ..."

**Related code:**
https://codesandbox.io/s/snowy-tree-40hl4

**Environment**

* React-admin version: 2.9.4
* React version: 16.8.6
* Browser: Chrome 75

**Comment by fzaninotto** [comment] 2019-07-12 10:02
Confirmed, thanks for the report and the cocesandbox. Note that it is not a duplicate of #3359 - the bug appears when clicking *outside* of the buttons.

**Closed** 2019-07-13 17:51 UTC
Labels: bug
