### ISSUE TITLE
When switching between browser tabs, the list data disappears

### ISSUE THREAD

**Issue by ogroppo** [marmelab/react-admin#7300] opened 2022-02-24 15:49 UTC
**What you were expecting:**
I have a react-admin tab open with a list view, I go to another tab (anything), I come back and the data is still there

**What happened instead:**
The data disappears and the "No results found" is shown

**Steps to reproduce:**
Use 2 tabs on chrome or firefox

**Environment**

* React-admin version: 3.19.7
* React version: 17.0.2
* Browser: Chrome/Firefox

**Comment by djhi** [comment] 2022-02-24 16:08
I can't reproduce this issue. Can you confirm you have the same behavior with the demo? https://marmelab.com/react-admin-demo/#/commands

**Comment by fzaninotto** [comment] 2022-02-24 16:52
Is it possible that the problem occurs only if you come back to the other tab more than 10 minutes after seeing it?

**Comment by ogroppo** [comment] 2022-02-24 19:37
Hi @djhi, thank you for getting back to me. I'm attaching a screen recording for your convenience -

https://user-images.githubusercontent.com/4820803/155594712-bcab1f47-d71c-473b-9cc2-0e7bf36011e2.mov

So as you can see in the network, a new call is performed when coming back to the page (this doesn't happen in the demo tho) and although the response has technically the right data in it, it's showing the empty list... is it something connected to useQuery maybe?

**Comment by fzaninotto** [comment] 2022-02-24 19:47
That's the first time I see that in a react-admin app. I suspect the problem is on your side. 

As we can't reproduce this behavior, you'll have to attach a link to an app reproducing it, e.g. based on the simple example codesandbox.

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by ogroppo** [comment] 2022-02-28 22:32
Hello, I found the bit causing the issue and seems to be adding options (a label in this case) prop to the `Resource` component... I know you're probably thinking this makes no sense :D But have a look at the screen recording please.

https://user-images.githubusercontent.com/4820803/156069348-77e99d42-9db4-4c87-9f90-ac84649066fa.mov

I tried to reproduce in codesandbox but can't find the combination

**Comment by CampingPanda** [comment] 2022-03-07 10:48
Was bored at work and tried to replicate it in the sandbox: 
![image](https://user-images.githubusercontent.com/33489797/157013633-08596694-9c30-4edf-819c-f8da853e372e.png)
https://codesandbox.io/s/naughty-haibt-e5pen3?file=/src/index.tsx
Everything seems to work fine there.
It also doesn't do a new request like yours after switching tabs, so that is weird of your version.
You can clone my sandbox if you want if I did not replicate it correctly.

**Comment by ogroppo** [comment] 2022-03-07 13:31
Hi @CampingPanda, thank you so much for looking into this! again, I keep commenting out stuff on the project trying to boil it down to the minimum so that I can make a codesandbox but as of now it happens only with the whole next.js boilerplate around it, I'll keep trying... one thing tho I noticed, if the options are passed with useMemo the reload does not happen

<img width="339" alt="Screenshot 2022-03-07 at 13 30 40" src="https://user-images.githubusercontent.com/4820803/157043641-c68ee994-64f1-4599-b5b4-502ac539d4b5.png">

Could that have something to do with the re-registration of the resource, because the props are detected as changed on rerender?

**Comment by fzaninotto** [comment] 2022-05-01 13:00
No news for some time, closing.

**Closed by fzaninotto** 2022-05-01 13:00 UTC
Labels: needs more info
