### ISSUE TITLE
Can't resolve 'css-mediaquery' in "/react-admin/examples/demo/node_modules/ra-ui-materialui/esm/layout"

### ISSUE THREAD

**Issue by tusmenko** [marmelab/react-admin#3610] opened 2019-08-27 12:44 UTC
**What you were expecting:**
Trying to Build Demo app on Alpha 3.0, getting error:

Failed to compile.

./node_modules/ra-ui-materialui/esm/layout/DeviceTestWrapper.js
Module not found: Can't resolve 'css-mediaquery' in '.../react-admin/examples/demo/node_modules/ra-ui-materialui/esm/layout'

**Steps to reproduce:**
Download source code, go to examples/demo/
run `npm install`
run `npm run start`

Can be fixed by adding `css-mediaquery` to projects dependencies in package.json.

**Environment**

* React-admin version: 3.0.0-alpha.3
* React version:16.8.6
* Browser: Chrome

**Comment by fzaninotto** [comment] 2019-08-27 12:53
duplicate of #3597

**Closed by fzaninotto** 2019-08-27 12:53 UTC
