### ISSUE TITLE
enableGetChoices prevents setting defaultValue on AutocompleteInput

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#7687] opened 2022-05-11 18:40 UTC
**What you were expecting:**
For a AutocompleteInput with a ReferenceInput as a parent to receive the prop "defaultValues" and make the required reference call to populate that value regardless of the status of the enableGetChoices prop on the parent ReferenceInput

**What happened instead:**
No reference call is made, the form element remains empty.

**Steps to reproduce:**
Add a ReferenceInputwith an AutocompleteInput as a child. Pass a function that will return false without input to the ReferenceInput, and pass an id to the AutocompleteInput as a defaultValue.

**Related code:**
Check the new "author" input (which has enableGetChoices and defaultValues props pass to corresponding inputs) on the backlinks iterator on this page:
https://codesandbox.io/s/romantic-hermann-i8c0dm?file=/src/posts/PostCreate.tsx

**Other information:**
I am unsure if this is strictly a bug, or if some defeater needs to be added to enableGetChoices to override its ability to prevent defaultValues, but I know that this pattern worked in 3.19 and does not work in 4.0

**Environment**

* React-admin version: 4.0.3
* Last version that did not exhibit the issue (if applicable): 3.19.10
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by slax57** [comment] 2022-06-02 15:59
@ZachSelindh To be honest I don't see a direct link between the changes we have brought to 4.1.0 and this issue, but your codesandbox is a good enough proof to me that the issue is no more present.

I'll then close this Issue. Thanks for taking the time to update us about it! 🙂

**Closed by slax57** 2022-06-02 15:59 UTC
Labels: bug
