### ISSUE TITLE
Datagrid expands all rows when clicked on any of the rows

### ISSUE THREAD

**Issue by akadiraslan** [marmelab/react-admin#9548] opened 2023-12-27 08:35 UTC
**What you were expecting:**
When expanding a datagrid row, I expect only the row that clicked one should be expanded.

**What happened instead:**
When click one of the rows, all rows in the datagrid are expanded

**Steps to reproduce:**
Add a Datagrid as a ReferenceManyField component's chield with expands another component and set true the expandSingle prop

```
 <ReferenceManyField
      reference="bddScenario/getSessionGroups"
      target="sessionId"
      label=""
  >  
<Datagrid
          bulkActionButtons={false}
          rowClick={'expand'}
          expand={<BddScenarioShow/>}
          expandSingle={true}
      >
          <TextField source="groupName" label='Session Group Name'/>
      </Datagrid>
  </ReferenceManyField>

```

**Other information:**
I found that similar issue [7814](https://github.com/marmelab/react-admin/issues/7814) that closed and fixed in the version after 4.1.4. But I use later version of that
**Environment**

* React-admin version:^4.8.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2024-01-03 13:23
I cannot reproduce the issue in the ReferenceManyField story, with the following story:

```tsx
export const WithDatagridExpand = () => (
    <Wrapper>
        <ReferenceManyField reference="books" target="author_id">
            <Datagrid expand={<>Hello</>} expandSingle={true}>
                <TextField source="title" />
            </Datagrid>
        </ReferenceManyField>
    </Wrapper>
);
```

So either the problem has been fixed since your react-admin version (you're on 4.8, we're at v4.16 now), or it lies elsewhere. 

In any case, we'll need a reproduction to investigate further. Please fork the simple example Stackblitz at https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple and modify it until you can reproduce the bug.

**Comment by fzaninotto** [comment] 2024-01-23 20:27
No news for some time, closing.

**Closed by fzaninotto** 2024-01-23 20:27 UTC
Labels: needs more info
