### ISSUE TITLE
BooleanInput under SimpleFormIterator has an empty string as default value

### ISSUE THREAD

**Issue by seongwon-privatenote** [marmelab/react-admin#8816] opened 2023-04-07 15:16 UTC
**What you were expecting:**

`BooleanInput` has `false` value for its default value when no `defaultValue` prop is set.

**What happened instead:**

Its default value is actually an empty string.

**Steps to reproduce:**

[Codesandbox example](https://codesandbox.io/p/sandbox/blue-river-cq6iym?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A46%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A46%7D%5D&file=%2Fsrc%2FApp.tsx)

1. Open the page in a real browser.
2. Go to the "Todos" list.
3. Go to any edit page.
4. Add an elem for "Contents", but don't touch any fields.
5. Click the "Save" button.
6. Capture the traffic sent to the backend.  You can see `""` value for the boolean field `subfield2`.
<img width="860" alt="스크린샷 2023-04-08 00 11 21" src="https://user-images.githubusercontent.com/121408862/230632740-d08898e2-dcff-48e3-9000-f3d8acfc8064.png">

**Related code:**

[Codesandbox example](https://codesandbox.io/p/sandbox/blue-river-cq6iym?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A46%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A46%7D%5D&file=%2Fsrc%2FApp.tsx)

It seems that the root cause could be https://github.com/marmelab/react-admin/pull/8029/files .

**Other information:**

**Environment**

* React-admin version: 4.9.1
* Last version that did not exhibit the issue (if applicable): 4.2.5
* React version: 18.2.0
* Browser: MacOS Chrome 112.0.5615.49
* Stack trace (in case of a JS error):

**Comment by slax57** [comment] 2023-04-07 15:50
Probably a duplicate of https://github.com/marmelab/react-admin/issues/8785, which is already fixed.
Thanks for the report anyway!

**Closed by slax57** 2023-04-07 15:50 UTC
