### ISSUE TITLE
Auto translate resource fields does not work when using an add/edit form inside a Dialog

### ISSUE THREAD

**Issue by LucusWebsites** [marmelab/react-admin#6322] opened 2021-06-02 06:20 UTC
I have two ways to edit an alarm, one via a dedicated list with default create/edit forms, and one via a list inside the tab of a related parent record.

The fields in the default create/edit forms are translated properly, but not in the form inside the Dialog.

I have added a short video to demonstrate what I mean. https://user-images.githubusercontent.com/3696955/120433238-4884f980-c37b-11eb-81af-ea5db4d4c50f.mp4

Edit:
Saving form when hitting enter inside a TextField does not work as well, possibly related?
/Edit

I am using:
- "react-dom": "17.0.2"
- "react": "17.0.2"
- "react-admin": "3.15.2"
- "ra-i18n-polyglot": "3.15.2"

The code for the "Alarms" tab:

```js
import {
    Button, Datagrid, ExportButton, FormWithRedirect, List, required, SaveButton, TextField, TextInput, TopToolbar, 
    TranslatableFields, useCreate, useListContext, useNotify, useRefresh,
} from "react-admin";
import {useState} from "react";
import AddIcon from "@material-ui/icons/Add";
import {Dialog, DialogActions, DialogContent, DialogTitle} from "@material-ui/core";
import IconCancel from "@material-ui/icons/Cancel";
import locales from "../../../locales.js";

const AddAlarmDialog = ({machineTypeId, open = false, onClose, onSuccess}) => {
    const [create, { loading }] = useCreate('machine-files');
    const notify = useNotify();

    const handleSubmit = async values => {
        create(
            {
                payload: {
                    data: {
                        ...values,
                        machineTypeId: machineTypeId
                    }
                }
            },
            {
                onSuccess: () => {
                    onSuccess();
                },
                onFailure: (error) => {
                    notify(error.message, 'error');
                }
            }
        );
    };

    return (
        <Dialog
            open={open}
            onClose={onClose}
            fullWidth
            maxWidth="md"
        >
            <DialogTitle>Alarm toevoegen</DialogTitle>
            <FormWithRedirect
                resource="machine-alarms"
                save={handleSubmit}
                render={({
                             handleSubmitWithRedirect,
                             pristine,
                             saving
                         }) => (
                    <>
                        <DialogContent>
                            <TextInput
                                source="code"
                                validate={[required()]}
                            />
                            <TranslatableFields locales={locales}>
                                <TextInput multiline fullWidth source="cause" />
                                <TextInput multiline fullWidth source="description" />
                                <TextInput multiline fullWidth source="solution" />
                            </TranslatableFields>
                        </DialogContent>
                        <DialogActions>
                            <Button
                                label="ra.action.cancel"
                                onClick={onClose}
                                disabled={loading}
                            >
                                <IconCancel />
                            </Button>
                            <SaveButton
                                handleSubmitWithRedirect={
                                    handleSubmitWithRedirect
                                }
                                pristine={pristine}
                                saving={saving}
                                disabled={loading}
                            />
                        </DialogActions>
                    </>
                )}
            />
        </Dialog>
    )
}

const ListActions = ({props, machineTypeId}) => {
    const [showAddAlarmDialog, setShowAlarmDialog] = useState(false);
    const refresh = useRefresh();

    const {
        maxResults,
    } = props;

    const {
        currentSort,
        resource,
        filterValues,
        total,
    } = useListContext();

    return (
        <>
            <TopToolbar>
                <Button
                    size="small"
                    label="Toevoegen"
                    onClick={() => {
                        setShowAlarmDialog(true);
                    }}
                >
                    <AddIcon />
                </Button>
                <ExportButton
                    disabled={total === 0}
                    resource={resource}
                    sort={currentSort}
                    filterValues={filterValues}
                    maxResults={maxResults}
                />
            </TopToolbar>
            <AddAlarmDialog
                props={props}
                open={showAddAlarmDialog}
                onClose={() => {
                    setShowAlarmDialog(false);
                }}
                onSuccess={() => {
                    setShowAlarmDialog(false);
                    refresh(); // todo refresh only alarm list and not everything
                }}
                machineTypeId={machineTypeId}
            />
        </>
    )
}

const TabAlarms = ({props, machineTypeId}) => {
    return (

        <List
            {...props}
            style={{
                width: '100%'
            }}
            resource="machine-alarms"
            filter={{
                machineTypeId: machineTypeId
            }}
            perPage={25}
            title=" "
            actions={<ListActions
                props={props}
                machineTypeId={props.id}
            />}
            empty={false}
        >
            <Datagrid>
                <TextField
                    source="id"
                />
                <TextField
                    source="cause.nl"
                />
                <TextField
                    source="description.nl"
                />
                <TextField
                    source="solution.nl"
                />
            </Datagrid>
        </List>
    )
}

export default TabAlarms;
```

**Comment by djhi** [comment] 2021-06-02 08:52
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by LucusWebsites** [comment] 2021-08-17 09:44
Translation also fails when I am using an Input inside a FormDataConsumer

For example:
```JS
<FormDataConsumer>
    {({ formData, ...rest }) => (
        <>
            {formData.userTypeId === 2 &&
            <BooleanInput
                source="receivesSystemEmails"
                helperText="resources.users.fieldHelperTexts.receivesSystemEmails" // <<<<<<<< fails here
            />
            }
        </>
    )}
</FormDataConsumer>

<BooleanInput
    source="receivesSystemEmails"
    helperText="resources.users.fieldHelperTexts.receivesSystemEmails" // <<<<<<<<< works here
/>

**Comment by LucusWebsites** [comment] 2021-08-17 10:14
Also I am using the Enterprice edition, could you please fix this as soon as possible?

**Comment by fzaninotto** [comment] 2021-08-23 08:54
Hi Lucus,

I can't reproduce the problem you describe (failed translation inside a FormDataConsumer) with the simple example (see https://codesandbox.io/s/inspiring-bartik-1u4h9?file=/src/posts/PostEdit.tsx). There must be something else in your code that causes the bug. It may be caused by a duplicate ra-core or ra-ui-material-ui package in your yarn.lock.

Can you please try and reproduce your issue based on the URL above?

Cheers,

François

**Comment by fzaninotto** [comment] 2024-07-02 08:32
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2024-07-02 08:32 UTC
Labels: needs more info, v3
