### ISSUE TITLE
useDataProvider logoutIfAccessDenied promise 'then' method fails

### ISSUE THREAD

**Issue by farandal** [marmelab/react-admin#7679] opened 2022-05-10 16:04 UTC
**Error response from dataProvider.create should be sent to the useCreate onError method**

I need to capture the 422 responses from server to handle server side errors using onSubmit={onSave} where onSave is the useCallback implemeting onSuccess, and onError methods. 

**What happened instead:**

The error sent from dataProvider is lost, because
TypeError: Cannot read properties of undefined (reading 'then') 

It seems that  `logoutIfAccessDenied(error).then(` fails, 
when calling the promise then method
before the error from my axios request can be propagrated to the onCreate callback

 at useDataProvider.ts:110:40
```try {
                        return dataProvider[type]
                            .apply(dataProvider, args)
                            .then(response => {
                                if (process.env.NODE_ENV !== 'production') {
                                    validateResponseFormat(response, type);
                                }
                                return response;
                            })
                            .catch(error => {
                                if (process.env.NODE_ENV !== 'production') {
                                    console.error(error);
                                }
                                return logoutIfAccessDenied(error).then(
                                    loggedOut => {
                                        if (loggedOut) return;
                                        throw error;
                                    }
                                );
                            });
                    } ```


**Steps to reproduce:**
* dataProvider create method must be provided of an axios request that fails with error 422.
* A resource form must implement the onSubmit callback, implemeting onError to capture server side errored response. 

**Other information:**

https://user-images.githubusercontent.com/1222578/167672649-05c7724c-838d-45b7-8409-075b2a27339d.png

https://user-images.githubusercontent.com/1222578/167672664-065f4107-d71f-4166-a562-2846d5465e7d.png

**Environment**

* React-admin version: 4.0.3
* React version: 18
* Browser: Chrome 101 on macOS (Big Sur)
* Stack trace (in case of a JS error):
    mutation.js:106 TypeError: Cannot read properties of undefined (reading 'then')
    at useLogoutIfAccessDenied.ts:49:29
    at useDataProvider.ts:110:40

**Comment by slax57** [comment] 2022-05-16 09:23
Hi,
This seems to be an error specific to your code and/or your authProvider.
If you are using a custom authProvider, then please provide us with a codesandbox including a working version of your authProvider so that we can reproduce your issue and work on it.
If you are using a third-party authProvider, then please open an issue on their bug tracker instead.

**Comment by fzaninotto** [comment] 2022-06-17 12:43
No news for some time, closing.

**Closed by fzaninotto** 2022-06-17 12:43 UTC
Labels: needs more info
