### ISSUE TITLE
ReferenceManyField refreshes the view only the first time a record is deleted if delete undoable is false

### ISSUE THREAD

**Issue by Alex1844** [marmelab/react-admin#4978] opened 2020-06-24 19:31 UTC
I have a ReferenceManyField in a form that shows several related records. I expect the list to be refreshed every time I delete a record by clicking on Delete button. The Delete Undoable is set to false

When i click on the Delete button to delete the first record, I am asked to confirm the deletion. Once I click on the Confirm it deletes the record at the backend, shows a notification and refreshes the list.
However, when I after that click on the Delete button of a different record, I am again asked to confirm but this time when I click on Confirm it deletes the record at the backend, shows a notification that it was deleted but the Confirm dialog does not disappear, the list is not refreshed and Confirm button is available again. If click again, it tries to delete the same record that was already deleted but again it does not refresh the list
If I set the Undoable to true, it works fine and refreshes the list

I feel this is related to this issue https://github.com/marmelab/react-admin/issues/4789

Here is the code
```
export const DeptEmployeeEdit = props => {
    return <Edit {...props}>
        <SimpleForm >
            <ReferenceManyField addLabel={false} reference="departmentapps" target="deptID" >
                <Datagrid >
                    <TextField label="Application" source="AppName" />
                    <TextField label="Permission" source="AppRightsText" />
                    <DeleteButton undoable={false} redirect={false} />
                </Datagrid>
            </ReferenceManyField>
        </SimpleForm>
    </Edit>
};
```

**Comment by djhi** [comment] 2020-06-28 06:05
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by djhi** [comment] 2020-06-29 06:20
I cannot reproduce this issue on the following fork of the simple example: https://codesandbox.io/s/romantic-hermann-gjj48?file=/src/posts/PostEdit.js. Please provide a way to reproduce the issue or we'll close the issue.

**Comment by fzaninotto** [comment] 2020-08-05 08:16
No news for some time, closing.

**Closed by fzaninotto** 2020-08-05 08:16 UTC
Labels: needs more info
