### ISSUE TITLE
dataProvider bug in previousData

### ISSUE THREAD

**Issue by lisij86** [marmelab/react-admin#1865] opened 2018-05-30 07:30 UTC
I use react-admin 2.0

**What happened instead:**
Add Image Input Component
```
<ImageInput so
![jwyeb](https://user-images.githubusercontent.com/26143822/40705754-6cef9260-63f4-11e8-9b94-91d034ae24f6.jpg)
urce="pictures" label="Related pictures" accept="image/*">
    <ImageField source="src" title="title" />
</ImageInput>
```
create decorator for Data Providing
```
const additionalPrepareData = requestHandler => async (type, resource, params) => {
    if (type === 'UPDATE' || type === 'CREATE') {
        const token = localStorage.getItem('token');
        ...............
```
I want use params.previousData to know the previous src image. But src image wrong
![jwyeb](https://user-images.githubusercontent.com/26143822/40705770-79915bac-63f4-11e8-96ff-c5efec11bf1f.jpg)

* React-admin version: 2.0
* React version: 16.4.0
* Browser: Chrome 66.0.3359.181

**Comment by fzaninotto** [comment] 2018-06-05 12:57
I don't understand your problem. The src has the value that your data provider decorator defines, react-admin does nothing here. Most probably, the error is in your code here.

As I think this is not a bug in react-admin, I'm closing this bug. Feel free to reopen it if you can create a CodeSandbox demonstrating the problem.

**Closed by fzaninotto** 2018-06-05 12:57 UTC
