### ISSUE TITLE
Pagination broken with next and previous (reset to 1 everytime)

### ISSUE THREAD

**Issue by Etienne-bluelogic** [marmelab/react-admin#9645] opened 2024-02-06 09:05 UTC
Hello, 

I've seen that there have been problems with pagination in the past. I decided to create a custom component for pagination. 
```
import React from "react";
import { Button, useListContext } from "react-admin";
import { Box } from "@material-ui/core";
import KeyboardArrowRightIcon from "@mui/icons-material/KeyboardArrowRight";
import KeyboardArrowLeftIcon from "@mui/icons-material/KeyboardArrowLeft";

const CustomPagination = (props) => {
  const { page, perPage, setPage, setFilters, filterValues } = useListContext();
  const nextPageInfo: any = localStorage.getItem("paginationNext");
  const prevPageInfo: any = localStorage.getItem("paginationPrev");
  console.log("page component:" + page);
  const handleNext = () => {
    setFilters(
      {
        ...filterValues,
        paginationDirection: "next",
        pageInfo: nextPageInfo,
      },
      null
    );
    setPage(page + 1);
  };

  const handlePrevious = () => {
    setFilters(
      {
        ...filterValues,
        paginationDirection: "previous",
        pageInfo: prevPageInfo,
      },
      null
    );
    setPage(page - 1);
  };

  return (
    <Box
      style={{ display: "flex", justifyContent: "flex-end", padding: "1em" }}
      mt={2}
    >
      {prevPageInfo && (
        <Button
          onClick={handlePrevious}
          label="Previous"
          startIcon={<KeyboardArrowLeftIcon />}
        />
      )}
      <Box ml={2}>
        {" "}
        <Button
          onClick={handleNext}
          label="Next"
          endIcon={<KeyboardArrowRightIcon />}
        />
      </Box>
    </Box>
  );
};

export default CustomPagination;
```

When I first click on the next button, it takes me to page 2 with a first request and then automatically returns to page 1. I don't really understand how it can go back. I've already seen that some people have had this problem. I've tried disabling the strict mode but it doesn't change anything for me.

Next js version : 13.5.6
react admin version: 4.15.1

**Comment by slax57** [comment] 2024-02-06 11:05
Hi, and thank you for your question.

Here is a quick hint for a possible lead: I believe this may be related to issue #4189 , for which a solution has been documented in this PR #9639 .

However, your question looks to me like a support request, and not a bug report nor a feature request.

As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- Community support: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system.
- Community support: Ask your question on [Discord](https://discord.gg/B4G7AEQ3jm). Some react-admin users and contributors might have time to answer your questions.
- Professional support: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly.
If your problem is urgent, please consider subscribing to the [Enterprise Edition](https://marmelab.com/ra-enterprise/), starting at 125€. It's a good way to contribute to the sustainability of react-admin.

So I'm closing this issue, and inviting you to ask your question in one of the support channels above if ever the provided hint was not enough to figure out a solution.

**Closed by slax57** 2024-02-06 11:05 UTC
