### ISSUE TITLE
ra-input-rich-text seems to have wrong dependencies

### ISSUE THREAD

**Issue by palagonKevo** [marmelab/react-admin#10147] opened 2024-08-16 12:18 UTC
**What you were expecting:**
Input similar to what appears in https://marmelab.com/react-admin/RichTextInput.html

**What happened instead:**
Once installed and launched, returns an error with imports within ra-core.

**Steps to reproduce:**
I installed it via yarn, so I did yarn add ra-input-rich-text. After this point, nothing works as expected. I've tried to delete yarn.lock and node_modules, just in case.

**Related code:**
```
import { RichTextInput } from 'ra-input-rich-text'
...
<Create>
    <SimpleForm>
      <RichTextInput fullWidth source="notes" label="Notas" textAlign="left" />
    </SimpleForm>
</Create>
```

**Other information:**

I did nothing strange, I just installed everything normally. I'm using react-router-dom@^6.8.0 and last versions on every other dependency, updated via ncu. Likewise, I think this is pretty much because they removed HistoryRouter for V5 of react-admin, so I guess that here's the issue.

**Environment**

* React-admin version: 5.1.1
* React version: ^18.3.1
* Browser: Opera, Chrome, Firefox (Error it's not related to the browser)
* Compiling tool: vite@^5.4.1
* OS:  NAME="Amazon Linux"
VERSION="2023"
PRETTY_NAME="Amazon Linux 2023.5.20240708"

* Stack trace (in case of a JS error):
![image](https://github.com/user-attachments/assets/e6bdf9a2-dbc9-4432-ab23-ddb112945a09)

**Comment by slax57** [comment] 2024-08-19 08:56
This looks to me like a problem in your project setup, but I see nothing wrong with `ra-input-rich-text`'s dependencies.

From your stacktrace, it seems that you somehow still have an old version of `ra-core` running (v4.x), because we don't import from the `history` package in v5 anymore.

To be on the safe side, I also initialized a new project from scratch using [create-react-admin](https://marmelab.com/react-admin/CreateReactAdmin.html), and ran `yarn add ra-input-rich-text`, but I did not reproduce your issue. Everything works fine and the component is rendered with no error.

Please double check in your `yarn.lock` file that you don't have duplicate versions of `ra-core` in it.

Since I'm not convinced there is anything wrong with `ra-input-rich-text` I'll close this issue, but feel free to reopen if you find new elements indicating that there might be a bug in the project's code.

**Closed by slax57** 2024-08-19 08:56 UTC
