### ISSUE TITLE
Provide a way to disable url parameters to become part of the new record

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#3414] opened 2019-07-15 12:16 UTC
**Is your feature request related to a problem? Please describe.**
For a different reason, I have some URL parameter (x) in there while I submit a SimpleForm. I was surprised to see that that parameter became part of the record that was posted, resulting in my API saying:
> "column "x" of relation "posts" does not exist".

**Describe the solution you'd like**
Can I convince you guys to introduce a prop for Create that makes that behavior optional? I'm thinking:

```jsx
<Create 
    includeSearchValues={false}
    ...
/>
```

It would be an optional prop that's true by default.

**Describe alternatives you've considered**
If not, I'll probably copy and alter CreateController for this. Of course, I could intervene in just the `save` function and remove the key-value pairs from `data` that are exactly like that in the URL, but you can't be sure that that key-value wasn't actually also there as a field value in the form, so I suppose I need to copy and alter CreateController otherwise.

**Additional context**
I noticed that current functionality is intentional and built-in here: https://github.com/marmelab/react-admin/blob/c44c6953cc313fd167dc57b5525db58dd9ba2038/packages/ra-core/src/controller/CreateController.tsx#L104-L105 in this commit: https://github.com/marmelab/react-admin/commit/7845ebec7a8aead597e25ec9738f2cc19c845081#diff-2ade63f0bf44e74c12b44e9e88ff5a21

Related issue: https://github.com/marmelab/react-admin/issues/3111

**Comment by Kunnu01** [comment] 2019-08-22 06:42
@Kmaschta @djhi Is this issue confirmed? I was going through the conversation in #3111 and thought of asking you before implementing this. Should I work on this?

**Comment by djhi** [comment] 2019-08-22 07:20
I'm not sure it's necessary. As you can see in the linked file, we first check for the presence of a record. This means users could create a wrapper component around their `Create`, parse the url themselves and provide this record which will take precedence.

**Comment by christiaanwesterbeek** [comment] 2019-08-28 15:28
Is this what you mean @djhi ?

```javascript
const CreateIgnoringUrlParameters = ({ location = {}, ...rest }) => {
    // some safety guards for situations where location or location.state is missing
    location.state = { ...(location.state || {}), record: {} };
    //                                            ^^^^^^^^^^
    // disable url parameters to become part of the new record
    return (
        <CreateController location={location} {...rest}>
            {controllerProps => (
                <CreateView
                    location={location}
                    {...rest}
                    {...controllerProps}
                />
            )}
        </CreateController>
    );
};
```

**Comment by fzaninotto** [comment] 2020-10-14 23:00
This is no longer a problem since 3.0: we only parse the `source` query parameter. If you pass any other query parameter, it will be ignored:

https://github.com/marmelab/react-admin/blob/02031bdb6e126d3a03dffc811edb3718e48f1dce/packages/ra-core/src/controller/useCreateController.ts#L216-L239

So I'm closing this issue.

**Closed by fzaninotto** 2020-10-14 23:00 UTC
Labels: enhancement
