### ISSUE TITLE
List exporter does not take into account what is in the filter prop

### ISSUE THREAD

**Issue by Hatched-Kyle** [marmelab/react-admin#5286] opened 2020-09-21 20:04 UTC
**What you were expecting:**
I am using the `List` component like the following.

```
<List
        perPage={15}
        pagination={orderPagination()}
        actions={<OrderListActions />}
        filter={{ store_id: storeIdFilter }}
        filters={<OrderListFilter />}
        bulkActionButtons={false}
        exporter={exporter}
        className="admin-list"
        classes={otherClasses}
        sort={{ field: "placed_on", order: "DESC" }}
        {...rest}
      >
``` 
When using the exporter functionality I expect the request to contain the `store_id` filter I have defined in the `filter` prop. 

**What happened instead:**
The `GET` request does not contain the default filter `store_id` in the params

**Environment**

* React-admin version: 3.7.2
* Last version that did not exhibit the issue (if applicable): This did work at one point. Don't remember what version
* React version: 16.12.0
* Browser: All

**Comment by djhi** [comment] 2020-09-24 06:56
Indeed. Thanks for reporting

**Comment by fzaninotto** [comment] 2020-09-24 09:30
The regression came with commit c7129e22a13f4d1c6ef0de5e0319e14ab64f2ee8, when `<ExportButton>` started using data from the `ListContext` rather than from injected props. 

For the fix, the permanent `filter` must be merged into the `filterValues` in `ExportButton`. But since the `filter` isn't present in the `ListContext` yet, that implies modifying the `useListController` and `ListContext`.

**Comment by acrtz** [comment] 2020-09-27 17:20
I would like to make a pull request for this issue. 

I already made the changes and I am now trying to get the tests to pass correctly. When running `make test` on the code before my changes are applied there are already problems. Some of the e-2-e tests (integration/edit.js) are failing, and 8 of the unit tests are getting skipped (same tests fail or are skipped with and without my changes). 

Should I just ignore this and make the pull request or is this something I need to address?

**Comment by fzaninotto** [comment] 2020-09-28 07:30
The failing tests is something you need to address (master is green), you can ignore the skipped tests

**Comment by acrtz** [comment] 2020-09-28 23:26
Turns out the failing tests are due to a bug (#5116) that only affects people in a negative timezone such as GMT-700. I proposed a solution to that issue, and will finish the pull request for this issue after the other one is resolved.

**Comment by CompleteScone** [comment] 2020-12-04 21:18
Checking in on this issue. It looks like the `filter` prop in `useListController` just needs to be passed to the `useListParams()` call in addition to the `filterDefaultValues` prop which already is.

As a note, a work around for this if you don't have a filter component for the fields included in your `filter` prop, you can just pass the same criteria to the `filterDefaultValues` prop and it then appropriately filters the data sent to the `exporter` function.

**Comment by jayanth-2** [comment] 2020-12-15 11:45
I created a pr for this https://github.com/marmelab/react-admin/pull/5666

**Closed** 2020-12-16 14:54 UTC
Labels: bug, good first issue
