### ISSUE TITLE
[AutocompleteInput]: Chrome Address Autofill should be disabled by default

### ISSUE THREAD

**Issue by jtomaszewski** [marmelab/react-admin#5620] opened 2020-12-03 09:50 UTC
We have AutocompleteInput defined in such a way:

```jsx
        <ReferenceInput
          alwaysOn
          label="Owner"
          source="ownerId"
          reference="People"
          filterToQuery={(searchTerm) => ({ searchTerm })}
        >
          <AutocompleteInput
            optionText={ownerRenderer}
          />
        </ReferenceInput>
```

which now ends up in two autocomplete dropdowns being shown at the same time (one of them being the chrome adress autofill dropdown):

![image](https://user-images.githubusercontent.com/1862580/100992854-f6425780-3554-11eb-95b9-ae734d57b61a.png)

This is because the `<input />` has `autocomplete="off"` when it should be `autocomplete="no"` ([see this for reasoning](https://stackoverflow.com/a/30976223/1860149)):

![image](https://user-images.githubusercontent.com/1862580/100992933-09edbe00-3555-11eb-951a-aea7df99c0d1.png)

If I change it manually in Chrome dev tools to `autocomplete="no"`, then the issue is resolved.

IMO Native autocomplete should be turned off for such fields by default. (I don't even know how to turn it off myself - passing `inputProps={{ autocomplete: "no", autoComplete: "no" }}` to `AutocompleteInput` does nothing.

**Environment**

* React-admin version: 3.4.10
* Browser: Os X , chrome Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by djhi** [comment] 2020-12-03 13:31
Can you try the following?
```jsx
<AutocompleteInput
    optionText={ownerRenderer}
    options={AutocompleteOptions}
/>
```

Where `AutocompleteOptions` is:
```jsx
const AutocompleteOptions = { InputProps: { autoComplete: 'no' } }
```

**Comment by jtomaszewski** [comment] 2020-12-03 13:48
Yeah, then it works. Thanks @djhi 

Although it would still be nice to make it a default. I wanted to submit a PR, but I was hard for me to tell what would be the place to put it.

**Comment by etienne-bondot** [comment] 2020-12-08 19:18
I agree, I faced the same and it seems that `autoComplete` is already an available property, so could we at least use it to set `autoComplete: 'no'` ? 
Regards

**Comment by jtomaszewski** [comment] 2021-02-04 06:09
Hmm it works only when being placed in `<SimpleForm`, but not when it is in the list page `<Filters` . Any idea how can I hide the autocomplete for filters?

**Comment by jtomaszewski** [comment] 2021-02-05 04:10
Jesus, Chrome is terrible. See https://stackoverflow.com/questions/30053167/autocomplete-off-vs-false .

If it's a `AutocompleteInput` inside of `<Filters`, it needs to be `autoComplete: "off"` .

If it's a `AutocompleteInput` inside of `<SimpleForm`, it needs to be `autoComplete: "no",` .

Seriously.

I think in the simpleform, it treats it as address autocomplete, and chrome forces autocomplete even if the input has `autocomplete="off"`, and so you have to set it to some arbitrary value like `no` `nope`.

And in the filters, it uses some different autocomplete mechanism, which you have to simply turn off with the way it should be disabled, using `off` ( https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion ).

**Comment by fzaninotto** [comment] 2021-02-05 09:05
We can't do that in the AutocompleteInput, so I guess this boils down to documenting the solution. @jtomaszewski would you mind opening a PR for that?

**Comment by jtomaszewski** [comment] 2021-02-08 22:50
I'm sure we could provide at least one default, that works in one of the cases?

Also, are you sure we can't tell from the `AutocompleteInput` whether we are in `Filters` or not? We could tell that for example if `alwaysOn` prop is given.

So we could do the following inside of https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/AutocompleteInput.tsx#L525 :

```
autoComplete={props.alwaysOn ? "off" : "no"}
```

That would make it work out of the box in:

- inside of `SimpleForm`
- inside of `Filters` when `alwaysOn` prop is given

Which is already better than, work nowhere by default.

WDYT? Would u accept a PR for that? @fzaninotto

**Comment by fzaninotto** [comment] 2021-06-22 20:59
I can't reproduce the bug. Could you explain how to reproduce it?

**Comment by WiXSL** [comment] 2022-01-28 17:30
@jtomaszewski, could you explain how to reproduce this bug?

**Comment by davidhenley** [comment] 2022-03-01 20:11
"off" doesn't work in Chrome but "chrome-off" now works. I cannot believe Chrome keeps ignoring autocomplete props.

This might be the absolute most frustrating thing about React-Admin/Chrome at the moment.

**Comment by fzaninotto** [comment] 2022-07-21 16:53
No news for some time, closing.

**Closed by fzaninotto** 2022-07-21 16:53 UTC
Labels: needs more info
