### ISSUE TITLE
Scrollable tabs on TabForm

### ISSUE THREAD

**Issue by alauper** [marmelab/react-admin#3116] opened 2019-04-10 16:43 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want the possibility to scroll on <Tabs> of <TabbedForm>, when using mobile devices and there are many tabs, some become out of view and is not possible to scroll horizontally to see the hidden ones.

**Additional context**
Material-Ui <Tabs> component receives prop called scrollable that enables horizontal scrolling <TabbedForm> could receive the same prop.

This is similar to https://github.com/marmelab/react-admin/issues/2317 but for TabbedForm.

**Comment by fzaninotto** [comment] 2019-04-19 09:58
Duplicate of #2317

**Comment by fzaninotto** [comment] 2019-04-19 09:58
oops, sorry, I read too fast

**Comment by fzaninotto** [comment] 2019-06-13 07:28
Fixed by #3288

**Closed by fzaninotto** 2019-06-13 07:28 UTC
Labels: enhancement, good first issue
