### ISSUE TITLE
How to use react-admin with the latest version of material-ui?

### ISSUE THREAD

**Issue by dgkmurthy** [marmelab/react-admin#3075] opened 2019-03-31 15:04 UTC
We would like to use mix of custom components along with react-admin based on the latest version of Material-UI.  

As I understand the current version of react-admin is using material-ui 1.4.  

How to use react-admin with the latest version of Material-UI such as v3.9.3 or later?

**Comment by djhi** [comment] 2019-03-31 16:01
Duplicate of #2399

**Closed by djhi** 2019-03-31 16:01 UTC

**Comment by fzaninotto** [comment] 2019-04-05 14:35
see #3102
