### ISSUE TITLE
SimpleForm and TabbedForm forms do not support the "warn" parameter (from redux-form)  

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/react-admin#3218] opened 2019-05-14 11:39 UTC
The documentation states the following: "Tip: The props you pass to <SimpleForm> and <TabbedForm> end up as reduxForm() parameters. This means that, in addition to validate, you can also pass warn or asyncValidate functions. Read the reduxForm() documentation for details."

When I try to pass the "warn" parameter (warn={genWarning()}), the following error occurs:

Warning: Invalid value for prop `warn` on <form> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in form (created by SimpleForm)
    in SimpleForm (created by Form(SimpleForm))
    in Form(SimpleForm) (created by Connect(Form(SimpleForm)))
    in Connect(Form(SimpleForm)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in translate(ReduxForm) (created by Connect(translate(ReduxForm)))
    in Connect(translate(ReduxForm)) (at FPrints.js:345)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by WithStyles(Card))
    in WithStyles(Card)
    in div
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by UnconnectedCreateController)
    in UnconnectedCreateController (created by Context.Consumer)
    in translate(UnconnectedCreateController) (created by Connect(translate(UnconnectedCreateController)))
    in Connect(translate(UnconnectedCreateController))
    in Unknown (created by Create)
    in Create (at FPrints.js:344)
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (created by Context.Consumer)
    in translate(WithStyles(Component)) (created by Connect(translate(WithStyles(Component))))
    in Connect(translate(WithStyles(Component))) (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by Route)
    in Route (created by Resource)
    in Switch (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (at App.js:99)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Route)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Route)
    in Route (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
    in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (at Layout.js:31)
    in AppLayout (created by Connect(AppLayout))
    in Connect(AppLayout) (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdminBase)
    in Switch (created by CoreAdminBase)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdminBase)
    in TranslationProviderView (created by Connect(TranslationProviderView))
    in Connect(TranslationProviderView) (created by CoreAdminBase)
    in Provider (created by CoreAdminBase)
    in CoreAdminBase (created by withContext(CoreAdminBase))
    in withContext(CoreAdminBase) (at App.js:61)
    in App (at src/index.js:9)

Further, eliminating this error in my implementation of the form, I got that using the "warn" parameter has no effect.

* React-admin version: 2.9.0
* React version: 16.8.6
* Browser: Chrome 74.0.3729.131

**Comment by Kmaschta** [comment] 2019-05-14 16:39
Duplicate of https://github.com/marmelab/react-admin/issues/2919

**Closed by Kmaschta** 2019-05-14 16:39 UTC
