### ISSUE TITLE
AutocompleteInput does not insert emptyValue

### ISSUE THREAD

**Issue by Moritz-Friedemann** [marmelab/react-admin#6645] opened 2021-10-04 11:45 UTC
**What you were expecting:**
When the user clicks the empty option, in this case called "Other", the input's value is set to the emptyValue prop (in this case "other").

**What happened instead:**
When clicking the empty option, the searchText is set to the empty string which leads to multiple errors. This is because if the searchText is "", the input value is set to null [https://marmelab.com/react-admin/Inputs.html#:~:text=If%20true%20and%20the%20searchText%20is%20set%20to%20%27%27%20then%20the%20field%20will%20set%20the%20input%20value%20to%20null.](url).

**Steps to reproduce:**
- Create an AutocompleteInput with choices prop and allowEmpty, emptyText and emptyValue
- in the dropdown select the empty option (in this case "Other")
- click anywhere on the screen

**Related code:**

forked code sandbox demonstrating the issue: [https://codesandbox.io/s/react-admin-v3-advanced-recipes-quick-create-preview-forked-w2lf4](https://codesandbox.io/s/react-admin-v3-advanced-recipes-quick-create-preview-forked-w2lf4) Go to comments and click on the create button.

**Comment by WiXSL** [comment] 2021-11-23 14:13
Initial note:
Your code sandbox has an `AutocompleteInput` with choices defined inside a `ReferenceInput`, which is confusing.
After removing the `ReferenceInput`...

You are adding as `emptyValue` a value ("other") that doesn't exist in the defined choices, so it is set to `''`, so the behavior is expected according to the `allowEmpty` prop `If true and the searchText is set to '' then the field will set the input value to null.`

**Comment by WiXSL** [comment] 2022-01-28 11:11
I'm closing this issue since it's not a bug.

**Closed by WiXSL** 2022-01-28 11:11 UTC
Labels: needs more info
