### ISSUE TITLE
Login using customRoute not rerendering resources/drawer

### ISSUE THREAD

**Issue by cutamar** [marmelab/react-admin#4820] opened 2020-05-17 16:46 UTC
**What you were expecting:**

I except to use the login (from `useLogin`) function on a custom route to successfully login, and for the drawer/resources to reload the permissions.

**What happened instead:**

react-admin renders the drawer/resources in the background and at that moment it retrieves the permissions. After the login redirect it doesn't check for permissins anymore and the resources are not re-rendered. So that some resources  are not shown, because the app uses wrong permissions.

**Steps to reproduce:**

1. Use  permissions on`Resources` 
2. Use e.g. custom route for a custom signup page, which logs you in afterwards using (`useLogin`)

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

Those are my custom routes:  
```js
export default [
    <Route exact path="/signup" component={SignUp} noLayout />,
];
```  

Part of the `SignUp` component (the values contain phone and password, where phone is the username):  
```js
    const login = useLogin();
    const notify = useNotify();
    const classes = useStyles();
    const formik = useFormik({
        initialValues: {
            phone: '',
            password: '',
            role: '',
            first_name: '',
            last_name: ''
        },
        onSubmit: async (values, { setStatus }) => {
            try {
                const response = await httpClient('/api/auth/users/', {
                    method: 'POST',
                    body: JSON.stringify(values),
                })
                login({ phone: values.phone, password: values.password })
                    .catch(() => notify('Invalid phone number or password'));
            } catch (e) {
                notify(e.message, 'error');
            }
        }
    });
```
my `Admin` component:  
```js
  <Admin layout={Layout} dataProvider={drfProvider('/api', httpClient)} authProvider={authProvider} loginPage={LoginPage} customRoutes={customRoutes}>
    {role => {
      return [
        <Resource name="checkins" list={CheckInList} create={CheckInCreate} show={CheckInShow} icon={PersonPinCircleIcon} options={{ label: 'Check Ins' }} />,
        <Resource name="myplaces" list={role === ROLES.HOST ? PlaceList : null} edit={PlaceEdit} create={PlaceCreate} show={PlaceShow} icon={StoreIcon} options={{ label: 'My Places' }} />,
        <Resource name="myrooms" list={role === ROLES.HOST ? RoomList : null} edit={RoomEdit} create={RoomCreate} show={RoomShow} icon={RoomIcon} options={{ label: 'My Rooms' }} />,
        <Resource name="guests" list={role === ROLES.HOST ? GuestList : null} create={GuestCreate} show={GuestShow} icon={PeopleIcon} />,
        <Resource name="places" />,
        <Resource name="rooms" />,
      ]
    }}
  </Admin>
```
As you can see depending on the role, some routes won't be rendered. The problem is, the Admin component is only rendered in the background when I go to /signup page, and after the login redirect, it's not rerendered, so I don't see the correct resources.  

Here is also my authProvider:
```js
import jwtDecode from 'jwt-decode';

export default {
    // called when the user attempts to log in
    login: ({ phone, password }) =>  {
        console.log('login start')
        const request = new Request('/api/auth/jwt/create/', {
            method: 'POST',
            body: JSON.stringify({ phone, password }),
            headers: new Headers({ 'Content-Type': 'application/json' }),
        });
        return fetch(request)
            .then(response => {
                if (response.status < 200 || response.status >= 300) {
                    throw new Error(response.statusText);
                }
                return response.json();
            })
            .then(({ access }) => {
                localStorage.setItem('token', access);
            });
    },
    // called when the user clicks on the logout button
    logout: () => {
        localStorage.removeItem('token');
        return Promise.resolve();
    },
    // called when the API returns an error
    checkError: ({ status }) => {
        if (status === 401 || status === 403) {
            localStorage.removeItem('token');
            return Promise.reject();
        }
        return Promise.resolve();
    },
    // called when the user navigates to a new location, to check for authentication
    checkAuth: () => {
        return localStorage.getItem('token')
            ? Promise.resolve()
            : Promise.reject();
    },
    // called when the user navigates to a new location, to check for permissions / roles
    getPermissions: () => {
        console.log('getPermissions start')
        const token = localStorage.getItem('token');
        let role = null;
        try {
            const decodedToken = jwtDecode(token);
            role = decodedToken.role;
        } catch (e) {
            role = '';
        }
        console.log('role ' + role)
        return Promise.resolve(role);
    }
};
```

**Other information:**

**Environment**

* React-admin version: 3.5.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.1
* Browser:
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2020-05-18 06:11
React-admin re-renders the resources if the `authenticated` status changes. In your case, I understand you're only asking the user to log in to update the permissions, so the user is always `authenticated` and the resources only render once. 

https://github.com/marmelab/react-admin/blob/0e81f4fe75294b0a49f5ae2b996c6652940ecfee/packages/ra-core/src/core/CoreAdminRouter.tsx#L42-L46

The solution: when you redirect to the signup page to get updated permissions, you should logout the user first.

**Comment by cutamar** [comment] 2020-05-19 03:40
@fzaninotto thanks for helping with the issue.
The user isn't logged in, in my case (there is no token in the localStorage). The same `SignUp` component works when I use it as a custom LoginPage, but not when using custom routes. Looking at the code, `react-admin` optimistically assumes, the user is authenticated, maybe it's something about that?  

Anyways, I've added a logout (using `useLogout`) in the `SignUp` component now, and it seems to work. It feels kind of a workaround though.

**Comment by fzaninotto** [comment] 2020-05-19 05:59
I can't help you further without looking at more code, and it's not the place to do it - this bug tracker is not for troubleshooting, but only for bugs. so I'm closing this issue as there does not seem to be a bug in react-admin.

**Closed by fzaninotto** 2020-05-19 05:59 UTC
Labels: needs more info

**Comment by rickkln** [comment] 2020-09-27 14:12
Adding to the issue tracker here as I reckon this (_how to implement a signup screen_) is something that could definitely benefit from a sentence or two being added to the documentation as every implementation probably runs into this. I'm happy to submit a PR for that documentation change but first need to just understand what the "proper" way is to implement a custom signup route in `react-admin`.

Currently based on the above we have code similar to the following:
```ts
const SignUp = () => {
  const login = useLogin();
  const logout = useLogout();
  const handleSubmit = async (data: FormValues) => {
      await Api.signUp(data);
      logout('/signup');
      login(data, '/completeYourProfile');
  }
}
```

However despite the inclusion of '/signup' in the logout call it causes the app to first redirect to a blank login screen for a couple of seconds before logging-in, which I'm sure is not the intended behaviour.

**Comment by rickkln** [comment] 2020-09-27 14:41
On my side what I actually ended up doing was this:
```ts
const SignUp = () => {
  const login = useLogin();
  // Required to correctly update authState as unauthenticated and then authenticated after login below.
  // Without this react-admin resources are not correctly re-initialised after login.
  useAuthState(); 
  const handleSubmit = async (data: FormValues) => {
      await Api.signUp(data);
      login(data, '/completeYourProfile');
  }
}
```
It seems calling `useAuthState()` is a decently clean solution to make sure the auth state is correctly tracked on a signup page.
