### ISSUE TITLE
id="react-admin-title" stops working in a custom layout if you use a Custom ListBase on your ListView component

### ISSUE THREAD

**Issue by cordial** [marmelab/react-admin#6210] opened 2021-04-25 15:16 UTC
**What you were expecting:**
If I replace my ListView using the component List with ListBase, the id="react-admin-title" no longer seems to be set inside my CustomLayout
**What happened instead:**
I would expect this to the unaffected by the change.

**Steps to reproduce:**
1. Create Custom Layout
2. Create custom ListView but use ListBase rather than the List component. 

The example in the docs seems to use {props.title} suggesting it should also inside the List view component (its not there either for me - although I dont need it there) - 
https://marmelab.com/react-admin/List.html#the-listbase-component

My Resource - 
```
  <LMSResource projection={["details"]} name="Generic" options={{label: 'Assignments'}} create={AssignmentCreate} list={AssignmentList}
                   title="Assignments" show={AssignmentShow} edit={AssignmentEdit} icon={AssignmentIcon}/>
```

Here is the AssignmentList component - 
```
const AssignmentList = props => {
    return (
    <CustomList
        {...props}
        filterDefaultValues={{ status: 'all' }}
        sort={{ field: 'details.dueDate', order: 'DESC' }}
        perPage={25}
        title="Assignment"
    >
        <TabbedDatagrid />
    </CustomList>
)}; export default AssignmentList;
```

Here is my custom list -   
 
```const CustomList = ({children, ...props}) => (
    <ListBase {...props}>
        <Card>
            <BulkActionsToolbar>
                {props.bulkActionButtons}
            </BulkActionsToolbar>
            {cloneElement(children, {
                hasBulkActions: props.bulkActionButtons !== false,
            })}
            <Pagination />
        </Card>
    </ListBase>
); export default CustomList
 ```

Then deep inside my custom Layout I use the id prop to display the resource name

```
const PageTitle = ({title}) => {
    const classes = useStyles();
   
    return (
        <Typography variant="h6" color="inherit" className={classes.title} id="react-admin-title"/>
    )
}; export default PageTitle
```

Should that not still work? It works fine if I use the normal List component. 

**Other information:**

**Environment**

* React-admin version: "^3.7.1",
* Last version that did not exhibit the issue (if applicable): n/a
* React version: "^17.0.2",
* Browser: any
* Stack trace (in case of a JS error):

**Comment by djhi** [comment] 2021-04-26 07:11
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment] 2021-04-26 07:26
This is by design. `<ListBase>` doesn't set the page title, it's up to you to do it inside `<ListBase>` children using react-admin's `<Title>` component.

This should be documented, though, so I'm marking this as a documentation issue.

**Closed** 2021-06-23 13:39 UTC
Labels: documentation
