### ISSUE TITLE
TabbedForm FormTab not rendering with customRoute

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#4879] opened 2020-06-01 09:08 UTC
**What you were expecting:**
I expected the profile page to work as in Advanced Tutorial [Add a User Profile Page](https://marmelab.com/blog/2019/03/07/react-admin-advanced-recipes-user-profile.html).
For my project on react-admin v 2.3.x, I did profile editing with `<TabbedForm/>`, everything worked there.

**What happened instead:**
I created a similar page on the react admin v 3.5.5. When you select any tab except the main one, nothing is render.

**Steps to reproduce:**
1. Create customRoute Profile
2. Create ProfileEdit with `<TabbedForm/>`
3. Select second Tab

**Related code:**
```
import React from 'react';
import { useSelector, shallowEqual } from 'react-redux';
import { makeStyles } from '@material-ui/core/styles';
import { useEditController, EditView, TextInput, PasswordInput, Toolbar, TabbedForm, FormTab} from 'react-admin';
import SaveProfileButton from '../Buttons/SaveProfileButton';

const validateName = [required(), minLength(2)];
const validateEmail = [ email()];
const validatePhone = [ required() ];

const useStyles = makeStyles(theme => ({
    referenceArrayInput:{
        marginTop: 8,
        marginBottom: 4,
    },
}));

const ProfileToolbar = props => {
    return (
        <Toolbar {...props} >
            <SaveProfileButton />
        </Toolbar>
    );
}

const ProfileEdit = ({staticContext, ...props}) => { 
    const controllerProps = useEditController(props);

    return (
        <EditView 
            {...props}
            {...controllerProps}
            title="Профиль"
            resource="User"
        >
			<TabbedForm redirect="show" toolbar={<ProfileToolbar />}>
				<FormTab label="General">
					<TextInput source="name" validate={validateName} fullWidth/>
				</FormTab>
				<FormTab label="Advanced" path="advanced">
					<PasswordInput source="password" inputProps={{ autoComplete: 'new-password' }}/>
				</FormTab>
			</TabbedForm>
        </EditView>
    );
};


ProfileEdit.defaultProps = {
    resource: "Profile",
    basePath: "/Profile",
    redirect: false,
    
};


const ProfileHOC = (props) => {
    const user = useSelector(state => state.user, shallowEqual);
    if (!user) return null;

    return <ProfileEdit id={user.id} {...props}/>
} 


export default ProfileHOC;
```

**Environment**

* React-admin version: 3.5.5
* Last version that did not exhibit the issue (if applicable): 2.3.x

**Comment by fzaninotto** [comment] 2020-06-02 20:22
I've managed to display tabs in a custom page using react-admin v3, by modifying the simple example:

```jsx
const ProfileEdit = ({ staticContext, ...props }) => {
    return (
        <Edit
            {...props}
            title="Профиль"
            resource="users"
            id={2}
            basePath="/custom2"
        >
            <TabbedForm redirect="show">
                <FormTab label="General">
                    <TextInput source="name" fullWidth />
                </FormTab>
                <FormTab label="Advanced" path="advanced">
                    <PasswordInput source="password" />
                </FormTab>
            </TabbedForm>
        </Edit>
    );
};

const App = () => (
    <Admin
        customRoutes={[
            <Route
                path="/custom2"
                component={props => <ProfileEdit {...props} />}
            />,
        ]}
```

![image](https://user-images.githubusercontent.com/99944/83565960-8ad4ea00-a51f-11ea-8bb4-8f51f206d4f4.png)

So I can't reproduce the bug you're describing.  There is probably a bug in other parts of your code. I suggest you ask for help on StackOverflow.

As this is not a react-admin bug, I'm closing this issue.

**Closed by fzaninotto** 2020-06-02 20:22 UTC

**Comment by wmwart** [comment] 2020-06-03 07:31
Thank! It works. The problem was in customRoutes. I passed the `<Route path="/Profile" component={ProfileEdit} />,` (as stated in Advanced Tutorial) instead `<Route path="/Profile" component={props => <ProfileEdit {...props} />} />` now.
