### ISSUE TITLE
ReferenceArrayInput not passing choices anymore to underlying component (3.0.0-alpha.3)

### ISSUE THREAD

**Issue by BowlingX** [marmelab/react-admin#3600] opened 2019-08-25 21:32 UTC
After upgrading to the latest 3.0 alpha version (alpha.3), the `ReferenceArrayInput` component does not pass down the `choices` props anymore. The cause is this: https://github.com/marmelab/react-admin/commit/57b85e716dab2698b32e1752fa5b0031e56389e8#diff-dc9a2e6b09c659aa6e40fb33102b911c commit (line: https://github.com/marmelab/react-admin/blob/57b85e716dab2698b32e1752fa5b0031e56389e8/packages/ra-ui-materialui/src/input/ReferenceArrayInput.js#L108). The children's props are passed as last argument and `choices` is overwritten with the default prop of  and empty Array (`[]`)

Version: `3.0.0-alpha.3`
React: `16.9.0`

**Comment by djhi** [comment] 2019-08-26 07:25
I can't reproduce it on the simple example (Post edition, miscellaneous tab, tags input). Can you setup a codesandbox to show your issue ?

**Comment by BowlingX** [comment] 2019-08-26 08:24
Thank you for looking into it.
Here is a codesandbox: https://codesandbox.io/s/priceless-mountain-cpcrg?fontsize=14

If you inspect the component Tree, you can see that the data actually exists but is not passed down further:

![image](https://user-images.githubusercontent.com/215671/63676621-9c989c80-c7eb-11e9-81a1-ca85f6d04118.png)

`SelectArrayInput`: 

![image](https://user-images.githubusercontent.com/215671/63676643-ac17e580-c7eb-11e9-9d2a-f380c5ddf78e.png)

**Comment by djhi** [comment] 2019-08-26 10:11
Confirmed. Thanks for reporting :+1:

**Comment by fzaninotto** [comment] 2019-08-26 13:03
Fixed by #3602

**Closed by fzaninotto** 2019-08-26 13:03 UTC
Labels: bug, v3-alpha

**Comment by Boredude** [comment] 2020-03-21 12:46
Seems like this is still hapenning on version 3.2.3

![image](https://user-images.githubusercontent.com/7926261/77226643-994b7080-6b82-11ea-8830-0fbdf2da2688.png)

the getList request is made to fetch the list of reference options
the getOne request is made to fetch the specific resource to edit
the third request getManyReference to fetch the choices is *not* being made
