### ISSUE TITLE
Remove filter button not working if List has filterDefaultValues

### ISSUE THREAD

**Issue by esoulution** [marmelab/react-admin#2547] opened 2018-11-19 22:03 UTC
Remove filter button does not hide filter when filter's default value is set in List component through filterDefaultValues property. Nothing happens on click and no any error message.

```
const ManagerFilter = (props) => (
    <Filter {...props}>
        <TextInput label="app.search" source="q" alwaysOn resettable clearAlwaysVisible />
	<SelectInput label="app.is_active" source="is_active" 
		choices={[
			{ id: 'active', name: 'app.yes' },
			{ id: 'inactive', name: 'app.no' },
		]}
	/>
    </Filter>
);

<List title="app.client_managers" actions={<ListActions />} bulkActions={false} 
    perPage={10} pagination={<Pagination />}
    sort={{ field: "username", order: "ASC" }}  
    filters={<ManagerFilter />} filterDefaultValues={{ is_active: "active" }} 
    {...props}>
```

**Environment**

* React-admin version: 2.4.2

**Comment by fzaninotto** [comment] 2018-12-05 18:38
I'm not sure what's supposed to happen in this case. I understand that you'd like the filter from `<Filter>` to disappear, but the `filterDefaultValue` setting from the `<List>` does indeed set that filter...

I guess it's a corner case that react-admin won't handle. 

I'm waiting for more opinions to close this of mark it as an enhancement.

**Comment by esoulution** [comment] 2018-12-10 16:06
`filterDefaultValue` should work the same way as `defaultValue` for Input components. It just sets default value, and user should be able to change or remove it. Otherwise it's weird user experience to see filter with remove button that does not work.

**Comment by esoulution** [comment] 2018-12-10 22:08
This issue might be related to #2472
`filterDefaultValue` should set filter value only on the first page load

**Comment by fzaninotto** [comment] 2019-01-30 09:22
Let's consider this as a duplicate of #2472. I'm fixing that bug, discussion can continue there.

**Closed by fzaninotto** 2019-01-30 09:22 UTC
