### ISSUE TITLE
Issues with update attempting to fill the GetManyAggregate query cache with [null]

### ISSUE THREAD

**Issue by AlexanderCleasby** [marmelab/react-admin#8513] opened 2022-12-16 16:02 UTC
**What you were expecting:**

We have a react-admin project where one resource 'investment' uses an AutoCompleteInput nested inside of a ReferenceInput that is also referencing the 'investment' dataProvider for the 'Primary' and 'Secondary Benchmark'.
So it looks like so:
```
<ReferenceInput
  label="Secondary Benchmark"
  source="secondaryBenchmarkId"
  reference="investment"
  sort={{ field: "name", order: "ASC" }}
  allowEmpty
>
  <AutocompleteInput optionText="name" />
</ReferenceInput>
```
We expect that no error should be thrown here since we provide allowEmpty.

**What happened instead:**

When we attempt to update this record with no related 'benchmark investment' we get an error whereby useGetManyAggregate is called with resource='investment' and ids=[null] this causes an error when the library tries to fill in the GetOne cache like so:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at onSuccess (useGetManyAggregate.ts:116:1)
    at notifyManager.js:62:1
    at NotifyManager.notifyFn (notifyManager.js:10:1)
    at notifyManager.js:77:1
    at Array.forEach (<anonymous>)
    at notifyManager.js:76:1
    at NotifyManager.batchedUpdates$1 [as batchNotifyFn] (react-dom.development.js:22380:1)
    at notifyManager.js:75:1
```

**Steps to reproduce:**

I believe the issue may be related to the fact that we are updating an 'investment' resource while referencing another 'investment' resource so a reproduction might include that type of data relationship.

**Other information:**

I don't want to lead anyone astray, but tracing my error back I believe these lines are important:

https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetManyAggregate.ts#L116
https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useUpdate.ts#L135

**Environment**

"react-admin": "4.5.4",
"react": "17.0.2"
Google Chrome Version 108.0.5359.98 (Official Build) (x86_64)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at onSuccess (useGetManyAggregate.ts:116:1)
    at notifyManager.js:62:1
    at NotifyManager.notifyFn (notifyManager.js:10:1)
    at notifyManager.js:77:1
    at Array.forEach (<anonymous>)
    at notifyManager.js:76:1
    at NotifyManager.batchedUpdates$1 [as batchNotifyFn] (react-dom.development.js:22380:1)
    at notifyManager.js:75:1
```

**Comment by slax57** [comment] 2022-12-16 17:30
Thanks for submitting this issue and for the investigation work you have done so far.
It seems like there may indeed be a bug we need to fix here, but it will be hard for us to work on a fix without a reproduction case.
Could you please provide a reproduction sandbox forked either from [codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) or [stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple)?
Thanks

**Comment by kearfy** [comment] 2023-01-27 19:51
Heya, would like to note that I am running into the same issue. I have a ReferenceInput set in my edit page, but it throws this error if the field is empty. If a value is selected (a different resource) then it is not throwing an error. Feel free to take a look at my repo: https://github.com/theopensource-company/playrbase/commit/5a93805813eca090994be18da5d03590e40ad0ec

**Comment by kearfy** [comment] 2023-01-27 19:59
@slax57 I added a patch that fixes the issue for me for now, though I've not really invested time into the RA codebase, so I'm not certain if it's a "proper" fix. I included it as a .patch file 
[ra-core@4.7.2.patch](https://github.com/marmelab/react-admin/files/10522659/ra-core%404.7.2.patch)

**Comment by slax57** [comment] 2023-01-30 09:13
I'm not sure how you can encounter this error unless your dataProvider fails to return a response shaped like this: `{ data: {Record[]} }`
Since this is what's expected (have a look at the [Writing A Data Provider doc](https://marmelab.com/react-admin/DataProviderWriting.html#response-format)), I believe the change should be made in your dataProvider instead.

**Comment by fzaninotto** [comment] 2023-11-03 16:35
We think this is not a bug in react-admin but in the OP's data provider, so I'm closing the issue.

**Closed by fzaninotto** 2023-11-03 16:35 UTC
Labels: needs more info
