### ISSUE TITLE
Form 'warn' partially working

### ISSUE THREAD

**Issue by skoschik** [marmelab/react-admin#2016] opened 2018-07-13 17:21 UTC
Great project!!!

**What you were expecting:**
Warning messages do not appear after they are triggered.  Warning to work like [validation](https://marmelab.com/react-admin/CreateEdit.html#validation) via Redux-Form.

**What happened instead:**
No warnings appear, however the warning function gets called.  But it doesn't look like the messages get back the to form fields.

**Steps to reproduce:**
Codesandbox setup for demo of problem  - 
https://codesandbox.io/s/w6x7v4x6l5

**Related code:**
```

const commentWarnings = values => {
  let warnings = {};
  if (values.body && values.body.length < 186) {
    warnings.body = "Write a longer message";
  }
  console.log("warning", warnings);
  return warnings;
};


export const CommentEdit = props => (
  <Edit {...props}>
    <SimpleForm warn={commentWarnings}>
      <DisabledInput source="id" />
      <ReferenceInput
        source="post_id"
        reference="posts"
        perPage={15}
        sort={{ field: "title", order: "ASC" }}
      >
        <AutocompleteInput optionText="title" />
      </ReferenceInput>
      <TextInput source="author.name" validate={minLength(10)} />
      <DateInput source="created_at" />
      <LongTextInput source="body" validate={minLength(10)} />
    </SimpleForm>
  </Edit>
);
```
The warn function gets called but it's result isn't displayed on the form.

**Environment**

* React-admin version: 2.1.1
* React version: 16.4.1
* Browser: Chrome
* Stack trace (in case of a JS error):

Warning: Invalid value for prop `warn` on <form> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM

**Comment by djhi** [comment] 2018-07-13 17:33
Thanks for the report! Closing it as a duplicate of #1000 though

**Closed by djhi** 2018-07-13 17:33 UTC
