### ISSUE TITLE
Improper input value selection process for Autocomplete/ReferenceInput combo

### ISSUE THREAD

**Issue by ZachSelindh** [marmelab/react-admin#8096] opened 2022-08-23 21:20 UTC
**What you were expecting:**
Consistent behavior from AutocompleteInputs as children of ReferenceInputs.

**What happened instead:**
The AutocompleteInput will save incomplete text inputs without having made a dropdown selection. 

The ReferenceInput does not seem to be making the appropriate calls when given the prop "enableGetChoices"

**Steps to reproduce:**
Add an AutocompleteInput with common props such as filterToQuery and shouldRenderSuggestions as a child of a ReferenceInput with common props such as enableGetChoices.

**Related code:**
https://codesandbox.io/s/ecstatic-ptolemy-64jbky?file=/src/posts/PostCreate.tsx

**Environment**

* React-admin version: 4.3.0
* Last version that did not exhibit the issue (if applicable): 4.2.7
* React version: 17
* Browser: Chrome

**Comment by WiXSL** [comment] 2022-08-30 11:23
I don't understand your issue.
Could you be more schematic about how to reproduce the issue, and what is the intended behavior?
Thanks.

**Comment by ZachSelindh** [comment] 2022-08-30 14:03
@WiXSL Absolutely. Essentially, a ReferenceInput used to require to user to select one of the matching choices in the dropdown list. Now, the entered text persists whether a choice has been made or not, which is confusing and will lead to users believing they have made a choice when they have not.

**Comment by WiXSL** [comment] 2022-08-31 11:01
It seems like a bug. I'm marking it as such.
Let me see what I can find since by default, the `AutocompleteInput` has the MUI's `clearOnBlur` prop set to true, but it doesn't seem to be working

**Closed** 2022-09-01 16:24 UTC
Labels: bug
