### ISSUE TITLE
require("history") console warnings

### ISSUE THREAD

**Issue by handreistoicescu** [marmelab/react-admin#3138] opened 2019-04-18 08:02 UTC
Hi! I'm using react-admin version 2.8.5, and I'm getting these warnings in the console. What could be wrong? I did a yarn upgrade also, and the warnings are still there.

`Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.`

`Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.`

`Warning: Please use `require("history").createMemoryHistory` instead of `require("history/createMemoryHistory")`. Support for the latter will be removed in the next major release.`

`Warning: Please use `require("history").PathUtils` instead of `require("history/PathUtils")`. Support for the latter will be removed in the next major release.`

**Comment by fzaninotto** [comment] 2019-04-18 08:48
The core has been fixed fir these warnings (originating from an update in the `history` dependency) in #3085. It's likely that you have an instance of these calls in your own code.

So I'm closing this as we can't reproduce the problem.

In the future, please use the issue template and give us a way to reproduce the bug.

**Comment by handreistoicescu** [comment] 2019-04-18 13:57
I lost a whole day trying to NOT reproduce the problem in different environments. I'm really curious which is the environment that you used, @fzaninotto

**Comment by fzaninotto** [comment] 2019-04-18 15:00
Well, if you do provide a way to reproduce the bug, it helps.

I'm running the simple demo locally and I have no error. But I saw that the error occurs in [the react-admin CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) (that you should have linked form the issue template), so I'm reopening this issue.

**Comment by fvieira** [comment] 2019-04-18 21:19
This seems to be caused by the `react-router-dom` dependency of `ra-core` which is on version 4.2.2 and has been fixed since version 4.3.0-rc.1.

This is the commit that fixed it:
https://github.com/ReactTraining/react-router/commit/a3e6fac7c26dbe1976ccea1e08d63397ce1ffbc5#diff-03323cab9211ecbb380f296cabff2285

**Comment by RandalTeng** [comment] 2019-04-19 06:01
> This seems to be caused by the `react-router-dom` dependency of `ra-core` which is on version 4.2.2 and has been fixed since version 4.3.0-rc.1.
> 
> This is the commit that fixed it:
> [ReactTraining/react-router@a3e6fac#diff-03323cab9211ecbb380f296cabff2285](https://github.com/ReactTraining/react-router/commit/a3e6fac7c26dbe1976ccea1e08d63397ce1ffbc5#diff-03323cab9211ecbb380f296cabff2285)

About the `react-router`, I have upgrade to version 5.0.0, but the warnings is still there. I'm not really sure that this bug is because of this dependency, or there is an another way to  fixed expect of upgrade react-router's version.

**Comment by fzan** [comment] 2019-04-19 07:33
+1 for warnings in console

**Comment by blamze** [comment] 2019-04-19 07:35
I confirm that I get same warrning too, even though I'm using newest react-admin and react-router in my project

"react-router": "5.0.0",
"react-admin": "2.8.5",

And these errors only occured when I've added react-admin

Still hoping for a fix, because it's annoyng to ignore those warrning

**Comment by fzaninotto** [comment] 2019-04-19 08:21
I've been trying to reproduce the warnings within the examples, with no success. Even using tag 2.8.5, reinstalling all packages and rebuilding everything, I can't reproduce the warnings. 

But I do reproduce them by simply creating a new react application depending on react-admin 2.8.5... I'm really scratching my head over this one. I have an idea for a fix, but since I can't test it, I can't move forward.

P.S.: I understand that you're annoyed by these warnings, but you should understand that they don't come from react-admin. It's react-router who added them in a minor release. Feel free to voice your opinion regarding console errors in minor versions in their repository.

**Comment by fvieira** [comment] 2019-04-19 08:41
@RandalTeng @blamze Installing react-router on your project isn't going to fix the warnings, since both `ra-core` and `ra-ui-materialui` still use version `4.2.2` as a dependency.

What did fix the warnings was instaling `react-router` and `react-router-dom` at version `4.3.0`, and then going to node_modules and copying the packages to the node_modules inside `ra-core` and `ra-ui-materialui`.

Of course this isn't a proper fix, but it does seem to confirm my thesis...

**Comment by djhi** [comment] 2019-04-19 08:44
If using yarn, you may try the resolutions

**Comment by fzaninotto** [comment] 2019-04-19 08:55
Resolutions don't work on our monorepo (using yarn 1.15.2, which is the latest version available). But I've managed to reproduce the problem by editing the `yarn.lock` manually (!) and forcing resolution of `history` to 4.9.0 (which is what yarn does on new projects but, for some reasons, refuses to do on our monorepo). I've therefore been able to test my fix, which I'll open a PR for.

**Comment by RandalTeng** [comment] 2019-04-19 09:07
> Resolutions don't work on our monorepo (using yarn 1.15.2, which is the latest version available). But I've managed to reproduce the problem by editing the `yarn.lock` manually (!) and forcing resolution of `history` to 4.9.0 (which is what yarn does on new projects but, for some reasons, refuses to do on our monorepo). I've therefore been able to test my fix, which I'll open a PR for.

It's always cool. Thank you very much. And this issue should to be closed?

**Closed** 2019-04-19 09:08 UTC
Labels: bug

**Comment by handreistoicescu** [comment] 2019-04-19 13:12
Sorry to ask, but I'd need to clear this up: is this fixed now? I mean, are the errors in the console gone?

**Comment by djhi** [comment] 2019-04-19 13:17
we just merged the PR. This will be available in the next release

**Comment by handreistoicescu** [comment] 2019-04-19 13:19
Perfect. Thank you for your work on this!

**Comment by honey-saini** [comment] 2020-06-24 15:44
i solved the problem just by installing react router and react router dom of version 4.3.0

**Comment by jonorril** [comment] 2020-08-04 11:53
> This seems to be caused by the `react-router-dom` dependency of `ra-core` which is on version 4.2.2 and has been fixed since version 4.3.0-rc.1.
> 
> This is the commit that fixed it:
> [ReactTraining/react-router@a3e6fac#diff-03323cab9211ecbb380f296cabff2285](https://github.com/ReactTraining/react-router/commit/a3e6fac7c26dbe1976ccea1e08d63397ce1ffbc5#diff-03323cab9211ecbb380f296cabff2285)

this fixed it for me
