### ISSUE TITLE
ImageInput does not show image previews (it has been broken since v4.2.7)

### ISSUE THREAD

**Issue by magicxor** [marmelab/react-admin#8429] opened 2022-11-24 06:57 UTC
**What you were expecting:**
When you pick new pictures from your file system, `ImageInput` shows them as previews.

**What happened instead:**
When you pick new pictures from your file system, `ImageInput` does not show them.

**Steps to reproduce:**
1) Launch this [CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-ImageInput-bug/draft/elastic-silence?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522claupnbu0000t7ng7egibc2gx%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522claupnf6p000r2a69bwvewwyb%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clauporp0007m2a69nhcbd8w6%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fuser%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522claupoovd005l2a69utprq0ug%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or the code from this [repo](https://github.com/magicxor/react-admin-repro-ImageInput-bug).

2) Try to upload some pictures to the "Avatars (current)" field.

3) Try to upload some pictures to the "Avatars (old)" field (which uses the ImageInput from react-admin v4.2.6-).

![firefox_kWIYSbfSD8](https://user-images.githubusercontent.com/8275793/203714750-1e363959-fe45-4115-90f3-9871c7d2499d.gif)

**Related code:**
```tsx
                <ImageInput label="Avatars (current)" source="avatars1" multiple>
                    <ImageField source="url"/>
                </ImageInput>
```

[CodeSandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-ImageInput-bug/draft/elastic-silence?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522claupnbu0000t7ng7egibc2gx%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522claupnf6p000r2a69bwvewwyb%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clauporp0007m2a69nhcbd8w6%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fuser%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522claupoovd005l2a69utprq0ug%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or the code from this [repo](https://github.com/magicxor/react-admin-repro-ImageInput-bug).

**Other information:**
see:
https://github.com/marmelab/react-admin/issues/7877
https://github.com/marmelab/react-admin/pull/8052

**Workaround:**
Use the old version of ImageInput (https://github.com/magicxor/react-admin-repro-ImageInput-bug/tree/master/src/StableInputs)

**Environment**

* React-admin version: ^4.5.1
* Last version that did not exhibit the issue (if applicable): v4.2.6
* React version: ^18.2.0
* Browser: Chrome 107.0.5304.107 (Official Build) (64-bit) and Firefox 107.0 (64-bit)
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2022-11-24 11:29
Reproduced!
Thanks for the report

**Comment by fzaninotto** [comment] 2022-11-27 20:55
ì don't understand this bug.The doc  says that the preview component should use `src` as source ([even for 4.2](https://marmelab.com/react-admin/doc/4.2/ImageInput.html)). Your example uses `url` as source, which is incorrect.

I take it that it may have worked in the past, but this wasn't the documented usage. 

Or was the ability to use something else than `src` documented somewhere?

**Comment by magicxor** [comment] 2022-11-28 09:46
> ì don't understand this bug.The doc says that the preview component should use `src` as source ([even for 4.2](https://marmelab.com/react-admin/doc/4.2/ImageInput.html)). Your example uses `url` as source, which is incorrect.

"src" is just the name of the property:

![image](https://user-images.githubusercontent.com/8275793/204246008-1fd7ab34-f001-4076-905a-f9d3099482b3.png)

![image](https://user-images.githubusercontent.com/8275793/204246142-2d2e8255-33ae-4bb5-9880-d5fd77845d54.png)

It can be any other valid name

**Comment by fzaninotto** [comment] 2022-11-28 10:05
I don't thinks the doc is ambiguous:

> The input value must be an object or an array of objects with a title and a src property

Means you cannot put the source in another prop. 

If you have a better idea for how to document it, please open a PR! But as for this issue, I'll close it as it's not a bug.

**Closed by fzaninotto** 2022-11-28 10:05 UTC
Labels: needs more info
