### ISSUE TITLE
Rendering issue with hierarchical List inside Show view

### ISSUE THREAD

**Issue by charl3sj** [marmelab/react-admin#3281] opened 2019-05-28 07:00 UTC
**What you were expecting:**
Expecting a List (with permanent filter (whose value comes from API)) **inside Show component** to show contents relevant to the record being "Shown".

**What happened instead:**
List contents reflect rows of previous record as if filter didn't update in time (inconsistent behaviour).

**Steps to reproduce:**

Correct behaviour with TabbedLayout:
See screenshot here: https://imgur.com/a/i8rDCTZ
```
const SubLocationList = (props) =>
    <List {...props} sort={{ field: 'level', order: 'DESC'}}
          filter={{ childrenOf: props.record.lineage }}>
        <Datagrid rowClick="show">
            <TextField source="title"/>
            <TextField label="Type" source="typeString" />
        </Datagrid>
    </List>;

export const LocationDetail = props =>{
    return (
        <Show {...props}>
            <TabbedShowLayout>
                <Tab label="This Location">
                    <TextField source="title" label="Name" />
                    <TextField source="typeString" label="Type" />
                </Tab>
                <Tab label="SubLocations">
                    <SubLocationList {...props}/>
                </Tab>
            </TabbedShowLayout>
        </Show>
)};

```
In the 3rd line `filter={{ childrenOf: props.record.lineage }}>` , `props.record.lineage` is a Postgres LTREE value which is what determines the content of the List.

However, I want to display SubLocations on the same page:
```
export const LocationDetail = props =>{
    return (
        <Show {...props}>
            <SimpleShowLayout>
                <TextField source="title" label="Name" />
                <TextField source="typeString" label="Type" />
                <SubLocationList {...props}/>
            </SimpleShowLayout>
        </Show>
)};
```
In this case, the UI breaks.
See screenshot of desired but incorrect behaviour without TabbedLayout here: https://imgur.com/a/c5YEM2R

**CodeSandbox**
I don't know how to get this to work on CodeSandbox as the filter value depends on a API call and is a LTREE value.

**Environment**

* React-admin version: 2.9.1
* React version: 16.8.4
* Browser: Chrome 74.0.3729.169 (Official Build)

**Comment by fzaninotto** [comment] 2019-05-28 07:04
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Closed by fzaninotto** 2019-05-28 07:04 UTC

**Comment by charl3sj** [comment] 2019-05-28 07:05
This was posted here because it seems like a bug in the List component. Did you even see the behaviours in the screenshots? This is not a HOWTO question.

**Comment by djhi** [comment] 2019-05-28 07:17
It is because the List component is not intended to be used to show related records. Use the ReferenceManyField for that

**Comment by charl3sj** [comment] 2019-05-28 07:36
@djhi  Thanks for the helpful comment. Will try that out.

However, if possible, please do try reproducing the issue by embedding a List with dynamic permanent filter values in a Show view. I still do think it's buggy behaviour.

**Comment by fzaninotto** [comment] 2019-05-28 08:57
We know it doesn't work. But it is not a bug as Datagrid was never intended to be used inside a Show view. If you choose to use a component for another usage than what it was designed for, be prepared to troubleshoot it yourself.
