### ISSUE TITLE
ReferenceInput in a SimpleForm with a defaultValue is not being pre-populated

### ISSUE THREAD

**Issue by christiaanwesterbeek** [marmelab/react-admin#3199] opened 2019-05-07 17:42 UTC
**What you were expecting:**
ReferenceInput in a SimpleForm with a default value being pre-populated. It's demonstrated to be working with ra 2.1.0 here https://codesandbox.io/s/2393m2k5rj and described here: https://marmelab.com/blog/2018/07/09/react-admin-tutorials-form-for-related-records.html 

**What happened instead:**
The ReferenceInput stays empty.

**Steps to reproduce:**
- Open https://codesandbox.io/s/m7w28n9v58 (fork of the other, but with ra 2.9.0)
- Select A Post
- Go to Comments
- Click the Add a Comment button

The Post field (which is a ReferenceInput) stays empty.

**Related code:**
https://codesandbox.io/s/m7w28n9v58

**Other information:**
n/a

**Environment**

* React-admin version: 2.9.0
* Last version that did not exhibit the issue (if applicable): 2.1.0
* React version: 16.8.6
* Browser: Chrome
* Stack trace (in case of a JS error): n/a

**Comment by MhdSyrwan** [comment] 2019-05-09 11:38
I have the same issue. After hours of debugging, I can see now what's the cause of this issue.

What it's written in the example code is trying to feed the query parameters in the record object using the `defaultValue` attribute. meanwhile, there is a code recently added to implement that internally (see that below). https://github.com/marmelab/react-admin/blob/dc3935ec9318c39d0cbb6d26880e57fad8172e5f/packages/ra-core/src/controller/CreateController.tsx#L105

This piece of code does the same of what's done in the example but without parsing (to integer) which would result in duplication of keys ["1", 1] and will cause that behavior you're facing there.

I think there should be a way to disable or override that.

**Comment by MhdSyrwan** [comment] 2019-05-09 11:39
One more note, this can be observed on `react-admin#2.8.2` too.

**Comment by MhdSyrwan** [comment] 2019-05-09 13:08
@christiaanwesterbeek as a workaround, you can pass a fake location to solve the issue like this:

```jsx
const location = { state: { record: { /** defaults to be entered here **/ } } }
return <Create title="bla bla" {...props} location={location}>
{ /** ... **/ }
</Create>
```

make sure you pass the location after the `{...props}` expression, otherwise, your fake `location` would be overridden by the real one in `props`.

**Comment by MhdSyrwan** [comment] 2019-05-09 13:43
see this too, it should solve the issue in a clean way:

https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record

**Comment by MhdSyrwan** [comment] 2019-05-13 09:07
Since it turned out that it's not a bug, and moreover everything was mentioned in the link above. I think we just need to update the example codesandbox to reflect the new "prefill" mechanism.

**Comment by Kmaschta** [comment] 2019-05-14 16:43
Thanks for your findings @MhdSyrwan

**Comment by MhdSyrwan** [comment] 2019-05-15 07:38
Yup, it may be a bug. I think changing the priorities between form defaults and controller defaults would solve the issue and make the old example code work. I mean to make the form defaults override anything else.

**Comment by fzaninotto** [comment] 2020-10-14 22:32
The documentation explains how to initialize a create form using the Link state: https://marmelab.com/react-admin/CreateEdit.html#prefilling-a-create-record

We can close this bug.

**Closed by fzaninotto** 2020-10-14 22:32 UTC
Labels: bug
