### ISSUE TITLE
TypeScript error - when start the demo 

### ISSUE THREAD

**Issue by Selvi-winvest** [marmelab/react-admin#5316] opened 2020-09-29 07:08 UTC
Am trying to run the demo in example.. but below error am getting

SyntaxError: F:\react-admin\examples\demo\src\products\GridList.tsx: Identifier 'width' has already been declared (51:4)

  49 |
  50 | const LoadingGridList: FC<GridProps & { nbItems?: number }> = ({
> 51 |     width ,
     |     ^
  52 |     nbItems = 20,
  53 | }) => {
  54 |     const classes = useStyles();
Compiling...
Compiling...
Files successfully emitted, waiting for typecheck results...
Files successfully emitted, waiting for typecheck results...
Failed to compile.

TypeScript error in F:/react-admin/examples/demo/src/products/GridList.tsx(58,35):
Argument of type 'string | number | undefined' is not assignable to parameter of type '"xs" | "sm" | "md" | "lg" | "xl"'.
  Type 'undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl"'.  TS2345

    56 |         <MuiGridList
    57 |             cellHeight={180}
  > 58 |             cols={getColsForWidth(width)}
       |                                   ^

**Comment by djhi** [comment] 2020-09-29 07:20
I don't have any errors when running the demo from the `master` branch. Can you pull the latest changes and retry?

**Comment by yograf** [comment] 2020-09-29 10:30
Same here.

**Comment by fzaninotto** [comment] 2020-09-30 09:31
What is the version of `react-admin`, `ra-ui-material-ui`, and `@material-ui/core` that you're using?

**Comment by CaoDuyThanh** [comment] 2020-10-04 03:36
hi @Selvi-winvest, I got the similar problem, try to use @types/react version 16.9.0, I found that the later version had additional field `width` in interface TableHTMLAttributes<T> in module `@types/react/index.d.ts` and it conflicts with WithWidth. Hope this help.

**Comment by fzaninotto** [comment] 2020-10-08 14:39
I'm not sure I understand: the bug occurs with a version of react types more recent than 16.9.0? Because I'm using `"@types/react-dom@^16.9.4"` and I don't see the problem.

**Comment by dream811** [comment] 2020-10-09 07:45
![image](https://user-images.githubusercontent.com/45660446/95556744-5a113e00-0a46-11eb-9ca4-9f0b5b918817.png)
I met same error.

**Comment by fzaninotto** [comment] 2020-10-12 16:49
I still can't reproduce the error. Here is what I did:

```sh
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
make install
make build
make run-demo
```

I'm using Node v12.16.1

Please give a way to reproduce the issue or we'll have to close it.

**Comment by yograf** [comment] 2020-10-13 06:20
OK, it's working fine now. thx @fzaninotto.

**Closed** 2020-10-13 06:56 UTC
Labels: needs more info

**Comment by Amitkad** [comment] 2020-10-28 14:57
I've also faced the issue, when trying the following:
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
cd examples
cd demo
npm start

is something wrong with the above ?

**Comment by fzaninotto** [comment] 2020-11-09 15:28
@Amitkad Please follow the steps explained in my comment above instead:

```
git checkout git@github.com:marmelab/react-admin.git
cd react-admin
make install
make build
make run-demo
```
