### ISSUE TITLE
NumberInput accepts letters on Firefox and Safari

### ISSUE THREAD

**Issue by guoyibj** [marmelab/react-admin#3167] opened 2019-04-26 07:52 UTC
**What you were expecting:**

NumberInput component should not accept letter input except letter e.

**What happened instead:**

On Firefox and Safari you are able to input any letters and special characters to the NumberInput field.

**Steps to reproduce:**

<img width="542" alt="safari-number" src="https://user-images.githubusercontent.com/35130561/56792047-36027280-683b-11e9-9274-7298dfdf74a2.png">

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by guoyibj** [comment] 2019-04-26 07:53
https://github.com/marmelab/react-admin/issues/2135

**Comment by manattersa** [comment] 2019-06-14 22:55
¿Any upgrade on this issue? This is still happening in v. 2.9.1.

**Comment by fzaninotto** [comment] 2019-06-17 12:53
Duplicate of #2135

**Closed by fzaninotto** 2019-06-17 12:53 UTC
Labels: bug

**Comment by Kmaschta** [comment] 2019-06-17 13:55
@fzaninotto `e` is a valid number for `1e10`, but all others characters shouldn't be accepted. They are not wiith chrome.

**Comment by fzaninotto** [comment] 2019-06-17 14:16
This is a Firefox issue.
