### ISSUE TITLE
BooleanInput has required attribute options

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#7915] opened 2022-06-30 14:58 UTC
Is this a Rider problem or are the props wrong?

`"react-admin": "^4.2.0"`

![Screen Shot 2022-06-30 at 9 56 49 AM](https://user-images.githubusercontent.com/15056748/176709830-fa2dba2a-51e8-4237-a557-d106322d2f66.png)

![Screen Shot 2022-06-30 at 9 58 05 AM](https://user-images.githubusercontent.com/15056748/176710003-38151044-5bdd-4f9d-9b41-60092a5b3389.png)

**Comment by slax57** [comment] 2022-07-01 08:21
Hi,

I'm not sure why the propTypes are marked as Requireable since we did not mark them as required in our source:

```tsx
BooleanInput.propTypes = {
    ...InputPropTypes,
    // @ts-ignore
    options: PropTypes.shape(Switch.propTypes),
    disabled: PropTypes.bool,
};

BooleanInput.defaultProps = {
    options: {},
};
```

Same thing happens with the `disabled` prop although it's obviously not required.

I'm not really sure what is happening here.

Do you have a way for us to reproduce this issue? Is it reproducible in a codesandbox for instance?

Thanks

**Comment by fzaninotto** [comment] 2022-08-05 15:44
No news for some time, closing

**Closed by fzaninotto** 2022-08-05 15:44 UTC
Labels: needs more info
