### ISSUE TITLE
Override of cell style in `Datagrid` not working as expected (for some css properties)

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#2329] opened 2018-09-18 07:32 UTC
**What you were expecting:**
Override of cell style in `Datagrid` through `withStyles` for `rowCell` to work for all style properties.

**What happened instead:**

The generated class is lower in order from the `Datagrid` (and some `mui) classes: 

![image](https://user-images.githubusercontent.com/7850073/45671340-e124ae00-bb2d-11e8-8102-7b9cbc5039f9.png)

**Related code:**

```
const styles = {
  rowCell: {
    padding: '0px',
    backgroundColor: 'red',
  }
};
const MovementListEnhanced = withStyles(styles)(MovementList);
export { MovementListEnhanced as MovementList };
```

AND

```
      <Datagrid
        rowStyle={rowStyle}
        classes={{ rowCell: classes.rowCell }}
      >
```

**Other information:**

**Environment**

* React-admin version: 2.3.1

**Comment by fzaninotto** [comment] 2018-09-19 14:06
I can't reproduce the issue on master. Can you provide a CodeSandbox demonstrating the problem?

**Comment by fzaninotto** [comment] 2018-09-28 06:38
Bump, can you provide a way to reproduce your issue?

**Comment by fzaninotto** [comment] 2018-10-02 16:07
No news for some time, closing.

**Closed by fzaninotto** 2018-10-02 16:07 UTC
