### ISSUE TITLE
[Feature Request] Allow the list to change its inner view component dynamically

### ISSUE THREAD

**Issue by shawnchen1980** [marmelab/react-admin#3030] opened 2019-03-20 13:18 UTC
My code is something like

```
<List ...{props}>
condition?<View1/>:<View2/>
</List>
```

But it doesn't work and I found this in the list logic

```
 shouldComponentUpdate(nextProps: Props & EnhancedProps, nextState) {
        if (
            nextProps.translate === this.props.translate &&
            nextProps.isLoading === this.props.isLoading &&
            nextProps.version === this.props.version &&
            nextState === this.state &&
            nextProps.data === this.props.data &&
            nextProps.selectedIds === this.props.selectedIds &&
            nextProps.total === this.props.total
        ) {
            return false;
        }
        return true;
    }
```

I think there should be a way to allow the list re-render a new view without fetching the data. Even a customized datagrid doesn't help sometimes. For example, I want one view with the pagination toolbar but the other view without it.

**Comment by djhi** [comment] 2019-03-20 13:37
Can you please explain your use case with more details?

**Comment by fzaninotto** [comment] 2019-03-20 13:39
I think it's a duplicate of #1488

**Comment by shawnchen1980** [comment] 2019-03-20 15:06
I'm developing an app to teach my son English words. Each entry in the list is for a single word. In the quiz mode, the list component should show a series of quiz for each word. It also has its navigation button so I want to hide the pagination tool bar. Now the following codes work but in an inefficient way because each time I switch the mode, the whole list is unmounted and remounted and the data for the same page is re-fetched.
```
const renderView = mode => {
 
  return mode === "edit" ? (
    <Datagrid rowClick="edit">
      <TextField source="wordbook.name" />
      <TextField source="word.spelling" />
      <TextField source="word.translation" />
    </Datagrid>
  ) : (
    <WordQuiz />
  );
};
const WList = ({ mode, dispatch, ...props }) => {
 
  return (
    <List key={mode} {...props} pagination={mode === "edit" ? undefined : null}>
      {renderView(mode)}
    </List>
  );
};
```

**Comment by fzaninotto** [comment] 2019-03-20 15:23
Definitely a duplicate, I'm closing this issue, please comment on the other one.

**Closed by fzaninotto** 2019-03-20 15:23 UTC
Labels: awaiting more info
