### ISSUE TITLE
Rerender Issue after image upload

### ISSUE THREAD

**Issue by abhishekrup** [marmelab/react-admin#9180] opened 2023-08-14 08:54 UTC
Hii, 
I am getting a re-render issue when i am uploading image inside Edit in react-admin 
As soon as i am uploading the image from file manager it gets re-render and uploaded image gets removed and also you can see in video when i am clearing the console and clicking on the screen then also it gets re-render i am uploading the video and also the code. Need a solution 

```jsx
const EditForm1 = () => {
    return (
        <FileInput source="attachments">
            <FileField source="src" title="title" />
        </FileInput>
    )
}

const ComplaintManagementsEdit = ({ ...props }) => {
 <SimpleForm toolbar={<EditToolbar />}>
            <EditForm1 />
        </SimpleForm>
}
```

 "react": "18.2.0",
 "react-admin": "^4.11.3",
 
 

https://github.com/marmelab/react-admin/assets/134288913/106dbfdb-7ee4-4ee3-b524-4c6d9e221ef5

**Comment by fzaninotto** [comment] 2023-08-14 16:42
I cannot reproduce the issue you describe in the simple example Stackblitz:

https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Fposts%2FPostEdit.tsx

Click on a post in the list, click on the "related pictures" area in the post edition form, attach a picture, and it appears. 

Could you please fork this stackblitz and modify it to demonstrate the issue?

**Comment by abhishekrup** [comment] 2023-08-16 04:46
Ok so i have a screen of edit with <Edit> tag and under that <SimpleForm> so under simpleForm i have called a function of EditForm and under that i have a option of file upload, so as soon as i upload new file the screen gets render and it started showing old data again also if i click anywhere outside the screen and then again click on screen at that time also it renders the screen you can see it on the video uploaded above 

const EditForm = () => {

<FormDataConsumer>
                    {({ formData, ...rest }) => {
                        console.log("formData////////", formData)
                        console.log("inside rest", rest);

                        const GetFiles = async (files) => {
                            setFileTypeValidation(false);
                            setFileSizeValidation(false);
                            setFileExtensionValidation(false);
                            // this.setState({
                            //     fileTypeValidation: false,
                            //     fileSizeValidation: false,
                            //     fileExtensionValidation: false

                            // });
                            console.log('files', files)
                            const maxSize = 10;
                            let fileSize = 0;
                            const fileExtension = ["jpg", "png", "doc", "docx", "xls", "xlsx", "ods", "odt", "csv", "pdf", "JPG", "PNG"];
                            const validFileType = ["application/pdf", "text/csv", "application/msword", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "image/gif", "image/png", "image/jpeg", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.oasis.opendocument.spreadsheet", "application/octet-stream", ""]
                            let seletedArrayType = []
                            let seletedFileExtension = []
                            {
                                files.forEach(file => {
                                    fileSize += file.file.size;
                                    seletedArrayType.push(file.file.type)
                                })
                            }
                            let extension;
                            {
                                files.forEach(file => {
                                    // file.file.name.item.split(".").pop(-1);
                                    extension = file.file.name.substring(file.file.name.lastIndexOf(".") + 1, file.file.name.length);
                                    console.log('extension>>>>>>>>', extension);
                                    seletedFileExtension.push(extension.toLowerCase());
                                })
                            }
                            // console.log('seletedFileExtension', seletedFileExtension);
                            // console.log('validFileType', validFileType);
                            // console.log('seletedArrayType', seletedArrayType);
                            if (!(!seletedFileExtension.some(val => fileExtension.indexOf(val) === -1))) {
                                setFileExtensionValidation(true);
                                // this.setState({
                                //     fileExtensionValidation: true
                                // });

                            }

                            if (!fileExtensionValidation) {
                                console.log("inside1");
                                if (!(!seletedArrayType.some(val => validFileType.indexOf(val) === -1))) {
                                    setFileTypeValidation(true);
                                    console.log("inside2");
                                    // this.setState({
                                    //     fileTypeValidation: true
                                    // });
                                } else {
                                    console.log("inside3");
                                    // formData.files = files

                                    for (let x = 0; files.length > x; x++) {
                                        let data = compress(files[x]);
                                        console.log('inside data', data)
                                    }

                                }
                                if ((fileSize / 1024 / 1024) > maxSize) {
                                    console.log("inside4");
                                    setFileSizeValidation(true);
                                    // this.setState({
                                    //     fileSizeValidation: true
                                    // });
                                }
                                else {
                                    console.log("inside5", files);
                                    // formData.files = files
                                    // formContext.setValue("files", files);
                                    // const updatedFormData = { ...formData, files: files };
                                    // rest.setFormData(updatedFormData);
                                    console.log("formData555555", formData);
                                }
                            }


                        }

                        const compress = (e) => {
                            console.log('inside eeee', e);
                            return new Promise((resolve, reject) => {
                                const fileName = e.name;
                                const reader = new FileReader();
                                reader.readAsDataURL(e.file);
                                reader.onload = (event) => {
                                    const img = new Image();
                                    img.src = event.target.result;
                                    img.onload = () => {
                                        const elem = document.createElement('canvas');
                                        const imgWidth = img.width;
                                        const width = (imgWidth / 100) * 75;
                                        // const size = img.size / 1024 / 1024;
                                        const scaleFactor = width / imgWidth;
                                        elem.width = width;
                                        elem.height = img.height * scaleFactor;
                                        const ctx = elem.getContext('2d');
                                        ctx.drawImage(img, 0, 0, width, img.height * scaleFactor);
                                        ctx.canvas.toBlob((blob) => {
                                            const file = new File([blob], fileName, {
                                                type: 'image/jpeg',
                                                lastModified: Date.now(),
                                            });
                                            resolve(true);
                                        }, 'image/jpeg', 0.75);
                                    };
                                    img.onerror = () => {
                                        reject(false);
                                    }


                                    reader.onerror = error => reject(false);
                                };
                            });
                        }

                        // console.log('hii')
                        return (
                            <div>
                                <div>
                                    <p className="upload-files-label">{translate('resources.complaints.fields.upload_file')}</p>
                                    <FileBase64
                                        multiple={true}
                                        onDone={GetFiles} />
                                    {fileExtensionValidation &&
                                        <div class="complaint-file-error">{translate('resources.complaints.fields.file_extension_invalid')}</div>
                                    }

                                    {fileSizeValidation && !(fileSizeValidation && fileTypeValidation) &&
                                        <div className="complaint-file-error">{translate('resources.complaints.fields.file_size')}</div>
                                    }
                                    {fileTypeValidation && !(fileSizeValidation && fileTypeValidation) &&
                                        <div className="complaint-file-error">{translate('resources.complaints.fields.file_type_invalid')} </div>
                                    }
                                    {fileSizeValidation && fileTypeValidation &&
                                        <div className="complaint-file-error">{translate('resources.complaints.fields.both_invalid')} </div>
                                    }
                                </div>
                                <div className="valid-file-upload">
                                    <p>{translate('resources.complaints.fields.instruction')}</p>
                                    <ul>
                                        <li>{translate('resources.complaints.fields.allowed_type')}</li>
                                        <li>{translate('resources.complaints.fields.max_size')}</li>
                                        <li>{translate('resources.complaints.fields.please_wait')}</li>
                                        <li>{translate('resources.complaints.fields.upload_timing')}</li>
                                    </ul>
                                </div>
                            </div>
                        )

                    }

                    }
                </FormDataConsumer>
                }

const ComplaintManagementsEdit = ({ ...props }) => {
return (
 <Edit title={<EditTitle />} actions={<ShowActions />}>
            <SimpleForm toolbar={<EditToolbar />}>
            <EditForm />
        </SimpleForm>
        </Edit>
)
}

Here is my code also i have used "import FileBase64 from 'react-file-base64'" this package to upload the file i tried with using FileInput of react-admin as well but render issue is still there

**Comment by abhishekrup** [comment] 2023-08-16 04:59
Ok so i have a screen of edit with tag and under that so under simpleForm i have called a function of EditForm and under that i have a option of file upload, so as soon as i upload new file the screen gets render and it started showing old data again also if i click anywhere outside the screen and then again click on screen at that time also it renders the screen you can see it on the video uploaded above
I am uploading below my file in which i am getting the issue 
[renderEditForm.js.zip](https://github.com/marmelab/react-admin/files/12355808/renderEditForm.js.zip)

**Comment by fzaninotto** [comment] 2023-08-16 07:38
This is not enough for us to investigate, we need to be able to run a project that reproduces the issue. Please tweak the aforementioned StackBlitz until you can reproduce the issue.

**Comment by fzaninotto** [comment] 2023-09-13 19:22
No news for some time, closing.

**Closed by fzaninotto** 2023-09-13 19:22 UTC
Labels: needs more info
