### ISSUE TITLE
SimpleFormIterator causes warning: Each child in a list should have a unique "key" prop -- why?

### ISSUE THREAD

**Issue by dejancg** [marmelab/react-admin#5289] opened 2020-09-22 20:26 UTC
**What you were expecting:**
I expected the key prop to be set properly.

**What happened instead:**
Chrome threw a console error, saying `Warning: Each child in a list should have a unique "key" prop.`

**Steps to reproduce:**
Hopefully I won't have to create a code sandbox for this, I imagine there are not many possible causes for `key` property to be left unset. 

Let's say I have a component called MyComponent, defined like this:

```ts
interface IMyComponentProps{
  choices: Array<{id: number, name: string, children: Array<{id: number, name: string}>}>
  source: string;
  label?: string;
  validate?: ((
    value: any,
    values: any
  ) =>
    | string
    | {
        message: string;
        args: any;
      }) & {
    isRequired: boolean;
  };
}

export const MyComponent = (props: IMyComponentProps) => {
  const { choices, source, validate, label, ...rest } = props;
  const form = useForm();
  const translate = useTranslate();

  return (
  <ArrayInput source={source} validate={validate} label={label} {...rest}>
    <SimpleFormIterator>
      <FormDataConsumer>
        {(formDataProps) => {
            if (!formDataProps.getSource) {
              return null;
            }

            const { getSource, scopedFormData } = formDataProps;
            return (
              <div className="some-css-class-name-I-used">
                <SelectInput
                  source={getSource("someId")}
                  validate={required()}
                  choices={choices}
                  onChange={() => form.change(getSource("someOtherId"), null)}
                  {...rest}
                  label={translate("resources.common.labels.someId")}
                />
                <SelectInput
                  source={getSource("someOtherId")}
                  validate={required()}
                  choices={
                    choices.find(
                      (x) =>
                        x.id === scopedFormData?.someId
                    )?.children
                  }
                  {...rest}
                  label={translate("resources.common.labels.someOtherId")}
                />
              </div>
            );
        }}
      </FormDataConsumer>
    </SimpleFormIterator>
  </ArrayInput>
  );
}
```

Now put this component into a form (I used a custom form based on your TabbedForm but shouldn't make any difference, right?)
and put the form, let's call it `MyForm`, into `MyCreate` and `MyEdit` components. When creating a record, I get no errors when adding multiple children to `MyComponent`. However when opening the `MyEdit` view, I get the above mentioned error in my console.

I have seen the code of `SimpleFormIterator` but the problem isn't obvious to me.

**Call stack trace:**
```
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SimpleFormIterator`. See https://fb.me/react-warning-keys for more information.
    in CSSTransition (created by SimpleFormIterator)
    in SimpleFormIterator (at MyComponent.tsx:32)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ArrayInput)
    in ArrayInput (at MyComponent.tsx:31)
    in MyComponent (at MyForm.tsx:69)
    in div (created by FormInput)
    in FormInput (created by FormTab)
    in span (created by FormTab)
    in FormTab (at MyForm.tsx:63)
    in Route (at MyCustomTabbedForm.tsx:247)
    in div (at MyCustomTabbedForm.tsx:238)
    in form (at MyCustomTabbedForm.tsx:224)
    in TabbedFormView (at MyCustomTabbedForm.tsx:131)
    in FormView (created by ReactFinalForm)
    in ReactFinalForm (created by FormWithRedirect)
    in FormWithRedirect (at MyCustomTabbedForm.tsx:128)
    in TabbedForm (at MyForm.tsx:40)
    in MyForm (at MyEdit.tsx:11)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by EditView)
    in div (created by EditView)
    in div (created by EditView)
    in EditView (created by Edit)
    in Edit (at MyEdit.tsx:10)
    in MyEdit (created by WithPermissions)
    in WithPermissions (created by Context.Consumer)
    in Route (created by ResourceRoutes)
    in Switch (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (at AdminWrapper.tsx:77)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Context.Consumer)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Context.Consumer)
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in ThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (at Layout.tsx:41)
    in Unknown (created by Context.Consumer)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Context.Consumer)
    in Route (created by CoreAdminUI)
    in Switch (created by CoreAdminUI)
    in CoreAdminUI (created by AdminUI)
    in AdminUI (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by CoreAdminContext)
    in TranslationProvider (created by CoreAdminContext)
    in CoreAdminContext (created by AdminContext)
    in AdminContext (created by Admin)
    in Admin (at AdminWrapper.tsx:56)
    in AdminWrapper (at App.tsx:60)
    in Provider (at App.tsx:46)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)
```

**Environment**

* React-admin version: 3.8.5
* Last version that did not exhibit the issue (if applicable): n/a
* React version: 16.13.1
* Browser: Chrome 85.0.4183.102
* Stack trace (in case of a JS error): above

**Comment by djhi** [comment] 2020-09-24 06:51
Thanks for reporting this. Can you please provide a sample application by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) showing the issue?

**Comment by fzaninotto** [comment] 2020-09-24 09:42
Yes, unfortunately we really need a codesandbox reproducing the issue, because a similar code is used in the simple example without emitting any warning. 

```jsx
// in examples/simple/src/posts/PostEdit.js
const PostEdit = ({ permissions, ...props }) => (
    <Edit title={<PostTitle />} actions={<EditActions />} {...props}>
        <TabbedForm initialValues={{ average_note: 0 }} warnWhenUnsavedChanges>
            <FormTab label="post.form.summary">
                ...
                {permissions === 'admin' && (
                    <ArrayInput source="authors">
                        <SimpleFormIterator>
                            <ReferenceInput
                                label="User"
                                source="user_id"
                                reference="users"
                            >
                                <AutocompleteInput />
                            </ReferenceInput>
                            <FormDataConsumer>
                                {({
                                    formData,
                                    scopedFormData,
                                    getSource,
                                    ...rest
                                }) =>
                                    scopedFormData && scopedFormData.user_id ? (
                                        <SelectInput
                                            label="Role"
                                            source={getSource('role')}
                                            choices={[
                                                {
                                                    id: 'headwriter',
                                                    name: 'Head Writer',
                                                },
                                                {
                                                    id: 'proofreader',
                                                    name: 'Proof reader',
                                                },
                                                {
                                                    id: 'cowriter',
                                                    name: 'Co-Writer',
                                                },
                                            ]}
                                            {...rest}
                                        />
                                    ) : null
                                }
                            </FormDataConsumer>
                        </SimpleFormIterator>
                    </ArrayInput>
                )}
            </FormTab>
            ...
        </TabbedForm>
    </Edit>
);
```

**Comment by dejancg** [comment] 2020-09-24 13:36
Hey @fzaninotto and @djhi, thanks for your responses.
I didn't want to deal with that simple example from CodeSandbox as me and CodeSandbox seem to be having hard time getting along. Whenever I tried to fork your simple example I'd receive an error in console saying WDS Disconnected, which resulted in inability to refresh the browser preview on the right after I edited the code. And besides, I don't have the time to set up the code sandbox with custom models on json-server which would allow us to open an edit form for some resource which matches this issue.

Anyway. I have resolved this issue. I understand it would be preferable if I submitted a PR and resolved it that way, which would also put my name amongst the great contributors of this great project, but I figured it would also be OK if I just shared the resolution here, so one of you guys can make a PR out of it if you feel the solution is OK.

I will explain the issue.
Let's first take a look at the code which causes the warning:

```ts
<TransitionGroup component={null}>
    {fields.map((member, index) => (
      <CSSTransition
        key={ids.current[index]} // <------ ids.current[index] is undefined
        timeout={500}
        classNames="fade"
        {...TransitionProps}
      >
         ...
      </CSSTransition>
</TransitionGroup>
```
The problem was caused by `ids.current[index]` being undefined, because `ids.current` contained an empty array. But that shouldn't happen if `fields` were not empty, right? So let's see what caused that.

In `SimpleFormIterator` component, you initialized the `nextId` ref using the length of `fields` array if there were any received. If there were no fields received, the component looked for any `defaultValues` and initialized the `nextId` value using the length of `defaultValues` which also must be an array. If both of those were empty or undefined, it was initialized to 0. A little later, the `ids` ref is initialized using the value from `nextId`, so it contains as many IDs as there are elements in `fields` or `defaultValues`. If `nextId` was 0, that would cause `ids` to be initialized to an empty array.

This part with `defaultValues` is OK. The previous part with `fields` wasn't OK and caused problems. 

The problem occurred because at that moment, the `fields` array was still undefined, even though we might have opened an edit form with existing ArrayInput values, which left us with `nextId` initialized to 0. The correct way to implement this would be to only initialize `nextId` and `ids` using the `defaultValues`, and use an effect to override those values if `fields` were supplied.

So, when initializing these refs, I used the following code:

```ts
  // ...

  // We need a unique id for each field for a proper enter/exit animation
  // so we keep an internal map between the field position and an auto-increment id.

  /* BEGIN MODIFICATION */
  // If we have defaultValue array as a prop and it contains items, use that to initialize the next id.
  // If the component receives fields, useEffect will override this value using the received fields length.
  const nextId = useRef<number>((defaultValue && defaultValue.length) ?? 0);
  /* END MODIFICATION */

  // We check whether we have a defaultValue (which must be an array) before checking
  // the fields prop which will always be empty for a new record.
  // Without it, our ids wouldn't match the default value and we would get key warnings
  // on the CssTransition element inside our render method
  const ids = useRef(
    nextId.current > 0 ? Array.from(Array(nextId.current).keys()) : []
  );

  /* BEGIN MODIFICATION */
  useEffect(() => {
    // Dont't run this effect if there are no fields received by the component
    if (!fields || !fields.length) {
      return;
    }

    // Set the nextId and ids refs respectably based on the length of supplied fields.
    nextId.current = fields.length;
    ids.current = Array.from(Array(fields.length).keys());
  }, [fields]);
  /* END MODIFICATION */

```

Hopefully this made sense. It certainly did solve the warning for me.
Feel free to close the issue yourself after the PR is created and merged (or not :D)

**Comment by fzaninotto** [comment] 2020-09-24 15:48
Thanks for taking the time to look into the problem. 

I understand your line of thought, what I don't understand is why you have a warning and I don't. Using the simpleExample, it works fine without your changes.

Also, you say that the problem occurs when the `fields` is undefined. But in that case, `nextId` is set to `defaultValue.length` anyway, so there is no difference with your code. 

It would really help if you could build a minimal reproductible case. If codesandbox doesn't work for you, try forking the react-admin repository and tweaking the simple example to reproduce the warning. Use `make install && make run` to test your changes.

**Comment by fzaninotto** [comment] 2020-09-24 16:18
> But even if you specified ~~defaultProps~~ `defaultValue` I think there could possibly be a problem of not matching lengths of defaultValues and actual fields, which might cause bad values in ids ref.

Do you mean if someone passes an array of `defaultValue` without the same lengths as the children of `SimpleFormIterator`? Yes, that's a possibility - but in my opinion, this is a problem on the developer side. We could detect it and throw an error, though. 

> someone already opened a similar issue in the past

You're probably referring to #5090. I can't reproduce it either on the simple example.

> If you are still not convinced, I might try to bake an example

We'll definitely need that. Thanks for your help!

**Comment by dejancg** [comment] 2020-09-26 11:46
Hey guys @fzaninotto and @djhi,

Here are some more informations in hope that they would help get a hold of this issue.

I tried to reproduce the issue first by using your simple example as a starting point. When that worked fine, I tried to do the same with demo example, but that worked fine too, even with my custom form elements.

Then I went to my project and noticed that when the form renders, some values are rendered with a delay when using the regular API call for `dataProvider.getOne()`. If I switch to using the mock API for that resource, values were rendered insantly.

When opening the edit form and using the call to the regular API, I get these two in the console:
```
[Violation] Forced reflow while executing JavaScript took 79ms <--- Form inputs are rendered empty
[Violation] Forced reflow while executing JavaScript took 101ms <--- Form values are rendered
```

However, when opening the edit form and using the call to the mock API, I also get these two messages in the console, with similar times, except both form inputs and values get rendered at the same time, with the first message.

There is nothing special about my data provider when calling API versus when calling the mock API. Both are APIs, regular API is hosted in ASP.NET Core and mock API is hosted in json-server, both are running at the same time and both on localhost. The only difference is, when calling the regular API, proxy methods are resolved from a really big file auto-generated by openapi-generator.

**Comment by WiXSL** [comment] 2020-09-29 13:03
I am having exactly this same issue, I'll try to upload to codesandbox when I can.

**Comment by dejancg** [comment] 2020-09-29 13:27
> I am having exactly this same issue, I'll try to upload to codesandbox when I can.

Try using a custom SimpleFormIterator with changes I described here: https://github.com/marmelab/react-admin/issues/5289#issuecomment-698348786

It should fix the warning because the nextId and ids refs should be set to proper `fields.length` when `fields` prop is received.

Even though @fzaninotto said this:
> Also, you say that the problem occurs when the fields is undefined. But in that case, nextId is set to defaultValue.length anyway, so there is no difference with your code.

I have to disagree because `defaultValue` might not be set at all.

**Comment by WiXSL** [comment] 2020-09-29 13:34
@dejancg thank you.
I've already read your post and  I'll try it and comment.

**Comment by dejancg** [comment] 2020-09-29 13:50
The root cause could be somewhere in edit controller (I am not yet familiar with that part of react-admin) which calls dataProvider to obtain the record for edit.  It should probably not render the form if the data hasn't been obtained yet,

**Comment by WiXSL** [comment] 2020-10-05 00:09
The simplest way I found to reproduce it is to duplicate the "authors" `ArrayInput` in `PostEdit`.

https://codesandbox.io/s/awesome-blackwell-o0yo2

1. Edit any Post
2. At the bottom of the `Summary` tab try to add an author in any of the two `ArrayInput` components

![error](https://user-images.githubusercontent.com/8268610/95030406-e954d500-0685-11eb-8cee-6b00792a342b.png)

**Comment by dejancg** [comment] 2020-10-06 22:05
Well, I should also note that the workaround I posted in the comments above with `useEffect` caused some unforseen consequences when using `react-final-form`'s `form.change()`  - in some cases after the aforementioned method is used, the custom iterator I produced above failed to render anything at all.. so I'm back to using the original `SimpleFormIterator` and the mystery still remains.

**Comment by fzaninotto** [comment] 2020-10-08 13:18
@WiXSL I can reproduce the bug with your example but 1/ I don't understand what happens (it must be a bug in react-final-form-arrays) and 2/ it's not a valid use case (It doesn't make sense to give 2 ways to edit the same array). When I have 2 ArrayInput in the same form with different names, I can't reproduce the issue. 

So I'm still stuck at reproducing this bug for a valid use case...

**Comment by fzaninotto** [comment] 2020-10-29 16:24
Any updates on this one?

**Comment by dejancg** [comment] 2020-10-29 16:30
It's likely a bug with react-final-form, but I have one more scenario on my
mind. It's difficult to find time for that these days, but I will try to
bake one more example in the next few days.

**Comment by dejancg** [comment] 2020-11-21 18:12
@fzaninotto Unfortunately, I wasn't able to reproduce this. I don't know what else to try. It still happens in my app all the time, but...I'm out of ideas.

**Comment by fzaninotto** [comment] 2020-11-23 09:52
Without any way to reproduce it, I have to close this issue. We have to focus on problems that we can actually fix.

Thanks anyway for the report!

**Closed by fzaninotto** 2020-11-23 09:52 UTC
Labels: needs more info
