### ISSUE TITLE
Layout breaks when building react admin in a react app

### ISSUE THREAD

**Issue by 7hibault** [marmelab/react-admin#3796] opened 2019-10-09 19:58 UTC
**What you were expecting:**

The same layout as in dev mode

**What happened instead:**

The layout is perfectly fine locally

![image](https://user-images.githubusercontent.com/8068131/66515283-1efcc780-eadf-11e9-9c17-c1d93ab14d25.png)

But when I build the app, the layout breaks and behaves weirdly (it sometimes does as in the screenshot as sometimes becomes unreadable because too narrow).

![image](https://user-images.githubusercontent.com/8068131/66515203-eeb52900-eade-11e9-99ca-06e749d91159.png)

PS: only the grey bars were added to hide the data, but the rest is as shown in the screenshot

**Steps to reproduce:**

* Create a react app using CRA
* Create a React Admin app
* Create a route in the react app to redirect to React Admin
* Build the code 
* Serve the build

I haven't been able to reproduce a smaller example that displays the bug but I'm working on it

**Environment**

* React-admin version:^2.9.6
* React version:^16.9.0
* Browser: observed in firefox and chrome

**Comment by fzaninotto** [comment] 2019-10-10 07:08
Probably a duplicate of #3741 or other production rendering bugs. Please search for existing issues with "production" or "styles".

**Closed by fzaninotto** 2019-10-10 07:08 UTC
