### ISSUE TITLE
Incorrect caching of resources after authentication error

### ISSUE THREAD

**Issue by fzan** [marmelab/react-admin#7976] opened 2022-07-15 07:13 UTC
Hi,
After a week struggling to find what i did wrong in my code, i finally think that this is a bug.
Please note to follow carefully the steps to reproduce.

**What you were expecting:**
after an error like 401 (eg: token expiration) when i log again, i expect the list resource i was visiting (example: the /posts list) to ask dataProvider for fresh data and show the list

**What happened instead:**
React admin shows "data.map is not a function".
![datamapnotafunction](https://user-images.githubusercontent.com/6927527/179167486-1c6585c7-7844-4f15-9a6a-7ae6418470ab.png)

**Steps to reproduce:**
1) open this sandbox (i think any with react-admin ^4.0.0 is affected) [https://codesandbox.io/s/iuxnw](https://codesandbox.io/s/iuxnw)
2) when you start the sandbox, you are already logged in. Now simulate an error using, for example `localstorage.setItem("session_ended",true) `
![sessionend](https://user-images.githubusercontent.com/6927527/179168327-7b9e4f68-070c-4944-beca-4792da856dc3.png)
Please use the sandbox terminal like in the screenshot
3) visit another resource, like Comments or Posts or whatever
4) you are logged out with an error **"Session Ended"** in the console
![sessionenderror](https://user-images.githubusercontent.com/6927527/179168537-ee1d2440-0d02-42b2-b5fc-371491b6baf7.png)
5) you are now in the login page. Now remove the data from localStorage with `localStorage.removeItem("session_ended") `
6) please enter the login data: "admin" and "password".
7) you will see the error 

**Other information:**

IMHO this problem relates to the cache system, i think react-query save the request, and associate it to the resource via internal cache system
https://marmelab.com/react-admin/Caching.html
even if it is an error.

The only way to reload correctly the resource is to actually completely refresh the page, triggering again the resource request.

**Please note** that, even if you made a redirect after login, as
`navigate("/")`
the resource is **still broken**, and when you will visit it, the error will be shown

**Environment**

* React-admin version: 4.2.2
* React version: 17.0.0 (sandbox but i tested also with 18 on my project)
* Browser: chrome
* Stack trace (in case of a JS error):

data.map is not a function

    at CommentGrid (https://iuxnw.sse.codesandbox.io/index.bundle.js:184112:81)
    at ListView (https://iuxnw.sse.codesandbox.io/index.bundle.js:184150:79)
    at ListContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:108909:20)
    at ResourceContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:111804:23)
    at ListBase (https://iuxnw.sse.codesandbox.io/index.bundle.js:108756:23)
    at CommentList
    at Routes (https://iuxnw.sse.codesandbox.io/index.bundle.js:174589:5)
    at ResourceContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:111804:23)
    at Resource (https://iuxnw.sse.codesandbox.io/index.bundle.js:111709:24)
    at Routes (https://iuxnw.sse.codesandbox.io/index.bundle.js:174589:5)
    at ErrorBoundary (https://iuxnw.sse.codesandbox.io/index.bundle.js:166894:37)
    at div
    at main
    at div
    at div
    at https://iuxnw.sse.codesandbox.io/index.bundle.js:590:66
    at Layout (https://iuxnw.sse.codesandbox.io/index.bundle.js:132815:20)
    at __WEBPACK_DEFAULT_EXPORT__
    at div
    at Routes (https://iuxnw.sse.codesandbox.io/index.bundle.js:174589:5)
    at CoreAdminRoutes (https://iuxnw.sse.codesandbox.io/index.bundle.js:111570:79)
    at Routes (https://iuxnw.sse.codesandbox.io/index.bundle.js:174589:5)
    at CoreAdminUI (https://iuxnw.sse.codesandbox.io/index.bundle.js:111640:20)
    at AdminUI (https://iuxnw.sse.codesandbox.io/index.bundle.js:121592:27)
    at InnerThemeProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:39499:70)
    at ThemeProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:39210:5)
    at ThemeProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:39519:5)
    at ThemeProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:134101:23)
    at ResourceDefinitionContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:111877:17)
    at NotificationContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:118069:23)
    at I18nContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:117532:17)
    at Router (https://iuxnw.sse.codesandbox.io/index.bundle.js:174523:15)
    at HistoryRouter (https://iuxnw.sse.codesandbox.io/index.bundle.js:118290:23)
    at InternalRouter (https://iuxnw.sse.codesandbox.io/index.bundle.js:118210:23)
    at BasenameContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:118262:23)
    at AdminRouter (https://iuxnw.sse.codesandbox.io/index.bundle.js:118199:22)
    at QueryClientProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:172589:21)
    at StoreContextProvider (https://iuxnw.sse.codesandbox.io/index.bundle.js:118607:20)
    at CoreAdminContext (https://iuxnw.sse.codesandbox.io/index.bundle.js:111509:30)
    at AdminContext (https://iuxnw.sse.codesandbox.io/index.bundle.js:121537:20)
    at Admin (https://iuxnw.sse.codesandbox.io/index.bundle.js:138266:30)

**Comment by joobacca** [comment] 2022-07-15 07:38
This is probably a duplicate of #7911. I was able to fix the problem somewhat by disabling the react-query cache (as I mentioned [here](https://github.com/marmelab/react-admin/issues/7911#issuecomment-1180462707)), but some end users are still having the issue and the error can only be dodged by manually setting different filter values (than the cached request) with query parameters.

**Comment by fzan** [comment] 2022-07-15 07:47
hello @joobacca , thank you
my bad that i didn't find that issue. 
I searched before posting, but #7911 is still not labeled as a bug. 
Let's hope that, with a more clear explanation of the steps, it will be labeled as bug and then assigned and resolved.

Your suggestion furthermore may can cover my use case, that after login the redirect url resource is broken because the missing cache. I will try to figure out how to manually redirect after login, adding some trivial random querystring parameters

**Comment by septentrion-730n** [comment] 2022-07-20 12:36
Reproduced! Thanks for the detailed report, this is undoubtedly an annoying bug.

**Comment by fzan** [comment] 2022-07-20 12:52
> Reproduced! Thanks for the detailed report, this is undoubtedly an annoying bug.

Thank you @septentrion-730n , i also want to let you know that the solution @joobacca provided is working. 

Disabling React-query cache via

```
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            cacheTime: 0,
            staleTime: 0,
        },
    },
});
```

and adding it in <Admin> as the queryClient solve the issue. 
But obviously it disable the cache so there is a huge performance hit.

**Closed** 2022-07-20 20:56 UTC
Labels: bug
