### ISSUE TITLE
Error in handleRedirection generator

### ISSUE THREAD

**Issue by in19farkt** [marmelab/react-admin#1781] opened 2018-04-25 05:32 UTC
**What you were expecting:**
If `dataProvider` in `GET_ONE` case rejects error, that should be redirected to the list

**What happened instead:**
`handleRedirection` thrown exception `Cannot read property 'id' of null`.

**Steps to reproduce:**
Change your data provider:
```
async function dataProvider(type, resource, params) {
  switch (type) {
    case GET_ONE: return Promise.reject();
    default: throw new Error(`Unsupported fetch action type ${type}`);
  }
}
```
and go to any show page.

**Environment**

* React-admin version: 2.0.0-RC2
* React version: 16.2.0
* Browser: Google Chrome 66
* Stack trace (in case of a JS error):
```
uncaught at rootSaga at rootSaga 
 at admin 
 at admin 
 at takeEvery 
 at handleRedirection 
 TypeError: Cannot read property 'id' of null
    at handleRedirection$ (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:193703:137)
    at tryCatch (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:124573:40)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:124807:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:124625:21)
    at next (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39095:27)
    at proc (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39054:3)
    at runForkEffect (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39338:19)
    at runEffect (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39219:872)
    at next (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39099:9)
    at currCb (http://localhost:8080/js/vendor-4a08fd59667eb1e680b7.bundle.js:39172:7)
```

**Comment by fzaninotto** [comment] 2018-05-09 10:26
Duplicate of #1789

**Closed by fzaninotto** 2018-05-09 10:26 UTC

**Comment by goussakamarwan** [comment] 2018-10-25 10:03
Hi,
I have reached this stage ( Connecting To A Real API)
and i create All page  But iget error => Failed to fetch 

I change URL to New URL const API_URL = "https://goussaka.com";
See this img Thanks

- error
<img width="1280" alt="screen shot 2018-10-25 at 10 56 52 am" src="https://user-images.githubusercontent.com/7656403/47492380-c936fd00-d844-11e8-9ef8-b04b343364de.png">
- my APP.JS
<img width="1280" alt="screen shot 2018-10-25 at 10 58 32 am" src="https://user-images.githubusercontent.com/7656403/47492461-f08dca00-d844-11e8-9d9c-aab493d0e8ec.png">

**Comment by fzaninotto** [comment] 2018-10-25 12:39
@goussakamarwan Posting comments multiple times in unrelated and closed issues is not cool. Don't spam us it again or we'll ban you from this repo.

**Comment by karamokoisrael** [comment] 2021-08-11 13:50
> Duplicate of #1789

thanks
