### ISSUE TITLE
ReferenceInput -> AutocompleteArrayInput - item disappears visually after choosing

### ISSUE THREAD

**Issue by ilaif** [marmelab/react-admin#4514] opened 2020-03-11 19:41 UTC
**What you were expecting:**
When using an `<AutocompleteArrayInput>` inside a `<ReferenceInput>`, and typing for autocomplete, the chosen item should stay visible in the UI choices.

**What happened instead:**
The item disappears visually (but no in the actual store):
![2020-03-11-21-24-disappearing](https://user-images.githubusercontent.com/3540825/76456085-25210800-63df-11ea-8bb8-116bb5f426c0.gif)

**Steps to reproduce:**

Creating this layout reproduces the bug:

```javascript
<SimpleForm resource={RESOURCE_NAME}>
  <ReferenceInput
    source="externalId"
    reference={RESOURCE_NAME}
    filterToQuery={searchText => ({
      _q_name: searchText
    })}
  >
    <AutocompleteArrayInput optionValue="externalId" label="" />
  </ReferenceInput>
</SimpleForm>
```

Where RESOURCE_NAME is defined under the main <Admin> component and **this SimpleForm is on another screen**. It seems like the input is trying to insert a value that it cannot find after choosing the value.

This also happens with `<AutocompleteInput>`.

When choosing from the initial list without typing, it works fine:

![Peek 2020-03-11 21-37](https://user-images.githubusercontent.com/3540825/76456965-990fe000-63e0-11ea-941e-e8ca02b2eab0.gif)

**Environment**

* React-admin version: 2.9.0
* Last version that did not exhibit the issue (if applicable): -
* React version: ^16.12.0
* Browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by fzaninotto** [comment] 2020-03-12 10:56
This is fixed in v3. If someone from the community wants to fix this in v2, then please open a PR. Otherwise, we'll close this issue within a few months.

**Comment by ilaif** [comment] 2020-03-12 17:47
@fzaninotto Can you reference the area of the code that is problematic along with hints as to why it's not working?

A non-related issue: I actually tried to upgrade to v3, but I used refs in many places on react-admin components that were changed to functional components, and I'm now kind of lost in how to fix that. It's not mentioned in the migration guide. Where would I ask such a question to get some help? 

Thanks!

**Comment by JulienMattiussi** [comment] 2020-03-13 08:42
IMO, Sucess this v3 migration would be the best solution to solve your `AutocompleteArrayInput`

`refs` are not especially described in the Migration guide because they are not supposed to be problematic.
When rewriting a component to functional, you just have to call `useRef` now.
Something like replacing `this.myRef = React.createRef();` by `const myRef = React.useRef()`
Can you give a more specific example of what is currently blocking with refs ?

**Comment by ilaif** [comment] 2020-03-13 10:08
Sure,

I'm creating a ref inside a parent component:
```
class Parent extends Component {
  constructor() {
    this.innerSimpleFormRef = React.createRef();
  }

  render() {
    <SimpleForm ref={this.innerSimpleFormRef} ...>
      <ReferenceInput ....>
        ...
      </ReferenceInput>
    </SimpleForm>
  }
}

Then, one of my methods are checking the state of the SimpleForm to extract the AutoCompletes chosen value.

If this is off-topic we can move the discussion elsewhere.

Thanks a lot!
Ilai

**Comment by JulienMattiussi** [comment] 2020-03-13 12:31
@ilaif But if you write this, it doesn't work ?

```
const Parent = () => {
  const innerSimpleFormRef = React.useRef();

  return (
    <SimpleForm ref={this.innerSimpleFormRef} ...>
      <ReferenceInput ....>
        ...
      </ReferenceInput>
    </SimpleForm>
  );
}
```

**Comment by ilaif** [comment] 2020-03-13 18:25
It says:
```
react-dom.development.js:16178 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons...
```

**Comment by jdemangeon** [comment] 2020-04-14 08:00
Hello @ilaif, do you have tested @JulienMattiussi solution? In absence of response, we'll consider closing this issue.

**Comment by erheme318** [comment] 2020-08-25 07:27
>This is fixed in v3. 

@fzaninotto
The issue is still there in `3.8.2`. So, when you type autocomplete input (<AutocompleteArrayInput> inside a <ReferenceInput>), the previous selected items are disappeared. IMO it's because suggestion list don't include the previous items, so the previous selected item names are disappeared. But i'm not sure

**Comment by Geekstips** [comment] 2021-02-19 20:01
I also have this issue while trying to use example from here and one of the fields from the dialog is ReferenceInput:
https://voyci.csb.app/#/comments/create
Please any hint on how to solve this?

**Comment by fzaninotto** [comment] 2021-02-26 07:54
If you believe this bug still appears in the latest version of react-admin, please open a new issue and follow the issue template to include a reproducible example.

**Comment by WiXSL** [comment] 2022-01-28 23:34
No news for over a year. Closing this Issue.
Please, feel free to re-open it if you find a way to reproduce it with the latest version of react-admin.

**Closed by WiXSL** 2022-01-28 23:34 UTC
Labels: v2
