### ISSUE TITLE
ReferenceInput and AutocompleteInput  is not cleaning data after updated

### ISSUE THREAD

**Issue by jadzeino** [marmelab/react-admin#3609] opened 2019-08-27 08:32 UTC
hi,

i have 2 fields the first called **Partner** and the second called **AcquisitionSubchannel** 
when user select a partner the AcquisitionSubchannel should be changed based on the partner id since its a reference input.

## Problem
however if there was already selected AcquisitionSubchannel and you changed the partner it looks like selected AcquisitionSubchannel is added to the component  along with the right partner-AcquisitionSubchannel

## expected:
the old selected AcquisitionSubchannel should be cleaned out and the new AcquisitionSubchannel related to the selected partner should be the only available one.

here is the code:- 

```
<PartnersSingleInput
                            reference="partners_filter"
                            label="resources.campaigns.filters.partner"
                            source="partner_id"
                            resource="partner_id"
                            {...rest}
                        />

<FormDataConsumer>
                        {({formData, ...rest}) =>
                            formData.partner_id && (
                                <ReferenceInput
                                    allowEmpty
                                    label="resources.campaigns.fields.acquisitionSubchannel"
                                    source="acquisition_subchannel_id"
                                    resource="partner_id"
                                    reference="acquisition_subchannels_filter"
                                    filter={{partner_id: formData.partner_id}}
                                    sort={{field: 'name', order: 'ASC'}}
                                    perPage={0}
                                    validate={validateAcquisitionSubchannel}
                                    {...rest}
                                >
                                    <AutocompleteInput optionText="name" />
                                </ReferenceInput>
                            )
                        }
                    </FormDataConsumer>
```

and for the **PartnerSingleInput** here is the code

![final_5d64ea36d75b320014564224_287370](https://user-images.githubusercontent.com/11145282/63754854-df26ab80-c8b5-11e9-8148-4349cb6ec2ca.gif)

```
export const PartnersSingleInput = ({label, source, reference}) => (
    <Query type={GET_LIST} resource={reference} payload={payload}>
        {({data}) =>
            data && (
                <AutocompleteInput
                    allowEmpty
                    label={label}
                    source={source}
                    choices={data}
                    translateChoice={false}
                    validate={validatePartner}

                />
            )
        }
    </Query>
)
```
 👍

**Comment by fzaninotto** [comment] 2019-09-03 21:55
Duplicate of #2431

**Closed by fzaninotto** 2019-09-03 21:55 UTC
