### ISSUE TITLE
Wrong "previousData" sent to data provider from <ReferenceArrayInput>

### ISSUE THREAD

**Issue by Sheraff** [marmelab/react-admin#3618] opened 2019-08-28 13:41 UTC
This issue occurs inside an `<Edit>` view, and only if the user directly lands on that page. There is no issue when *navigating to* that page from a `<List>` view for example.

Basic structure:
```html
<Edit>
	<SimpleForm>
		<ReferenceArrayInput reference="sessions" source="relationships.sessions">
			<CustomDragAndDropArrayReorderingInput/>
		</ReferenceArrayInput>
	</SimpleForm>
</Edit>
```

On page load, I have a `<FormDataConsumer>` logging the received record:
`formData.relationships.sessions [17, 11, 16, 15, 14, 13]`

When the user makes an edit, the same `<FormDataConsumer>` logs the changes:
`formData.relationships.sessions [17, 11, 16, 15, 14]`

And when I click *submit*, the `dataProvider` receives:
```js
params: {
	data: {
		relationships: {
			sessions: [17, 11, 16, 15, 14]
		}
	},
	previousData: {
		relationships: {
			sessions: [17, 11, 16, 15, 14]
		}
	}
}
```

**Environment**

- macOS 10.14.6
- Chrome 76.0.3809.100
- react-admin 2.9.6

**Comment by Kmaschta** [comment] 2019-09-23 12:57
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by fzaninotto** [comment] 2019-11-07 19:21
No news for some time, plus I can't reproduce the issue, so I must close it.

**Closed by fzaninotto** 2019-11-07 19:21 UTC
Labels: awaiting more info
