### ISSUE TITLE
TypeError: authProvider.checkAuth is not a function

### ISSUE THREAD

**Issue by amelyec** [marmelab/react-admin#5200] opened 2020-08-28 22:29 UTC
**What you were expecting:**
login page
**What happened instead:**
TypeError: authProvider.checkAuth is not a function
**Steps to reproduce:**
Only added App.js and authProvider.js 
**Related code:**

```
import * as React from "react";
import authProvider from './authProvider';
import { Admin, Resource, ListGuesser } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';


const dataProvider = jsonServerProvider('https://jsonplaceholder.typicode.com');
const App = () => (
    <Admin dataProvider={dataProvider} authProvider={authProvider}>
        <Resource name="users" list={ListGuesser} />
    </Admin>
);

export default App;
```

**Other information:**

**Environment**

* React-admin version:^3.8.2
* Last version that did not exhibit the issue (if applicable):
* React version:^16.13.1
* Browser:Chrome
* Stack trace (in case of a JS error):
```TypeError: authProvider.checkAuth is not a function
(anonymous function)
E:/code/my-app/node_modules/ra-core/esm/auth/useCheckAuth.js:49
  46 | if (params === void 0) { params = {}; }
  47 | if (logoutOnFailure === void 0) { logoutOnFailure = true; }
  48 | if (redirectTo === void 0) { redirectTo = defaultAuthParams.loginUrl; }
> 49 | return authProvider.checkAuth(params).catch(function (error) {
     | ^  50 |     if (logoutOnFailure) {
  51 |         logout({}, error && error.redirectTo
  52 |             ? error.redirectTo

```

**Comment by djhi** [comment] 2020-08-31 06:26
There is not enough information here to understand what you did. Please fork the codesandbox and modify it to show the issue.

**Comment by fzaninotto** [comment] 2020-10-08 15:26
No news for more than a month, closing.

**Comment by rafaellehmkuhl** [comment] 2020-10-14 12:43
I can confirm this happens by following the [Authentication tutorial](https://marmelab.com/react-admin/Authentication.html).

Apparently the code provided for the authProvider is incomplete (missing checkAuth):

```javascript
// in src/authProvider.js
const authProvider = {
    login: ({ username, password }) =>  {
        const request = new Request('https://mydomain.com/authenticate', {
            method: 'POST',
            body: JSON.stringify({ username, password }),
            headers: new Headers({ 'Content-Type': 'application/json' }),
        });
        return fetch(request)
            .then(response => {
                if (response.status < 200 || response.status >= 300) {
                    throw new Error(response.statusText);
                }
                return response.json();
            })
            .then(auth => {
                localStorage.setItem('auth', JSON.stringify(auth));
            });
    },
    // ...
};

export default authProvider;
```

**Comment by artemkozlenkov** [comment] 2020-10-28 21:18
> I can confirm this happens by following the [Authentication tutorial](https://marmelab.com/react-admin/Authentication.html).
> 
> Apparently the code provided for the authProvider is incomplete (missing checkAuth):
> 
> ```js
> // in src/authProvider.js
> const authProvider = {
>     login: ({ username, password }) =>  {
>         const request = new Request('https://mydomain.com/authenticate', {
>             method: 'POST',
>             body: JSON.stringify({ username, password }),
>             headers: new Headers({ 'Content-Type': 'application/json' }),
>         });
>         return fetch(request)
>             .then(response => {
>                 if (response.status < 200 || response.status >= 300) {
>                     throw new Error(response.statusText);
>                 }
>                 return response.json();
>             })
>             .then(auth => {
>                 localStorage.setItem('auth', JSON.stringify(auth));
>             });
>     },
>     // ...
> };
> 
> export default authProvider;
> ```

yes you're right, the sample code is incomplete, probably intentionally since it would be pretty obvious; 
you may overcome this with looking at the type of `AuthProvider` in `node_modules/ra-core/src/types.ts`, there you will see minimum amount of methods necessary for good working authenticator, however, experience proves, you need only 3 of those: 

`login, checkAuth and getPermissions`, so for the other use temporary work around to see the direct output:

```
// in src/authProvider.js
export const authProvider = {
    login: ({username, password}) => {
        const request = new Request('https://mydomain.com/authenticate', {
            method: 'POST',
            body: JSON.stringify({username, password}),
            headers: new Headers({'Content-Type': 'application/json'}),
        });
        return fetch(request)
            .then(response => {
                if (response.status < 200 || response.status >= 300) {
                    throw new Error(response.statusText);
                }
                return response.json();
            })
            .then(auth => {
                localStorage.setItem('auth', JSON.stringify(auth));
            });
    },
    checkAuth: (...params) => {
        return Promise.resolve();
    },
    getPermissions: () => {
        return Promise.resolve();
    }
};
```

please, note, that in order to build fully functioning, secure authenticator you may need to fully implement all those functions.
Regards.

**Comment by Stefanbracke** [comment] 2021-06-09 22:37
The tutorial could be adapted as everyone comes back to this page.

**Comment by djhi** [comment] 2021-06-10 07:02
We would gladly accept a PR to fix it :)

**Closed** 2021-12-06 08:47 UTC
Labels: documentation
