### ISSUE TITLE
React admin not unmounting nested `ArrayInput`s

### ISSUE THREAD

**Issue by andriivitrenko** [marmelab/react-admin#9839] opened 2024-05-10 14:21 UTC
**What you were expecting:**
I have a form with nested `ArrayInput`s and those inputs are required to make sure that they have at least one element. And I wanted to remove one of `categories` from the list. The list was not empty and I expected successfully save it.

**What happened instead:**
Instead I received error in removed element that `rows` are required.

**Steps to reproduce:**
1. Fill `categories` with more than 1 element
2. Save it
3. Remove one element
4. Try to save form
5. See error

**Related code:**

```
<ArrayInput source="categories" validate={required()}>
  <SimpleFormIterator>
    <ArrayInput source="rows" validate={required()}>
      <SimpleFormIterator>
        <TextInput source="title" validate={required()} />
      </SimpleFormIterator>
    </ArrayInput>
  </SimpleFormIterator>
</ArrayInput>
```

**Environment**

* React-admin version: 4.16.12
* React version: 18.2.0
* Browser: latest

**Comment by erwanMarmelab** [comment] 2024-05-13 11:56
Hello @andriivitrenko, 

Could you please make a [stackblitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple) or a [codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple)

I made a first experimentation on this [Stackblitz repo](https://stackblitz.com/edit/github-zrf6w7?file=src%2Fusers%2FUserEditEmbedded.tsx) but this bug doesn't appears

**Comment by slax57** [comment] 2024-06-27 13:26
Closing as duplicate of https://github.com/marmelab/react-admin/issues/9961
Thanks for the report.

**Closed by slax57** 2024-06-27 13:26 UTC
Labels: needs more info
