### ISSUE TITLE
AutocompleteArrayInput chip not displaying as expected

### ISSUE THREAD

**Issue by Wraiyth** [marmelab/react-admin#5813] opened 2021-01-25 10:17 UTC
**What you were expecting:**
When editing an item that uses AutocompleteArrayInput wrapped inside ReferenceArrayInput, the chip will display correctly. 

**What happened instead:**
The chip works when selecting from the list, however when loading the page the chip is blank

**Steps to reproduce:**
Unable to provide a sample application

**Related code:**
Use of ReferenceArrayInput and AutocompleteArrayInput as follows:
```
<ReferenceArrayInput label="Assets" reference="webemt/assets" source="assetIDs" validate={[required()]} allowDuplicates="true">
      <AutocompleteArrayInput />
</ReferenceArrayInput>
```
When editing an item, the API calls are made as expected:

```
{"assetIDs":["25"],"id":1,"microtransactionId":1,"name":"Key","description":"Opens a locked Dinosaur or Human crate","originalPrice":199,"currentPrice":199,"currency":null,"categories":"Featured","isActive":false}
```

A subsequent API call is made to `assets?id=25`, which returns (truncated for brevity):
```
[{"id":25,"background_color":"000000","icon_url":null,"name":"Classic Key"}]
```

However, what I see in the UI is as follows:
![image](https://user-images.githubusercontent.com/1154986/105691885-e55d0380-5f51-11eb-9f56-04252030bfe5.png)

Noting that the autocomplete list works:
![image](https://user-images.githubusercontent.com/1154986/105691946-f9a10080-5f51-11eb-9507-ffd856a6d460.png)

And if I select something from the list, the chip is displayed correctly:
![image](https://user-images.githubusercontent.com/1154986/105691984-04f42c00-5f52-11eb-9627-823fb73c500b.png)

**Other information:**

**Environment**

* React-admin version: 3.10.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.1
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment] 2021-01-28 08:27
Hi and thanks for the report. I can't reproduce this issue on the simple example though. So unless you can provide a codesandbox showing the issue, I'll assume the problem is in your code and will close the issue

**Comment by Wraiyth** [comment] 2021-01-28 23:47
I'll see if I can put an example together to repro this issue

**Comment by otroboe** [comment] 2021-02-26 16:53
I don't know if it's related, but I have a different issue on my own, with the same duo `ReferenceArrayInput / AutocompleteArrayInput` also, which I don't have when I use `ReferenceArrayInput / SelectArrayInput`.

When I select an option, it's throwing me an error.
```
Uncaught TypeError: newIds.forEach is not a function
    at Object.onSelect (useReferenceArrayInputController.js:125)
    at Downshift.<anonymous> (downshift.esm.js:596)
```

I keep investigating on my own, and I'll probably create another issue.

**Comment by fzaninotto** [comment] 2021-04-13 20:57
No news for some time, closing.

**Closed by fzaninotto** 2021-04-13 20:57 UTC
Labels: needs more info

**Comment by Wraiyth** [comment] 2021-07-09 05:02
FWIW, I ended up tracking this down to being me stupidly returning the id array as an array of strings, not an array of integers.

`{"assetIDs":["25"],`
