### ISSUE TITLE
Bug row expansion on Datagrid

### ISSUE THREAD

**Issue by LorenzoStella** [marmelab/react-admin#3872] opened 2019-10-24 12:54 UTC
In datagrid row-click expansion occurs a bug after some time, showing only the first list's row element:

![BugExpandDatagrid](https://user-images.githubusercontent.com/35868011/67487494-52f2f380-f66e-11e9-81f9-8b863fb52a02.PNG)

This is an example found on official demo project

**Comment by djhi** [comment] 2019-10-25 10:01
We'll need more details to investigate this. I haven't been able to reproduce it

**Comment by WiXSL** [comment] 2019-10-27 15:46
Couldn't this bee the same as #3227

**Comment by djhi** [comment] 2019-10-27 19:07
Maybe. I need a way to reproduce it though

**Comment by fzaninotto** [comment] 2019-10-28 08:27
I tried lowering the `defaultCacheduration` as explained in #3227 but I can't reproduce this issue (or the one in #3227). We really need a step-by-step scenario for reproducing it.

**Comment by fzaninotto** [comment] 2019-11-24 18:12
No new for a month, closing.

**Closed by fzaninotto** 2019-11-24 18:12 UTC
Labels: needs more info
