### ISSUE TITLE
v4.0 Inconsistent mutationMode usage between Create and Edit components

### ISSUE THREAD

**Issue by panfiva** [marmelab/react-admin#7528] opened 2022-04-12 19:24 UTC
**Is your feature request related to a problem? Please describe.**
Currently, mutationMode attribute is available in `Edit` component, but not available in `Create` component

In order to specify mutation mode in Create component, I have to use `mutationMode` property of `Form` component, however it has 2 issues:
- It is undocumented in React-Admin
- It only works with `Create` components; and does not work with `Edit` components

```js
export const CreateForm= (props: CreateProps) => {
	return (
		<Create {...props} redirect='list'>
			<Form mutationMode='pessimistic' toolbar={<CustomToolbar />} />
		</Create>
	)
}

export const EditForm= (props: EditProps) => {
	return (
		<Edit {...props} redirect='list' mutationMode='pessimistic'>
			<Form toolbar={<CustomToolbar />} />
		</Edit>
	)
}
```

**Describe the solution you'd like**

- I would like mutation mode to be consistently used in both `Create` and `Edit` components.
- I also would like to remove `mutationMode` property from `Form` component properties (from `SimpleFormProps`) so that typescript will not offer it as an option

**Comment by fzaninotto** [comment] 2022-04-12 19:33
No `mutationMode` other than `pessimistic` is allowed in the Create view by design. Or, to put it otherwise, optimistic creations aren't supported (because the client-side often doesn't have the sequence required to create an identifier)

So `Create` doesn't need to support a `mutationMode` prop.

**Comment by panfiva** [comment] 2022-04-12 19:40
Since mutationMode is not supported, can we remove fmutationMode from `SimpleFormProps` so that typescript does not offer it as an option?

**Comment by fzaninotto** [comment] 2022-04-12 21:38
You're right, the type is wrong. I'm reopening this and marking it as a bug.

**Closed** 2022-04-13 13:29 UTC
Labels: bug
