### ISSUE TITLE
FormDataConsumer passes undefined as source inside ArrayInput

### ISSUE THREAD

**Issue by pedrohh** [marmelab/react-admin#1938] opened 2018-06-20 16:20 UTC
**What you were expecting:**
`<FormDataConsumer>` passes the correct source path when inside an `<ArrayInput`> element.

**What happened instead:**
Instead of passing the source `attachments[0].title` it is passing `attachments[0].undefined`.

**Steps to reproduce:**
Put the `<FormDataConsumer>` example from [documentation](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs) inside `<ArrayInput>` element.

**Related code:**
```
export const ArticleCreate = (props) => (
    <Create {...props}>
        <SimpleForm>
            <TextInput source="text"/>
            <FormDataConsumer>
                {({ formData, ...rest }) =>
                    <TextInput source="text" {...rest} />
                }
            </FormDataConsumer>
            <ArrayInput source="attachments">
                <SimpleFormIterator>
                    <TextInput source="title"/>
                    <FormDataConsumer>
                        {({ formData, ...rest }) =>
                            <TextInput source="title" {...rest} />
                        }
                    </FormDataConsumer>
                </SimpleFormIterator>
            </ArrayInput>
        </SimpleForm>
    </Create>
);
```

**Images:**

- https://image.ibb.co/jVjbxy/1.png
- https://image.ibb.co/b9GpHy/2.png

**Environment**

* React-admin version: 2.0.3
* React version: 16.4.0
* Browser: Chrome

**Comment by fzaninotto** [comment] 2018-07-03 21:05
Duplicate of #1871, fixed in v2.0.4.

**Comment by pedrohh** [comment] 2018-07-06 09:10
@fzaninotto Hello I'm trying this with the version 2.1.1 and is still not working. The problem is when using FormDataConsumer inside an ArrayInput. As you can see in the image bellow, the path is correct, but the field shows as undefined:

- https://image.ibb.co/dSFA6d/Untitled.png

**Comment by pedrohh** [comment] 2018-07-30 16:38
@fzaninotto @djhi can you check this please? I tried again with the latest v2.1.4 and this error still happens.  FormDataConsumer inside an ArrayInput returns the source as undefined.

**Comment by djhi** [comment] 2018-07-30 16:58
That's a corner case. Here's what happen:

`ArrayInput` passes the correct props to `FormDataConsumer` including the source which is indeed not defined on `FormDataConsumer`, hence the `undefined`.

`FormDataConsumer` passes all its props to the children function so, including the `source` prop which is `undefined`.

In your example, you override any props passed to your `TextInput` (`source="title"`) with the `rest` props which includes the `source` prop, hence overriding `"title"` with `undefined`.

You can fix this by using the `FormDataConsumer` like this:

```
<FormDataConsumer>
    {({ formData, source, ...rest }) =>
        <TextInput source="title" {...rest} />
    }
</FormDataConsumer>
```

**Comment by pedrohh** [comment] 2018-08-01 09:59
Hi @djhi thanks for the help. I tried not passing the source prop:

```
export const ArticleCreate = (props) => (
  <Create {...props}>
      <SimpleForm>
          <TextInput source="text"/>
          <ArrayInput source="attachments">
              <SimpleFormIterator>
                  <TextInput source="title"/>
                  <FormDataConsumer>
                      {({ formData, source, ...rest }) =>
                          <TextInput source="title" {...rest} />
                      }
                  </FormDataConsumer>
              </SimpleFormIterator>
          </ArrayInput>
      </SimpleForm>
  </Create>
);
```
In fact the undefined does not show, but as you can see in this [screenshot](https://image.ibb.co/jNHzke/1.png) if I fill the **TextInput source="title"** inside **FormDataConsumer**, nothing is sent inside the attachments array.

**Comment by djhi** [comment] 2018-08-01 10:00
Please set up a codesandbox

**Comment by pedrohh** [comment] 2018-08-01 10:27
@djhi here it is you can try to create a post and seeing the data in the console: https://codesandbox.io/s/vo63rpl37

**Comment by pedrohh** [comment] 2018-08-01 12:26
Doing something like this to the source seems to solve the problem:

```
export const PostCreate = props => (
  <Create {...props}>
    <SimpleForm>
      <TextInput source="text" />
      <ArrayInput source="attachments">
        <SimpleFormIterator>
          <TextInput source="title" />
          <FormDataConsumer>
            {({ formData, source, ...rest }) => (
              <TextInput
                source={`${source.substring(0, source.lastIndexOf("."))}.title`}
                {...rest}
              />
            )}
          </FormDataConsumer>
        </SimpleFormIterator>
      </ArrayInput>
    </SimpleForm>
  </Create>
);
```

**Comment by djhi** [comment] 2018-08-01 12:31
You beat me to it. Yes, the `FormDataConsumer` is not aware of its context, it just grabs the form values. I'll keep this issue open as a possible enhancement though. Ping @fzaninotto

**Comment by djhi** [comment] 2018-08-01 12:33
Actually, this is a separate issue. Can you create an new one?

**Closed** 2018-09-04 10:26 UTC
Labels: enhancement
