### ISSUE TITLE
useNavigate() may be used only in the context of a <Router> component (could not reproduce) 

### ISSUE THREAD

**Issue by jonArzelus** [marmelab/react-admin#8344] opened 2022-11-02 14:10 UTC
Our project stopped working and some `react-router` related errors appeared after upgrading. Checking this comment on [Stackoverflow](https://stackoverflow.com/a/73713976/19673428) and this comment in the [react-router docs
](https://github.com/remix-run/react-router/blob/main/packages/react-router/README.md) I guessed that the problem was importing things from `react-router-dom` and `react-router` at the same time. I am using imports from `react-router-dom` in our project and debugging the error leads to two files in the `react-admin` repos:
- `useResetErrorBoundaryOnLocationChange.js` from `ra-ui-materialui` (full path is `node_modules/ra-ui-materialui/dist/esm/layout/useResetErrorBoundaryOnLocationChange.js`)
- `useLogoutIfAccessDenied.js` from `ra-core` (full path is `node_modules/ra-core/dist/esm/auth/useLogoutIfAccessDenied.js`)

**What you were expecting:**

Everything to work  as usual with no `react-router` related errors

**What happened instead:**

The errors mentioned above happened

**Steps to reproduce:**

Import `useNavigate` from `react-router` using `BrowserRouter` upper in the tree imported from `react-router-dom`

**Related code:**

`node_modules/ra-ui-materialui/dist/esm/layout/useResetErrorBoundaryOnLocationChange.js`
`node_modules/ra-core/dist/esm/auth/useLogoutIfAccessDenied.js`

**Other information:**

Editing the mentioned two files manually and changing the import from `react-router` to `react-router-dom` fixed the problem and no more errors appeared in the console. I did not check if there are more files with this imports.
We deleted all `node_modules` and `yarn.lock`, reinstalled everything and everything seems to be fixed, this is more of a notification of issue than a bug report as we could not reproduce it again to show stack traces, but I think that it will prevent future errors changing all imports from `react-router` to `react-router-dom` making `react-admin` more future proof. 

Thanks in advance!!

**Environment**

* React-admin version: 4.4.4
* Last version that did not exhibit the issue (if applicable): We did not face this problem in 4.4.3
* React version: 18.2.0
* Browser: Firefox latest

**Comment by fzaninotto** [comment] 2022-11-02 15:52
Hi, and thanks for your report. As you could not reproduce the bug, we cannot look into it, and I'll close this issue.

**Closed by fzaninotto** 2022-11-02 15:52 UTC

**Comment by RedRush1** [comment] 2022-11-08 14:08
Can be reproduced on react-router-dom version 6.4.1

**Comment by jonArzelus** [comment] 2022-11-09 08:10
I have been trying to reproduce it in a new project but I have not been able to, @RedRush1 I guess if you upgrade `react-router-dom` and `react-admin` to the latest version the problem goes away, so did to me (latest for RA is 4.5.0). 
Nevertheless, I think that imports from `react-router` core package should be avoided as stated in the package documentation itself (linked in the issue description). Thnks!

**Comment by RedRush1** [comment] 2023-02-03 12:59
> I have been trying to reproduce it in a new project but I have not been able to. @RedRush1, I guess if you upgrade `react-router-dom` and `react-admin` to the latest version the problem goes away, so did to me (latest for RA is 4.5.0). Nevertheless, I think that imports from `react-router` core package should be avoided as stated in the package documentation itself (linked in the issue description). Thnks!
@fzaninotto @jonArzelus 
Yes, however he problem occurs again and again. Each time when "react-router-dom" has new version. This time bug reproduces on react-router-dom 6.7.0 and bug can be fixed by moving to 6.8.0. The problem is that it is not a long-term solution. It is likely then in a month I'll have to update again.

P/s we are using react-admin inside another application  on the route "admin":
![image](https://user-images.githubusercontent.com/49880633/216609264-810965a3-4528-4fa5-aa2d-0139b3f3fbac.png)

**Comment by jonArzelus** [comment] 2023-02-06 06:22
So, I have been getting this error nearly every time I update `react-router-dom` dependency as stated by @RedRush1, the solution I found (apart from changing `react-router` imports to `react-router-dom` in `react-admin` files) is to update your `package.json`, delete `node_modules` folder and `yarn.lock` and then install all dependencies from zero. This way seems to fix the `useNavigate() may be used only in the context of a <Router> component` error.
I will try to reproduce the error and report back if I have any luck (or bad luck lets say? :sweat_smile: )

**Comment by jonArzelus** [comment] 2023-02-06 07:13
Okay, so I did the following and I could reproduce the error in the latest `react-admin` release:
1. Create a new CRA project using `yarn create react-app ra-test`
2. Enter the project folder using `cd ra-test`
3. Add the required dependencies using `yarn add react-admin ra-data-json-server react-router-dom@6.7.0` (note that we select a previous release of `react-router-dom`)
4. Delete the `src` folder as we will add some basic components for testing using `rm -r src`
5. Create again the `src` folder using `mkdir src`
6. Enter the dir using `cd src`
7. Add the following components to the folder (they are the ones shown in the _getting started_ guide and the RA docs): [src.zip](https://github.com/marmelab/react-admin/files/10660396/src.zip) using `unzip src.zip` (or whatever zip program)
8. Go one dir up using `cd ..`
9. Execute the admin using `yarn start`
10. When everything compiles correctly, the admin is not shown, open the browser console and check the error message: `Uncaught Error: useRoutes() may be used only in the context of a <Router> component.`. If you do not get this error message continue reading (you might have got an error saying that our custom route is not a `<Route>` component).
11. Stop executing CRA and install the latest `react-router-dom` using `yarn add react-router-dom` (currently the latest version is `6.8.0`).
12. Execute the admin using `yarn start`. When the admin is compiled you probably do not get any errors in the console. 
13. Stop executing CRA and revert back to the previous `react-router-dom` version using `yarn add react-router-dom6.7.0`
14. Execute the admin using `yarn start`. You probably now are getting the error mentioned in step 10.

If someone can test this out to check if we can reproduce the issue would be super, @fzaninotto  let me know if you can reproduce it too.

**Comment by fzaninotto** [comment] 2023-02-06 16:59
@jonArzelus I didn't try your reproduction, because it is similar to the other feedbacks in this thread. The problem comes from installing a version of `react-router-dom` different than the one used by react-admin. This is a limitation of npm and React, not of react-admin. To overcome it, use the `resolutions` (yarn) or `overrides` (npm) key in your `packages.json` to force the `react-router-dom` version rather than installing it. 

```js
// in packages.json
{
   // ...
   "resolutions": {
       "react-router-dom": "6.7.0"
   }
}
```

* [yarn doc for resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
* [npm doc for overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

**Comment by jonArzelus** [comment] 2023-02-08 12:07
I tested adding _resolutions_ to the `package.json` and the same error persists, we use the resolutions solution with our production environment but as I mentioned earlier we have to delete all the dependencies and the lockfile to have it work again after an update. I changed the steps to add the _resolutions_ part:

1. Create a new CRA project using `yarn create react-app ra-test`
2. Enter the project folder using `cd ra-test`
3. Add the required dependencies in the `package.json`: 
`"react-admin": "^4.7.4"
"ra-data-json-server": "^4.7.2"
"react-router-dom": "^6.7.0"`
4. Add the _resolutions_ part to the `package.json`:
`"resolutions": { "react-router-dom": "6.7.0" }`
5. Delete the `src` folder as we will add some basic components for testing using `rm -r src`
6. Create again the `src` folder using `mkdir src`
7. Enter the dir using `cd src`
8. Add the following components to the folder (they are the ones shown in the _getting started_ guide and the RA docs): [src.zip](https://github.com/marmelab/react-admin/files/10660396/src.zip) using `unzip src.zip` (or whatever zip program)
9. Go one dir up using `cd ..`
10. Execute the admin using `yarn start`
11. When everything compiles correctly, the admin is not shown, open the browser console and check the error message: `Uncaught Error: useRoutes() may be used only in the context of a <Router> component.`. If you do not get this error message continue reading (you might have got an error saying that our custom route is not a `<Route>` component).
12. Stop executing CRA and install the latest `react-router-dom` using `yarn add react-router-dom` (currently the latest version is `6.8.0`).
13. Execute the admin using `yarn start`. When the admin is compiled you probably do not get any errors in the console. 
14. Stop executing CRA and revert back to the previous `react-router-dom` version using `yarn add react-router-dom6.7.0`
15. Execute the admin using `yarn start`. You probably now are getting the error mentioned in step 10.

@fzaninotto  let me know if you can reproduce it.

**Comment by fzaninotto** [comment] 2023-02-08 13:11
@jonArzelus This is a resolution problem with yarn, not with react-admin. 

If you want to force a specific version of react-router-dom, add the following resolution for *both* packages of react-router:

```
"resolutions": { "react-router-dom": "6.7.0", "react-router": "6.7.0" }
```

And don't add these packages as dependencies, because for some reason, yarn does not deduplicate them in that case (IMHO that's a yarn bug). 

The `packages.json` should look like the following:

```json
{
  "name": "ra-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.0",
    "react-admin": "^4.7.4",
    "ra-data-json-server": "^4.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "resolutions": {
    "react-router-dom": "6.7.0",
    "react-router": "6.7.0"
  }
}
```

Now run `yarn` and `yarn start` and the problem should be gone.

**Comment by jonArzelus** [comment] 2023-02-08 15:15
> @jonArzelus This is a resolution problem with yarn, not with react-admin.
> 
> If you want to force a specific version of react-router-dom, add the following resolution for _both_ packages of react-router:
> 
> ```
> "resolutions": { "react-router-dom": "6.7.0", "react-router": "6.7.0" }
> ```
> 
> And don't add these packages as dependencies, because for some reason, yarn does not deduplicate them in that case (IMHO that's a yarn bug).
> 
> The `packages.json` should look like the following:
> 
> ```json
> {
>   "name": "ra-test",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@testing-library/jest-dom": "^5.14.1",
>     "@testing-library/react": "^13.0.0",
>     "@testing-library/user-event": "^13.2.1",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-scripts": "5.0.1",
>     "web-vitals": "^2.1.0",
>     "react-admin": "^4.7.4",
>     "ra-data-json-server": "^4.7.2"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "react-app/jest"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "resolutions": {
>     "react-router-dom": "6.7.0",
>     "react-router": "6.7.0"
>   }
> }
> ```
> 
> Now run `yarn` and `yarn start` and the problem should be gone.

This one I think was the missing piece in the issue, I tested it in the example and does not fail anymore. Test it out @RedRush1 and report back so we can verify it. Thanks!

**Comment by RedRush1** [comment] 2023-02-16 09:22
> > @jonArzelus This is a resolution problem with yarn, not with react-admin.
> > If you want to force a specific version of react-router-dom, add the following resolution for _both_ packages of react-router:
> > ```
> > "resolutions": { "react-router-dom": "6.7.0", "react-router": "6.7.0" }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And don't add these packages as dependencies, because for some reason, yarn does not deduplicate them in that case (IMHO that's a yarn bug).
> > The `packages.json` should look like the following:
> > ```json
> > {
> >   "name": "ra-test",
> >   "version": "0.1.0",
> >   "private": true,
> >   "dependencies": {
> >     "@testing-library/jest-dom": "^5.14.1",
> >     "@testing-library/react": "^13.0.0",
> >     "@testing-library/user-event": "^13.2.1",
> >     "react": "^18.2.0",
> >     "react-dom": "^18.2.0",
> >     "react-scripts": "5.0.1",
> >     "web-vitals": "^2.1.0",
> >     "react-admin": "^4.7.4",
> >     "ra-data-json-server": "^4.7.2"
> >   },
> >   "scripts": {
> >     "start": "react-scripts start",
> >     "build": "react-scripts build",
> >     "test": "react-scripts test",
> >     "eject": "react-scripts eject"
> >   },
> >   "eslintConfig": {
> >     "extends": [
> >       "react-app",
> >       "react-app/jest"
> >     ]
> >   },
> >   "browserslist": {
> >     "production": [
> >       ">0.2%",
> >       "not dead",
> >       "not op_mini all"
> >     ],
> >     "development": [
> >       "last 1 chrome version",
> >       "last 1 firefox version",
> >       "last 1 safari version"
> >     ]
> >   },
> >   "resolutions": {
> >     "react-router-dom": "6.7.0",
> >     "react-router": "6.7.0"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now run `yarn` and `yarn start` and the problem should be gone.
> 
> This one I think was the missing piece in the issue, I tested it in the example and does not fail anymore. Test it out @RedRush1 and report back so we can verify it. Thanks!

@fzaninotto @jonArzelus thanks guys fix seems to work. However I used overrides instead of resolutions as our project uses npm

**Comment by seebham** [comment] 2023-05-03 15:18
I'm facing the same issue.
Tried @RedRush1's [solution](https://github.com/marmelab/react-admin/issues/8344#issuecomment-1432771401). Not working for me.

**Comment by RedRush1** [comment] 2023-05-03 17:23
> I'm facing the same issue. Tried @RedRush1's [solution](https://github.com/marmelab/react-admin/issues/8344#issuecomment-1432771401). Not working for me.
> 
> I might have missed a step while migrating to v4. Any clue which one could have caused this? I have checked the Routing one, and that's done, any other step?

Can you provide some code? Perhaps your **Resources** are not inside <Admin> component
