### ISSUE TITLE
Invalid prop `filters` of type `array` supplied to `List`, expected a single ReactElement.

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6429] opened 2021-07-12 20:14 UTC
Doing exactly what the docs say to do: https://marmelab.com/react-admin/List.html#filters-filter-inputs

```
const customerFilters = [
  <TextInput label="Search" source="q" alwaysOn />
];

export const CustomerList = props => (
  <List {...props} filters={customerFilters}>
    <Datagrid rowClick="show">
      <TextField source="id"/>
      <TextField source="name"/>
      <TextField source="city"/>
      <TextField source="type"/>
    </Datagrid>
  </List>
);
```

Error:

```
Warning: Failed prop type: Invalid prop `filters` of type `array` supplied to `List`, expected a single ReactElement.
    at List (http://localhost:3000/static/js/vendors~main.chunk.js:131056:79)
    at CustomerList
    at WithPermissions (http://localhost:3000/static/js/vendors~main.chunk.js:46449:23)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at ResourceContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:55372:21)
    at ResourceRoutes (http://localhost:3000/static/js/vendors~main.chunk.js:55238:17)
    at Resource (http://localhost:3000/static/js/vendors~main.chunk.js:55310:15)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at RoutesWithLayout (http://localhost:3000/static/js/vendors~main.chunk.js:55499:21)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3000/static/js/vendors~main.chunk.js:128890:24)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:6120:31)
    at C (http://localhost:3000/static/js/vendors~main.chunk.js:170153:37)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:167003:75)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:4822:24)
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:129008:26)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/vendors~main.chunk.js:54874:87)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at CoreAdminUI (http://localhost:3000/static/js/vendors~main.chunk.js:55090:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:169531:30)
    at ConnectedRouter (http://localhost:3000/static/js/vendors~main.chunk.js:14113:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/vendors~main.chunk.js:14236:25)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:167003:75)
    at TranslationProvider (http://localhost:3000/static/js/vendors~main.chunk.js:63882:28)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:166716:20)
    at CoreAdminContext (http://localhost:3000/static/js/vendors~main.chunk.js:54637:25)
    at AdminContext
    at Admin (http://localhost:3000/static/js/vendors~main.chunk.js:71741:22)
    at App
console.<computed> @ index.js:1
printWarning @ react-jsx-dev-runtime.development.js:117
error @ react-jsx-dev-runtime.development.js:93
checkPropTypes @ react-jsx-dev-runtime.development.js:620
validatePropTypes @ react-jsx-dev-runtime.development.js:1072
jsxWithValidation @ react-jsx-dev-runtime.development.js:1192
CustomerList @ Customers.js:28
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.js:7
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:9
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 2 more frames
```

**Comment by AuliaYF** [comment] 2021-07-13 04:35
In order to add a custom filter, here's the correct syntax:

```jsx
import { Datagrid, Filter, List, TextField, TextInput } from "react-admin";

const CustomerFilters = (props) => (
  <Filter {...props}>
    <TextInput label="Search" source="q" alwaysOn />
  </Filter>
);

export const CustomerList = (props) => (
  <List {...props} filters={<CustomerFilters/>}>
    <Datagrid rowClick="show">
      <TextField source="id" />
      <TextField source="name" />
      <TextField source="city" />
      <TextField source="type" />
    </Datagrid>
  </List>
);
```

**Comment by davidhenley** [comment] 2021-07-13 06:47
@AuliaYF where do you see this in the docs? I'm using the latest version of docs and package.

**Comment by djhi** [comment] 2021-07-13 06:55
Thanks for reporting this. I can't reproduce the issue on our simple example though. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

You should probably double check your dependencies and make sure you have no duplicates in your `yarn.lock` file if you use yarn

**Comment by AuliaYF** [comment] 2021-07-13 07:39
> @AuliaYF where do you see this in the docs? I'm using the latest version of docs and package.

In v3.17.0 the proptype for filters expected to be array, I'm sensing you're not using v3.17.0. Before v3.17.0, the proper syntax to customize the filter view is the one I provided before.

Try removing the node_modules directory and run yarn/npm install

**Comment by davidhenley** [comment] 2021-07-13 14:47
@AuliaYF I'm using `"react-admin": "^3.17.0",`

I don't have prop-types installed. Is this required? I'm just wondering why the latest docs are outdated.

**Comment by davidhenley** [comment] 2021-07-13 15:14
```
"dependencies": {
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-admin": "^3.17.0",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
  },
```

**Comment by djhi** [comment] 2021-07-21 15:46
The documentation isn't outdated. Both ways of providing filters are supported but we advise you to use the array syntax as it allows to customize the `ListActions` more easily (see #6368 for more details).

Please double check your `yarn.lock` or `package-lock.json` for duplicates and ensure you're using the latest versions.

I'll close this issue as we can't reproduce it and something is wrong with your setup. Feel free to comment if you can provide a way to reproduce it

**Closed by djhi** 2021-07-21 15:46 UTC
Labels: needs more info
