### ISSUE TITLE
ArrayInput component

### ISSUE THREAD

**Issue by 9747749366** [marmelab/react-admin#4001] opened 2019-11-19 07:27 UTC
**What you were expecting:**
I have a params array that stores strings as array values. Expected to input array values into a blank edit form while clicking +(add) button.

**What happened instead:**
 [object object] is shown instead of blank space on clicking +(Add) button of simpleformiterator

**Related code:**

```
<ArrayInput source="params" >
          <SimpleFormIterator>
            <TextInput />
          </SimpleFormIterator>
        </ArrayInput>
```

**Other information:**
We have params from the backend of the following pattern: "params":["hey","iiiih","new ","test1","test2"] while trying to add new value to params array [object Object] is shown

![arrayinputcomponent](https://user-images.githubusercontent.com/17401092/69125048-ea5f3100-0aca-11ea-977f-a707cf467aed.png)

**Environment**

* React-admin version:2.9.8
* Last version that did not exhibit the issue (if applicable):
* React version:16.11.0
* Browser: Google Chrome

while creating a new array this is how it is shown
![arrayinput](https://user-images.githubusercontent.com/17401092/69123164-b1bd5880-0ac6-11ea-9232-1b2481a6e0ac.png)

@fzaninotto 

* Stack trace (in case of a JS error):

**Comment by comxd** [comment] 2019-11-20 15:05
Related: https://github.com/marmelab/react-admin/issues/3249

**Comment by fzaninotto** [comment] 2019-11-21 13:29
I think it's a duplicate of #3249

**Closed by fzaninotto** 2019-11-21 13:29 UTC

**Comment by zsoltime** [comment] 2019-12-06 22:45
I also struggled with this and I had to create my own form iterator. `[object Object]` is a stringified empty object, pushed on [line 108](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/form/SimpleFormIterator.js#L108) in `SimpleFormIterator.js`. You can replace it with an empty string, that should solve your issue.

https://github.com/marmelab/react-admin/blob/c658516267764fe213ef133cfa40a975b21a90d1/packages/ra-ui-materialui/src/form/SimpleFormIterator.js#L105-L109

I wish `SimpleFormIterator` accepted a `defaultFieldValue` prop instead of the hard coded `{}`.
