### ISSUE TITLE
Menu highlighting becomes out-of-sync when navigating with browser back button.

### ISSUE THREAD

**Issue by lbordwell** [marmelab/react-admin#3396] opened 2019-07-09 19:33 UTC
**What you were expecting:**
Highlighted menu item does not match current route when using the browser back button to navigate through resources.

**What happened instead:**
Previously selected resource is highlighted instead of current resource.

**Steps to reproduce:**
Using the simple example from react-admin/examples:
1. `make install`
1.  `make run-simple`
1. Open browser to url shown in console.
1. **Posts** is initially highlighted, click **Comments** and then **Tags**.
1. Use the browser back button to navigate back from **Tags** to **Comments**.
1. **Comments** will be shown but **Tags** will remain highlighted.
1. Use browser back button to navigate back from **Comments** to **Posts**.
1. **Posts** will be shown but **Comments** will remain highlighted.

**Related code:**

**Other information:**

This seems to be fixed by adding `withRouter` to ra-ui-materialui/src/layout/Menu.js before the `connect`.

**Environment**

* React-admin version: v2.9.4
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2019-07-10 05:56
Thanks for the report. I managed to reproduce the bug on `master` (but not on `next`), see https://l91qk8j2r7.codesandbox.io.

**Comment by fzaninotto** [comment] 2020-10-14 23:03
Cannot reproduce on master, this seems fixed in 3.0.

**Closed by fzaninotto** 2020-10-14 23:03 UTC
Labels: bug
