### ISSUE TITLE
ReferenceField creates link to wrong resources

### ISSUE THREAD

**Issue by mlasy** [marmelab/react-admin#3619] opened 2019-08-28 16:08 UTC
**What you were expecting:**

I expect that after specifying `resource` in `ReferenceField` it will change basePath that creates a link to the page.
Expected link `/homes/1234`
**What happened instead:**

After specifying a resource created link contains path to root resource.
Created link `/comments/1234` because it is inside of comments resource

```
<ReferenceField label="Home" source="homeID._id" resource="homes" reference="homes" linkType="show" >
    <Component/>
</ReferenceField>
```
After I set basePath inside `TabbedShowLayout` that is wrapped around it. The basePath  changes
```
<TabbedShowLayout record={record} basePath={"/homes"} >
<Tab label="Base" basePath={"/tab"}>
```
Is it possible to change `basePath` inside `ReferenceField` directly?

**Other information:**

**Environment**

* React-admin version:^2.9.6
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.8.4
* Browser: chrome
* Stack trace (in case of a JS error):

**Comment by djhi** [comment] 2019-09-02 07:31
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment] 2019-09-02 08:39
Your `ReferenceField` uses the same resource name for resource and reference, I suspect it's a mistake on your side.

**Comment by mlasy** [comment] 2019-09-04 10:48
even when removing the `resource` and `reference`, the `basePath` is still not changed (but inherited by `TabbedShowLayout`)

**Comment by fzaninotto** [comment] 2019-12-02 16:41
Still can't reproduce, so I'm closing this bug. Feel free to reopen if you can provide a CodeSandbox reproducing the issue.

**Closed by fzaninotto** 2019-12-02 16:41 UTC
Labels: needs more info
