### ISSUE TITLE
Weird behavior by array input

### ISSUE THREAD

**Issue by TalOrlan** [marmelab/react-admin#5621] opened 2020-12-03 11:11 UTC
```jsx
 <FormDataConsumer>
          {({ formData, scopedFormData ,getSource, ...rest }) => {
            return (
              <ArrayInput source="countryIds">
                <SimpleFormIterator >
                  <ReferenceInput
                    label="country"
                    reference="FullCountries"
                    filterToQuery={(searchText) => ({ name: searchText })}
                  >
                    <AutocompleteInput
                      source="name"
                      matchSuggestion={(filter, choice) => {
                        if (!formData.countryIds.includes(choice.id))
                          return true;
                      }}
                    />
                  </ReferenceInput>
                </SimpleFormIterator>
              </ArrayInput>
            );
          }}
        </FormDataConsumer>

```
I have this code and when I try to add a new row it take the second object above it and move it also
I don't know how to explain it even and after refresh it's work fine
in the console I see this:
Check the render method of `SimpleFormIterator`
index.js:1 Warning: Each child in a list should have a unique "key" prop.

how can i fix it
**Update**
the problem still open but what happend is that all the list is go down by one line and hen go up again

**Comment by djhi** [comment] 2020-12-03 12:58
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by TalOrlan** [comment] 2020-12-03 13:57
another question I have is where getMany data go to after I back to the compoent
I mean I go to getMany get the data nad then what

**Comment by MicroJackson** [comment] 2020-12-08 07:08
The problem lies with your `id` field.
Make sure all your resources have a proper unique `id` field, or you will have this wonky animation.

**Comment by TalOrlan** [comment] 2020-12-14 07:33
"comments": [
            {
                "id": 24,
                "body": "yi",
                "type": "recipe",
                "entityId": 1,
                "isPublic": false,
                "children": [
                    {
                        "id": 25,
                        "body": "4234324",
                        "type": "comment",
                        "entityId": 24,
                        "isPublic": false,
                    }
                ],
            },
            {
                "id": 26,
                "body": "3242342",
                "type": "recipe",
                "entityId": 1,
                "isPublic": false,
                "children": [
                    {
                        "id": 27,
                        "body": "42423",
                        "type": "comment",
                        "entityId": 26,
                        "isPublic": false,
                    }
                ],
               
            }
        ]

**Comment by TalOrlan** [comment] 2020-12-14 07:34
this is the data everyone have it own uniqe id

**Comment by TalOrlan** [comment] 2020-12-14 07:35
when i handle the child he work just fine the problem is the main comments

**Comment by TalOrlan** [comment] 2020-12-14 08:01
![2020-12-14 (2)](https://user-images.githubusercontent.com/74725179/102055258-3d510800-3df3-11eb-8992-fba669117bcd.png)
as i check in the react tool it's looks like that the ref is empty and after a refresh he get the currect value

**Comment by fzaninotto** [comment] 2020-12-15 17:46
Again, please provide a sample application so that we can reproduce the problem, and add details about your react-admin version (as well as for other dependencies).

**Comment by TalOrlan** [comment] 2020-12-21 22:30
I couldn't do it becuase as I think FormDataConsumer get slight different data from the Find-One because as I see when I press edit it get the data of that row until the data from the FineOne is Fetched
because If I put the data as the value it's would recreate the problem becasue it act like I do the refresh and everything is work fine.
I couldn't find a good reason for the Ref to be empty

**Comment by fzaninotto** [comment] 2020-12-22 05:44
If you can't reproduce the problem in the codesandbox, the bug is most likely on your side and not in react-admin. 

So I'm closing this issue as we don't provide support via GitHub issues.

If you manage to build a reproducible case, and to use the issue template, then we may consider reopening the issue.

**Closed by fzaninotto** 2020-12-22 05:44 UTC
Labels: needs more info
