### ISSUE TITLE
ArrayInput wrongly placed Remove button

### ISSUE THREAD

**Issue by zavadpe** [marmelab/react-admin#2248] opened 2018-08-30 11:37 UTC
**What you were expecting:**
`ArrayInput` has correct width and Remove button is placed on the right side of the form.

**What happened instead:**
`ArrayInput` is shorter than expected and Remove button is not placed on the right side of the form.

<img width="907" alt="array_input" src="https://user-images.githubusercontent.com/6029270/44849189-a54aa700-ac59-11e8-9475-6d0ed3b77c38.png">

**Steps to reproduce:**
Please, refer to the code snippet and Tab 1 in a sandbox linked below. 

**Related code:**
```
<ArrayInput source="urls">
    <SimpleFormIterator>
        <TextInput source="url" />
    </SimpleFormIterator>
</ArrayInput>
```

**CodeSandbox**
https://codesandbox.io/s/6n0xlnjzkn

**Environment**
* React-admin version: 2.2.x
* Last version that did not exhibit the issue (if applicable): 2.1.x

**Comment by djhi** [comment] 2018-08-30 13:49
> ArrayInput is shorter than expected

What is the correct width ? If you want it to take all the space available, add a `fullWidth` prop on it (You'll have to add a `fullWidth` prop on its children too). We should document this.

> Remove button is not placed on the right side of the form

It is placed at the right side of the input. However, if you set the `fullWidth` prop as explained above, it will be on the right side of the form.

![screenshot](https://user-images.githubusercontent.com/1122076/44855828-3aef3200-ac6c-11e8-85cc-30982ee1065d.png)

I'll mark this issue as a enhancement to the documentation

**Comment by fzaninotto** [comment] 2018-08-30 15:09
In my opinion, there is no bug. It's the intended behavior. I don't see why we should explain how to set the `fullWidth` property here and not in the other input types...

So I'm closing this one.

**Closed by fzaninotto** 2018-08-30 15:09 UTC
Labels: enhancement, good first issue

**Comment by zavadpe** [comment] 2018-08-31 08:17
@djhi @fzaninotto Thanks both of you. I missed in documentation that fullWidth can be passed as a prop to Input component, I only tried it in style options. Anyway it's working and this is indeed not an issue.
