### ISSUE TITLE
When useGetList is in the disabled state, when the cache is updated somewhere, the error value is undefined.

### ISSUE THREAD

**Issue by zhiguow** [marmelab/react-admin#8940] opened 2023-05-24 04:23 UTC
**What you were expecting:**
In the same resources, I have a function of GetList when the condition is true (that is, when the condition is not true, GetList is in a disabled state, which is not true by default); at this time, I click delete. I expect the deletion to be successful and no error is reported.

**What happened instead:**
Under the same resources, when I execute useDelete successfully, useGetList whose status is disabled reports an error.

**Steps to reproduce:**
Click the delete button and delete successfully.

**Related code:**
```
const Example = () => {
    const [deleteOne] = useDelete();
    useGetList(Resources.Temp, {}, { enabled: false });
    return <Button onClick={() => deleteOne(Resources.Temp, { id: '001' })}>{'delete one'}</Button>;
};
```

**Analysis:**
In my useGetList, I set the value of enabled as a condition. When the condition is triggered, the list will be obtained. At this time, the value of my useGetList is undefined; when I execute useDelete successfully, it tries to update the cache. Execute the onSuccess passed to the third parameter of useQuery in the source code of useGetList, and onSuccess tries to get the data from the value, resulting in an error.

**Solution**
1 In all useGetLists that are disabled by default, add ‘ initialData: { data: [] } ’
```
useGetList(Resources.Temp, {}, { enabled: false, initialData: { data: [] } });
```
2 Do not use useDelete, use dataProvider.delete, and use the refresh method in finally
```
    const dataProvider = useDataProvider();
    const refresh = useRefresh();
    const handleDelete = () =>  dataProvider.delete(Resources.Temp, { id: ‘001’ }) .finally(() => refresh());
```

**Environment**

* React-admin version:4.9.3
* React version:18.2.0

**Comment by slax57** [comment] 2023-05-24 07:58
Thanks for the report.

I would have appreciated a reproduction sandbox, but your report was detailed enough so that I could understand the problem anyway.

Both your workarounds are valid, although, I'd recommend the first one (providing `initialData`) because the second one is basically bypassing react-query altogether and hence removing its benefits.

In any case, I believe that `useGetList.ts` should be fixed because this proves we should not assume that `value` has a `data` property at anytime.
Hence I'll label this as a bug.

**Closed** 2023-05-24 09:03 UTC
Labels: bug

**Comment by ArthurWD** [comment] 2023-07-19 10:08
This issue is also present on `useGetManyReference`. I rewrote it to use `useGetList` to bypass it, but I think `useGetManyReference` should be fixed as well.

**Comment by slax57** [comment] 2023-07-20 15:56
@ArthurWD nice catch! Fixed by https://github.com/marmelab/react-admin/pull/9116
