### ISSUE TITLE
ArrayInput bad UI and unique key prop warning

### ISSUE THREAD

**Issue by Siegrift** [marmelab/react-admin#3211] opened 2019-05-11 13:17 UTC
**What you were expecting:**
Similar design to the one in documentation https://marmelab.com/react-admin/Inputs.html#arrayinput and no unique key prop error

**What happened instead:**
![strangeLook](https://user-images.githubusercontent.com/22679154/57570174-97ac0a80-73ff-11e9-9a2f-f839a974b4fa.png)
This is the part of the code that is renderer in `TabbedForm`.
```
   <FormTab label="Files">
        <ArrayInput source="files">
          <SimpleFormIterator>
            <TextInput source="name" />
          </SimpleFormIterator>
        </ArrayInput>
      </FormTab>
```

**Steps to reproduce:**
It happens right after it's rendered.

**Related code:**
This is the full code of the edit component
```
export const EditProblem = (props: {}) => (
  <Edit {...props}>
    <TabbedForm asyncValidate={uniqueProblemNameValidation}>
      <FormTab label="General info">
        <DisabledInput source="id" />
        <TextInput source="name" validate={requiredField} />
      </FormTab>

      <FormTab label="Files">
        <ArrayInput source="files">
          <SimpleFormIterator>
            <TextInput source="name" />
          </SimpleFormIterator>
        </ArrayInput>
      </FormTab>
    </TabbedForm>
  </Edit>
)```

**Environment**

* React-admin version: 2.9.0
* React version: 16.7
* Browser: Chrome

**Comment by djhi** [comment] 2019-05-11 13:48
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by Siegrift** [comment] 2019-05-11 14:06
Unfortunately, there it works. My code is open sourced at https://github.com/Siegrift/bachelor-thesis

**Comment by fzaninotto** [comment] 2019-05-11 20:36
For troubleshooting, please use StackOverflow. I'm closing this issue as it seems that the problem is on your side rather than in the react-admin code. Feel free to reopen if you can provide a CodeSandbox demonstrating the issue.

**Closed by fzaninotto** 2019-05-11 20:36 UTC
