### ISSUE TITLE
ReferenceArrayInput choice list in Form embedded in Drawer displayed in the background

### ISSUE THREAD

**Issue by StephanePate** [marmelab/react-admin#3192] opened 2019-05-07 12:03 UTC
**What you were expecting:**
Choices List of ReferenceArrayInput in a TabbedForm embedded in a Drawer shall be displayed as part of the Drawer's modal area

**What happened instead:**
Choices List is displayed in the background of the Drawer's modal area

**Steps to reproduce:**

**Related code:**

```jsx
<Drawer
    open={isMatch || false}
    anchor="bottom"
    onClose={this.handleClose}
>
    {isMatch ? (
        <ExerciseActionEdit
            className={classes.drawerContent}
            id={isMatch ? decodeURIComponent(match.params.id) : null}
            onCancel={this.handleClose}
            {...props}
        />
    ) : (
        <div className={classes.drawerContent} />
    )}
</Drawer>
```

```jsx
const ExerciseActionEdit = ({ onCancel, ...props }) => (
    <Edit {...props}>
        <TabbedForm>
          <FormTab label="Participants">
            <ReferenceArrayInput label="Participants" reference="people" source="athlete">
                <AutocompleteArrayInput optionText="givenName" />
            </ReferenceArrayInput>
          </FormTab>
        </TabbedForm>
    </Edit>
);
```

<img width="661" alt="Capture d’écran 2019-05-07 à 12 02 41" src="https://user-images.githubusercontent.com/6461942/57297527-1804ff80-70d0-11e9-9683-2c084433c174.png">

**Environment**

* react-admin@2.8.5
* react@16.8.6
* Firefox 66.0.3

**Comment by Kmaschta** [comment] 2019-06-12 06:44
While trying to reproduce, I wrote the following code in the demo, in the Reviews edit view:

```jsx
<ReferenceArrayInput label="Product" reference="products" source="product_id">
    <AutocompleteArrayInput optionText="reference" />
</ReferenceArrayInput>
```

And I had the following error:
![image](https://user-images.githubusercontent.com/1819833/59329057-3d4be580-8cee-11e9-9a44-b6413f3947a0.png)

I'll check that later.

**Comment by Kmaschta** [comment] 2019-07-23 16:56
Can you please reproduce the issue on [this CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

This will help the core maintainers to reproduce and fix the issue.

**Comment by Kmaschta** [comment] 2019-09-23 13:02
I'll close this one since it seems to be related to a very custom implementation and no news from a few months.

Please feel free to answer with a reproducable example, preferably on a Code Sandbox.

**Closed by Kmaschta** 2019-09-23 13:02 UTC
Labels: awaiting more info
