### ISSUE TITLE
Chrome address suggestions appears on top of options in `AutocompleteInput`

### ISSUE THREAD

**Issue by MoonSeeing** [marmelab/react-admin#3533] opened 2019-08-15 04:09 UTC
```
 <Filter {...props}>
  <TextInput source="zipCode" label="ZipCode" resettable alwaysOn />
   <ReferenceInput
      label="Market Region"
      source="marketId"
      reference="markets"
      alwaysOn
    >
      <AutocompleteInput
        optionText="name"
        // options={{
        //   inputProps: {
        //     autoComplete: 'no',
        //   },
        // }}
        alwaysOn
      />
    </ReferenceInput>
  </Filter>
```

**Other information:**
when i use   label="Market Region" ,label have some word 'region','zipcode',the input will load the option from the chrom .
[
![lzc](https://user-images.githubusercontent.com/19420622/63072090-8d486200-bf54-11e9-90bf-a0306fd5f51e.jpg)
](url)
In fact i want to show is following
[
![2](https://user-images.githubusercontent.com/19420622/63072108-a0f3c880-bf54-11e9-9e50-910017784984.jpg)
](url)

i have try to modify my label  to some words others like : label="Market ", will not get option from chrom ,this seems is chrome have do something. if i  set options={{
           inputProps: {
           autoComplete: 'no',
           },
         }} to the <AutocompleteInput> ,also ,the chrome will not suggest the option.

while,if i remove the code
`<TextInput source="zipCode" label="ZipCode" resettable alwaysOn />`
  is also not suggest . maybe is the 'source' can be address word such as 'zipcode'?
I think is a bug for component , developer should care about a label  will effect the option display or  not 
**Environment** 

* React-admin version: 2.8.5
* Last version that did not exhibit the issue (if applicable):
* React version:16.8.6
* Browser:chrome have set address
[
![6](https://user-images.githubusercontent.com/19420622/63080389-7f560980-bf73-11e9-8396-164f97071c6c.jpg)
](url)
* Stack trace (in case of a JS error):

**Comment by MoonSeeing** [comment] 2019-08-15 06:39
At the same time ,i do a test on the  demo which Officially provided.just add the code following
`<TextInput source="zipCode" label="ZipCode" resettable alwaysOn />` in the (CommentFilter in CommnetList) 
`const CommentFilter = props => (
    <Filter {...props}>
        <SearchInput source="q" alwaysOn />
        <TextInput source="zipCode" label="ZipCode" resettable alwaysOn />   {/* add code  */}
        <ReferenceInput source="post_id" reference="posts" label='Market Region' alwaysOn>   {/* add code  */}
            <AutocompleteInput optionText="title" />
        </ReferenceInput>
    </Filter>
);
`
what will occur
[
![3](https://user-images.githubusercontent.com/19420622/63077303-67c65300-bf6a-11e9-9f01-446f35f7420e.jpg)
](url)
![4](https://user-images.githubusercontent.com/19420622/63077308-6dbc3400-bf6a-11e9-8ab8-0696362712b4.jpg)

some one can fix this proble ? i just confuse why it shoudl happened?

**Comment by Kmaschta** [comment] 2019-08-15 11:22
Thank you for opening this issue. In order to confirm it, we'll have to reproduce it.
As explained in the bug report template, please fork the following CodeSandbox and repeat your issue on it:

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

This is the simplest way to confirm a bug is related to the React Admin codebase.

**Comment by MoonSeeing** [comment] 2019-08-15 13:49
you  can check the Codesandbox [https://codesandbox.io/s/simple-31e1s](url)
before you test it ,you should add address in the chrome setting.
![3](https://user-images.githubusercontent.com/19420622/63098750-2489d580-bfa6-11e9-917d-15a73ae7ba90.jpg)
![4](https://user-images.githubusercontent.com/19420622/63098758-2a7fb680-bfa6-11e9-9662-f8de25637093.jpg)

After enter the Codesandbox, you can check the following page 
![1](https://user-images.githubusercontent.com/19420622/63098835-5e5adc00-bfa6-11e9-98d8-d91cf91e4ca6.jpg)
![2](https://user-images.githubusercontent.com/19420622/63098839-60249f80-bfa6-11e9-8ed6-b3b657fbfd1e.jpg)

**Comment by fzaninotto** [comment] 2019-08-17 14:09
Thanks for the report. This seems to be a Chrome related bug. A quick search on StackOverflow shows various solutions (e.g. https://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag). 

So I'm closing this as it's not a react-admin bug.

**Closed by fzaninotto** 2019-08-17 14:09 UTC
