### ISSUE TITLE
Dynamically removed resources still shown in sidebar

### ISSUE THREAD

**Issue by arnaudvergnet** [marmelab/react-admin#7601] opened 2022-04-29 10:30 UTC
**What you were expecting:**
When removing resources using state, associated sidebar entries should be removed as well.

**What happened instead:**
Associated entry is kept in the sidebar. Users can then click on it and be greeted with a "Not Found" page.

**Steps to reproduce:**
- Have several resources
- Hide one resource using state
- Observe how it is still present in the sidebar

**Related code:**
In this [example sandbox](https://codesandbox.io/s/dynamic-resources-oluids?file=/src/index.tsx) forked from the simple example, tags are initially shown and toggled every 3 seconds. As you can see, the first time the tag resource becomes active, it appears in the sidebar. But when it becomes inactive, it is not removed from the sidebar.

When you click on the tag entry, you will notice the view will change between the tag list and the "Not Found" page, indicating the resource is deactivated as expected.

**Environment**

* React-admin version: 4.0.1
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Firefox
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2022-04-29 12:00
Duplicate of #7527, will be fixed in 4.0.2

**Closed by fzaninotto** 2022-04-29 12:00 UTC
