### ISSUE TITLE
SimpleFormIterator default handling issue

### ISSUE THREAD

**Issue by kriskw1999** [marmelab/react-admin#8475] opened 2022-12-06 15:27 UTC
# Error in handling default in arrays due to SimpleFormIterator
Hi, I encountered issues in default handling of SImpleFormIterator, especially this is due to the nested components where it defaults all to "". I created a full example [here](https://codesandbox.io/s/fragrant-rain-dpslvn?file=/src/tags/TagEdit.tsx).

For details and steps Look into the link!

## What to investigate
- [ ] open the example and follow both instructions to reproduce the issues
- [ ] in the example you can see that array for a while is an empty string and this can break some computations
- [ ] in the example you can si that inputs that are not on the level of array input do not default correctly

**Comment by septentrion-730n** [comment] 2022-12-06 23:38
In your example, if I[ fix the error](https://codesandbox.io/s/eager-moser-qqxh3s?file=/src/tags/TagEdit.tsx) in `PetInput` (useless source parameter and inner references), all bugs vanish in thin air.
might have missed something, did I?

**Comment by kriskw1999** [comment] 2022-12-06 23:54
@septentrion-730n this does not the error because you are referencing the wrong source in your fork. To demonstrate it you can add two elements to the array and then change the age of only one of them. You will see that the age changes for both the elements of the array. This because in both cases you reference the `age` and not `people.${number}.age`.

The source passing in the way that I did is needed because when dealing with nested components the array input is not able to give them the correct source.

Let me know if you need more info!

**Comment by septentrion-730n** [comment] 2022-12-07 00:12
Shame on me. I'll look at it with a fresher head.

**Comment by slax57** [comment] 2022-12-08 14:32
**Regarding the SECOND ISSUE:**
Indeed `SimpleFormIterator` needs to inspect its children to build the `defaultValue` object.
You can have a look at the code [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/ArrayInput/SimpleFormIterator.tsx#L107) to see how it's done.
This explains why it no longer works if your wrap your components inside a `<div>`.
Currently this is a limitation of our implementation. Suggestions are welcome if you find a better way to do it.

**Regarding the FIRST ISSUE:**
This does not happen with simple use-cases of `ArrayInput`. I suspect this is due to the nesting of `ArrayInput` inside another, but couldn't confirm it for sure.
If you are willing to work further on this one, I recommend building a reproduction case that doesn't involve wrapping children of `SimlpleFormIterator` inside a `<div>` to begin with. We need our reproduction cases to be simple enough to be able to debug them without too much head-scrapping :sweat_smile: 

Thanks.

**Comment by fzaninotto** [comment] 2023-01-03 17:39
No news for some time, closing.

**Closed by fzaninotto** 2023-01-03 17:39 UTC
Labels: needs more info
