### ISSUE TITLE
Using a common fields component brake the list and show views design

### ISSUE THREAD

**Issue by soullivaneuh** [marmelab/react-admin#6982] opened 2021-12-12 15:20 UTC
**What you were expecting:**

In order to reduce some copy/pasta stacks on simple CRUD components, I created `*Fields` component to store common fields definitions.

This component is used on the show and list views.

As it's a refactoring process, I expect nothing changed at the end.

**What happened instead:**

The list and show views designs are broken:

![image](https://user-images.githubusercontent.com/1698357/145718180-e7ea56aa-2124-44bd-a336-590bccdb03ee.png)

![image](https://user-images.githubusercontent.com/1698357/145718195-774437f7-108f-4a1b-90dc-ba95184cc129.png)

**Steps to reproduce:**

1. Go to the reproduced sandbox case: https://codesandbox.io/s/react-admin-common-fields-2k4e9?file=/src/comments/CommentFields.tsx
2. Try to list the comments on the preview
3. Try to show a comment on the preview

**Related code:**

https://codesandbox.io/s/react-admin-common-fields-2k4e9?file=/src/comments/CommentFields.tsx

See also:

- `CommentShow`
- `CommentList`

**Other information:**

I suppose the bugs is caused by the usage of the `Fragment` (`<></>`) component to wrap the common fields. However, I did not find any workaround for that.

**Environment**

* React-admin version: `^3.19.2`
* Last version that did not exhibit the issue (if applicable):
* React version: `^17.0.2`
* Browser:
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2021-12-12 16:01
You are rendering one column by wrapping everything inside empty tags
This is not a bug

**Comment by soullivaneuh** [comment] 2021-12-12 16:07
@WiXSL I understand what you are explaining. However, do you agree the current situation is problematic as we currently don't have solution to avoid copy/pasting?

If there is one, I'm would like to learn! :wink: 

By the way, it could be a cookbook case.

Regards

**Comment by WiXSL** [comment] 2021-12-12 16:13
I'd suggest you to do your own custom `Datagrid` with your fields:
jsx
```
const CustomDatagrid = (props) => (
  <Datagrid {...props}>
    <TextField source="id" />
    <ReferenceField source="post_id" reference="posts">
      <TextField source="title" />
    </ReferenceField>
    <TextField source="author.name" label="The Author" />
    <DateField source="created_at" />
    <TextField source="body" />
  </Datagrid>
);
```

**Comment by soullivaneuh** [comment] 2021-12-12 22:14
@WiXSL I indeed did that for another usages, but your example looks incomplete. You are talking about a custom datagrid here, however the show view does not use a datagrid, but a show layout: https://codesandbox.io/s/react-admin-common-fields-2k4e9?file=/src/comments/CommentShow.tsx

I can not use the common fields between the view and list field with your proposition.

**Comment by WiXSL** [comment] 2021-12-12 22:51
I don't see this being a react-admin problem, please ask usage questions in stack-overflow

**Comment by fzaninotto** [comment] 2021-12-13 06:57
Hi @soullivaneuh,

The Field components don't render structure - they render a `<span>`. If you want to arrange them in a particular way, it's up to you to do it.

And if the SimpleList doesn't fit your need, you can always build a custom iterator component: https://marmelab.com/react-admin/List.html#using-a-custom-iterator

Besides, I don't understand this problem about copy/pasta. 

I'm closing this issue as there doesn't seem to be any bug in react-admin.

**Closed by fzaninotto** 2021-12-13 06:57 UTC

**Comment by soullivaneuh** [comment] 2021-12-13 18:56
Hi @fzaninotto and thanks for the detailed feedback.

> The Field components don't render structure - they render a <span>. If you want to arrange them in a particular way, it's up to you to do it.

Well it's not really up to m as the `<span>` element is something that seems to be created by the Fragment `<>` component. The goal of this component is not an arrangement, but just common logic refactoring.

You can see details on the `CommentList` and `CommentShow` component of the sandbox.

> And if the SimpleList doesn't fit your need, you can always build a custom iterator component: https://marmelab.com/react-admin/List.html#using-a-custom-iterator

The custom iterator looks great if I want to render an advanced version of the list view, but this is not what I want to do.

What I want to do is to avoid code repetition on the list and show views fields definitions.

> Besides, I don't understand this problem about copy/pasta.

Simple, here is a jscpd report to explain:

```
Clone found (tsx):
 - src/resources/discount-codes/DiscountCodeList.tsx [30:30 - 48:7] (18 lines, 87 tokens)
   src/resources/discount-codes/DiscountCodeShow.tsx [36:22 - 54:8]

 30 │ 36 │ >                                 
 31 │ 37 │       <TextField source="code" /> 
 32 │ 38 │       <TextField                  
 33 │ 39 │         source="label"            
 34 │ 40 │         label="Nom"               
 35 │ 41 │       />                          
 36 │ 42 │       <PriceField                 
 37 │ 43 │         source="amount"           
 38 │ 44 │         label="Somme"             
 39 │ 45 │       />                          
 40 │ 46 │       <DateField                  
 41 │ 47 │         source="beginAt"          
 42 │ 48 │         label="Date de début"     
 43 │ 49 │       />                          
 44 │ 50 │       <DateField                  
 45 │ 51 │         source="endAt"            
 46 │ 52 │         label="Date de fin"       
 47 │ 53 │       />                          
 48 │ 54 │     </                            
```

Both show and list view are configured the same way, because we have the same needs for both views.

It's a quite typical structure for tiny services that does not needs so much custom logic.

The goal was accurate: Move the targeted fields onto one component in order to include them onto both list and show views.

> I'm closing this issue as there doesn't seem to be any bug in react-admin.

Well, may be not a bug, but do we agree that the simple needs to put a list of `*Field` component on a common file in order to re-use them on both view is impossible?

Is react-admin improvable that way? I'm afraid I am not enough experienced to answer that part.
