### ISSUE TITLE
Pagination/Filtering is not working after browser history back 

### ISSUE THREAD

**Issue by zakaria-sdv** [marmelab/react-admin#4998] opened 2020-07-01 12:16 UTC
**What you were expecting:**
/comments?filter=%7B%7D&order=ASC&page=1&perPage=6&sort=id

**What happened instead:**
/comments/**8**?filter=%7B%7D&order=ASC&page=1&perPage=6&sort=id

**Steps to reproduce:**

1. Go to the dashboard page I have created and change the env. variable from the list ( prod / preprod )
2. Click "edit" on a component from the list
3. Navigate back using the browser button / mouse gesture / history.back()
4. Click on next button in pagination ( or any action )
5. You are redirected to the previous page you were before ( no action is applied)

![ko](https://user-images.githubusercontent.com/60648794/86256855-1a21fb80-bbb9-11ea-8f68-43702325c0f3.gif)

**Related code:**
* CodeSandbox : https://codesandbox.io/s/distracted-bassi-henh5?file=/src/index.js

Please check the index.js file ( the only file I have changed)
I have added this small portion of code, a dashboard containing a select attribute where a user can choose the desired environment (Env variable )
```
const [env = "prod", setEnv] = useState("prod");

  const HomePage = () => {
    return (
      <p>
        <p>
          <span>Welcome to the Comment Back-Office</span>
        </p>
        <span>
          Choose an environment : &nbsp;
          <select
            value={env}
            onChange={event => {
              setEnv(event.target.value);
            }}
          >
            <option value="prod">Prod</option>
            <option value="preprod">Preprod</option>
          </select>
        </span>
      </p>
    );
  };
```

**Other information:**
Maybe related to #4428

**Environment**

* React-admin version: 3.6.2
* React version: 16.9.0
* Browser: Chrome - Firefox - Sandbox
* Stack trace (in case of a JS error): NO JS ERROR

**Comment by Luwangel** [comment] 2020-07-03 08:31
Hello,

Thanks for reporting this issue.

By reading your example, I think the problem is caused by a re-rendering of the <Admin />. I've annotated it with a comment.

``` js
const App = () => {
    const [env, setEnv] = useState('prod');

    const HomePage = () => {
        return (
            <p>
                <p>
                    <span>Welcome to the Comment Back-Office</span>
                </p>
                <span>
                    Choose an environment : &nbsp;
                    <select
                        value={env}
                        onChange={event => {
                            // This will re-render the <App /> and recreate the <Admin/>
                            // Recreating the <Admin /> will break the router
                            setEnv(event.target.value);
                        }}
                    >
                        <option value="prod">Prod</option>
                        <option value="preprod">Preprod</option>
                    </select>
                </span>
            </p>
        );
    };

    return <Admin dashboard={HomePage} />;
};
```

That could explain why there is the following warning in the console:

> Warning: You cannot change <Router history>

The best way to fix it is to change your code by decoupling the <HomePage /> from the <App />. If you need to persist in the environment (prod / preprod) across your application, you can use Redux or the Local Storage.

I'm closing this issue for now. But if you come with another example I'll take a new look ;)

Have a good day,
Adrien

**Closed by Luwangel** 2020-07-03 08:31 UTC
