### ISSUE TITLE
The first time you click the custom button on the login page is invalid, you need to click it twice

### ISSUE THREAD

**Issue by curisegong** [marmelab/react-admin#8638] opened 2023-02-10 01:49 UTC
When I click on the non-from part of the login page, such as the background image, the system will focus my click on the input box of the login account by default, which is not what I want. When I add a button on the login interface, I hope to trigger my button event when I click this button for the first time, instead of focusing on the account input box, so I need to click twice to trigger the button event

**Comment by fzaninotto** [comment] 2023-02-14 13:36
Hi, and thanks for your feedback.

I don't understand your problem. The default Login page uses the HTML `autofocus` attribute on the login input, but doesn't do anything special with focus - I can't reproduce the problem you describe. Besides, to add a button to the login interface, you have written your own Login page, so the problem would be on your side... Or am I missing something? 

Please follow the issue template to explain how to reproduce your problem, the version you are using, the browser you are using, etc.

**Comment by fzaninotto** [comment] 2023-04-04 04:13
No news for some time, closing

**Closed by fzaninotto** 2023-04-04 04:13 UTC
Labels: needs more info
