### ISSUE TITLE
When a form contains ArrayInput with large entries. It takes more than a minute for a form to be submitted.

### ISSUE THREAD

**Issue by vardhanshahpirimid** [marmelab/react-admin#9783] opened 2024-04-19 08:31 UTC
**What you were expecting:**
The submission of the form with ArrayInput large entries should be fast.

**What happened instead:**
It takes more than a minute to submit a form and the page becomes unresponsive in between.

https://github.com/marmelab/react-admin/assets/96527080/e1a4513b-594e-4510-b41f-ee9d599120ba

**Steps to reproduce:**
[Sample Example v4](https://stackblitz.com/edit/github-rwg7tb-2vsyy7) Try running this project locally. somehow it works fine in Stackblitz but it's getting reproduced locally as well as in our application.

Once it's running locally follow these steps to reproduce.
1. Go to Posts resource.
2. Edit the first entry and submit the form.

**Other information:**

I performed a performance profiling on this event from dev-tool. As we can see there's lot of scripting happened after submitting the form. The performance profiler results show that one function named  `executeBuiltInValidation` from react-hook-form gets executed many times.

https://github.com/marmelab/react-admin/assets/96527080/962f8972-e990-4032-8492-d6311dd0d2d9

![Screenshot 2024-04-18 182600](https://github.com/marmelab/react-admin/assets/96527080/a3f76b94-c3ab-45ee-9723-1dce1e927246)

Similarly in our application when I performed the profiling. It took a long time to submit the form as `executeBuiltInValidation ` task takes a long time to execute.

![Screenshot 2024-04-18 181514](https://github.com/marmelab/react-admin/assets/96527080/44b5b815-a803-4dfc-8df0-68fdcbe989f9)

related issue:- https://github.com/marmelab/react-admin/issues/8949

**Environment**

* React-admin version: 4.10.6
* React version: 17.0.0
* Browser: Chrome

**Comment by slax57** [comment] 2024-04-19 09:48
Thanks for submitting this issue.

I confirm form submission is slow when there are many items in the ArrayInput, however I don't observe such drastic slowdowns.
Using the provided sandbox, performing the same action, on my computer the form submission only takes about 10 seconds.
I am running this on a 5 yo laptop.
See proof video below.


https://github.com/marmelab/react-admin/assets/14542336/5ced3981-65e6-4035-9baf-0044f8c0dd34



Besides, I also ran a profiling using Chrome DevTools, but I see no calls to `executeBuiltInValidation`.

![2024-04-19_11-47](https://github.com/marmelab/react-admin/assets/14542336/483f4759-0fa7-41ba-9a11-0b6b707fe86e)


I also ran a React DevTools profiling, which shows that the various `TextInput` components seem to be rerendered way too many times (approx. 236 rerenders at submission), which is certainly an issue.

![2024-04-19_11-46](https://github.com/marmelab/react-admin/assets/14542336/bd1cb537-99f4-45ed-91db-6bbd4dac4b89)


However, since the problem is, according to my tests, less critical than what your description leads to believe, and we do not have such a use-case on our projects at the moment, I can't guarantee we will fix this issue soon.

Any help diagnosing and fixing these slowdowns is welcome in the meantime.

**Comment by vardhanshahpirimid** [comment] 2024-04-19 10:35
Hello @slax57, Thank you for having a look. 

Somehow, it works fine in Stackblitz for me too, there's not much lag.

The issue does not appear to be reproducible in Stackblitz. However, when the application is running locally, or when it is deployed, there is a significant lag. The same behaviour is also observed in our application.

if possible, Can you please try again running on the local machine instead of Stackblitz? The delay will be reproduced and you can observe the `executeBuiltInValidation `in the profiler too.

PS:- Are there any suggestions or workarounds that can be employed until the problem is resolved?

**Comment by davishuang9** [comment] 2024-05-15 19:00
Locking react-admin and related packages to below versions fixed the slow down for me (~30s of JS runtime down to <1s for an ArrayInput of ~10 objects).
```
    "react-admin": "4.16.8",
    "ra-core": "4.16.8",
    "ra-i18n-polyglot": "4.16.8",
    "ra-language-english": "4.16.8",
    "ra-ui-materialui": "4.16.8",
    "react-hook-form": "7.49.3"
```

I suspect the problem is between react-admin and react-hook-form (possibly with material UI?)

**Comment by VladanStef** [comment] 2024-05-24 17:37
Can confirm that the slowdown still happens with react-admin 4.16.18 and react-hook-form 7.51.5, which are the latest versions as of this comment.

Pinning to the versions pointed out by @davishuang9 removes the slowdown.

**Comment by slax57** [comment] 2024-05-27 07:50
If I understand correctly, with the same version of react-admin, the issue is **present** with **react-hook-form 7.51.5**, and **absent** with **react-hook-form 7.49.3**. Is that correct?
This would tend to indicate the issue comes from react-hook-form.
Can someone check if the issue can be reproduced in a react-hook-form only sandbox?

**Comment by julian-schwab** [comment] 2024-05-29 10:21
Hi,
in our project, we have a form with around 60 input fields and saving the data takes significantly longer after upgrading to react-hook-form 7.51.1 or higher (5 seconds for 60 inputs, 12 seconds in dev mode). I tried to create a minimal example in this sandbox: [link](https://codesandbox.io/p/devbox/long-input-validation-with-react-hook-form-update-h6yy7r?file=%2Fsrc%2FApp.tsx%3A85%2C43&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwq8wqy800063b6iyf0bncyv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwq8wqy800023b6if0lxap6c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwq8wqy800043b6ig2fiwkei%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwq8wqy800053b6i5hm9inp6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwq8wqy800023b6if0lxap6c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwq8wqy800013b6idm8zs9j4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwq9e77f00023b6i49g8nacz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A85%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A85%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwq8wqy800023b6if0lxap6c%2522%252C%2522activeTabId%2522%253A%2522clwq9e77f00023b6i49g8nacz%2522%257D%252C%2522clwq8wqy800053b6i5hm9inp6%2522%253A%257B%2522id%2522%253A%2522clwq8wqy800053b6i5hm9inp6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clwqjbym800da3b6jo4qwg0cv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwqjbym800da3b6jo4qwg0cv%2522%257D%252C%2522clwq8wqy800043b6ig2fiwkei%2522%253A%257B%2522id%2522%253A%2522clwq8wqy800043b6ig2fiwkei%2522%252C%2522activeTabId%2522%253A%2522clwqj8v5u00a43b6jtgzll34l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwq8wqy800033b6ik9yjjvbq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwq8wr85000odjgz8c5eewxh%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clwqj8v5u00a43b6jtgzll34l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by manutuero** [comment] 2024-05-30 02:29
I had the exact same issue and managed to fix it by doing the following:

	1.	Locked the same versions in my package.json as @davishuang9 mentioned (copy & paste):

> Locking react-admin and related packages to below versions fixed the slow down for me (~30s of JS runtime down to <1s for an ArrayInput of ~10 objects).
> 
> ```
>     "react-admin": "4.16.8",
>     "ra-core": "4.16.8",
>     "ra-i18n-polyglot": "4.16.8",
>     "ra-language-english": "4.16.8",
>     "ra-ui-materialui": "4.16.8",
>     "react-hook-form": "7.49.3"
> ```
> 
> I suspect the problem is between react-admin and react-hook-form (possibly with material UI?)

	2.	Deleted the `node_modules` folder.
	3.	Deleted the `package-lock.json` file.
	4.	Ran `npm install` (used --force if necessary).

This solved the issue for me. Hope it helps you too!

**Comment by fzaninotto** [comment] 2024-05-30 13:03
#9885 has reproduced the same bug, but without ArrayInput. It seems to be caused by a regression in react-hook-form.

**Comment by fzaninotto** [comment] 2024-07-10 12:09
This should no longer be a problem with the latest version of react-hook-form ([7.52.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.52.0)), which contains the fix for this issue (https://github.com/react-hook-form/react-hook-form/pull/11995)

**Closed by fzaninotto** 2024-07-10 12:09 UTC
Labels: bug
