### ISSUE TITLE
ra 2.4.0 : Show component Warning : Invalid "classes" prop supplied

### ISSUE THREAD

**Issue by Flor27** [marmelab/react-admin#2448] opened 2018-10-19 10:40 UTC
My App shows a Warning with the Show component : 
`Failed prop type: Invalid prop `classes` supplied to `<<anonymous>>`, expected a ReactNode.`
Warning occurs at first hit on `/#/[ressource]/[id]/show` route.

Haven't got this warning with react-admin 2.3.4, 

* CodeSandbox : simple App example, only rect-admin version differs :

react-admin 2.3.4 : https://codesandbox.io/s/z40xwnx24
react-admin 2.4.0 : https://codesandbox.io/s/z5woqzxxl

**Comment by fzaninotto** [comment] 2018-10-19 11:16
Duplicate of #2443

**Closed by fzaninotto** 2018-10-19 11:16 UTC
