### ISSUE TITLE
Tooltip UserMenu issue

### ISSUE THREAD

**Issue by nkrmr** [marmelab/react-admin#6110] opened 2021-04-01 13:48 UTC
Hello,

I have this error message when I hover the user menu on my application

<img width="903" alt="Screenshot 2021-04-01 at 15 45 25" src="https://user-images.githubusercontent.com/686395/113303577-832dcf80-9301-11eb-8a60-aef2f0e7936d.png">

I override the Layout like this : 

```import React from 'react';
import { AppBar, UserMenu, Layout } from 'react-admin';
import Logout from '../Logout';

const CustomUserMenu = (props) => (
  <UserMenu {...props} logout={<Logout button />} />
);

const CustomAppBar = (props) => {
  return <AppBar {...props} userMenu={<CustomUserMenu />} />;
};

export const CustomLayout = (props) => {
  return <Layout {...props} appBar={CustomAppBar} />;
};
```
I use React-Admin 3.14.1

Does anyone facing this issue?

Best regards

**Comment by fzaninotto** [comment] 2021-04-01 17:07
Hi,

I can't reproduce the issue on the simple example. Please fork the [Simple Example CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak it to reproduce your issue, as explained in the issue template.

**Comment by fzaninotto** [comment] 2021-04-29 19:23
No news for some time, closing.

**Closed by fzaninotto** 2021-04-29 19:23 UTC
Labels: needs more info
