### ISSUE TITLE
DeleteButton's "redirect" redirects 2 times

### ISSUE THREAD

**Issue by ngocdaothanh** [marmelab/react-admin#5815] opened 2021-01-26 08:35 UTC
I'm using:
* react-admin: 3.11.4
* react-admin-firebase: 3.2.17
* react: 17.0.1
* react-dom: 17.0.1

My data model:
* 2 collections: `pages` and `items`
* `items` has `parentId` field to point to parent page

When deleting an item, I want to redirect to its parent page (not item list page).

My custom toolbar code:

```typescript
function EditToolbar(props: any) {
  const redirectDelete = () => {
    const target = `/pages/${props.record.parentId}`
    return target
  }

  return (
    <Toolbar {...props}>
      <SaveButton />
      <DeleteButton redirect={redirectDelete} />
    </Toolbar>
  )
}
```

My form code:

```typescript
const redirectForm = (basePath: any, id: any, data: any) => `/pages/${data.parentId}`

<SimpleForm redirect={redirectForm} toolbar={<EditToolbar />}>
  ...
</SimpleForm>
```

Expected behavior:
* DeleteButton's "redirect" redirects only 1 time, to `/pages/:pageId`.

Current buggy behavior:
* DeleteButton's "redirect" redirects 2 times.
* 1st time: it redirects to `/pages/:pageId`.
* 2nd time: it redirects to `/items`, and displays notification error: `Element does not exist`

In browser console, there's error log like this:

```
useDataProvider.js:16 Uncaught (in promise) {status: 200, message: "Error: Error getting id: XZHlFGGyZihM55lr7SII from collection: items", json: undefined}
```

The bug is probably related to:
https://github.com/marmelab/react-admin/issues/5541 (after delete & redirect from Edit page, react-admin still does a refresh on edit page calling `getOne` on the deleted object)

Currently, I have to use this `setTimeout` workaround to redirect another time (3rd time! And the error `Element does not exist` is still displayed to end users):

```typescript
const redirectDelete = () => {
  const target = `/pages/${props.record.parentId}`
  setTimeout(() => redirect(target), 6000)
  return target
}
```

**Comment by djhi** [comment] 2021-01-28 09:22
Hi and thanks for the report. I haven't been able to reproduce it though. Please provide a codesandbox showing the issue

**Comment by BowlingX** [comment] 2021-03-17 00:40
Maybe it helps someone; I had a similar problem, but in my case it was a `<DeleteButton />` inside a `<ReferenceField />`. I did not set the `link` prop to `false` for the `<ReferenceField />`, so it did multiple redirects (first to the resource, and then to the list).

**Comment by djhi** [comment] 2021-03-17 07:35
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by BowlingX** [comment] 2021-03-18 20:45
> Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

I think in my case this was not a bug per se but expected, as the `DeleteButton` does not cancel bubbling the event it went up to the `ReferenceField` and both fired a redirect.

**Comment by fzaninotto** [comment] 2021-03-19 08:49
You're right! We've added a stopPropagation in EditButton and ShowButton, but not in the 2 DeleteButtons. I'm marking it as a bug.

**Comment by filip-jk** [comment] 2021-03-19 12:40
I'm experiencing the exact same issue, even without altering the `toolbar` of the `<SimpleForm>` component.

@fzaninotto Any ETA on fixing this issue?

**Closed** 2021-03-19 13:57 UTC
Labels: bug
