### ISSUE TITLE
Form in filters

### ISSUE THREAD

**Issue by OVarLaz** [marmelab/react-admin#6195] opened 2021-04-20 15:18 UTC
**What you were expecting:**
Add a search filter in `<List />`

**What happened instead:**
I get an error about the input field: `Error: useField must be used inside of a <Form> component`
![image](https://user-images.githubusercontent.com/12819313/115416544-7e03c800-a1bd-11eb-9461-b3756c61106a.png)

**Steps to reproduce:**

1. Get a Users from List, using custom dataprovider, based on simpleRest (here I removed the query string, to get the values from the API)
2. Using the tutorial, I added filters like the example, with `filters` property
3. Basically, I copy the filters from the tutorial, and if the field use `alwaysOn`, I get an error when I try to render the view, and if I didn’t use `alwaysOn`, and add the new filter, I get the previous error about `useField`.
4. If I add a "form" I didn't get the error, but that is not specified in the tutorial

**Related code:**
```
const UserFilter: React.FC = (props) => (
  <Filter {...props}>
    {/* <SimpleForm> */}
    <SearchInput source="firstName" />
    <QuickFilter
      source="watchTutorialVideo"
      label="Tutorial"
      defaultValue={true}
    />
    <QuickFilter
      source="inviteThreeFriends"
      label="(3)friends"
      defaultValue={true}
    />
    <QuickFilter
      source="completeOnboardingProcess"
      label="Onboarding"
      defaultValue={true}
    />
    {/* </SimpleForm> */}
  </Filter>
) 
```
...
```
<List
      {...props}
      title="User List"
      filters={<UserFilter />}
      bulkActionButtons={<UsersBulkActionButtons />}
    >
```

**More Details:**

![image](https://user-images.githubusercontent.com/12819313/115419857-477b7c80-a1c0-11eb-82db-5a6627ab6923.png)
![image](https://user-images.githubusercontent.com/12819313/115419762-3468ac80-a1c0-11eb-9af9-666797b627d2.png)
![image](https://user-images.githubusercontent.com/12819313/115419926-595d1f80-a1c0-11eb-8448-dbf53200da2e.png)
select FirstName:
![image](https://user-images.githubusercontent.com/12819313/115420020-6f6ae000-a1c0-11eb-9d12-0e9cbbdfec99.png)

![image](https://user-images.githubusercontent.com/12819313/115419688-2581fa00-a1c0-11eb-8351-355b1d628f23.png)
![image](https://user-images.githubusercontent.com/12819313/115420209-932e2600-a1c0-11eb-9a42-de64b47060ef.png)

**Environment**

* React-admin version: "^3.13.2"
* React version: "^17.0.1"
* Browser: Chrome / Safari

**Comment by fzaninotto** [comment] 2021-04-20 16:00
I can't reproduce the error on the Simple example. Could you please fork the Simple example CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) and tweak the Posts list until you can reproduce the error, then paste the link of you fork here?

**Comment by OVarLaz** [comment] 2021-04-21 00:06
I couldn’t reproduce it, but I found an issue where the solution was to update the package, I did it and it works, thanks for the time!

**Comment by OVarLaz** [comment] 2021-04-21 03:37
I am trying to add a `SelectField`, in the filter, but it doesn't show any value, in the filter or in `EditView` either
This is the link with the `SelectField` added in the filter (tier field):
https://codesandbox.io/s/epic-dust-txk18?file=/src/posts/PostList.tsx

![image](https://user-images.githubusercontent.com/12819313/115493025-94933900-a228-11eb-8603-9ec6b1fc8e92.png)

**Comment by rassie** [comment] 2021-04-21 15:22
I've got a variation of the problem on my hands right now: the error message `Error: useField must be used inside of a <Form> component` only appears in production builds, even though I'm using `SearchInput` outside a form, but development works fine (using `create-react-app`).

**Comment by fzaninotto** [comment] 2021-04-21 17:14
You're using a SelectField instead of a SelectInput...

Anyway, I realize you need support more than you declare a bug in the library. The right channel for that is StackOverflow, as we keep the GitHub issues only for problems with the library itself, not its usage. 

So I'm closing the issue.

**Closed by fzaninotto** 2021-04-21 17:14 UTC
Labels: needs more info
