### ISSUE TITLE
ReferenceField always display

### ISSUE THREAD

**Issue by nacimgoura** [marmelab/react-admin#2388] opened 2018-10-04 13:38 UTC
Hello,
thanks you for your project.
I think there is a bug with ReferenceField.
When I use ReferenceField and the source is null, the loading appears but remains indefinitely. I have the impression that the field does not check before if the source is not null.

![capture d ecran 2018-10-04 a 15 34 00](https://user-images.githubusercontent.com/9990521/46477547-2b26b880-c7eb-11e8-92ed-f4fd4448c55b.png)

I was able to correct this by doing it like that but I think there must be a better solution:
```javascript
const ConditionalReferenceField = ({ record, ...rest }) =>
  record && record[rest.source] ? (
    <ReferenceField {...rest}>
      <TextField source="name" />
    </ReferenceField>
  ) : null;
```

* React-admin version: 2.3.3
* Last version that did not exhibit the issue (if applicable): no applicable
* React version: 16.5.2
* Browser: Chrome
* Stack trace (in case of a JS error): no

**Comment by TomJannes** [comment] 2018-10-04 14:10
I think you can use the  allowEmpty={true} attribute on the ReferenceField

**Comment by nacimgoura** [comment] 2018-10-04 14:15
This does not correct the problem. What I want to do is display the reference when the source exists otherwise do not display anything (no loading when there is nothing).

**Comment by djhi** [comment] 2018-10-04 14:30
@TomJannes is correct, that what `allowEmpty` does on a `ReferenceField`

**Comment by nacimgoura** [comment] 2018-10-04 14:43
I tried with allowEmpty={true} and allowEmpty={false}, but I still have the loading bar although the value is null.

**Comment by djhi** [comment] 2018-10-04 14:47
Why did you close it?

**Comment by nacimgoura** [comment] 2018-10-04 14:48
I edited my issue. Finally it works with `allowEmpty={true}`

**Comment by nacimgoura** [comment] 2018-10-08 10:08
I'm reopening the subject, a bug does exist.

When a reference data exists the loading bar is replaced by the data but when it does not find anything the loading bar remains all the time. I don't think that's the way it should be.

![capture d ecran 2018-10-08 a 12 05 00](https://user-images.githubusercontent.com/9990521/46603183-9d9cde80-caf2-11e8-984e-3f064fd0d7ff.png)

Here, on the first line it does not find any data (infinite loading bar). on the second line, existing data and deleting the loading bar.
Ideally, the loading bar should disappear after a certain period of time without finding any data.

**Comment by fzaninotto** [comment] 2018-12-12 17:20
Let me reiterate: if a reference data does not exist but you don't allow empty, then your data has a referential integrity problem. React-admin assumes you respect referential integrity, and cannot handle cases when it's not the case...

Closing the issue as won't fix. Feel free to reopen if you disagree.

**Closed by fzaninotto** 2018-12-12 17:20 UTC

**Comment by fzaninotto** [comment] 2018-12-13 19:56
and by the way, this is probably a duplicate of #854

**Comment by fzaninotto** [comment] 2019-08-22 08:08
Refixed in #3550
