### ISSUE TITLE
Cleared filterDefaultValues field is reset to default when another filter is added

### ISSUE THREAD

**Issue by jburghes** [marmelab/react-admin#2472] opened 2018-10-25 15:14 UTC
**What you were expecting:**
`filterDefaultValues` should only set the value of a `Filter` field on the first page load, not when another filter is populated

**What happened instead:**
If a `Filter` field with an associated `filterDefaultValues` is cleared, then another filter is populated, the first filter will be reset with it's default value.

**Steps to reproduce:**
Go the to posts page of the below codesandbox, clear the `title` filter, enter any text in the `search` box, notice that the title filter has been reset to it's `filterDefaultValues` value

**Related code:**
https://codesandbox.io/s/6vrvnn0kzr - react-admin v2.4
https://codesandbox.io/s/k5y489x333 - react-admin v2.3

**Environment**

* React-admin version: 2.4 & 2.3
* Last version that did not exhibit the issue (if applicable): Unknown
* React version: 16.3.0 and 16.3.2
* Browser: Chrome

**Comment by djhi** [comment] 2018-10-25 15:20
Reproduced. Thanks for reporting!

**Comment by fzaninotto** [comment] 2018-10-25 15:54
Not sure it's a bug, because *a default value is what an input should get when it has no value*. If you clear the input, and expect to have no value, then you should not set a `defaultValue, but an `initialValue` (except this one is not implemented).

**Comment by jburghes** [comment] 2018-10-25 16:07
I agree in part, but would add _a default value is what an input should get when it has no value at creation time_. Once created, an input should be able to be set to anything and not be overridden by the default.

Regardless, I'm happy if this is resolved by either changing the behaviour of `filterDefaultValues` or by adding a new `filterInitialValues` (or something similar).

**Comment by fzaninotto** [comment] 2018-10-25 16:08
Right. Marking this as an enhancement.

**Comment by fzaninotto** [comment] 2019-01-30 09:24
Re-qualifying as bug. The defaultFilterValues should only apply the first time. If the user sets another filter, it's their decision, and we should respect it.

Working on a fix.

**Comment by fzaninotto** [comment] 2019-01-30 09:37
Sorry, I closed this bug by mistake - by pushing to master. Reverting my commit to open a proper PR.

**Closed** 2019-01-30 11:58 UTC
Labels: bug
