### ISSUE TITLE
Datagrid component with custom query  for ListContextProvider  data

### ISSUE THREAD

**Issue by Netsoro** [marmelab/react-admin#5883] opened 2021-02-08 08:04 UTC
When i use the sample of react admin 3.12.1 documentation [https://marmelab.com/react-admin/List.html#uselistcontroller](url) 

```js
import React, { useState } from 'react'
import keyBy from 'lodash/keyBy'
import {
    useQuery,
    ResourceContextProvider,
    ListContextProvider,
    Datagrid,
    TextField,
    Pagination,
    Loading,
} from 'react-admin'

const CustomList = (props) => {
    const [page, setPage] = useState(1);
    const perPage = 50;

    const path = 'camp/getListEtiq/' + props.id + '/non_charge';
    const basePath = '/' + path;

    const { data, total, loading, error } = useQuery({
        type: 'getList',
        resource: path,
        payload: {
            pagination: { page, perPage },
            sort: { field: 'id', order: 'ASC' },
            filter: {},
        }
    });

    if (loading) {
        return <Loading />
    }
    if (error) {
        return <p>ERROR: {error}</p>
    }
    return (
        <ResourceContextProvider value={path}>
            <ListContextProvider
                value={{
                    basePath: basePath,
                    data: keyBy(data, 'id'),
                    ids: data.map(({ id }) => id),
                    currentSort: { field: 'id', order: 'ASC' },
                    selectedIds: [],
                }}
            >
                <Datagrid currentSort={{}}>
                    <TextField source="id" />
                    <TextField source="numCodeEtiq" />
                </Datagrid>
                <Pagination
                    page={page}
                    perPage={perPage}
                    setPage={setPage}
                    total={total}
                />
            </ListContextProvider>
        </ResourceContextProvider>
    );
}

export default CustomList;
```

I have the below error with Datagrid : 

TypeError: currentSort is undefined 

When i add an empty currentSort props to Datagrid  like this `<Datagrid currentSort={{}} >` it's avoid the error, but my displayed List is empty  with the correct number of rows.

This is simillar to this issue [https://github.com/marmelab/react-admin/issues/813](url).

But with empty currentSort prop when i click on sort field, the web page crash with error : TypeError: setSort is not a function

**Comment by djhi** [comment] 2021-02-08 09:07
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by Merkure** [comment] 2021-03-29 10:59
Hi Netsoro, 
try adding resource to ListContextProvider. Example: `<ListContextProvider
        value={{
          basePath: resource,
          data: keyBy(data, 'id'),
          ids: data.map(({ id }) => id),
          currentSort: { field: 'id', order: 'ASC' },
          selectedIds: [],
          resource,
        }}
      >` 
It helped me

**Comment by fzaninotto** [comment] 2021-04-13 20:54
I can't reproduce the error in 3.14.3, so I'm closing this issue. Feel free to reopen if you can provide a link to a CodeSandbox showing the issue.

**Closed by fzaninotto** 2021-04-13 20:54 UTC
Labels: needs more info
