### ISSUE TITLE
AutocompleteArrayInput becomes empty after search

### ISSUE THREAD

**Issue by magicxor** [marmelab/react-admin#8410] opened 2022-11-21 09:04 UTC
**What you were expecting:**
Search adds a new item; the old items remain intact.

**What happened instead:**
Search adds a new item; the old items disappear.

![ezgif-3-b23f9c2b1d](https://user-images.githubusercontent.com/8275793/203006271-05f73aac-d1ff-4219-be7e-f957f6528cdd.gif)

**Steps to reproduce:**
1) Launch [codesandbox](https://codesandbox.io/p/github/magicxor/react-admin-repro-AutocompleteArrayInput-bug/csb-rrv91n/draft/nice-leftpad?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522claqizetb000ml2gs626m9yem%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522claqj0xps008u2a699nt49mby%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fuser%252F112%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522claqj0v70006z2a699kl0hjhh%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) or the code from the [repo](https://github.com/magicxor/react-admin-repro-AutocompleteArrayInput-bug) directly.
2) Open http://localhost:3000/#/user/112 (edit achievements of user 112)
3) Start typing

**Related code:**
Repro: https://github.com/magicxor/react-admin-repro-AutocompleteArrayInput-bug

```tsx
        <ReferenceArrayInput label="Achievements" source="achievements" format={formatAnyArray} reference="achievement" allowEmpty fullWidth>
          <AutocompleteArrayInput optionText={o => o.name} format={formatAnyArray} filterToQuery={createSearchFilter} disableClearable clearOnBlur={false} fullWidth />
        </ReferenceArrayInput>
```

**Other information:**
I guess that the bug reproduces when there is `format` attribute in `ReferenceArrayInput` and `AutocompleteArrayInput` tags.

**Environment**

* React-admin version: ^4.5.1
* Last version that did not exhibit the issue (if applicable):
* React version: ^18.2.0
* Browser: Chrome 107.0.5304.107 (Official Build) (64-bit) and Firefox 107.0 (64-bit)
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2022-11-22 04:34
Duplicate of #8181

**Comment by fzaninotto** [comment] 2022-11-23 09:25
As it's a duplicate, I'm closing this bug in favor of the other one. Thanks for the report!

**Closed by fzaninotto** 2022-11-23 09:25 UTC
Labels: bug
