### ISSUE TITLE
make command error.

### ISSUE THREAD

**Issue by Bundara123** [marmelab/react-admin#1900] opened 2018-06-11 08:31 UTC
make i info Invoking install target
(node:10236) UnhandledPromiseRejectionWarning: undefined
(node:10236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                                   error originated either by throwing inside of an async function without a catch                                                                                                                                   block, or by rejecting a promise which was not handled with .catch(). (rejectio                                                                                                                                  n id: 1)
(node:10236) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr                                                                                                                                  ecated. In the future, promise rejections that are not handled will terminate th                                                                                                                                  e Node.js process with a non-zero exit code.
**make **× ERR**  not found: make-package.json**

**Comment by fzaninotto** [comment] 2018-06-12 14:00
Can't reproduce from a fresh install:

```sh
➜  tmp git clone git@github.com:marmelab/react-admin.git
Cloning into 'react-admin'...
remote: Counting objects: 23977, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 23977 (delta 6), reused 4 (delta 0), pack-reused 23949
Receiving objects: 100% (23977/23977), 77.16 MiB | 894.00 KiB/s, done.
Resolving deltas: 100% (17739/17739), done.
Checking connectivity... done.
➜  tmp cd react-admin
➜  react-admin git:(master) make install
yarn install v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-core@2.0.2" has unmet peer dependency "react@~16.0.0 || ~16.1.0 || ~16.2.0 || ~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-core@2.0.2" has unmet peer dependency "react-dom@~16.0.0 || ~16.1.0 || ~16.2.0 || ~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-data-graphcool@2.0.2" has unmet peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-data-graphql-simple@2.0.2" has unmet peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-data-graphql@2.0.2" has unmet peer dependency "graphql@^0.13.2".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-input-rich-text@2.0.2" has unmet peer dependency "react@~16.0.0 || ~16.1.0 || ~16.2.0 || ~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-input-rich-text@2.0.2" has unmet peer dependency "react-dom@~16.0.0 || ~16.1.0 || ~16.2.0 || ~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-realtime@2.0.2" has unmet peer dependency "react-router@~4.2.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-realtime@2.0.2" has unmet peer dependency "react-router-redux@~5.0.0-alpha.9".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-realtime@2.0.2" has unmet peer dependency "redux-saga@~0.16.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-ui-materialui@2.0.2" has unmet peer dependency "react@~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > ra-ui-materialui@2.0.2" has unmet peer dependency "react-dom@~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > react-admin@2.0.2" has unmet peer dependency "react@~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > react-admin@2.0.2" has unmet peer dependency "react-dom@~16.3.0".
warning "workspace-aggregator-d8f1dbb9-281b-4666-8996-3689645f44f8 > demo > json-graphql-server > graphql-tag@2.0.0" has incorrect peer dependency "graphql@^0.9.x".
[4/4] 📃  Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.7.0", while you're on "1.6.0".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
✨  Done in 37.85s.
```

You probably have a too old version of node. Which one is it?

**Comment by fzaninotto** [comment] 2018-07-03 06:40
No news for some time, closing.

**Closed by fzaninotto** 2018-07-03 06:40 UTC

**Comment by blueneel05** [comment] 2018-10-31 20:06
I am also facing same issue. how did you solve it ?i am facing it on fresh installation of react with fresh installation of node

**Comment by fzaninotto** [comment] 2018-11-05 12:59
What's your platform?

**Comment by e-ndrus** [comment] 2019-01-11 11:23
In my case, it's Windows 10. Same issue.
