### ISSUE TITLE
Include admin in another application error

### ISSUE THREAD

**Issue by kolyabres** [marmelab/react-admin#2063] opened 2018-07-22 11:02 UTC
I got error `ListController.js:413 Uncaught TypeError: Cannot read property 'list' of undefined` while  I'm tryiing include react admin in another application
```
ListController.js:413 Uncaught TypeError: Cannot read property 'list' of undefined
    at Function.mapStateToProps [as mapToProps] (ListController.js:413)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:52)
    at mapToPropsProxy (wrapMapToProps.js:43)
    at handleFirstCall (selectorFactory.js:26)
    at pureFinalPropsSelector (selectorFactory.js:74)
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)
    at constructClassInstance (react-dom.development.js:6355)
```

Code
```
import React from "react"
import { render } from "react-dom"
import { Provider } from 'react-redux'
// import storeConfig from './store'
import Routes from './routes'

import {
    adminSaga,
    TranslationProvider,
} from 'react-admin';
import restProvider from 'ra-data-simple-rest';
import { authCheck } from './modules/auth/store/actions'
import createSagaMiddleware from 'redux-saga';
import thunk from "redux-thunk";
import { routerMiddleware, ConnectedRouter } from 'react-router-redux';
import createHistory from "history/createHashHistory";
import {applyMiddleware, compose, createStore} from "redux/index";
import rootReducer from "./store/reducers";


const sagaMiddleware = createSagaMiddleware();
const dataProvider = restProvider('http://path.to.my.api/');
const history = createHistory();


const store = storeConfig({},[sagaMiddleware, routerMiddleware(history), thunk])

const authProvider = () => Promise.resolve();
sagaMiddleware.run(adminSaga(dataProvider, authProvider));

store.dispatch(authCheck())

render((<Provider store={store}>
    <TranslationProvider>
        <ConnectedRouter history={history}>
            <Routes/>
        </ConnectedRouter>
    </TranslationProvider>
  </Provider>),
    document.getElementById('app')
)

function storeConfig (initialState = {}, middlewares) {
    const store = createStore(
        rootReducer,
        initialState,
        compose(
            applyMiddleware(...middlewares),
            window.devToolsExtension ? window.devToolsExtension() : f => f,
        )
    )

    // For hot reloading reducers
    if (module.hot) {
        // Enable Webpack hot module replacement for reducers
        module.hot.accept('./reducers', () => {
            const nextReducer = require('./reducers').default // eslint-disable-line global-require
            store.replaceReducer(nextReducer)
        })
    }

    return store
}
```
```
import {combineReducers} from 'redux'

import auth from '../modules/auth/store/reduer'
import user from '../modules/user/store/reducer'
import articles from '../modules/article/store/reducer'
import organization from '../modules/organization/store/reducer'
import {
    adminReducer,
    i18nReducer
} from 'react-admin';
import { reducer as formReducer } from 'redux-form';
import {  routerReducer } from 'react-router-redux';
export default combineReducers({
    admin: adminReducer,
    i18n: i18nReducer('en', {}),
    form: formReducer,
    routing: routerReducer,
    auth,
    user,
    articles,
    organization
})

```
```
import React from 'react'
import {Switch, Route} from 'react-router-dom'
import routes from './routes'
import PrivateRoute from './Private'
import PublicRoute from './Public'

import Layout from '../layout'
import {OrganizationList} from "../modules/organization/pages/admin/list";


const Routes = () => (
    <Layout>
        <Switch>
            {routes.map((route, i) => {
                if (route.auth) {
                    return <PrivateRoute key={i} {...route} />
                }
                return <PublicRoute key={i} {...route} />
            })}
            <Route exact path="/organizations"
                   render={(routeProps) => <OrganizationList resource="organizations" {...routeProps} />}/>
        </Switch>
    </Layout>

)

export default Routes
```

**Comment by djhi** [comment] 2018-07-22 11:04
Thanks for reporting! Closing it as a duplicate of #2025

**Closed by djhi** 2018-07-22 11:04 UTC
