### ISSUE TITLE
FormDataConsumer is resetting the form when a contained component has a defaultValue

### ISSUE THREAD

**Issue by stopmachine** [marmelab/react-admin#1906] opened 2018-06-13 14:51 UTC
**What you were expecting:**
For `FormDataConsumer` to be evaluated once and render the inner components if needed.

**What happened instead:**
The `FormDataConsumer` is rendered two times, once with the correct form values, then if an inner component has a `defaultValue` the form is reset and `FormDataConsumer` is evaluated again with the form values reset.

**Steps to reproduce:**
See [this sandbox](https://codesandbox.io/s/129r0lx3l), which was edited in `PostCreate.js` at line 60. If you type a character in the Create Post page in the Title field it immediately disappears, and the Average note field does not appear, until you type the character again.

**Related code:**
CodeSandbox:
https://codesandbox.io/s/129r0lx3l

**Other information:**

**Environment**

* React-admin version: 2.0.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.3.17
* Browser: Firefox 60.0.1 and Chrome 67.0.3396.62 on Ubuntu 16.04
* Stack trace (in case of a JS error):

**Comment by ashim-k-saha** [comment] 2018-07-03 09:48
+1

**Comment by fzaninotto** [comment] 2018-07-04 15:30
Bug reproduced and confirmed, thanks for taking the time to isolate and reproduce it with a sandbox.

Here are the Redux actions dispatched when there is no `defaultValue`:

![2018-07-04_1727](https://user-images.githubusercontent.com/99944/42285444-efbcf260-7faf-11e8-90a9-36a5e029e669.png)

And when there is one:

![2018-07-04_1728](https://user-images.githubusercontent.com/99944/42285450-f4d1af20-7faf-11e8-8452-9e1d314f99ee.png)

Our `RA/INITIALIZE_FORM` action seems to be creating the problem.

**Comment by fzaninotto** [comment] 2018-07-24 14:35
#1997 has been reverted in #2075 because it caused side effects, so this bug effectively reappears.

**Comment by djhi** [comment] 2018-08-01 07:42
Fixed by #2082

**Closed by djhi** 2018-08-01 07:42 UTC
Labels: bug
