### ISSUE TITLE
Reference Input with Autocomplete Input do not work as they should

### ISSUE THREAD

**Issue by softeasyweb** [marmelab/react-admin#3341] opened 2019-06-17 18:52 UTC
**What you were expecting:**
I was hoping to type the exam option and the return appears below the input and after selecting does not reappear the selected option

**What happened instead:**
After typing the option to be selected the return appears at the top of the screen and after selecting it only appears again the option selected below the input as if it had made a new query only with the id of the option selected previously

**Steps to reproduce:**
![Jun-17-2019 16-01-22](https://user-images.githubusercontent.com/31162087/59629452-3ae7f200-9119-11e9-8ada-af4127606207.gif)

**Related code:**

 ```jsx
                <ReferenceInput label="Exame" sort={{ field: 'descricao', order: 'ASC' }} source="exame_id" reference="exame" perPage={100} validate={required()}>
                    <AutocompleteInput optionText="descricao" optionValue="id" shouldRenderSuggestions={(val) => { return val.trim().length > 2 }} 
                        inputValueMatcher={(input, suggestion, getOptionText) => input.toUpperCase().trim() === suggestion.descricao || input.toLowerCase().trim() === getOptionText(suggestion).toLowerCase().trim()}
                    />  
                </ReferenceInput> 
```

* CodeSandbox
https://codesandbox.io/s/react-with-hooks-g0u3m

**Environment**
* React-admin version: 2.9.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.6.0
* Browser: Chrome Versão 74.0.3729.169 (Versão oficial) 64 bits

**Comment by djhi** [comment] 2019-06-26 05:43
The codesandbox cannot run because of imports errors. Please fix it so that we can investigate. Better yet, try to reproduce it on the official codesandbox: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by softeasyweb** [comment] 2019-06-27 18:35
Thanks for the feedback, below is an example image in the codesandbox that you requested to simulate the problem.

![Jun-27-2019 15-34-08](https://user-images.githubusercontent.com/31162087/60291309-0f22f400-98f1-11e9-966d-7e1735f25e93.gif)

**Comment by Kmaschta** [comment] 2019-06-28 08:27
Can you share the link of your CodeSandbox please? The image is really tiny and illegible.

**Comment by softeasyweb** [comment] 2019-07-01 14:39
Yes, of course, it goes below 
https://codesandbox.io/embed/wizardly-stonebraker-soeeu

**Comment by softeasyweb** [comment] 2019-08-13 12:44
Dears, good morning !

Can you tell us if this issue will be included in version 3.0? Our team is almost giving up on using react-admin, but I'm arguing that it's a problem that will be solved.

I thank you for your attention and feedback.

**Comment by Kmaschta** [comment] 2019-08-13 13:19
Hey, I just found out that this issue is a duplicate of #2961 you might find some workaround there.
Also, there is a full rewrite of that component in progress: #3031 

Yes, the rewrite with bug fixes of the `<AutocompleteInput>` is our V3 Roadmap (see #3194).

**Closed** 2019-08-13 13:19 UTC
Labels: bug

**Comment by codefingas** [comment] 2020-01-30 10:33
hi @softeasyweb you should check for the data being returned from your source. Some of them might have the essential property missing which causes it to fail.
