### ISSUE TITLE
Infinite loop occurs in page rendering when perPage is set to a negative number in List Component

### ISSUE THREAD

**Issue by aoki-atsushi** [marmelab/react-admin#9745] opened 2024-03-27 09:36 UTC
**What you were expecting:**

Even if a negative number is set in perPage, it is replaced by the default positive number.

**What happened instead:**

URL and List Component are rendered indefinitely

**Steps to reproduce:**

Access the page using ListComponent with the following query string
`?page=1&perPage=-1`

**Related code:**

Perhaps this is occurring because there is no logic to account for negative numbers in the following places
https://github.com/marmelab/react-admin/blob/master/packages/ra-data-simple-rest/src/index.ts#L45-L46

**Other information:**

**Environment**

* React-admin version: 4.16.13
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Google Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2024-03-28 06:33
I can't reproduce it in the [simple example StackBlitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=README.md). Perhaps it's because the problem is only in `ra-data-simple-rest`?

In any case, this is a minor bug for a corner case, so we won't prioritize it. Feel free to open a PR for it if the bug is more critical for your use case.

**Comment by adguernier** [comment] 2024-04-05 08:09
I can't either reproduce. Please, provide a reproductible example using the React-admin v4 [StackBlitz](https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple (v4)) template. 
Of course, a PR is welcome :+1:

**Comment by fzaninotto** [comment] 2024-05-03 19:56
No news for some time, closing.

**Closed by fzaninotto** 2024-05-03 19:56 UTC
Labels: needs more info
