### ISSUE TITLE
TabbedForm and TabbedShowLayout tab navigation is broken

### ISSUE THREAD

**Issue by silversonicaxel** [marmelab/react-admin#9468] opened 2023-11-22 20:10 UTC
**What you were expecting:**
I've an `<Edit />` component View page to edit a record and I use it in combination with `<TabbedForm />` component.
I expect to switch among `<TabbedForm.Tab />`s and edit the fields of the record.

**What happened instead:**
The `<TabbedForm.Tab />`s beyond the first one are not reachable, instead first `<TabbedForm.Tab />` keeps being visible. What also happens in the url is that, every time I click a `<TabbedForm.Tab />`, the url keeps adding the index of the clicked `<TabbedForm.Tab />` to the end of the url. Application is not broken though, so no javascript error occurs.

**Steps to reproduce:**
The application is based on Nextjs and ReactAdmin, but it is private, so unsharable.

What I can say is that I've a CRUD scenario, with an Edit view based on Tabs and since the upgrade from version 4.14.3 to 4.16.0 happened, the Application has this behaviour.

**Related code:**
I can't really show examples, but an official react-admin demo example https://github.com/marmelab/react-admin/tree/master/examples/simple visible at this link
https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple shows also that current implementation has the same issue. To reproduce it in the example app do the following steps:
- Click on the left sidebar the menu item Tags
- Edit one tag, for example Sport
- Edit one item in the bottom grid.
- Click one of the tabs in the Edit view
- Tabs are not switching

**Other information:**
/

**Environment**

* React-admin version: 4.16.0
* Last version that did not exhibit the issue (if applicable): 4.14.3
* React version: 18.2.0
* Browser: all
* Stack trace (in case of a JS error): /

**Comment by fzaninotto** [comment] 2023-11-22 22:01
Yep, I saw that bug, too, only a bit later. This is a regression, we'll work on fixing it soon.

**Comment by silversonicaxel** [comment] 2023-11-22 22:51
As far as I understand, the `simple` example is used for e2e tests. Could something be improved there?

**Comment by slax57** [comment] 2023-11-23 10:52
Turns out this is due to 2 regressions introduced in **react-router v6.19.0** and **v6.20.0**.

I have opened an issue on their repo to request for a fix: https://github.com/remix-run/react-router/issues/11053

Until this is fixed, you will need to use version **v6.18.0** at most, which does not show the issue.

Thanks for the report!

**Comment by fzaninotto** [comment] 2023-11-23 11:09
I think that using `<TabbedForm syncWithLocation={false}>` allows to temporarily fix the bug, if you don't need the tabs to be synced with location (and support the back button in tab navigation).

**Comment by StefanFl** [comment] 2023-11-26 07:32
I see the same bug for `<TabbedShowLayout>`.

**Comment by 1vanguard** [comment] 2023-11-28 06:32
I have the same problem in the TabbedForm component

**Comment by silversonicaxel** [comment] 2023-11-28 14:42
@fzaninotto maybe they are going to reopen them both, first it is!

**Comment by fzaninotto** [comment] 2023-11-29 13:09
Fixed by #9480, where we forbid recent react-router versions in react-admin's dependencies. 

We may relax these requirements in the future if the react-router fixes the problem upstream.

**Closed by fzaninotto** 2023-11-29 13:09 UTC
Labels: bug

**Comment by fzaninotto** [comment] 2023-12-01 22:15
I reverted #9480 as the react-router team has fixed the problem upstream by publishing a new version, 6.20.1. 

If you encounter this problem, please upgrade your dependencies to the latest react-router and react-router-dom versions (>= 6.20.1)

**Comment by mpriestau** [comment] 2025-01-22 19:28
Not sure if this is related, but after upgrading to RA 5.5.0 and upgrading React versions i seem to be getting the same problem as originally reported

**Comment by slax57** [comment] 2025-01-23 14:52
@mpriestau I confirm updating to react-router v7 (which is possible since RA v5.5) brings back the same bug.
I won't reopen though as it's already tracked here: https://github.com/marmelab/react-admin/issues/10458
