### ISSUE TITLE
Dashboard loses colors, theming, title

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6430] opened 2021-07-12 21:16 UTC
When adding a Dashboard with latest version, the title, and colors go away on the app bar.

![Screen Shot 2021-07-12 at 4 15 45 PM](https://user-images.githubusercontent.com/15056748/125356908-7c651e80-e32c-11eb-9e73-af6821f10606.png)

**Comment by djhi** [comment] 2021-07-13 06:44
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by andrico1234** [comment] 2021-07-13 11:01
I've had this issue before, make sure you're using consistent versions of material-ui in your project. There's a bit in the FAQ about it [here](https://marmelab.com/react-admin/FAQ.html#ui-in-production-build-is-empty-or-broke)

**Comment by olehmelnyk** [comment] 2021-07-13 20:18
I have the same problem, most likely caused by recent MaterialUI minot update with breaking changes.
adding `"resolutions": { "ra-ui-materialui": "3.15.0" },` to package.json and setting `"@material-ui/core": "4.11.4",` seams to solve the issue, but of course it's a temporary solution.

**Comment by davidhenley** [comment] 2021-08-02 14:16
The new MUI update did not fix this

**Comment by fzaninotto** [comment] 2021-08-02 14:27
@davidhenley This is usually caused by multiple material-ui version in your node_modules. 

The comments above gave you 2 ways to troubleshoot your issue, and we've asked you to provide a reproducible test case.

**Comment by fzaninotto** [comment] 2021-09-10 08:41
No news for some time, closing.

**Closed by fzaninotto** 2021-09-10 08:41 UTC
Labels: needs more info
