### ISSUE TITLE
useUpdate call empties a list of results from useGetList

### ISSUE THREAD

**Issue by romannotroman** [marmelab/react-admin#6780] opened 2021-11-15 07:38 UTC
**What you were expecting:**
I have a component where results are retrieved from the endpoint "videos" with the help of `useGetList`, and when a user edits one of the videos and it's updated with `useUpdate` expected behaviour is that a list of "videos" should also reflect the changes,  Everything works as expected when you use `ReferenceManyField` as a parent and `useListContext` to retrieve "videos" inside the component.

**What happened instead:**
Instead, if you use `useUpdate` to the same endpoint, results from `useGetList` are emptied. If you call `refetch` in `onSuccess` everything works, but it's an extra API call.

**Steps to reproduce:**
1. Create a component which retrieves data from an endpoint with `useGetList`.
2. Update one of the retrieved results with `useUpdate`.
3. A list of results from `useGetList` is emptied.

**Related code:**

```
const VideoEditor = (props) => {
   ...
   const { data: videos, ids: videoIds, loading, loaded, refetch } = useGetList(
            "videos",
            { page: 1, perPage: 10 },
            { field: "index", order: "ASC" },
            { video_id: record.id},
            { enabled: !!record.id},
        );
   ...
   
   const handleVideoUpdate = (values) =>  {
        const options = {
            onSuccess: (data) => {
                // refetch (); - **don't want to refetch the list**
            },
        };
        update("videos", activeVideoId, values, videos[activeVideoId], options);
    };
};
```

**Other information:**

**Environment**

* React-admin version: 3.19.0

**Comment by djhi** [comment] 2021-11-15 08:26
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by romannotroman** [comment] 2021-11-16 07:58
Hello

Is this a bug, or a feature?

**Comment by WiXSL** [comment] 2021-11-17 14:44
@romannotroman, this is not a bug, you have to refresh the view from the `success` side effect

**Comment by romannotroman** [comment] 2021-11-17 14:55
> @romannotroman, this is not a bug, you have to refresh the view from the `success` side effect

I'm not sure about this. This will trigger data refetch, if you use `ReferenceManyField` there is no need in extra request to backend. 
And, besides, what's the logic behind clearing of results from useGetList?

**Comment by WiXSL** [comment] 2021-11-17 17:42
Yep, the use of `useUpdate` plus `useGetList` in your example seems to make the `useGetList` return empty data instead of the cached data, let me dig in a little more and I get back to you

**Comment by romannotroman** [comment] 2021-11-18 09:02
@WiXSL 

Yeah, and this behaviour, frankly, quite weird. Following the logic of how React Admin works, `useUpdate` should update a cached item and results from `useGetList`.

**Comment by WiXSL** [comment] 2021-11-18 10:56
This looks like a bug indeed.
I'll mark it such and ping @djhi

**Comment by rkfg** [comment] 2021-11-25 07:40
I just hit this bug in the exact same scenario and after several unsuccessful attempts to find out what I'm doing wrong I decided to search here. Thanks for reporting it!

To expand why fixing this is important I'll describe my case. It's a custom page that creates or updates records every time the user changes the client status. As soon as the update happens it seems that cached query results in the Redux store are cleared and it causes all statuses to disappear. Refetching makes it work but statuses still get reset between the moment the update finishes and the moment the updated state arrives from the server. It looks bad and not fluent.

I expect "optimistic" rendering take care of it since it should patch the Redux state so that `useGetList` returns the updated state immediately while it requests the new data from the server in background. Instead `useGetList` starts to return an empty list and _never_ even tries to request the new one! So maybe this bug is deeper than it looks: local state gets reset (or isn't accessible because the `data` object for this resource in Redux looks fine) instead of being patched + remote state isn't queried after update.

**Comment by romannotroman** [comment] 2022-01-18 11:16
Hello

Is there any update on this bug?

**Comment by fzaninotto** [comment] 2022-01-21 13:09
`useUpdate` cannot perfectly update the result from `useGetList`, so a `refresh` is always necessary. 

Let me give you an example. Say you have a `useGetList('books', { sort: 'title', 'ASC' })`. The first element has probably a title starting with an 'A' (like: 'A brief history of time'). Say you use `useUpdate()` to update its title to say "Zorro". `useUpdate` can update the *record* so that it gets the right title, but the *position* of the element in the list will change, and there is no way to determine it client-side. Therefore, you MUST refresh/refetch getList after an update.

There are some particular cases where it's not strictly necessary, but react-admin must work in the general case. If you need to skip the refresh in your case, I suggest you use use custom hooks that call the dataProvider directly.

**Comment by rkfg** [comment] 2022-01-21 13:14
This makes sense but maybe it's possible to automatically refetch `getList` instead of returning empty list? I don't really understand why `useGetList` starts returning empty list after `useUpdate`. If the Redux cache is invalidated (your example perfectly explains why it's required!) I expect it to be automatically repopulated from the server next time the component is rerendered. Instead it just breaks...

**Comment by fzaninotto** [comment] 2022-01-21 13:20
In react-admin, the refresh is called by every component that calls useUpdate (see e.g. [BulkUpdateWithUndoButton](https://github.com/marmelab/react-admin/blob/7f0aac12074d6a3319012c71e7aecf6cca1faec1/packages/ra-ui-materialui/src/button/BulkUpdateWithUndoButton.tsx). We expect that you do the same in your components. 

You could argue that this refresh should be in the data layer (the data Provider hooks) rather than in the controller layer, but changing that would be a breaking change. We won't address it in version 3.0. 

In the `next` version, you shouldn't have this problem.

**Comment by romannotroman** [comment] 2022-01-27 14:09
I still don't quite understand why everything works perfectly well if you fetch data with ReferenceManyField (for example), but if you use useGetList it's not. The problem is that if you have a complex component and fetch data with the latter and then do update one of the item, your UI gets painfully slowly re-rendered from the ground.

**Comment by fzaninotto** [comment] 2022-07-22 11:57
This problem was due to the way react-admin handled query cache in 3.0. It is fixed in 4.x.

**Closed by fzaninotto** 2022-07-22 11:57 UTC
Labels: bug
