### ISSUE TITLE
<ReferenceInput> inside <SimpleFormIterator> throws warnings

### ISSUE THREAD

**Issue by vascofg** [marmelab/react-admin#1973] opened 2018-06-28 18:58 UTC
Using react-admin `2.0.3`.
When rendering a `<ReferenceInput>` inside a `<SimpleFormIterator>` (`<ArrayInput>`), I get the following warnings:
```
The prop `resource` is marked as required in `ReferenceInputView`, but its value is `undefined`.
```
```
 React does not recognize the `fullWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fullwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

The component seems to work fine. This happens only on first render, if I navigate around it never throws the warnings again.

**Comment by fzaninotto** [comment] 2018-06-28 19:30
Duplicate of #1871 and #1957

**Closed by fzaninotto** 2018-06-28 19:30 UTC
