### ISSUE TITLE
first tag gets empty after selecting second one in AutocompleteArrayInput 

### ISSUE THREAD

**Issue by zohaib055** [marmelab/react-admin#2689] opened 2018-12-23 04:47 UTC
I'm using AutocompleteArrayInput  component when try to select second chip tag it makes the first one empty not sure why it's happening i saw another request going with filter q:'' after selecting second one

**Comment by fzaninotto** [comment] 2019-01-31 16:15
I can't reproduce the problem with the simple example on master, can you provide a CodeSandbox showing the issue?

**Comment by fzaninotto** [comment] 2019-04-25 16:51
No news for some time, closing.

**Closed by fzaninotto** 2019-04-25 16:51 UTC
Labels: awaiting more info
