### ISSUE TITLE
Add ability to create options in AutoCompleteInput

### ISSUE THREAD

**Issue by webant-ltd** [marmelab/react-admin#5981] opened 2021-03-02 09:28 UTC
I always get frustrated when I am unable to add an option to AutoCompleteInput.

Add an prop to AutoCompleteInput, which will allow adding an entry to the array if this one not found in the search.

Perhaps there are no alternatives.

For example https://material-ui.com/components/autocomplete/#creatable

**Comment by djhi** [comment] 2021-03-05 09:00
It would definitely be a nice addition. However, our time is limited and this is not a priority for us. We would love a PR though. Feel free to start working on it and submit one

**Comment by fzaninotto** [comment] 2021-03-08 18:06
Duplicate of #744

**Comment by fzaninotto** [comment] 2021-04-27 10:10
Fixed by #6215

**Closed by fzaninotto** 2021-04-27 10:10 UTC
Labels: enhancement
