### ISSUE TITLE
react-admin won't redirect to /login page when {(permissions) => {}} is passed as a child of <Admin /> instead of list of <Resource /> 

### ISSUE THREAD

**Issue by kopax** [marmelab/react-admin#4485] opened 2020-03-07 11:08 UTC
I am experiencing an issue when the user is not authed, this started after upgrading from v2 to v3 (this is the last bug I have from this migration),  it seems that there is a regression change of #1605,

![image](https://user-images.githubusercontent.com/1866564/76142191-c33e6680-609d-11ea-9054-ab579e3651b6.png)

Adding `/login` to the URL and press enter will display the login form.

After being logged, I can hit the `/` path without trouble.

I have tried to add a `<Redirect from="/" to="/login" />` but this will break the login page and was a bad option.

I use the ` {(permissions) => {}}` as `<Admin />` children.

I know the login dispatched event have been removed in v3,  did anything change recently? 

This is how looks like my new `authProvider`:

```jsx
export default function createAuthProvider(urls, client) {
  return {
    login: (params) =>  {
      return fetchLoginBatch(params, urls, client);
    },
    logout: (params) => params.jwt ? fetchLogout(makeRequestLogout(urls.logout, params.jwt)) : Promise.resolve(),
    checkError: (error) => {
      const { status } = error;
      if (status === 401 || status === 403) {
        return Promise.reject();
      }
      return Promise.resolve();
    },
    checkAuth: (params) => params.jwt ? Promise.resolve() : Promise.reject(),
    getPermissions: (params) => params.jwt ? Promise.resolve(params.jwt.authorities) : Promise.resolve(),
    refreshJwt: (params) => params.jwt ? fetchRefreshJwt(makeRefreshJwtRequest(client.accessTokenUri, {
      grant_type: 'refresh_token',
      refresh_token: params.jwt.refresh_token,
    }, client)) : Promise.resolve()
  };
}
```

## Reproduction

[Here](https://staging-backoffice.icimatin.com)

## Related issues:

- https://github.com/marmelab/react-admin/issues/1605

**Comment by kopax** [comment] 2020-03-10 07:43
Solved, for me the issue was that the `AuthContext` was existing twice, I was able to solve it by adding this in my webpack configuration:

```jsx
    config.resolve.alias['./AuthContext'] = join(__dirname, 'node_modules', 'ra-core/lib/auth/AuthContext');
```

This only concerns people that split their app in multiple packages.

**Comment by fzaninotto** [comment] 2020-03-10 17:08
I can't reproduce it on the simple example (which uses the permissions syntax) on master. Please provide a CodeSandbox reproducing the issue based on [the simple admin CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by JulienMattiussi** [comment] 2020-04-03 09:20
We still don't know how to reproduce your issue.
It's a month since you opened it and maybe you jus have found a solution now.
I close it.
But feel free to reopen if you can provide a reproducing case, or if you have more elements to investigate.

**Closed by JulienMattiussi** 2020-04-03 09:20 UTC
Labels: needs more info

**Comment by kopax** [comment] 2020-04-03 20:54
Hi @JulienMattiussi sorry for this, I completely lost the track of this. You are welcome to close the issue, I am not sure how I fixed it but now I can tell it's not happening anymore. Thanks for offering to reopen this if needed it is well appreciated.

**Comment by fzaninotto** [comment] 2023-01-23 08:31
@hs-dev-web That's weird. Please open a new issue following the issue template.
