### ISSUE TITLE
Error in dependency package "ra-ui-materialui" used by react-admin

### ISSUE THREAD

**Issue by rohan-techahead** [marmelab/react-admin#6728] opened 2021-10-27 15:58 UTC
Hi Team,
I am currently facing a issue which appears to be appearing from one of the dependent package used by react-admin which is "ra-ui-materialui".

It says **"./node_modules/ra-ui-materialui/esm/layout/DeviceTestWrapper.js Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles' ".**
I am using "react-admin": "^3.17.0".

Following are the some of the package version which I m using.
   
` "@material-ui/core": "4.11.4",`
   ` "@types/react": "^16.14.11",`
   ` "react-admin": "^3.17.0".`
    `"react": "^16.13.1",`
    `"typescript": "~3.8",`

Due to above reason, my code has stopped working.
If you need anything else please let me know.

![Capture1](https://user-images.githubusercontent.com/80825511/139102493-94fc0387-9ef3-48c7-bfd5-cb104e047324.PNG)

**Comment by rohan-techahead** [comment] 2021-10-31 20:40
Hi @djhi can you please reopen this issue as it is still unresolved.

**Comment by snvini** [comment] 2021-11-01 18:07
I have the exactly same problem...

**Comment by rohan-techahead** [comment] 2021-11-01 18:36
Hi @djhi , Is there any update on this, as it is a blocker and we have dependency on this. Please revert as soon as possible. Thanks

**Comment by snvini** [comment] 2021-11-01 19:11
@rohan-techahead i removed all material-ui from my package.json and let the react-admin resolve his material dependencies... that worked for me

**Comment by rohan-techahead** [comment] 2021-11-01 19:13
> @rohan-techahead i removed all material-ui from my package.json and let the react-admin resolve his material dependencies... that worked for me

What if I am using material-ui for other purposes as well?

**Comment by djhi** [comment] 2021-11-02 07:58
Well, I just tried the following steps:

```
npx create-react-app test
cd test
npm i react-admin ra-data-fakerest @material-ui/core@4.11.4
```

Then updated the `App.js` file like this:

```jsx
import { Admin } from "react-admin";
import dataProvider from "ra-data-fakerest";

function App() {
  return <Admin dataProvider={dataProvider({})} />;
}

export default App;
```

And I still can't reproduce the issue.

**Comment by rohan-techahead** [comment] 2021-11-02 08:16
@djhi I followed the same step as you and recreated a new app and please look what I got in terminal
![Capturenew](https://user-images.githubusercontent.com/80825511/139810052-675de9dc-fbaa-403e-9ef1-8560ee40a5fc.PNG)

**Comment by djhi** [comment] 2021-11-02 08:19
I believe you but until I can't reproduce it, I can't fix it

**Comment by rohan-techahead** [comment] 2021-11-02 08:20
@djhi What should I do in this case, please suggest.

**Comment by djhi** [comment] 2021-11-02 08:21
Set up a public repo I could use to investigate?

**Comment by rohan-techahead** [comment] 2021-11-02 09:48
@djhi I tried this on codesandbox, and there is no error there as somehow it is resolving the dependency at their end. But once you do these setups in your local it breaks. I double checked in my team members system as well and it is breaking there too. I request you to please install it locally to see the error.

**Comment by djhi** [comment] 2021-11-02 09:50
I did and couldn't reproduce

**Comment by rohan-techahead** [comment] 2021-11-02 11:45
Hi @djhi 
here is the public repo, https://github.com/rohan-techahead/react-admin

**Comment by rohan-techahead** [comment] 2021-11-03 07:53
Hi @djhi, are you being able to reproduce the bug from above provided repo now? If not, kindly let me know.

**Comment by rohan-techahead** [comment] 2021-11-08 05:50
Hi @djhi, I have already shared the repo above, kindly revert back if or if not you are being able to reproduce it, Our project is getting hampered due to this. Need your assistant ASAP. Thanks

**Comment by fzaninotto** [comment] 2021-11-08 10:54
I'm reopening the issue to let @djhi give it a try.

**Comment by djhi** [comment] 2021-11-08 11:13
I just cloned the repo, ran `npm install` and `npm start` and it seems to work fine. Maybe it's related to the version of npm you're using? What is it?

**Comment by rohan-techahead** [comment] 2021-11-08 11:23
Hi @djhi  I am using node version v14.17.2

**Comment by terox** [comment] 2021-11-09 10:04
Hello!
After upgraded react-admin 3.18 to 3.19 (also ra-data-simple-rest and ra-i18n-polyglot are updated to 3.19) I am receiving that message:

>  "./node_modules/ra-ui-materialui/esm/layout/DeviceTestWrapper.js Attempted import error: 'createTheme' is not exported from '@material-ui/core/styles' ".

I downgraded the packages but the problem persist.... thats annoying.

**Comment by djhi** [comment] 2021-11-09 10:12
Thanks @rohan-techahead, 

I tried again from a clean clone of your repository, this time using node `v14.17.6` and npm `v6.14.15`. I'm still unable to reproduce the issue. Have you tried deleting your `node_modules` directory and installing again?

**Comment by rohan-techahead** [comment] 2021-11-09 10:19
Hi @djhi , Actually I just a found the problem, I think it is happening due to typescript version. The older typescript version below 4 seems not to be compatible with react-admin newer version. When I updated my typescript version, after few fixes it seems to be working for me now. Running few more test to be sure that it is not breaking. But the it is an issue, so please test compatibility issue with typescript older version like <4 or so. Thanks

**Comment by terox** [comment] 2021-11-09 10:24
@rohan-techahead what version of typescript are using? I'm using the 4.4.4

**Comment by rohan-techahead** [comment] 2021-11-09 10:25
@djhi 
"react": "^16.13.1",
"typescript": "~3.8",

**Comment by rohan-techahead** [comment] 2021-11-09 10:30
@terox If you are using material-ui then you have to use  4.12.1 version with react-admin. I downgraded from v4.12.3 to 4.12.1.

**Comment by terox** [comment] 2021-11-09 10:33
After update typescript package from ^4.4.4 to ~3.8 and the same version of react, for me, the issue persists.

@rohan-techahead as you say, I think that it is related with the package version of material-ui. I haven't included directly in my package.json, but I have same library that it is directly related. May be it is requesting that version.

I test it now and I will write the feedback

**Comment by terox** [comment] 2021-11-09 11:04
I can confirm that after include the package **"@material-ui/core": "4.12.1"** the issue is fixed. But it is only a patch, I understand that it is so

Thank you

**Comment by ENGR-MANSOOR** [comment] 2022-07-15 09:44
The problem still persist while dockerizing the react-admin  app

**Comment by mytharcher** [comment] 2022-10-04 05:14
I also got this error after upgraded both `react-admin` and `ra-ui-materialui` to `4.4.0`, and changed `@material-ui/core` 
to `@mui/material@5.10.8`:

```
ERROR in ./node_modules/ra-input-rich-text/dist/esm/RichTextInput.js 30:0-60
Module not found: Error: Can't resolve 'ra-ui-materialui' in '.../node_modules/ra-input-rich-text/dist/esm'

ERROR in ./node_modules/ra-input-rich-text/dist/esm/buttons/ColorButtons.js 20:0-44
Module not found: Error: Can't resolve 'ra-ui-materialui' in '.../node_modules/ra-input-rich-text/dist/esm/buttons'
```

And I found `ra-core` and `ra-ui-materialui` are peerDependencies in package `ra-input-rich-text`, not sure if this cause the errors.

**Comment by fzaninotto** [comment] 2022-10-04 05:28
I'm closing this issue as we never managed to reproduce the problem and it's almost one year old.

**Closed by fzaninotto** 2022-10-04 05:28 UTC
