### ISSUE TITLE
react-admin2.6 display error title

### ISSUE THREAD

**Issue by ethluz** [marmelab/react-admin#3268] opened 2019-05-23 02:35 UTC
![image](https://user-images.githubusercontent.com/1680814/58221639-e59d0880-7d45-11e9-9679-61b2e205bd54.png)

![image](https://user-images.githubusercontent.com/1680814/58221504-542d9680-7d45-11e9-9bce-99ddf2a5c7e7.png)

Environment

React-admin version: 2.6.0
React version: 16.7.0

**Comment by djhi** [comment] 2019-05-23 04:22
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment] 2019-05-23 06:11
Can you check if upgrading to 2.9 fixes the issue? I think this was fixed in the last months.

**Comment by fzaninotto** [comment] 2019-05-23 06:11
Also, try deleting your node_modules and reinstalling.

**Comment by jamescremona-highlight** [comment] 2019-05-24 09:49
I have the same problem after updating to the latest version. Tried to remove node_modues and re-installing but to no avail
![image](https://user-images.githubusercontent.com/43636604/58319311-f4ed8600-7e19-11e9-9444-d78a6bae0fd9.png)

**Comment by Kmaschta** [comment] 2019-05-24 11:59
I have hard time reproducing this one...

@jamescremona-highlight did you managed to reproduce it in a CodeSandbox (as requested above https://github.com/marmelab/react-admin/issues/3268#issuecomment-495061940) ?
That would be really useful.

**Comment by fzaninotto** [comment] 2019-05-24 20:52
it seems to be a duplicate of #3007

**Comment by fzaninotto** [comment] 2019-05-28 08:43
Closed as duplicate.

**Closed by fzaninotto** 2019-05-28 08:43 UTC
