### ISSUE TITLE
ReferenceInput with ra-data-graphql-simple not working in v3.0.

### ISSUE THREAD

**Issue by wmwart** [marmelab/react-admin#3999] opened 2019-11-18 10:00 UTC
**What you were expecting:**
ReferenceInput value 

**What happened instead:**
Request Error

**Steps to reproduce:**
1) Add a ReferenceInput to the Edit form as in the documentation.
2) get an request Error

**Related code:**
```
 <SimpleForm>
...
                <ReferenceInput source="type" reference="GasMeterType" >
                    <AutocompleteInput optionText="name" />
                </ReferenceInput>
 ...       
</SimpleForm>
```

```
{operationName: "allGasMeterTypes", variables: {filter: {ids: [{id: "ck2onynbn01tl0768ec3yl09z"}]}},…}
operationName: "allGasMeterTypes"
query: "query allGasMeterTypes($filter: GasMeterTypeFilter) {↵  items: allGasMeterTypes(filter: $filter) {↵    id↵    name↵    description↵    alias↵    createdAt↵    createdBy {↵      id↵      authId↵      login↵      email↵      phone↵      name↵      online↵      blocked↵      deleted↵      updatedAt↵      createdAt↵      searchIndex↵      __typename↵    }↵    updatedAt↵    deleted↵    searchIndex↵    __typename↵  }↵  total: _allGasMeterTypesMeta(filter: $filter) {↵    count↵    __typename↵  }↵}↵"
variables: {filter: {ids: [{id: "ck2onynbn01tl0768ec3yl09z"}]}}
    filter: {ids: [{id: "ck2onynbn01tl0768ec3yl09z"}]}
        ids: [{id: "ck2onynbn01tl0768ec3yl09z"}]
            0: {id: "ck2onynbn01tl0768ec3yl09z"}
                id: "ck2onynbn01tl0768ec3yl09z"
```

`message: "Variable "$filter" got invalid value { ids: [[Object]] }; Expected type ID at value.ids[0]; ID cannot represent value: { id: "ck2onynbn01tl0768ec3yl09z" }"`

**Other information:**

The problem is either in the Final-form or in buildVariables.js. 
You can solve it by changing buildVariables.js, but there was no error with the same code in RA v2.0. I'm not sure what to fix this buildVariables.js correctly.

Moreover, everything works in the `<Create />` `SimpleForm`, an error appears in the `<Edit />` `SimpleForm`.

* React-admin version: 3.0.0-beta.6
* RA-data-graphql-simple version: 3.0.0-beta.6

**Comment by ThieryMichel** [comment] 2020-01-02 12:53
linked to #4231

**Comment by fzaninotto** [comment] 2020-01-03 16:12
@ThieryMichel is it fixed now that #4237 is merged?

**Comment by ThieryMichel** [comment] 2020-01-06 08:29
Now I can investigate with the working demo.

**Comment by ThieryMichel** [comment] 2020-01-06 08:57
Reproduced by adding filter props to ReferenceInput.
Does not happen anymore since 3.0.0.
Please update your version.

**Closed by ThieryMichel** 2020-01-06 08:57 UTC
