### ISSUE TITLE
CustomApp  - admin.resources state disappearing on load

### ISSUE THREAD

**Issue by dgkm** [marmelab/react-admin#3405] opened 2019-07-12 00:46 UTC
**What you were expecting:**
Trying to integrate react-admin with a custom material-ui sample appliction.  The React-admin has configured with configureStore including the resource registration as follows:
e.g.,
```
    <MuiThemeProvider theme={theme}>
        <Resource name="customers" context="registration" />
        ...
```

Expecting to load the page as per the Route configuration without any issues
e.g., 

```
          { /* Admin Dashboard */ }
          <Route exact path="/app/admin" component={AdminDashboard} />
```

```
          { /* customers */ }
          <Route exact path="/app/admin/customers" render={(routeProps) => { return (<visitors.list hasCreate hasEdit hasList hasShow basePath="/app/admin/customers" resource="customers" {...routeProps} />);}} />

` 
```

**What happened instead:**

The admin dashboard is loading successfully at /app/admin configured above using Route configuration as it is using the dataProviderFactory directly instead of the redux

```
      dataProviderFactory('rest').then(
        dataProvider => {

```
When calling pages having List Controls based on Redux, firstly all the resources registered in the store such as admin.resources are disappering and throwing the following error:

```
Uncaught TypeError: Cannot read property 'resources' of undefined
    at Function.mapStateToProps [as mapToProps] (ListController.js:380)
    at mapToPropsProxy (wrapMapToProps.js:54)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:63)
    at mapToPropsProxy (wrapMapToProps.js:54)
    at handleFirstCall (selectorFactory.js:37)
    at pureFinalPropsSelector (selectorFactory.js:85)
    at Object.runComponentSelector [as run] (connectAdvanced.js:43)
    at Connect.initSelector (connectAdvanced.js:195)
    at new Connect (connectAdvanced.js:136)
    at constructClassInstance (react-dom.development.js:11447)`
```

**Steps to reproduce:**

> Integrated React-admin demo application with a Material-UI theme sample following the CustomApp documentation.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 2.9.4
* Last version that did not exhibit the issue (if applicable):
* React version: 16.4.1
* Browser: Chrome
* Stack trace (in case of a JS error):

> Uncaught TypeError: Cannot read property 'resources' of undefined
>     at Function.mapStateToProps [as mapToProps] (ListController.js:380)
>     at mapToPropsProxy (wrapMapToProps.js:54)
>     at Function.detectFactoryAndVerify (wrapMapToProps.js:63)
>     at mapToPropsProxy (wrapMapToProps.js:54)
>     at handleFirstCall (selectorFactory.js:37)
>     at pureFinalPropsSelector (selectorFactory.js:85)
>     at Object.runComponentSelector [as run] (connectAdvanced.js:43)
>     at Connect.initSelector (connectAdvanced.js:195)
>     at new Connect (connectAdvanced.js:136)
>     at constructClassInstance (react-dom.development.js:11447)

**Comment by djhi** [comment] 2019-07-12 07:38
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)
* A sample application via GitHub

**Comment by dgkm** [comment] 2019-09-02 16:19
Do you have a working sample integrated using CustomApp documentation?

**Comment by djhi** [comment] 2019-09-02 16:29
Nope, you'll have to create it from scratch on codesandbox

**Comment by fzaninotto** [comment] 2019-11-07 19:23
No news for some time, and we can't reproduce it, so I have to close it.

**Closed by fzaninotto** 2019-11-07 19:23 UTC
Labels: awaiting more info
