### ISSUE TITLE
Profile page refreshing throws an error after updating to 3.6.2

### ISSUE THREAD

**Issue by hardrese7** [marmelab/react-admin#4991] opened 2020-06-29 11:42 UTC
I updated to 3.6.2, created a profile page like it's described [here](https://marmelab.com/blog/2019/03/07/react-admin-advanced-recipes-user-profile.html).

**What you were expecting:**
Refreshing of the profile page works correctly

**What happened instead:**
Refreshing of the profile page throws: 
```
No <Resource> defined for "profile". useGetOne() relies on the Redux store, so it cannot work if you don't include a <Resource>.
```

**Steps to reproduce:**
1. Update your react-admin to 3.6.2
2. Create a profile page as described [here](https://marmelab.com/blog/2019/03/07/react-admin-advanced-recipes-user-profile.html) 
3. Update this page

**Related code:**
I forked your example from the article and updated react-admin.
[demo](https://99cb9.csb.app/#/my-profile) 
[sandbox](https://codesandbox.io/s/react-admin-advanced-recipes-user-profileconfiguration-99cb9?fontsize=14&hidenavigation=1&theme=dark)

**Environment**

* React-admin version: 3.6.2
* Last version that did not exhibit the issue (if applicable): 3.5.3
* React version: 16.13.1
* Browser: Chrome 83
* Stack trace (in case of a JS error):
```
eval
https://99cb9.csb.app/node_modules/ra-core/esm/dataProvider/useGetOne.js:16:13
useSelectorWithStoreAndSubscription
https://99cb9.csb.app/node_modules/react-redux/es/hooks/useSelector.js:27:23
useSelector
https://99cb9.csb.app/node_modules/react-redux/es/hooks/useSelector.js:79:12
useQueryWithStore
https://99cb9.csb.app/node_modules/ra-core/esm/dataProvider/useQueryWithStore.js:65:47
useGetOne
https://99cb9.csb.app/node_modules/ra-core/esm/dataProvider/useGetOne.js:8:40
useEditController
https://99cb9.csb.app/node_modules/ra-core/esm/controller/useEditController.js:32:45
Edit
https://99cb9.csb.app/node_modules/ra-ui-materialui/esm/detail/Edit.js:41:95
renderWithHooks
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14803:18
mountIndeterminateComponent
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17482:13
beginWork
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:18596:16
HTMLUnknownElement.callCallback
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:188:14
Object.invokeGuardedCallbackDev
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:237:16
invokeGuardedCallback
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:292:31
beginWork$1
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23203:7
performUnitOfWork
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22154:12
workLoopSync
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22130:22
performSyncWorkOnRoot
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21756:9
scheduleUpdateOnFiber
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21188:7
updateContainer
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24373:3
eval
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24758:7
unbatchedUpdates
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21903:12
legacyRenderSubtreeIntoContainer
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24757:5
Object.render
https://99cb9.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24840:10
```

**Comment by djhi** [comment] 2020-06-29 12:07
Thanks! Closing as duplicate of #4985 though

**Closed by djhi** 2020-06-29 12:07 UTC
