### ISSUE TITLE
Always redirecting to first page in the list

### ISSUE THREAD

**Issue by appsdevpk** [marmelab/react-admin#7238] opened 2022-02-14 22:24 UTC
**What you were expecting:**
When clicking on any page number in list pagination, that respective page should open

**What happened instead:**
It always redirects to first page.

**Steps to reproduce:**
Create multiple admin components for different purposes, everything will work fine until you click on a page number greater than one. Below is the main app component, here i am using react-admin in three routes
/admin
/employee-dashboard
/client-dashboard

**Related code:**

```
<Router>
<Switch>
	<Route exact path="/" component={Home} />
	<Route exact path="/admin" component={AdminApp} />
	<Route path="/employee-signup" component={EmployeeCreate} />
	<Route path="/employee-dashboard" component={EmployeeApp} />
	<Route path="/client-dashboard" component={ClientApp} />
	<Route path="/job-apply" component={JobApplyForm} />
	<Route path="/news" component={NewsPage} />
</Switch>
</Router>
```

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.19.0
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: firefox
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2022-02-15 07:12
Hi,

The bug you describe doesn't occur in [the simple example CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple). So the problem probably lies on your side (I suspect your dataProvider returns no result for pages other than 1).  

If you are sure this is a bug on the react-admin side, please provide a link to a reproduction, e.g. based on the CodeSandbox I linked above. The code samples you provided aren't enough to investigate further.

**Comment by appsdevpk** [comment] 2022-02-15 13:26
here is the demo. https://codesandbox.io/s/modern-sun-ccs8x?file=/src/index.tsx

**Comment by fzaninotto** [comment] 2022-02-15 13:58
React-admin v3 doesn't support being mounted as a descendent of an existing Router without sharing the `history` (otherwise, react-admin creates its own Router). This is somehow explained in the https://marmelab.com/react-admin/CustomApp.html chapter. 

Note that this should work seamlessly in react-admin v4.

**Comment by WiXSL** [comment] 2022-02-22 17:37
Since this has been addressed, I'm closing this issue

**Closed by WiXSL** 2022-02-22 17:37 UTC
Labels: needs more info
