### ISSUE TITLE
Choices getting bold in AutocompleteInput

### ISSUE THREAD

**Issue by AnubhavMukhija7** [marmelab/react-admin#6907] opened 2021-11-26 13:01 UTC
**What you were expecting:**

To display options in AutocompleteInput without the text getting bold.

**What happened instead:**

Sometimes the second word in the choice gets bold.

**Steps to reproduce:**

Choose sales admin -> change to office admin -> from the remaining options, the second word will become bold from now on.

**Related code:**

```
<AutocompleteInput validate={[required()]} source="roles" choices={ADMIN_ROLES} />
const ADMIN_ROLES = [
  { id: "rep", name: "Sales Representative" },
  { id: "office", name: "Office Admin" },
  { id: "corp", name: "Corporate Admin" },
];
```

**Other information:**

Have attached the screen shot for the same. From now on the word "admin" will remain bold in the options menu.
![Screenshot from 2021-11-26 18-07-56](https://user-images.githubusercontent.com/77374757/143584750-93ab6467-3623-44f6-a86c-841c40d2d525.png) same thing is happening while editing.

**Environment**

* React-admin version: 3.18.3
* React version: 17.0.2
* Browser: Chrome

**Comment by fzaninotto** [comment] 2021-12-22 09:23
By design, we highlight the part that matches the text entered by the end user in the input. I understand that you didn't type anything but selecetd the option with the mouse, is that so?

Could you please link to a repro by forking the react-admin CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by WiXSL** [comment] 2022-01-28 11:28
No news for some time.
I'm closing this issue.
Please, feel free to re-open it if you can provide a way to reproduce this behavior.

**Closed by WiXSL** 2022-01-28 11:28 UTC
Labels: needs more info
