### ISSUE TITLE
useUnselectAll has no effect

### ISSUE THREAD

**Issue by dylanlt** [marmelab/react-admin#8233] opened 2022-10-05 00:53 UTC
**What you were expecting:**
useUnselectAll() clears the count of selected items in the top bar of a data grid and unselects the check box in each row of the data grid.

**What happened instead:**
The notification appears but the rows remain selected and the counter is not reset to zero.

**Steps to reproduce:**
Select a few posts and click "RESET VIEWS". Note that this code has a success handler with a notification and useUnselectAll(). This also happens with row deletion, where the count and selectedId array remain unchanged even though the items are deleted.

**Related code:**
https://codesandbox.io/s/peaceful-darwin-6400pm?file=/src/posts/ResetViewsButton.tsx

**Environment**

* React-admin version: 4.4.0
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2022-10-05 04:13
I can't reproduce the problem you describe in the codesandbox you linked. When clicking "reset views" or "delete", the action works properly, the rows are deselected, and the counter is reset to zero.

**Comment by dylanlt** [comment] 2022-10-09 22:31
I noticed that in the sandbox it initially worked and then later it didn't. I tried restarting the server but the bug persisted. The code in the forked sandbox is also identical to the original. I don't know how I can investigate this further. Is there a workaround I can use in the meanwhile?

**Comment by fzaninotto** [comment] 2022-10-10 07:35
If you can't provide a reproduction, we can't provide a fix...

**Comment by dylanlt** [comment] 2022-10-10 23:56
Okay, I found it. Replace <List> with <ListView> and the record selection is empty, ergo the records cannot be unselected. I don't know if this is by design or not, but it's a simple fix to replace the <ListView> with <List>.

**Comment by dylanlt** [comment] 2022-11-01 04:16
Here is the[code sandbox](https://codesandbox.io/s/green-firefly-1ob9kz?file=/src/data.tsx) replication of the problem with a simple delete on 4.4.4. Delete an item and you see "1 item selected" remains. Select another item (so only 1 is selected) and now it shows "2 items selected" and the API call fails in the real world because one of the items is already deleted. This issue has now been found in several data grids in the app. My first question is, is it necessary to always use unSelectAll now? If not, then this would be a bug.

**Comment by WiXSL** [comment] 2022-11-01 11:05
`... Delete an item and you see "1 item selected" remains. ...`
If you are talking about the `Post` List component, I can't reproduce this behavior on your code sandbox.

**Comment by dylanlt** [comment] 2022-11-15 01:14
It's in the comments tab. Try this: https://1ob9kz.sse.codesandbox.io/#/posts/9/3 

Delete a comment, and notice that the message in the top bar is unchanged. unSelectAll also doesn't resolve the issue. Select another comment, now "2 items selected" shows. Clicking delete now causes an error because one of the items has already been deleted.

**Comment by fzaninotto** [comment] 2022-11-15 09:13
@dylanlt This has been fixed in #8358, released in 4.5.1. I can't reproduce the problem you describe on master.

**Comment by fzaninotto** [comment] 2022-12-01 17:46
No news for some time, closing.

**Closed by fzaninotto** 2022-12-01 17:46 UTC
Labels: needs more info
