### ISSUE TITLE
ReferenceArrayInput + AutocompleteArrayInput doesn't show selected values when options don't include selections

### ISSUE THREAD

**Issue by jonamax2** [marmelab/react-admin#10170] opened 2024-08-28 15:14 UTC
**What you were expecting:**

The (Reference/Autocomplete)ArrayInput to display chips with the selected values regardless if those values are within the available options or not.

**What happened instead:**

The values displayed in chip format are not visibly shown until you search for them.

**Steps to reproduce:**

1. Have a reference input with options fetched remotely
2. Select a value from a search result that isn't in the initial set of options
3. Change the options to make sure the selected value isn't listed among them

**Related code:**

The Component's code is very straight forward
```
   <DefaultReferenceArrayInput
      clearOnBlur={false}
      clearOnEscape={false}
      {...restProps}
    >
      <AutocompleteArrayInput {...props} />
    </DefaultReferenceArrayInput>
```

**Other information:**

Here is a recording of the issue
[ReferenceInputBug.webm](https://github.com/user-attachments/assets/cbef2040-637f-4f09-b319-21bed6771b95)

**Environment**

* React-admin version: 4.9.3
* React version: 18
* Browser: any

**Comment by slax57** [comment] 2024-08-29 12:58
Thank you for your report.

Can you please help us reproduce the issue by providing a reproduction sandbox? You can fork this one for a react-admin v4 example: https://stackblitz.com/github/marmelab/react-admin/tree/4.x/examples/simple

Also, I see you are not using the latest v4.x version. Can you please try to upgrade to the latest version to see if the issue persists?

Thanks.

**Comment by jonamax2** [comment] 2024-08-30 07:10
Hello @slax57.

I've created a [forked version](https://stackblitz.com/edit/github-dajzdh?file=src%2Fcomments%2FCommentEdit.tsx%3AL135) as requested and updated the form on the comments resource to include a reference array input.

As for the version update recommendation, i was able to reproduce the issue to some extend on the sandbox as well and the version referenced in the package.json is `"react-admin": "^4.16.20",` so i'm not sure if that will be of much help.

The issue on the sandbox is a tad different however, the values seem to disappear when there are no options resulting from a search (searching random text "aasdadsgf" should do the trick) rather than when they aren't included on the listing, atleast that's what i observed.

Hope this info helps, Thanks.

**Comment by slax57** [comment] 2024-08-30 08:34
@jonamax2 Thank you for the additional information.

I tried the sandbox you provided, but did not manage to reproduce the issue in it.

It is necessary for us to have a deterministic reproduction scenario. Values that 'seem to disappear sometimes' are not enough, and probably the reason I can't reproduce.

Also, I noticed that:
- Your `package.json` file still contains `"react-admin": "^4.9.3"` instead of `"react-admin": "^4.16.20"`
- The `post_id` values in the `data.tsx` file are still numbers, instead of an array of numbers (since you are now using a `ReferenceArrayInput`)

Can you please fix those issues in your sandbox, and provide a deterministic reproduction scenario?

Thanks.

**Comment by jonamax2** [comment] 2024-08-30 13:52
I made the version change to check if behavior inside the sandbox and forgot to change it back that's my bad, but changing it back and also changing post ids in the mock data made no difference to the overall outcome. 

I was unable to reproduce the bug within the sandbox environment and as i mentioned before the reference array input we encountered this bug on was a bare bone implementation, similar to what i added in the sandbox.

The only difference between the sandbox and my environment that i can guess is that the results are from a remote server for my instance.

This might not be enough information, but given circumstances it's all i can manage.

Thanks for the effort never the less.

**Comment by slax57** [comment] 2024-08-30 14:18
Ok I understand.

Unfortunately, If we're not able to reproduce, we won't be able to help fix the issue.

For this reason I'll close this issue.
If you manage to reproduce in a sandbox, or better understand under which circumstances the bug occurs, feel free to reopen it.
Thanks.

**Closed by slax57** 2024-08-30 14:18 UTC
Labels: needs more info
