### ISSUE TITLE
Infinite loop if initialValue is defined in a SelectArrayInput which is integrated in a formdataconsumer

### ISSUE THREAD

**Issue by nicodmf** [marmelab/react-admin#5593] opened 2020-11-26 14:15 UTC
**What you were expecting:**
Defined initial values for SelectArrayInput in a FormDataConsumer and have a working environment

**What happened instead:**
An infinite loop take place and stop application.

**Steps to reproduce:**
- Go to https://codesandbox.io/s/sweet-darkness-15q1m?file=/src/posts.js:1446-1462
- Open your browser inspector
- Go in the integrated browser to post/create 
- You should see "Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render." in the console
- Choose nom 2 in the first select
- You should see an infinite loop and real browser (firefox at least) ask to stop the process

**Related code:**
- Go to https://codesandbox.io/s/sweet-darkness-15q1m?file=/src/posts.js:1446-1462

```js
<SimpleForm>
      <FormDataConsumer>
        {({ formData, ...rest }) => {
          return (
            <SelectArrayInput
              label="User"
              source="userId"
              initialValue={[1]}
              choices={[
                { id: 1, name: "nom1" },
                { id: 2, name: "nom2" },
                { id: 3, name: "nom3" },
                { id: 4, name: "nom4" }
              ]}
            >
              <ChipField source="name" />
            </SelectArrayInput>
          );
        }}
      </FormDataConsumer>
      {/*...*/}
</SimpleForm>
```

**Other information:**

**Environment**

* React-admin version: 3.10.2
* React version: 17.0.1
* Browser: firefox & chrome tested
* Stack trace (in case of a JS error):

**Comment by etienne-bondot** [comment] 2020-11-26 23:27
I've tested you code, and fix it, this is working

```
 <Create {...props}>
    <SimpleForm>
      <SelectArrayInput
        label="User"
        source="userId"
        initialValue={[1]}
        choices={[
          { id: 1, name: "nom1" },
          { id: 2, name: "nom2" },
          { id: 3, name: "nom3" },
          { id: 4, name: "nom4" }
        ]}
      >
        <FormDataConsumer>
          {({ getSource, ...rest }) => <ChipField source={getSource("name")} />}
        </FormDataConsumer>
      </SelectArrayInput>
      <TextInput source="title" />
      <TextInput multiline source="body" />
    </SimpleForm>
  </Create>
```

See here https://codesandbox.io/s/condescending-hopper-31heb?file=/src/posts.js

**Comment by fzaninotto** [comment] 2020-11-27 17:15
Thanks @etienne-bondot !

**Comment by pflima92** [comment] 2021-01-29 19:56
Hi @etienne-bondot, the fix proposed does not seems to work when you do need to have the `SelectArrayInput` as a child of a `FormDataConsumer`,  e.g:
```javascript
<SimpleForm>
      <FormDataConsumer>
        {({ formData, ...rest }) => {

            formData.someValue ? <SelectArrayInput
              label="User"
              source="userId"
              initialValue={[1]}
              choices={[
                { id: 1, name: "nom1" },
                { id: 2, name: "nom2" },
                { id: 3, name: "nom3" },
                { id: 4, name: "nom4" }
              ]}
            >
              <ChipField source="name" />
            </SelectArrayInput> : null // or some other stuff
        }}
      </FormDataConsumer>
      {/*...*/}
</SimpleForm>
```

The brow will crash as described by @nicodmf

**Comment by Nunobpinto** [comment] 2021-06-28 15:00
I'm still experiencing this bug as well, why is it closed?

**Comment by djhi** [comment] 2021-06-28 15:27
@Nunobpinto Can you please provide a sandbox showing the issue ?

**Comment by djhi** [comment] 2021-06-28 15:28
Nevermind, the original sandbox still shows the issue indeed.

**Comment by razorsharpshady** [comment] 2022-01-17 20:21
@pflima92 Thank you for pointing out the **initialValue** part, It saved my day :)

**Comment by WiXSL** [comment] 2022-03-24 19:49
UPDATE: I can't reproduce this in version 4 anymore

**Comment by fzaninotto** [comment] 2024-07-02 08:31
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2024-07-02 08:31 UTC
Labels: bug, v3
