### ISSUE TITLE
Validation in FormDataConsumer is not updated (taking previous validation) when selected option is updated in SelectInput.

### ISSUE THREAD

**Issue by aishahsofea** [marmelab/react-admin#4434] opened 2020-02-20 08:21 UTC
**What you were expecting:**
I am expecting that validation will change according to the selected value in SelectInput dropdown.

**What happened instead:**
It validates against the previously selected value.

**Steps to reproduce:**
1. Create new comment. Click on Post SelectInput and a dropdown will appear. Select the last post (id = 1).
2. In the field right below Post, write 'abcde', and we'll get validation error 'max 1 char'
3. Now go back to Post and select the second last option (id = 2)
4. Notice that the validation error is still 'max 1 char'
5. Then, select last post (id = 1) again. Now we'll get validation error 'max 2 char' which is what we're supposed to get when selected id = 2.

**Related code:**
Code is in PostReferenceInput.js
I reproduced this issue in this [codesandbox](https://codesandbox.io/s/react-admin-advanced-recipes-quick-createpreview-3lx1c?fontsize=14&hidenavigation=1&theme=dark)

```
import * as React from 'react';
import { Field } from 'redux-form';
import { maxLength, required } from 'ra-core';
import {
    ReferenceInput,
    SelectInput,
    FormDataConsumer,
    LongTextInput
} from 'react-admin';

import PostQuickCreateButton from './PostQuickCreateButton';
import PostQuickPreviewButton from './PostQuickPreviewButton';

class PostReferenceInput extends React.Component {
    constructor(props) {
        super(props);
        this.renderValue = this.renderValue.bind(this);
        this.validate = this.validate.bind(this);
    }
    validate(type) {
        if (type === 1) {
            return maxLength(1, 'max 1 char');
        } else if (type === 2) {
            return maxLength(2, 'max 2 char');
        }
    }

    renderValue() {
        return (
            <FormDataConsumer>
                {({ formData, ...rest }) => {
                    const type = formData.post_id && formData.post_id;
                    console.log(type);

                    return (
                        <LongTextInput
                            source="ruleValue"
                            label={type}
                            validate={this.validate(type)}
                        />
                    );
                }}
            </FormDataConsumer>
        );
    }

    render() {
        return (
            <React.Fragment>
                <ReferenceInput {...this.props}>
                    <SelectInput optionText="id" />
                </ReferenceInput>
                {this.renderValue()}

                <PostQuickCreateButton />
                {/* We use Field to get the current value of the `post_id` field */}
                <Field
                    name="post_id"
                    component={({ input }) =>
                        input.value && (
                            <PostQuickPreviewButton id={input.value} />
                        )
                    }
                />
            </React.Fragment>
        );
    }
}

export default PostReferenceInput;

```

**Other information:**

**Environment**

* React-admin version: 2.8
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 16.3
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by JulienMattiussi** [comment] 2020-03-17 10:58
Reproduced
Same in v3
https://codesandbox.io/s/late-https-f2zce

**Comment by JulienMattiussi** [comment] 2020-03-17 11:17
I'm not sure we can do something for this.
Form validation is managed by react-final-form (or redux-form in v2).
It seems they both don't care that a change made on a field can trigger a dynamic validation error on another field.

I tryed using multi validation functions instead of a unique validation function having multl messages, but it doesn't change the behaviour

**Comment by aishahsofea** [comment] 2020-04-01 04:06
@JulienMattiussi is there any workaround (that probably ditches redux-form)?

**Comment by Rawphs** [comment] 2020-06-24 15:25
To circumvent this I am passing `validateOnBlur={true}` to the form, but that messed with my `ImageInput` validation because it never blurs. I guess it could help you if you don't have also an image in your form.

**Comment by duongthaicuong** [comment] 2022-02-25 07:41
I had same problem. 
And I prefer If you want to validate between multiple value.  
```
validate={[
        required(),
        minValue(),
        anyCustom,
]}

//value: value of current input
//allValues : all values of current form
const anyCustom = (value, allValues) => {
    if (...) {
     return errorMessage : string
    }
    return undefined
}
```

**Comment by fzaninotto** [comment] 2024-07-02 08:24
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2024-07-02 08:24 UTC
Labels: bug, v3
