### ISSUE TITLE
useQuery returns error after optimistic save

### ISSUE THREAD

**Issue by megantaylor** [marmelab/react-admin#6751] opened 2021-11-05 17:37 UTC
**What you were expecting:**

Fetch data with useQuery from inside Edit/Create components and correctly receive data.

**What happened instead:**

useQuery returns an error after save: `error TypeError: Cannot read properties of undefined (reading 'data')`.

**Steps to reproduce:**

I am trying to fetch data with useQuery from inside Edit/Create components. I have `redirect={false}` on the SaveButton so the form stays visible.

If `mutationMode={"undoable"}`, useQuery returns an error after save: `error TypeError: Cannot read properties of undefined (reading 'data')`.

**Related code:**

I tried to reproduce this in the CodeSandbox at https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple but I keep getting this error when it tries to compile:

```
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'proxy-polyfill/proxy.min.js' in '/sandbox/src'
 @ ./src/polyfills.ts 5:0-38
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8080 (webpack)/hot/dev-server.js ./src/polyfills.ts
 ```

I have reproduced this behavior in the react-admin demo app (pulled the repo and ran the demo locally) by changing `src/reviews/ReviewEditToolbar.tsx` like so:

```
import * as React from 'react';
import { Fragment } from 'react';
import MuiToolbar from '@material-ui/core/Toolbar';
import { makeStyles } from '@material-ui/core/styles';

import { SaveButton, DeleteButton, ToolbarProps } from 'react-admin';
import AcceptButton from './AcceptButton';
import RejectButton from './RejectButton';
import { Review } from '../types';
import { useQuery } from 'ra-core';

const useStyles = makeStyles(theme => ({
    root: {
        backgroundColor: theme.palette.background.paper,
        display: 'flex',
        justifyContent: 'space-between',
    },
}));

const ReviewEditToolbar = (props: ToolbarProps<Review>) => {
    const {
        basePath,
        handleSubmitWithRedirect,
        invalid,
        record,
        resource,
        saving,
    } = props;
    const classes = useStyles();

    const { data, loading, error } = useQuery({
        type: 'getMany',
        resource: 'categories',
        payload: { ids: [0] },
    });

    console.log('loading', loading);
    console.log('data', data);
    console.log('error', error);

    if (!record) return null;
    return (
        <MuiToolbar className={classes.root}>
            {record.status === 'pending' ? (
                <Fragment>
                    <AcceptButton record={record} />
                    <RejectButton record={record} />
                </Fragment>
            ) : (
                <Fragment>
                    <SaveButton
                        handleSubmitWithRedirect={handleSubmitWithRedirect}
                        invalid={invalid}
                        saving={saving}
                        redirect={false}
                        submitOnEnter={true}
                    />
                    <DeleteButton
                        basePath={basePath}
                        record={record}
                        resource={resource}
                    />
                </Fragment>
            )}
        </MuiToolbar>
    );
};

export default ReviewEditToolbar;
```

**Comment by djhi** [comment] 2021-11-09 11:16
Can you elaborate on your usecase? What are you trying to achieve? I tried the code you put in the demo without having any issue.

**Comment by megantaylor** [comment] 2021-11-09 17:23
I've updated my issue to follow the issue template. 

I tried to reproduce this in the CodeSandbox at https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple but I keep getting this error when it tries to compile:

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'proxy-polyfill/proxy.min.js' in '/sandbox/src'
 @ ./src/polyfills.ts 5:0-38
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8080 (webpack)/hot/dev-server.js ./src/polyfills.ts
 
I am able to reproduce the issue by running the demo from the repo locally. The error is visible in the browser devtools console.

**Comment by jasonlimantoro** [comment] 2021-11-18 01:08
also experienced this issue.

- `redirect={false}` on a `<SimpleForm />` component (rendered by `<Edit />`)
- `useQuery` returns the error

Error happens here on line 134

![image](https://user-images.githubusercontent.com/31163334/142332475-559952ea-b239-445f-9d71-7fc601e9047c.png)

**Comment by megantaylor** [comment] 2021-11-18 19:03
I made a codesandbox fork here: https://codesandbox.io/s/keen-snowflake-tmftd

The changes I made are in src/posts/PostEdit.tsx

To reproduce the error:

1. Click on a Post to go to Post Edit view
2. Make some change, click save
3. Wait for save to complete
4. Look in the console, you will see: `error TypeError: Cannot read properties of undefined (reading 'data')`

**Comment by megantaylor** [comment] 2021-12-08 22:50
any progress on this issue?

**Comment by JustMonk** [comment] 2021-12-24 06:57
same issue, but i used dataProviderProxy from `useDataProvider` hook (`useQuery` works the same, calling `useDataProvider` too)

**usecase**: my api entity has multiple relationships and complex formatting logic on userside. I need to fetch some data (in my List or Datagrid component) for processing this in `FunctionField`. Yeah i know about `ReferenceField` but it doesn't suit me because api return nested data structures with many-to-many relationships.

another example in codesandbox: https://codesandbox.io/s/usedataprovider-example-jb68p-jb68p
step to reproduce same as @megantaylor say

0. for simplicity list has "fetched value" col and succesfuly show fetched data
![image](https://user-images.githubusercontent.com/21010114/147323940-9b54f20e-6acf-44a3-bec0-2bc030cee629.png)

1. Click on any row for open edit form
2. Edit text field value and press save button
3. After redirect we have re-mount list and `dataProvider.getList` return undefined
![image](https://user-images.githubusercontent.com/21010114/147324767-ab4dd0b0-fc2e-41c9-adf6-d903931133dd.png)

**some notes**:
as already mentioned, the problem lies in the `mutationMode: 'optimistic' | 'undoable'`
if you push `REFRESH_VIEW` action, data will show as expected
![image](https://user-images.githubusercontent.com/21010114/147325477-3652124d-0127-4035-9dd1-10b740866dc1.png)


**workaround**:

- instead of `useQuery` and `useDataProvider` hooks you can call pure dataProvider object methods
`const dataProvider = useContext(DataProviderContext);` (from [docs](https://marmelab.com/react-admin/Actions.html#usedataprovider-hook))
- [specialized hooks](https://marmelab.com/react-admin/Actions.html#specialized-hooks) (useGetList, useUpdate, etc) works fine too
- disable optimistic mode by pass prop to Create/Edit components `<Edit mutationMode="pessimistic" {...props}>`

**Comment by fzaninotto** [comment] 2021-12-24 08:29
Reproduced, thanks for the codesandbox.

**Comment by jakedeg** [comment] 2022-06-24 20:24
Hi! Just wanted to check in on this. Is it fixed as part of v4? If not, any plan on addressing it soon?

**Comment by fzaninotto** [comment] 2024-07-02 08:32
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2024-07-02 08:32 UTC
Labels: bug, v3
