### ISSUE TITLE
Validator number() useless unless required() is also used

### ISSUE THREAD

**Issue by Oshgnacknak** [marmelab/react-admin#4862] opened 2020-05-27 11:19 UTC
**What you were expecting:**
Expected build-in number validation to only let something like `^[+-]?\d+$` pass through, and to show an error to the user for all inputs not matching re given regex.

**What happened instead:**
However, if the NumberInput is supplied with something like "0aaaaaaa", the value is accepted as `null`. A defaulValue was also specified but not used. Using a required validator as well catches the null value, but shows "required" instead of "wrong number format". Thus the number validator is useless unless the required validator is also used, but still not working as expected.

**Steps to reproduce:**
Any form with the number validator creates this issue:
```jsx
import { number } from 'react-admin';
 
const MyForm = () => (
   <SimpleForm>
        <NumberInput
            source="age"
            defaultValue="0"
            validate={[number()]} />
    </SimpleForm>
)
```
Submitting the form with age as "0aaaaa" sends the following to the server:
```json 
{
  "age":null
}
```
**Environment**

* React-admin version: 3.5.3
* React version: 16.13.1
* Browser: FireFox 76.0.1 (64-bit) (on archlinux)

**Edit**
As requested sample code is now available on [CodeSandox](https://codesandbox.io/s/withered-paper-e4c45). The number validator on the score field does not catch `123aaaa`. Furthermore, as said in the comment below in FireFox As can be typed into the score field. On Chromium they are ignored.

**Comment by fzaninotto** [comment] 2020-05-27 11:54
I can't reproduce this in the simple example (edit a post, switch to the Miscellaneous tab, edit the average note field) with or without the required validator. When I type '0aaa', only the 0 appears in the input (because it only accepts numbers). I suspect there is something else in your setup that causes the bug.  

If there is indeed a bug in react-admin, please modify the [simple example CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) to show it.

**Comment by Oshgnacknak** [comment] 2020-05-27 15:08
Thanks for the rapid reply, but sadly I think we found yet another bug: I tested to reproduce the previous bug  in chromium. As described by @fzaninotto in Chromium (`Version 81.0.4044.138 (Official Build) Arch Linux (64-bit)`) the NumberInput only accepts numbers from the keyboard. I typed the exact same in both FireFox and Chromium `123aaaa`, yet only in Chromium the As are ignored. This seems to be a bug deep within the NumberInput.

**Comment by fzaninotto** [comment] 2020-05-27 16:38
This is not a react-admin bug, this is how different browsers handle numeric inputs. There is nothing we can do about it.

**Comment by fzaninotto** [comment] 2020-05-27 16:55
I think the cause of the original bug you mention in Firefox is that the browser considers a non-number as a null value in a number input (instead of refusing it or showing a warning). The react-admin number validator doesn't see the value the user has entered, but null, the value passed by Firefox. 

So if your input isn't required, entering a non-numeric value will result in a null value.

There is nothing we can do about it as Firefox doesn't transmit the value. It's a Firefox bug/feature, there is numerous mentions of it (e.g. https://stackoverflow.com/questions/49923588/input-type-number-with-pattern-0-9-allows-letters-in-firefox). 

So I'll close this issue as a "wontfix". Thanks for the report anyway.

**Closed by fzaninotto** 2020-05-27 16:55 UTC
Labels: needs more info

**Comment by Oshgnacknak** [comment] 2020-05-27 17:06
Thanks for your time and effort nonetheless. 

For those who see this in the future, one can easily craft a "working" number validator like follows:
```js
import { number, required } from 'react-admin';
function MyNumberValidator(msg="Is not a number") {
  return [number(msg), required(msg)];
}
```
