### ISSUE TITLE
cannot run demos

### ISSUE THREAD

**Issue by markeastman** [marmelab/react-admin#4692] opened 2020-04-16 15:47 UTC
I cloned the master a few days ago and all worked ok. I then deleted my folder on disk as I made some changes to the examples which I wanted to discard. I cloned the master branch today and followed the instructions to run the simple example (which did work the other day). When I issue make install I now get :
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/include/node'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/src'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/deps/openssl/config'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/deps/openssl/openssl/include'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/deps/uv/include'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/deps/zlib'
clang: error: no such file or directory: '1/Library/Caches/node-gyp/13.12.0/deps/v8/include'
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/13.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command \"/usr/local/Cellar/node/13.12.0/bin/node\" \"/usr/local/Cellar/node/13.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/markeastman 1/Projects/github/react-admin/node_modules/fsevents
✨  Done in 91.96s.

I cannot run the examples at all now either. 

I am running on a MAC, running npm 6.14.4 but like i said above this worked fine the last couple of days it is just the new download that has failed.

**Comment by fzaninotto** [comment] 2020-04-16 16:09
I can't reproduce on Linux using node 12.16.1 (LTS) or 13.13.0 (current). The problem is likely on your side, or in a third-party package that was broken on MacOS. Nothing we can do on our side anyway, so I'm closing this issue.

**Closed by fzaninotto** 2020-04-16 16:09 UTC

**Comment by markeastman** [comment] 2020-04-16 16:14
Thanks for confirming that - I will investigate. Strange how it has worked for over a week. I then delete the folder re clone the project and now it fails.

**Comment by markeastman** [comment] 2020-04-17 15:31
When investigating I checked the home folder that react-admin had been extracted to and it was on a Mac with a space in the name of the root folder. I cloned the repo to another area on disk without the space in the name and all works fine now.

Sorry to have troubled you
