### ISSUE TITLE
Aggregate crudGetMatching requests from ReferenceInput

### ISSUE THREAD

**Issue by ronfogel** [marmelab/react-admin#2004] opened 2018-07-08 11:13 UTC
**Is your feature request related to a problem? Please describe.**
Browser is stuck (page load forever and after a while the "kill page" prompt appears)

**Describe the solution you'd like**
ArrayInput should aggregate all the needed requests and made only 1 request for each resource it uses with all the ids it uses and bind the data correctly.

**Describe alternatives you've considered**
Create a component that makes the above but not as generic as I would want it to be.

**Additional context**
Created a code sandbox to show my problem
https://r7jxw6748n.codesandbox.io/#/posts/1 (if you need to login, user: admin, password: password)
https://imgur.com/arni0wi

**Comment by fzaninotto** [comment] 2018-07-10 11:56
If I understand correctly, the problem isn't related to `ArrayInput`, it's related to `ReferenceInput`. Because you're using a `ReferenceInput` inside an `ArrayInput`, the list of possible values is fetched as many times as there are items in the array. 

So if I'm not mistaken, your feature request is of an aggregation of the `crudGetMatching` actions. If so, please update the title of this issue.

As for the pagination, it's already possible using the `perPage` prop (see [the `ReferenceInput` documentation](https://marmelab.com/react-admin/Inputs.html#referenceinput)).

**Comment by ronfogel** [comment] 2018-07-10 12:05
@fzaninotto I guess you are right about the first thing, but you didnt understand correctly my second thing.

Lets take my code sandbox as an example.
Lets say the post had 1000 comments, I wouldnt want to show all the 1000 comments (and make a request to get 1000 users) but instead I would like to have the option to show only CERTAIN amount of iterrations (lets say, 10) and so `crudGetMatching` will result in 10 users and I will have a pagination to see the next 10 comments and so on.

The pagination is related to the `ArrayInput` not to the `ReferenceInput`

**Comment by fzaninotto** [comment] 2018-07-10 16:53
Gotcha. So that's 2 different feature requests, both valid. Would you mind updating this one to cover only the request aggregation, and open a new one for ArrayInput pagination?

**Comment by ronfogel** [comment] 2018-07-11 06:51
Done. the second feature request may be found here: https://github.com/marmelab/react-admin/issues/2010

**Comment by fzaninotto** [comment] 2018-08-30 09:53
Fixed by #2060

**Closed by fzaninotto** 2018-08-30 09:53 UTC
Labels: enhancement

**Comment by LittleMeow** [comment] 2018-10-04 00:46
It was working for me on 2.3.0 and 2.3.1. However, after I upgrade the version to 2.3.2, this request accumulation in reference input within ArrayInput feature stopped working for me.. Do I have to include other things？
