### ISSUE TITLE
`useNotify` multiline does not work

### ISSUE THREAD

**Issue by evergreen-trading-systems** [marmelab/react-admin#7187] opened 2022-02-04 06:38 UTC
**What you were expecting:**
```notify(`Hello mate. It time to go.`,{multiLine:true,type:"info",autoHideDuration:50000,undoable:true})```js to print 

```
Hello mate.
It time to go.
```

**What happened instead:**
`Hello mate. It time to go.`

**Steps to reproduce:**
```notify(`Hello mate. It time to go.`,{multiLine:true,type:"info",autoHideDuration:50000,undoable:true})```

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: latest
* Browser: chrome
* Stack trace (in case of a JS error): none

**Comment by WiXSL** [comment] 2022-02-04 10:43
@evergreen-trading-systems, thanks for reporting this.
But this is not a bug. New lines imply having `\n` character in your message to identify new lines, not dots (`.`).
So I'm closing this issue. Feel free to re-open it if you find a way to reproduce it.

**Comment by evergreen-trading-systems** [comment] 2022-02-04 11:03
I am reopening. You say use `\n` but I did. I opened this issue expecting you to at least test it or point to a working example. `\n` does not work.

**Comment by WiXSL** [comment] 2022-02-04 11:31
Please, I'm just trying to help you. There is no need for that tone.

**Closed** 2022-02-04 13:00 UTC
Labels: bug
