### ISSUE TITLE
Selectinput component need a disable prop

### ISSUE THREAD

**Issue by vipzhicheng** [marmelab/react-admin#2459] opened 2018-10-22 16:11 UTC
In my case, I need <Selectinput /> disabled when editing， but I can't. I use <Selectinput> in ReferenceInput, I checked the source, but seems <Selectinput> can not be disabled, so I tried to change <Selectinput> to <DisabledInput>, but also seems not work.

In my opinion, all basic component need a disabled or readonly prop in special use case, and I think it's best to implement it in react-admin not using hack way.

I already implement the effect using  a simple custom component, so it's just a suggestion.

**Comment by fzaninotto** [comment] 2018-10-22 17:39
Did you try setting `options={{ disabled: true }}`?

**Comment by fzaninotto** [comment] 2018-10-22 17:45
Correction: the `disabled` prop already works, no need for `options`.

```jsx
<SelectInput source="foo" disabled />
```

As I can't reproduce your issue, I'm closing it. Feel free to reopen if you can provide a CodeSandbox reproducing the issue.

**Closed by fzaninotto** 2018-10-22 17:45 UTC
