### ISSUE TITLE
Failed to compile the code from setUp tutorial

### ISSUE THREAD

**Issue by Smedzlatko** [marmelab/react-admin#2194] opened 2018-08-22 08:36 UTC
**What you were expecting:**
I was following the official tutorial for setting up the application: [tutorial](https://marmelab.com/react-admin/Tutorial.html).

**What happened instead:**
During the second step (replacing `App.js` content): 
```
import React from 'react';
import { Admin, Resource } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';

const dataProvider = jsonServerProvider('http://jsonplaceholder.typicode.com');
const App = () => <Admin dataProvider={dataProvider} />;

export default App;
```

I got the following exception:
```
./node_modules/@material-ui/icons/LockOutline.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/interopRequireDefault' in '/home/smajl/Software/test-admin/node_modules/@material-ui/icons'
```

**Steps to reproduce:**
Follow the tutorial step by step until the error occurs. I did not do any other modifications.

**Environment**
Ubuntu 18.04 with npm and yarn installed.

* React-admin version: ^2.2.0
* React version: ^16.4.2
* Browser: Chromium
* Stack trace (in case of a JS error):

```
Starting the development server...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/smajl/Software/test-admin/public ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/smajl/Software/test-admin/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
```

**Comment by djhi** [comment] 2018-08-22 08:47
Duplicate of #2183. See this issue for a workaround

**Closed by djhi** 2018-08-22 08:47 UTC

**Comment by Smedzlatko** [comment] 2018-08-22 08:54
HI, thanks for the link. The material-ui/icons are not defined in the package.json. Am I supposed to change them in the yarn.lock?

**Comment by djhi** [comment] 2018-08-22 08:54
Just add it as a dependency to your own package.json
