### ISSUE TITLE
Custom routes without auth doesn't work after add permissions to resources

### ISSUE THREAD

**Issue by ackalhan** [marmelab/react-admin#4821] opened 2020-05-17 17:17 UTC
**What you were expecting:**
I have few custom routes for forget password and reset password after i update permissions for the resources iam expecting those two pages are working as before 

**What happened instead:**
once i click on forget pwd link it will redirect to the login page

**Steps to reproduce:**

**Related code:**
![image](https://user-images.githubusercontent.com/7387018/82155150-62e35680-9890-11ea-84c1-2762ce066ccf.png)

**Comment by fzaninotto** [comment] 2020-05-18 06:04
I believe that's because your route contains the string '/login'. Try using a route path without that string.

**Comment by ackalhan** [comment] 2020-05-18 09:25
I have tried by putting 
![image](https://user-images.githubusercontent.com/7387018/82196185-05deb380-9917-11ea-920c-d636f0365a32.png)

but still the same issue happens
anyway i have figured it out, that because on each route change `getPermissions` and `checkAuth` is calling in authProvider, since i don't have the token and the permission at that time it will reject the promise and that will redirect it back to the login

So i have check the window.location.hash is related to non-auth route then i have resolved the promise

![image](https://user-images.githubusercontent.com/7387018/82196580-81406500-9917-11ea-939b-d2c4f75a2f8a.png)

It's better if there's a way to define non auth routes like login page

**Comment by fzaninotto** [comment] 2020-05-18 09:54
React-admin should not call `checkAuth` on custom routes. You're likely doing it yourself in your `ForgotPassword` and `ResetPassword` components.

Anyway, since the problem is solved on your side, I'm closing this issue.

**Closed by fzaninotto** 2020-05-18 09:54 UTC
Labels: needs more info

**Comment by ackalhan** [comment] 2020-05-18 10:03
@fzaninotto i guess no because it was working well until i add the permission to resources

**Comment by alextaymx** [comment] 2020-11-11 11:25
Hi there, I am having the same issue, custom pages are protected by auth provider, i couldn't proceed to other pages without log in, also after configuring getPermission method in authProvider

**Comment by dioris-moreno** [comment] 2024-10-15 18:41
If somebody has this problem in 2024, the issue could be how you link your custom pages. As stated in the documentation, you have to link your custom pages using react-router’s Link component. 

From [Linking To Custom Routes](https://marmelab.com/react-admin/CustomRoutes.html#linking-to-custom-routes)

`
import { Link as RouterLink } from 'react-router-dom';
import { Link } from '@mui/material';

const SettingsButton = () => (
    <Link component={RouterLink} to="/settings">
        Settings
    </Link>
);
`
