### ISSUE TITLE
Laggy form with validator are included in a FormDataConsumer

### ISSUE THREAD

**Issue by gearFifth** [marmelab/react-admin#6102] opened 2021-03-31 07:32 UTC
When a validator is included in a form with at least 10-15 fields the form gets painfully slow.

**Steps to reproduce:**
please use the form component below to reproduce the issue.

```
import * as React from 'react';
import { useState } from 'react';
import {
  TextInput,
  NumberInput,
  required,
  DateInput,
  FormDataConsumer,
  SelectInput,
  ReferenceInput,
  AutocompleteInput,
  useGetOne,
  ImageInput,
  ImageField,
} from 'react-admin';
import { useFormState } from 'react-final-form';

import { Typography, Box } from '@material-ui/core';
import { makeStyles, Theme } from '@material-ui/core/styles';
import { Styles } from '@material-ui/styles/withStyles';
import axios from 'axios';
import CarLocationInput from './CarLocationInput';
import CarStatusInput from './CarStatusInput';
import { ApiModels } from '../types';
import { CarLocation, CarStatus } from './types';

export const styles: Styles<Theme, any> = {
  input: { display: 'inline-block', marginRight: 32, width: 200 },
};

const useStyles = makeStyles(styles);

export const CarsForm = (props: any) => {
  const classes = useStyles(props);
  const { values } = useFormState();
  const [initialStatus] = useState(values.status);
  const [currentVin, setCurrentVin] = useState('empty');
  const [vinDetails, setVinDetails] = useState({
    vehicleDetails: {
      ccmTech: '',
      constructionType: '',
      cylinder: '',
      cylinderCapacityCcm: '',
      cylinderCapacityLiter: '',
      fuelType: '',
      fuelTypeProcess: '',
      impulsionType: '',
      manuId: '',
      manuName: '',
      modId: '',
      modelName: '',
      motorType: '',
      year: '',
      powerHpFrom: '',
      powerHpTo: '',
      powerKwFrom: '',
      powerKwTo: '',
      typeName: '',
      typeNumber: '',
      valves: '',
      yearOfConstrFrom: '',
      rmiTypeId: '',
    },
  });

  const [submodelSelected, setSubmodelSelected] = useState('');
  const { data: selectedSubmodel } = useGetOne(ApiModels.submodels, submodelSelected);

  const requiredValidate = [required()];

  const SectionTitle = ({ label }: { label: string }) => (
    <Typography variant="h6" gutterBottom>
      {label}
    </Typography>
  );

  const Separator = () => <Box pt="1em" />;

  const getStatus = () => {
    let status: CarStatus[] = [];
    if (props.isEdit) {
      switch (initialStatus) {
        case CarStatus.Auctioned:
          status = [CarStatus.Auctioned, CarStatus.PreDisAssemblyCheck];
          break;
        case CarStatus.PreDisAssemblyCheck:
          status = [CarStatus.PreDisAssemblyCheck, CarStatus.WaitingForDisAssembly];
          break;
        case CarStatus.WaitingForDisAssembly:
          status = [CarStatus.WaitingForDisAssembly, CarStatus.InDisAssembly];
          break;
        case CarStatus.InDisAssembly:
          status = [CarStatus.InDisAssembly, CarStatus.DisAssembled];
          break;
        case CarStatus.DisAssembled:
          status = [CarStatus.DisAssembled, CarStatus.Scraped];
          break;
        case CarStatus.Scraped:
          status = [CarStatus.Scraped];
          break;
      }
    } else {
      status = [
        CarStatus.Auctioned,
        CarStatus.PreDisAssemblyCheck,
      ];
    }
    return status;
  };

  return (
    <FormDataConsumer {...props}>
      {({ formData, ...rest }) => (
        <>
          <>
            <SectionTitle label="Car Details" />
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="vin"
                // validate={requiredValidate}
                onBlur={(event: any) => {
                  formData.make = '';
                  formData.model = '';
                  formData.year = '';
                  formData.submodel = '';
                }}
              />
            </Box>
            {formData?.vin ? (
              <Box className={classes.input}>
                <ReferenceInput
                  reference={ApiModels.make}
                  fullWidth
                  source="make"
                  // validate={requiredValidate}
                >
                  <AutocompleteInput
                    optionText="name"
                    onSelect={(event: any) => {
                      formData.model = '';
                      formData.year = '';
                      formData.submodel = '';
                    }}
                    helperText={vinDetails.vehicleDetails.manuName}
                  />
                </ReferenceInput>
              </Box>
            ) : (
              <Box className={classes.input}>
                <SelectInput
                  fullWidth
                  disabled
                  source="make"
                  // validate={requiredValidate}
                  choices={[]}
                />
              </Box>
            )}
            {formData?.vin && formData?.make ? (
              <Box className={classes.input}>
                <ReferenceInput
                  reference={ApiModels.model}
                  fullWidth
                  source="model"
                  filter={{ parent: formData.make }}
                  // validate={requiredValidate}
                >
                  <AutocompleteInput
                    optionText="name"
                    onSelect={(event: any) => {
                      formData.year = '';
                      formData.submodel = '';
                    }}
                    helperText={vinDetails.vehicleDetails.modelName}
                  />
                </ReferenceInput>
              </Box>
            ) : (
              <Box className={classes.input}>
                <SelectInput
                  fullWidth
                  disabled
                  source="model"
                  // validate={requiredValidate}
                  choices={[]}
                />
              </Box>
            )}
            {formData?.vin && formData?.make && formData?.model ? (
              <Box className={classes.input}>
                <ReferenceInput
                  reference={ApiModels.year}
                  fullWidth
                  source="year"
                  filter={{ parent: formData.model }}
                  // validate={requiredValidate}
                >
                  <AutocompleteInput
                    optionText="name"
                    onSelect={(event: any) => {
                      formData.submodel = '';
                    }}
                    helperText={vinDetails.vehicleDetails.year}
                  />
                </ReferenceInput>
              </Box>
            ) : (
              <Box className={classes.input}>
                <SelectInput
                  fullWidth
                  disabled
                  source="year"
                  // validate={requiredValidate}
                  choices={[]}
                />
              </Box>
            )}
            {formData?.vin
                && formData?.make
                && formData?.model
                && formData?.year ? (
                  <Box className={classes.input}>
                    <ReferenceInput
                      reference={ApiModels.submodels}
                      fullWidth
                      filter={{ parent: formData.year }}
                      source="submodel"
                      onBlur={(event: any) => {
                        setSubmodelSelected(formData.submodel);
                      }}
                      // validate={requiredValidate}
                    >
                      <AutocompleteInput
                        optionText="name"
                        helperText={vinDetails.vehicleDetails.typeName}
                      />
                    </ReferenceInput>
                  </Box>
              ) : (
                <Box className={classes.input}>
                  <SelectInput
                    fullWidth
                    disabled
                    source="submodel"
                    // validate={requiredValidate}
                    choices={[]}
                  />
                </Box>
              )}
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="style"
                helperText={`${vinDetails.vehicleDetails.constructionType}`}
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="color"
              />
            </Box>
            <Box className={classes.input}>
              <NumberInput
                min={0}
                fullWidth
                source="doors"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                helperText={vinDetails.vehicleDetails.fuelType}
                source="fuelType"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="engineNo"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="engineCode"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                helperText={`${selectedSubmodel?.variant ? selectedSubmodel?.variant : ''}`}
                source="engine"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                source="licensePlate"
              />
            </Box>
            <Box className={classes.input}>
              <NumberInput
                min={0}
                fullWidth
                source="odometer"
              />
            </Box>
            <Box className={classes.input}>
              <TextInput
                fullWidth
                helperText={vinDetails.vehicleDetails.impulsionType}
                source="drive"
              />
            </Box>
            <Box className={classes.input}>
              <NumberInput
                min={0}
                fullWidth
                helperText={`${vinDetails.vehicleDetails.cylinder} ${selectedSubmodel?.engine ? selectedSubmodel?.engine : ''}`}
                source="cylinder"
              />
            </Box>
            <Box className={classes.input}>
              <NumberInput
                min={0}
                fullWidth
                helperText={vinDetails.vehicleDetails.cylinderCapacityLiter}
                source="cylinder_capainput_liter"
              />
            </Box>
          </>
          <>
            <Separator />
            <SectionTitle label="Car Yard details" />
            <Box className={classes.input}>
              <CarStatusInput
                // validate={requiredValidate}
                status={getStatus()}
              />
            </Box>
            <Box className={classes.input}>
              <CarLocationInput
                // validate={requiredValidate}
                locations={
                      formData?.status === CarStatus.Auctioned
                        ? [CarLocation.AwaitingArrival]
                        : [CarLocation.InYard]
                }
              />
            </Box>
          </>
          <>
            <Separator />
            <SectionTitle label="Car Purchase Details" />
            <Box className={classes.input}>
              <DateInput
                fullWidth
                source="purchasedDate"
                // validate={requiredValidate}
              />
            </Box>
            <Box className={classes.input}>
              <ReferenceInput 
                perPage={10} 
                source="purchased_from" 
                // validate={requiredValidate} 
                reference={ApiModels.customers}
              >
                <AutocompleteInput optionText="firstName" />
              </ReferenceInput>
            </Box>
          </>
          <>
            <Separator />
            <SectionTitle label="Car Images" />
            <Box>
              <ImageInput 
                multiple 
                validate={requiredValidate} 
                maxSize={5000000} 
                source="pictures" 
                label="Car images" 
                accept="image/*"
              >
                <ImageField source="src" title="title" />
              </ImageInput>
            </Box>
          </>
        </>
      )}
    </FormDataConsumer>
  );
};
```

**Environment**

```json
{
  "name": "client",
  "proxy": "http://localhost:5000",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint \"./src/**/*.{js,jsx,ts,tsx}\""
  },
  "dependencies": {
    "@material-ui/core": "^4.11.2",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/styles": "^4.11.3",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^13.1.1",
    "@types/inflection": "^1.5.28",
    "@types/recharts": "^1.8.19",
    "axios": "^0.21.1",
    "classnames": "^2.2.6",
    "date-fns": "^2.19.0",
    "formik": "^2.2.6",
    "graphql": "^15.5.0",
    "prop-types": "^15.7.2",
    "qrcode.react": "^1.0.1",
    "query-string": "^7.0.0",
    "ra-data-fakerest": "^3.13.0",
    "ra-data-graphql": "^3.11.4",
    "ra-data-simple-rest": "^3.9.1",
    "ra-i18n-polyglot": "^3.13.1",
    "ra-input-rich-text": "^3.12.0",
    "ra-language-english": "^3.13.1",
    "react": "^17.0.2",
    "react-admin": "^3.14.1",
    "react-dom": "^17.0.2",
    "react-final-form": "^6.5.3",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "recharts": "^2.0.8",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "typescript": "^4.2.3"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/classnames": "^2.2.11",
    "@types/qrcode.react": "^1.0.1",
    "@types/react-dom": "^17.0.3",
    "@types/react-redux": "^7.1.16",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-google": "^0.14.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-react": "^7.23.1",
    "eslint-plugin-react-hooks": "^4.2.0"
  }
}
```

**Comment by fzaninotto** [comment] 2021-03-31 08:01
So #6092 didn't fix the problem for you?

**Comment by fzaninotto** [comment] 2021-03-31 08:03
Also, is it a regression? Did you experience this lag in oler versions? 

Finally, please give a link to a CodeSandbox reproducing the problem. We can't run your code example.

**Comment by gearFifth** [comment] 2021-03-31 08:07
> Also, is it a regression? Did you experience this lag in oler versions?
> 
> Finally, please give a link to a CodeSandbox reproducing the problem. We can't run your code example.

i tried the form after updating the package and the lag is still there. when I commented the validation then the form worked fine. i will get a sandbox version going and attack the link in a while.

**Comment by capJavert** [comment] 2021-03-31 14:58
Using `validate` on form components for example `TabbedForm` provides good performance.

**Comment by gearFifth** [comment] 2021-04-05 13:36
field leve validation is still slow but the form level validation is fine. i scrapped the field level validation like in the code above and replaced it with the form level validation and the form are speedy :)

**Comment by fzaninotto** [comment] 2021-04-29 19:38
I can't reproduce the problem on `master` with the following code:

```jsx
const req = [required()];

const PostEdit = (props) => (
    <Edit {...props}>
        <SimpleForm>
            <TextInput source="title" validate={req} />
            <TextInput source="title1" validate={req} />
            <TextInput source="title2" validate={req} />
            <TextInput source="title3" validate={req} />
            <TextInput source="title4" validate={req} />
            <TextInput source="title5" validate={req} />
            <TextInput source="title6" validate={req} />
            <TextInput source="title7" validate={req} />
            <TextInput source="title8" validate={req} />
            <TextInput source="title9" validate={req} />
            <TextInput source="title10" validate={req} />
            <TextInput source="title11" validate={req} />
            <TextInput source="title12" validate={req} />
            <TextInput source="title13" validate={req} />
            <TextInput source="title14" validate={req} />
        </SimpleForm>
    </Edit>
);
```

So I'm closing this issue. If you can provide a reproducible test case base on [the simple example codesandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple), we'll reopen the issue.

**Closed by fzaninotto** 2021-04-29 19:38 UTC
Labels: needs more info
