### ISSUE TITLE
Pagination randomly resetting (broken)

### ISSUE THREAD

**Issue by ilaif** [marmelab/react-admin#4655] opened 2020-04-07 11:45 UTC
**What you were expecting:**
When clicking on the next page button, I expect it to redirect to the next page.

**What happened instead:**
When clicking on the next page button, sometimes the page goes back to 1 instead of the next page.

**Steps to reproduce:**
A simple example in codesandbox: https://codesandbox.io/s/dazzling-babbage-610z1

![Peek 2020-04-07 14-44](https://user-images.githubusercontent.com/3540825/78665384-68876d00-78de-11ea-9566-ea64873d5006.gif)

**Environment**

React-admin version: 3.4.0
Last version that did not exhibit the issue (if applicable): -
React version: 16.13.1
Browser: Chrome 80
Stack trace (in case of a JS error): -

**Comment by Kmaschta** [comment] 2020-04-07 12:43
The pagination heavily depends of what the API returns.
It seems like https://jsonplaceholder.typicode.com/ is currently down? I have a 503 on your codesandbox.

**Comment by ilaif** [comment] 2020-04-07 13:59
@Kmaschta Just tried again now from incognito, and it seems fine. Can you try again?

**Comment by Kmaschta** [comment] 2020-04-07 14:26
I can definitely reproduce the issue! Working on the root cause

**Comment by Kmaschta** [comment] 2020-04-07 14:47
I took the liberty to rewrite the issue with a reproduction process, let me know if it suits you.
Thanks for opening the issue!

**Comment by ilaif** [comment] 2020-04-07 15:36
@Kmaschta Thanks for looking into this!
However, I'm afraid that while the new way you described the issue might be an actual problem that should be solved, it's **different** from the problem I described.

I opened again my original example (https://codesandbox.io/s/dazzling-babbage-610z1) and produced the following recording that shows that even if I wait for the API call to finish, I still sometimes get double ACTION to location_change, and the second one is always to page 1:

![Peek 2020-04-07 18-33](https://user-images.githubusercontent.com/3540825/78688996-882e8d80-78fe-11ea-9507-172d79a9a1bd.gif)

So, if it's ok by you, can you restore the original issue description? This is what I face in production in my app.

**Comment by Kmaschta** [comment] 2020-04-07 16:06
Reverted, sorry, I opened a new one with my edit then!

**Comment by fzaninotto** [comment] 2020-04-07 16:52
This is a duplicate of #4616. The bug is caused by `<React.StrictMode>`.

**Closed by fzaninotto** 2020-04-07 16:52 UTC
Labels: bug

**Comment by ilaif** [comment] 2020-04-07 18:55
@fzaninotto You told me in https://github.com/marmelab/react-admin/issues/4616 that this issue is probably not related.

Please note:
- this problem happens also when running npm run build for production.
- this problem persists all the time, not only in the second click.

How do I solve it in production?

**Comment by fzaninotto** [comment] 2020-04-07 19:48
@ilaif you said in #4616 that you weren't using StrictMode. But in the CodeSandbox you provided to reproduce the problem, it appears that you DO use StrictMode in index.js. That's why I think it is actually a duplicate of #4616

**Comment by ilaif** [comment] 2020-04-07 20:01
@fzaninotto You are correct, my bad.
