### ISSUE TITLE
dataProvider reuses filter object between requests

### ISSUE THREAD

**Issue by Dreamsorcerer** [marmelab/react-admin#8888] opened 2023-05-06 14:21 UTC
I'm not sure if you want to add a warning to the documentation, or use a fresh object in future to make the code more robust, but this totally caught me out.

To save me creating a custom referenceMany endpoint, I just did this in the dataProvider:
```
getManyReference: (resource, params) => {
    params["filter"][params["target"]] = params["id"];
    return dataRequest(resource, "get_list", params);
}
```
(compared to getList: `getList: (resource, params) => dataRequest(resource, "get_list", params)`, it just adds to the filter)

But, the filter object is actually reused across requests, so each time I navigate to a different object, I was actually adding another filter value, thus breaking the requests.

Fixed by doing:
```
getManyReference: (resource, params) => {
    params["filter"] = {...params["filter"], [params["target"]]: params["id"]};
    return dataRequest(resource, "get_list", params);
},
```

**Comment by fzaninotto** [comment] 2023-05-07 16:59
I don't understand the bug. Can you give an example and a reproduction?

**Comment by Dreamsorcerer** [comment] 2023-05-07 18:49
I'm running a little short on time, but imagine you have 2 different resources, which both have a ReferenceManyField with different targets (e.g. `foo_id` and `bar_id`) in the list view.


If you use the code from the first example (replacing dataRequest() with whatever you need to do a get_list request), then when you view the list for the first resource and look at the network request made, you'll see `filter={"foo_id": 1}` or similar, which is the expected behaviour.

Then if you navigate to view the list of the second resource, you'll see requests made with `filter={"foo_id": 1, "bar_id": 1}` or similar. Likely the second resource has no `foo_id`, so the API will likely error or return no results. You need to refresh the page in order for it to create the correct request (e.g. `filter={"bar_id": 1}`).

This is because `params.filter` that is passed in is not a newly created object for each dataProvider call, but appears to be reused each time, so modifying the values actually persists across calls. Hence the second version shown above, which clones the filter object instead of modifying the original (so `filter={"foo_id": 1, "bar_id": 1}` never happens with this approach).

**Comment by fzaninotto** [comment] 2023-05-08 09:21
I still don't understand. Would you mind building a reproduction based on the simple example StackBlitz?

https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple

**Comment by fzaninotto** [comment] 2023-05-09 15:11
I still don't understand what I'm supposed to look at. Please be more specific. 

Also, you should not modify the parameters passed as arguments to a function inside a function. Lots of react-admin code (and React code) is based on the assumption that you will not do that:

```
    getManyReference: (resource, params) => {
        params["filter"][params["target"]] = params["id"];
        return  fakeProvider.getList(resource, params)
    },
````

Otherwise, every function call should be done by value and not by reference, and we'd have to clone everything.

**Comment by Dreamsorcerer** [comment] 2023-05-09 16:12
> I still don't understand what I'm supposed to look at. Please be more specific.
> 
> Also, you should not modify the parameters passed as arguments to a function inside a function. Lots of react-admin code (and React code) is based on the assumption that you will not do that

That is the issue, I was just suggesting that it be documented if sending a new object in every call is not something you want to do (which sounds like that is the react way...).

> we'd have to clone everything.

Which is exactly the solution I've used, as shown in the original comment.

**Comment by slax57** [comment] 2023-05-10 09:40
Thanks for your reply.
I'm not in favor of documenting this in the react-admin documentation either, because, to me, this is really down to the way JavaScript works, and this is not at all specific to react-admin.
As you figured out, you need to fix this in your dataProvider implementation by cloning the params before mutating them.
Hence I'll close this issue.

**Closed by slax57** 2023-05-10 09:40 UTC
Labels: needs more info

**Comment by Dreamsorcerer** [comment] 2023-05-10 15:47
If you also use async code, I don't understand how this is meant to work correctly.

e.g. If some code is awaiting inside a getMany() request, and a new, different, getMany() request is made, then the object in the first request is going to be changed and potentially break the code. (Probably, there are not multiple simultaneous calls to getMany() for most people, so maybe it never happens in reality).

**Comment by slax57** [comment] 2023-05-11 08:37
What I meant by "it's the way JavaScript works" was referring to passing the parameters by value vs. by reference, and the need to clone the parameters with the latter.
In any case, react-admin expects dataProvider functions to be pure functions, [which is a good practice in general](https://dev.to/sulistef/the-benefits-of-pure-functions-in-javascript-1d2b).
I don't think it's relevant to mention this in the RA docs, because it's a common assumption to make, but if the community disagrees (and you are free to disagree), I'll reopen this issue and document this caveat.

**Comment by Dreamsorcerer** [comment] 2023-05-11 14:37
> react-admin expects dataProvider functions to be pure functions

Sure, but from that link:

> pure functions are functions that don’t modify the global state and don’t depend on any external input

What I provided was a pure function, it only modified the input given to it as an argument. The fact that a global, reusable object was passed to the function is the only thing I'm questioning (why pass the object as an argument if it's global anyway?).
