### ISSUE TITLE
Initially disabled inputs are not validated after enabled when form is submitted

### ISSUE THREAD

**Issue by endrits079** [marmelab/react-admin#9870] opened 2024-05-23 07:23 UTC
**What you were expecting:**

I have a form with 2 inputs, both inputs are required but the second is disabled if there is no value for the first input, after I provide a value for the first input the second input becomes enabled but if I submit the form without providing a value for second input the form submission should failed because the required() should fail,
**What happened instead:**

The form was submitted and ignored the fact that there is no value on a required() validation input.
**Steps to reproduce:**

1.Go to create post,
Fill in the required fields but leave the average_note blank, it is required() and minimum 1 but it can submit the form without providing value for it

**Related code:**

* Preferably, a sandbox forked from 
https://stackblitz.com/edit/github-xm5t9q?file=src%2Fposts%2FPostCreate.tsx
```
**Environment**

* React-admin version:4.16.18
* Last version that did not exhibit the issue (if applicable):
* React version:17.0
* Browser:Chrome
* Stack trace (in case of a JS error):

**Comment by adguernier** [comment] 2024-05-23 08:47
Reproduced, thanks. This issue seems to be related to #9753. 

For now, you can use the [`validate` prop](https://marmelab.com/react-admin/Validation.html#global-validation) of the `<Form>` component to apply the validation you need.

**Comment by fzaninotto** [comment] 2024-05-23 12:22
Indeed, if you replace `disabled` by `readOnly`, the problem disappears. I suspect this is a react-hook-form bug.

**Comment by endrits079** [comment] 2024-05-25 18:33
> Indeed, if you replace `disabled` by `readOnly`, the problem disappears. I suspect this is a react-hook-form bug.

I didn't check in details how are you using react hook form but  I tried a basic example with react hook only and it was working fine

**Comment by slax57** [comment] 2024-05-27 07:59
@endrits079 we had [issues](https://github.com/marmelab/react-admin/issues/9498) in the past with a [breaking change introduced by RHF in version 7.47.0](https://github.com/react-hook-form/react-hook-form/issues/11055) which affected disabled inputs. That's why we made sure the `readOnly` prop is supported on every input component in react-admin (https://github.com/marmelab/react-admin/pull/9656).
If using `readOnly` allows to fix the problem, we will consider this issue solved.
If using `readOnly` cannot be applied in your case, feel free to elaborate.

**Comment by fzaninotto** [comment] 2024-07-10 11:33
@endrits079 Any updates?

**Comment by endrits079** [comment] 2024-07-10 12:35
> @endrits079 Any updates?

using readonly indeed solved the issue, but introduced a new issue, because it was validating readonly fields so I had to change the validation logic to ignore readonly fields

**Comment by slax57** [comment] 2024-08-30 08:37
Fixed via https://github.com/marmelab/react-admin/pull/10163

**Closed by slax57** 2024-08-30 08:37 UTC
Labels: bug
