### ISSUE TITLE
Fix Sidebar scrolling on page scrolling

### ISSUE THREAD

**Issue by JochenFerchland** [marmelab/react-admin#6440] opened 2021-07-16 05:26 UTC
Hi,
we are using ra-enterprise. I was told to ask this request here, so my question is:
The sidebar isn't fixed when scrolling the data/content in a view.
This issue was already asked here: [https://www.gitmemory.com/issue/marmelab/react-admin/4684/622791163](https://www.gitmemory.com/issue/marmelab/react-admin/4684/622791163)
Sidebar items should be fixed, otherwise they scroll out of the user’s focus.
The behaviour should be like in this demo: [https://material-kit-pro-react.devias.io/dashboard](https://material-kit-pro-react.devias.io/dashboard)

BR
Jochen

**Comment by fzaninotto** [comment] 2021-07-22 16:15
Duplicate of #4684

**Closed by fzaninotto** 2021-07-22 16:15 UTC
Labels: enhancement, good first issue

**Comment by JochenFerchland** [comment] 2021-08-02 09:50
Hello Francois,

yes, it’s a duplicate.
But actually now solution for that?

Mit freundlichen Grüßen | Best Regards

Dipl.-Wirt. Inform.
Jochen Ferchland
Software-Ingenieur

HCC/KPM Electronics GmbH
Eisenhüttenstraße 21
57074 Siegen / Germany

T: +49 (0) 271 6906 410
F: +49 (0) 271 6906 411
***@***.******@***.***>

Handelsregister Siegen, HRB 5300
Geschäftsführer | President: Maximilian Thoma

Von: Francois Zaninotto ***@***.***>
Gesendet: Donnerstag, 22. Juli 2021 18:16
An: marmelab/react-admin ***@***.***>
Cc: Ferchland, Jochen ***@***.***>; Author ***@***.***>
Betreff: Re: [marmelab/react-admin] Fix Sidebar scrolling on page scrolling (#6440)


Duplicate of #4684<https://github.com/marmelab/react-admin/issues/4684>
