### ISSUE TITLE
Error: Invariant failed: You should not use <NavLink> outside a <Router>

### ISSUE THREAD

**Issue by taufiq596** [marmelab/react-admin#4331] opened 2020-01-21 16:00 UTC

**Comment by djhi** [comment] 2020-01-23 09:23
Please follow the issue template and provide a codesandbox showing the issue.

**Comment by josias-r** [comment] 2020-01-28 08:08
This error could be caused, when you use `npm link somepackage` to locally link a package w/ react-router-dom installed too.

Possible fix (w/ reat-app-rewired):
```
const path = require("path");
const { override, addWebpackAlias } = require("customize-cra");

// Adds legacy decorator support to the Webpack configuration.
module.exports = override(
  // this allows linking the casaone-styleguide to autocompile without causing any compiling errors
  addWebpackAlias({
    react: path.resolve("./node_modules/react"),
    "react-router": path.resolve("./node_modules/react-router"),
    "react-router-dom": path.resolve("./node_modules/react-router-dom"),
  }),
);

```

**Comment by fzaninotto** [comment] 2020-01-28 14:57
No news for some time, and besides it's probably a duplicate of #3078

**Closed by fzaninotto** 2020-01-28 14:57 UTC
Labels: needs more info
