### ISSUE TITLE
AutocompleteSuggestionList is hidden beneath Dialog

### ISSUE THREAD

**Issue by isumix** [marmelab/react-admin#5375] opened 2020-10-09 08:19 UTC
https://github.com/marmelab/react-admin/blob/27a6927daadb037bbb26cb349b5408e09e594b2d/packages/ra-ui-materialui/src/input/AutocompleteSuggestionList.tsx#L9

```ts
import {
  Dialog,
} from '@material-ui/core';
```

Dialog has `z-index: 1300` which makes suggestion popup invisible as it has `z-index: 2`

```tsx
<Dialog open>
  <AutocompleteInput
    source="url777"
    choices={[
        { id: 'programming', name: 'Programming' },
        { id: 'lifestyle', name: 'Lifestyle' },
        { id: 'photography', name: 'Photography' }
    ]}
  />
</Dialog>
```
![image](https://user-images.githubusercontent.com/16747416/95560509-b01bbc80-0a19-11eb-92f1-79cf664327d8.png)

**Comment by djhi** [comment] 2020-10-09 08:43
Duplicate of #5181

**Comment by isumix** [comment] 2020-10-09 10:03
hmm, the solution mentioned in #2456 did not worked for **v3.9.2**

**Comment by djhi** [comment] 2020-10-09 10:14
Then can you please provide a codesandbox reproducing the issue?

**Comment by isumix** [comment] 2020-10-09 14:21
> Then can you please provide a codesandbox reproducing the issue?

here you go https://codesandbox.io/s/react-admin-debug-cjo7w?file=/src/post/edit.tsx

**Comment by fzaninotto** [comment] 2020-10-13 07:27
reproduced, thanks

**Closed** 2020-10-13 08:42 UTC
Labels: bug
