### ISSUE TITLE
defaultValue of Inputs inside ArrayInput not working

### ISSUE THREAD

**Issue by AndresVelandia** [marmelab/react-admin#2489] opened 2018-10-31 01:57 UTC
**What you were expecting:**
I set defaultValue of Inputs inside an ArrayInput and expect that when I add a new element it sets the default value. For example, if I have an array of posts each one with and id, title, created_at, description, and set the defaultValue of created_at DateInput to Date.now(), I expect that everytime I add a new post the created_at will be Date.now()

**What happened instead:**
It doesn't work

**Related code:**
Forked from simple demo, edit a post and try to add a new backlink in the miscellaneous tab. 
https://codesandbox.io/s/k06x14xy8v

**Environment**

* React-admin version: 2.4.1
* React version: ^16.6.0
* Browser: Chrome

**Comment by fzaninotto** [comment] 2018-11-05 22:43
Confirmed and reproduced. That's because `defaultValues` are currently only set at one level:

```js
// in ra-core/form/getDefaultValues.js
const getDefaultValues = (data = {}, defaultValue = {}, defaultValues = {}) => {
    const globalDefaultValue =
        typeof defaultValue === 'function' ? defaultValue() : defaultValue;
    return { ...globalDefaultValue, ...defaultValues, ...data };
};
```

Let's say a record has sub elements, as follows:

```
{
  id: 123,
  foos: [
    { bar: 'baz' }
 ]
}
```

Given there is an `ArrayInput` written as:

```jsx
<ArrayInput>
  <SimpleFormIterator>
    <TextInput source="bar" defaultValue="hello" />
  </SimpleFormIterator>
</ArrayInput>
```

When a user add a `foo` by way of `ArrayInput`, the default value of `foos` is set to: 

```
[
    { bar: 'baz' },
    { bar: 'hello' }
]
```

but since `foos` *already has a value*, this default value is never used...

**Comment by afilp** [comment] 2018-12-01 09:31
@fzaninotto So is this an issue that we should raise in `redux-form` repo? Or we should investigate how to do this with `react-admin` code? Maybe iterate on the fileds upon the addition of a new item and add the `default` values to it too?

**Comment by fzaninotto** [comment] 2018-12-12 17:24
react-admin does its own default value voodoo to overcome the redux-form limitations in this field. the solution must be found in react-admin.

**Comment by tusmenko** [comment] 2019-06-12 20:09
One point to add - I found that it's not working on Edit view, but works on Create page.

**Comment by brian-isenpai** [comment] 2019-08-01 12:54
We're experiencing issues with default value of NumberInput and TextInput inside ArrayInput and SimpleFormIterator. The default values work the first time you add a value, but after that it doesn't work. 

Any updates on when this issue will be resolved?

**Comment by djhi** [comment] 2019-08-01 12:59
It might be fixed in v3 as we migrate from redux-form to react-final-form. I'll check when I'll have the time

**Comment by fzaninotto** [comment] 2019-09-17 14:56
ping @djhi

**Comment by nosequeldeebee** [comment] 2019-10-01 00:31
can we get a status update on this? I don't currently see this ticket in the v3 roadmap.

**Comment by tusmenko** [comment] 2019-10-01 09:14
@nosequeldeebee I found this fixed till 3.0.0-alpha.2

**Comment by gvillo** [comment] 2020-01-14 20:28
Still happening to me on v3.1.2

`<ArrayInput source="tags">
        <SimpleFormIterator>
          <TextInput label="Tag" initialValue="" />
        </SimpleFormIterator>
      </ArrayInput>`

is there a way to fix it?, it keeps adding [object Object] as default value

<img width="365" alt="image" src="https://user-images.githubusercontent.com/11096470/72379996-46bd8600-36f3-11ea-975a-9cb84aba9aca.png">

Thank you!

**Comment by nkigen** [comment] 2020-01-15 12:49
> ```js
> initialValue="" 
> ```

Any Solution on this?

**Comment by nkigen** [comment] 2020-01-15 12:49
Any solution on this?

**Comment by gvillo** [comment] 2020-01-16 23:32
I just did a fix for my issue #4306 , it's related to this bug, but it's not 100% this bug, please give me your feedback and see if we could fix this issue. Thanks!

**Comment by nkigen** [comment] 2020-01-17 00:16
A simple workaround () for now while awaiting the above fix to be merged is to format the source as below  `format={v=> { return v instanceof Object ? '' : v;}} ` . You can the apply it to an inner input component.

`
<ArrayInput source="subCategories" label='Sub Categories'>
                <SimpleFormIterator>
                    <TextInput format={v=> { return v instanceof Object ? '' : v;}} />
                </SimpleFormIterator>
            </ArrayInput>
`

**Comment by JulienMattiussi** [comment] 2020-03-04 16:04
Issues are fixed in https://github.com/marmelab/react-admin/pull/4394
(ra 3.2)
(both `object Object` and defaultValues are ok)

**Closed** 2020-03-04 17:03 UTC
Labels: bug

**Comment by Jongmun-Park** [comment] 2020-07-17 06:31
> Still happening to me on v3.1.2
> 
> ```js
> <ArrayInput source="tags">
>    <SimpleFormIterator>
>       <TextInput label="Tag" />
>    </SimpleFormIterator>
> </ArrayInput>
> ```
> 
> is there a way to fix it?, it keeps adding [object Object] as default value (to reproduce it you have to omit `source` attribute, this is an array of strings, I want ['tag1', 'tag2'] as result)
> 
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/11096470/72379996-46bd8600-36f3-11ea-975a-9cb84aba9aca.png">
> 
> Environment
> 
> ```
> React-admin version: 3.1.2
> React version: 16.12.0
> Browser: Firefox developer edition 73.0b2 (64-bit) // Google Chrome 79.0.3945.117 (Official Build) (64-bit)
> ```
> 
> Thank you!

If you want empty string instead of [object Object],
you can add `defaultValue=""` in the TextInput.
maybe there is empty string, not [object Object]
