### ISSUE TITLE
After some minutes opening an expand clears the list

### ISSUE THREAD

**Issue by esistgut** [marmelab/react-admin#3227] opened 2019-05-15 12:32 UTC
I'm seeing this locally using react-admin-2.9.1 but the issue is visible on the [demo/invoices page](https://marmelab.com/react-admin-demo/#/invoices) aswell.

The expected behaviour is the one we can see just after opening the page and clicking on the expand arrow: the expand opens and every other record on the list remains visible.

If you open the invoices list, wait for 5-10 minutes (I'm not sure about the exact timeout) and click an expand arrow the expand opens correcly but _**every other**_ item on the list disappear.

**Comment by fzaninotto** [comment] 2019-05-15 16:43
Thanks, I reproduced the issue. It's easier to spot by lowering down the `defaultCacheDuration` in `packages/ra-core/src/util/getFetchedAt.ts`.

the problem comes from `packages/ra-core/src/reducer/admin/resource/list/ids.ts`, which invalidates outdated elements in the list when a `CRUD_GET_ONE_SUCCESS` is dispatched. In that case, the reducer should only *replace* the existing record with the new one and not invalidate the others.

**Comment by hoangtuan438** [comment] 2019-09-17 07:33
@fzaninotto 

Is this issue fixed. we're waiting for this fix because I got this problem too.

thanks for your framework :)

**Comment by Kmaschta** [comment] 2019-09-20 07:26
@hoangtuan438 As you can see, [a PR is open](https://github.com/marmelab/react-admin/pull/3266) to fix the issue.

The author didn't give news from a month or so, hence the issue isn't fixed.
Feel free to open your own PR to fix the issue! It is marked as *good first issue* so, it's manageable from entry level contributor :)

**Comment by hoangtuan438** [comment] 2019-09-20 08:08
@Kmaschta thanks for your feedback. I saw this PR but how can I add the fix to the dependency in package.json. I tried it, but it doesn't work. 
The author said the react-admin is mono-repository, so we can't do that
Do you know how to include the PR to dependency

**Comment by esistgut** [comment] 2019-09-20 10:31
I am very sorry, I did not know you were waiting for my input. Will test ASAP.

**Comment by fzaninotto** [comment] 2020-01-09 17:08
Fixed by #4261

**Closed by fzaninotto** 2020-01-09 17:08 UTC
Labels: bug, good first issue
