### ISSUE TITLE
pass enctype to simpleform?

### ISSUE THREAD

**Issue by thatshailesh** [marmelab/react-admin#4286] opened 2020-01-14 08:58 UTC
I want to build file upload functionality using simpleform component of admin-on-rest framework.

For this, I want to pass `enctype="multipart/form-data"` to form.

I am not able find any documentation or forums to understand, how can I pass this, if inside any props, or some other way.

Please help with this.

**This question have been asked on stackoverflow and no answer received since 2 years**
https://stackoverflow.com/questions/48096825/how-to-pass-enctype-to-simpleform-in-admin-on-rest
Hence submitting here

```
<Create {...props}>
    <SimpleForm enctype="multipart/form-data">
        <FileInput source="files" label="Related files" multiple accept="text/*,image/*">
            <FileField source="src" title="title" />
        </FileInput>
    </SimpleForm>
</Create>
```

**Comment by fzaninotto** [comment] 2020-01-14 09:05
Duplicate of #4284. @thatshailesh this is rude, you've been banned from this repo.

**Closed by fzaninotto** 2020-01-14 09:05 UTC
