### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by kamleshwebtech** [marmelab/react-admin#5671] opened 2020-12-15 08:02 UTC
I am getting this issue at the time of compile in mac:

```
/Applications/XAMPP/xamppfiles/htdocs/sites/reactprojects/react-admin/examples/demo/src/products/GridList.tsx
TypeScript error in /Applications/XAMPP/xamppfiles/htdocs/sites/reactprojects/react-admin/examples/demo/src/products/GridList.tsx(58,35):
Argument of type 'string | number | undefined' is not assignable to parameter of type '"xs" | "sm" | "md" | "lg" | "xl"'.
  Type 'undefined' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl"'.  TS2345

    56 |         <MuiGridList
    57 |             cellHeight={180}
  > 58 |             cols={getColsForWidth(width)}
       |                                   ^
    59 |             className={classes.gridList}
    60 |         >
    61 |             {' '}
This error occurred during the build time and cannot be dismissed.
```

Kindly suggest what is the issue and how can we fix it.  Thanks a lot :)

**Comment by fzaninotto** [comment] 2020-12-15 17:26
Please follow the issue template

**Comment by Md-Khaleelur** [comment] 2020-12-16 13:41
Please install yarn and try running those application. I faced the same issue using npm package manager
Follow these three commands 
make install
make build
make run-demo (to run the demo application in /examples folder)

**Comment by fzaninotto** [comment] 2021-01-03 20:24
I can't reproduce the error you're describing on a fresh install. Please follow the issue template and include your Node / Yarn versions.

As per XAMPP, I don't have access to this platform, so we won't be able to debug it.

**Comment by fzaninotto** [comment] 2021-02-16 12:19
No news for some time, closing.

**Closed by fzaninotto** 2021-02-16 12:19 UTC
Labels: needs more info
