### ISSUE TITLE
ra-data-json-server UPDATE_MANY uses PATCH instead of PUT

### ISSUE THREAD

**Issue by jheiska** [marmelab/react-admin#2372] opened 2018-10-01 10:49 UTC
**What you were expecting:**
UPDATE_MANY to send multiple PUT calls.

**What happened instead:**
Multiple PATCH calls are made instead.

**Steps to reproduce:**
Use ra-data-json-server UPDATE_MANY -action.

**Other information:**
https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/src/index.js

**Environment**

* React-admin version: 2.3.2

**Comment by Mclovinn** [comment] 2018-10-02 18:55
I would like to work on this

**Comment by Kmaschta** [comment] 2018-10-02 20:08
@Mclovinn Go for it! Just open a PR and we'll help you.
Be sure to read the [contribution guidelines](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md).

**Comment by jheiska** [comment] 2018-10-10 08:04
It does, but I think it's confusing that UPDATE uses PUT but UPDATE_MANY uses PATCH. Especially when it's stated in the file:

https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/src/index.js

"json-server doesn't handle filters on UPDATE route, so we fallback to calling UPDATE n times instead"

Also, in my case, the backend doesn't support PATCH calls at all so it's a big problem for me. I don't know if this is a common problem or is PATCH usually supported? I'm quite new to web development.

**Comment by fzaninotto** [comment] 2018-10-10 11:55
The problem is that your fix is a breaking change. Anyone using the `ra-data-json-server provider` with a custom API modeled after the provider will have the update_many stop working.

So there are two ways to handle this:

1. Consider that the provider was only made for json-server in the first place. As it supports both PUT and PATCH for updates, it's not a BC break. Anyone who modeled an API based on that provider is in a non-supported use case, and we don't care if they break
2. Delay this change until we release a major version

@djhi any opinion?

**Comment by jheiska** [comment] 2018-10-15 06:59
Sorry, I don't completely understand what you're saying. There won't be a change until the next major release and I should just update my backend to support PATCH calls?

Maybe you should change the comments in ra-data-json-server? As it is, UPDATE_MANY doesn't call the same http method as UPDATE, so saying "we fallback to calling UPDATE n times" is quite misleading.

**Comment by fzaninotto** [comment] 2018-11-29 21:10
Fixed by #2382

**Closed by fzaninotto** 2018-11-29 21:10 UTC
