### ISSUE TITLE
SelectColumnsButton add unlabelled column for Show/Edit Buttons and Selectable Columns checkbox

### ISSUE THREAD

**Issue by martin-fv** [marmelab/react-admin#8488] opened 2022-12-09 14:08 UTC
![Screenshot from 2022-12-09 22-05-04](https://user-images.githubusercontent.com/105156564/206720062-95af5e99-c180-42a8-8837-fb6dba06ff7e.png)
I'm quite happy about this new feature, but it seems to add column select options for Show/Edit Buttons and Selectable Columns checkbox.

This also seems to mess up the toggle effect that show/hide column is offset by 1.

Happy to add reproducible code if needed.

**Environment**

* React-admin version: 4.6.1

**Comment by septentrion-730n** [comment] 2022-12-09 14:31
Thanks for your feedback! Reproducible code would be welcomed indeed!

**Comment by mshd** [comment] 2022-12-11 15:34
Here's an example of the show button which turns into an unlabelled column 
https://wikidata-table.vercel.app/#/international-airports

[Source code](https://github.com/codeledge/entitree-monorepo/tree/main/apps/wikidata-table)


![Screenshot from 2022-12-11 23-32-53](https://user-images.githubusercontent.com/17379661/206912823-7315dd42-aee6-44df-b6ec-0ae0de94b8f7.png)

**Comment by slax57** [comment] 2022-12-13 10:26
@mshd The apparition of 'unlabeled columns' is actually not a bug, but a technical limitation. You see, `DatagridConfigurable` works by scanning its children and fetching their `source` or `label` props to build the available columns list. (see https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridConfigurable.tsx#L67)
Since `<ShowButton>` has neither, it appears as unlabeled.
You should be able to wrap it with a dummy component that allows a `source` or `label` prop to have the label properly displayed.

Regarding the offset issue, could you provide a repro?
Thanks

**Comment by fzaninotto** [comment] 2023-01-03 17:35
No news for some time, closing.

**Closed by fzaninotto** 2023-01-03 17:35 UTC
Labels: needs more info
