### ISSUE TITLE
AutocompleteInput shakes when using multiple flex children

### ISSUE THREAD

**Issue by HTMHell** [marmelab/react-admin#5926] opened 2021-02-16 16:48 UTC
**What you were expecting:**
The select box should not shake while I hover the options.

**What happened instead:**
The select box shakes while I hover the options.

**Steps to reproduce:**
Create a form with the following code:

**Related code:**

1. Currencies array: https://pastebin.com/hWRyTQdR
2. Code:
```
<FormWithRedirect
      {...props}
      render={(formProps: any) => (
        <Card>
          <Box display={{ md: "flex" }}>
            <Box flex={1}>Test</Box>
            <Box flex={1}>
              <AutocompleteInput
                source="currency"
                choices={currencies}
                optionValue="cc"
                optionText="cc"
              />
            </Box>
          </Box>
        </Card>
      )}
    />
```

**Other information:**

When Using one flex child, it's OK:
![6b68e1523c12666d67becd36704cd046](https://user-images.githubusercontent.com/6322901/108093963-36a27380-7076-11eb-86e9-90cdeca01619.gif)

When using multiple flex children:
![f51527ca194fc18f59383040e593445c](https://user-images.githubusercontent.com/6322901/108094030-4ae67080-7076-11eb-8ced-f66c0887e601.gif)

**Environment**

* React-admin version: ^3.12.1
* React version: ^17.0.1
* Browser: Chrome

**Comment by djhi** [comment] 2021-02-18 10:06
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by HTMHell** [comment] 2021-02-18 11:37
> Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

Here you go:
https://codesandbox.io/s/red-frost-dbec0?file=/src/posts/PostCreate.js

Click on post create.

**Comment by andion** [comment] 2021-03-31 14:55
This does not need more info anymore, does it?

**Comment by fzaninotto** [comment] 2021-05-31 22:04
Thanks you for the CodeSandbox, bug confirmed. 

However, as we don't use such layouts in our apps, we won't spend time trying to fix this in the near future. If someone wants to tackle this, we'll gladly merge their PR.

**Comment by f-jost** [comment] 2021-09-14 13:39
Hello, I'm having the same issue on an app I'm currently working on where I use a lot of `AutocompleteInput`.

I just tested on the react admin-crm-demo (to see if the problem was only on my app) and the problem is present, see the video capture.

The demo page:
https://marmelab.com/react-admin-crm/#/contacts/371

Tested on Google Chrome Version 93.0.4577.63 (Build officiel) (64 bits)

https://user-images.githubusercontent.com/9694162/133267365-293c8a5f-519f-4cfa-b5b5-cd4c16170682.mp4

Is there a way around this?

Thanks.

**Comment by thcolin** [comment] 2021-11-10 11:46
Seems partially fixed on `4.0.0-alpha.0` with MUI v5 upgrade, first shake on focus still here

https://user-images.githubusercontent.com/9131757/141107343-33dac141-b2cc-476f-a0c8-674ed1ebb51c.mov

Tested on Chrome Version 93 on Windows 11

**Comment by thcolin** [comment] 2021-11-16 13:32
Can be fixed by disabling [**PopperJS** `gpuAcceleration`](https://popper.js.org/docs/v1/#modifiers..computeStyle.gpuAcceleration) (library used by **material-ui** in the `<Popper />` component used by **react-admin** `<AutocompleteSuggestionList />` component).

```jsx
<AutocompleteArrayInput
  {...props}
  options={{
    suggestionsContainerProps: {
      modifiers: {
        computeStyle: {
          enabled: true,
          gpuAcceleration: false,
        },
        applyStyle: {
          enabled: true,
        },
      },
    }
  }}
/>
```

**Comment by WiXSL** [comment] 2022-11-17 12:10
> Can be fixed by disabling [**PopperJS** `gpuAcceleration`]

Since a user land fix has been provided plus seems fixed in latest version of MUI, I'm closing this issue

**Closed by WiXSL** 2022-11-17 12:10 UTC
Labels: bug
