### ISSUE TITLE
FormWithRedirect is merging data from the background record

### ISSUE THREAD

**Issue by fzan** [marmelab/react-admin#7483] opened 2022-04-04 14:13 UTC
**What you were expecting:**
FormWithRedirect should read only the current form data

**What happened instead:**
FormWithRedirect read all the background record data then merge them in a single record

**Steps to reproduce:**
Go here:
https://codesandbox.io/s/react-admin-v3-advanced-recipes-quick-create-preview-forked-kefpy0?file=/src/comments/PostQuickCreateButton.js

on this page, please
0- Open developer tools :-)
a) navigate to /comments/1
b) click on "create"
c) add Title and Teaser
d) please note the console messages

Briefly, the FormWithRedirect component is submitting the two fields (title and teaser) but adding also the fields from comment 
(body, created_at, id, post_id, teaser, title) 
And that is obviously a problem because the post with id:1 already exist.

You can see that:
1) react admin is @3.19.10
2) react final form is at @6.5.9 (same behaviour with 6.5.7) 

After 2 days of investigation (...) i noticed that on react@3.19.2 this problem is not happening. 
My suspect went to
https://github.com/marmelab/react-admin/pull/6932

specifically related to this

https://github.com/marmelab/react-admin/pull/6932/files#diff-8535e4db04baeef00e2e572f5d575a7202403cdd652c8682082818f0dec7c62e

I'm sorry i cannot provide a fix, because this is beyond my knowledge of the framework :-( 

I actually can only suggest a **workaround**: 
- "clean" the data values during the create phase, removing the background record values.

**Environment**
in the sandbox

**Comment by slax57** [comment] 2022-04-05 08:44
Reproduced, thanks for submitting this!

**Comment by WiXSL** [comment] 2022-04-15 14:52
I cannot reproduce this issue with the latest version of react and react-admin.
Can you upgrade them?

![codeSandbox](https://user-images.githubusercontent.com/8268610/163585466-cb2d39c9-74d1-487b-8f4e-22e7e7edd72d.png)

**Comment by fzan** [comment] 2022-04-15 15:37
Hello @WiXSL ,

Just updated the version with 3.19.11
tested on 2 different browsers (just to be really sure the bug is still here)

https://codesandbox.io/s/react-admin-v3-advanced-recipes-quick-create-preview-forked-kefpy0?file=/src/comments/PostQuickCreateButton.js

I can confirm that on 2 different pc, the behaviour is the same
![screen](https://user-images.githubusercontent.com/6927527/163590675-88913a21-c697-4ba0-9505-d320d86cdbfb.png)

**Comment by WiXSL** [comment] 2022-04-15 15:45
What about trying with react version 17 ?

**Comment by fzan** [comment] 2022-04-15 15:45
@WiXSL sorry just updated the answer :-)

**Comment by fzan** [comment] 2022-04-15 15:48
be careful to follow the steps, you are creating he comment, instead you need to update a comment (so a record already exist and is loaded in background) ;-)

**Comment by fzan** [comment] 2022-04-28 10:20
@WiXSL can you please re-add the bug label? it's indeed a bug :-(
thanks

**Comment by fzaninotto** [comment] 2024-07-02 08:32
With the release of react-admin v5, react-admin v3 has reached its end of life. We won't fix bugs or make any new release on the 3.x branch. We recommend that you switch to a more recent version of react-admin. 

So I'm closing this issue as we won't fix it.

**Closed by fzaninotto** 2024-07-02 08:32 UTC
Labels: bug, v3
