### ISSUE TITLE
Phantom (created/deleted) item in ReferenceInput 

### ISSUE THREAD

**Issue by furaiev** [marmelab/react-admin#2699] opened 2018-12-28 14:38 UTC
**What you were expecting:**
1) Create item for reference
2) 1 new item is appeared in the reference list
3) Delete item for reference
4) Deleted item is disappeared in the reference list

**What happened instead:**
1) Create item for reference
2) **2** new item is appeared in the reference list (1 real and 1 phantom)
3) Delete item for reference
4) Phantom item is still in the reference list (till hard reset)

**Steps to reproduce:**
1) Create item for reference
2) Go to the reference list -> there are 2 items with the same name
3) Delete item for reference
4) Go to the reference list -> there is a phantom item
5) Refresh the page (via browser tools) -> a phantom item disappeared

**Related code:**
```
<Filter {...props}>
    <TextInput label="Name / email" source="name" alwaysOn/>
    <ReferenceInput label="Language" source="language" reference="language" alwaysOn>        
        <SelectInput optionText="name"/>
    </ReferenceInput>
</Filter>
```

**Other information:**
![ezgif-4-b41b00e96773](https://user-images.githubusercontent.com/33546696/50518536-d4b1d900-0abe-11e9-9ae3-efb2cac8731b.gif)

**Environment**

* React-admin version: 2.5.2
* React version: 16.5.2
* Browser: chrome

**Comment by djhi** [comment] 2018-12-28 18:06
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/vvw21793w0)
* A sample application via GitHub

**Comment by fzaninotto** [comment] 2018-12-31 19:53
I can't reproduce the problem on the simple example.

**Comment by furaiev** [comment] 2019-01-03 09:08
Thank you for checking,
After hours of investigating I've found that I don't get an item id during item creation.
So it worked like:
1) CREATE - Create an item without id and put it in the list
2) GET_LIST - Update the list with a new element (the same as without id)
This was the case of doubling.

**Comment by djhi** [comment] 2019-01-03 09:12
Can we close this then ?

**Comment by furaiev** [comment] 2019-01-03 09:21
Yes, please

**Closed** 2019-01-03 09:22 UTC
