### ISSUE TITLE
Create button should not be disabled when providing default values

### ISSUE THREAD

**Issue by yong2579** [marmelab/react-admin#9302] opened 2023-09-22 03:24 UTC
**What you were expecting:**
Create button should be enabled when providing SimpleForm default values

**What happened instead:**
Create button is disabled, instead after clearing the default values, the create button is enabled

**Steps to reproduce:**
Clone from https://github.com/yong2579/ra-help1
npm run install
npm run dev

Navigate to http://localhost:5174/#/incidents/create (or whichever the port that is auto assigned by vite)

The following should be displayed
Notice that the create button is disabled
![image](https://github.com/marmelab/react-admin/assets/16757815/c2a1b74b-99f1-4cb0-95a7-4cc390bfb923)

Try to clear the title value
Notice that the create button is enabled
![image](https://github.com/marmelab/react-admin/assets/16757815/db636a73-0cbd-425e-86a3-97f958d9e2b5)

**Related code:**
https://github.com/yong2579/ra-help1

**Other information:**
Suspect the default values provided to the SimpleForm become part of the initial state which FormContext / FormState may have use to determine the dirty state

**Environment**

* React-admin version: 4.12.0
* Last version that did not exhibit the issue (if applicable): NA
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2023-09-22 16:12
Hi, and thanks for your report. I think it's a duplicate of #9217, so let's track its resolution there.

**Closed by fzaninotto** 2023-09-22 16:12 UTC
