### ISSUE TITLE
resettable in SelectInput

### ISSUE THREAD

**Issue by vedmalex** [marmelab/react-admin#2413] opened 2018-10-11 07:36 UTC
**What you were expecting:**
Using resettable attribute on SelectInput is broken.
I have reproduce it here https://yj0lyojwyz.codesandbox.io/#/comments/create?post_id=7

which was forked from https://codesandbox.io/s/ypp9ljxqlj

code snippet:
for file src/comments/PostReferenceInput.js

````
        <ReferenceInput {...props}>
            <SelectInput optionText="title" resettable />
        </ReferenceInput>
````

to reproduce: 
select on create Comment form field "Post" that will longer than input width.

expected: to clear button not break layout

**Comment by fzaninotto** [comment] 2018-10-11 13:07
![kapture 2018-10-11 at 15 06 59](https://user-images.githubusercontent.com/99944/46806221-58351700-cd67-11e8-97c3-1956228d7c73.gif)

**Comment by fzaninotto** [comment] 2019-01-31 16:12
I can't reproduce the bug anymore, can you confirm that it's still there with the latest version of react-admin?

**Comment by fzaninotto** [comment] 2019-03-08 13:53
No news for more than a month, closing.

**Closed by fzaninotto** 2019-03-08 13:53 UTC
Labels: awaiting more info
