### ISSUE TITLE
<AutocompleteArrayInput/> choices get reset (flickering) when using format and parse functions

### ISSUE THREAD

**Issue by gengue** [marmelab/react-admin#8032] opened 2022-08-03 17:14 UTC
**What you were expecting:**
`ReferenceArrayInput` and `AutocompleteArrayInput` can work together when using `parse/format` props

**What happened instead:**
After typing in the `AutocompleteArrayInput`, the filtered list of choices get reset and the previous selected choices flickers

**Steps to reproduce:**
1. Open an "Animal" record to edit
2. Type something in the "Locations" autocomplete input
3. After a few milliseconds, the input flickers and it doesn't apply the filter to the available choices

**Related code:**
Reproduced in [this CodeSandbox]( https://codesandbox.io/s/silly-shirley-j5mw7c?file=/src/animals/AnimalEdit.js)

I noticed this only happens when use `parse` and `format` functions to map a data structure like this:

```
{
      id: 0,
      name: "Comb Duck",
      locations: [
        {
          id: 2,
          name: "Santa Marta",
          country: "Colombia",
        },
        {
          id: 3,
          name: "Confresa",
          country: "Brazil",
        },
      ],
 }
 ```
So I suspect there is an issue in the choice's context that is triggering an input reset in `@mui/material/Autocompplete`

**Other information:**
![Screenshot GIF](https://media3.giphy.com/media/QSRkliYkV8Tbzn9Q5b/giphy.gif)

**Environment**

* React-admin version: 4.2.5
* Last version that did not exhibit the issue (if applicable):4.0.0
* React version: 18.2.0
* Browser: All modern browsers

**Comment by fzaninotto** [comment] 2022-08-04 07:55
Duplicate of #7767

**Closed by fzaninotto** 2022-08-04 07:55 UTC
