### ISSUE TITLE
Error handling for ReferenceArrayField

### ISSUE THREAD

**Issue by zhouhao27** [marmelab/react-admin#3864] opened 2019-10-23 05:59 UTC
**What you were expecting:**

I have a **posts** table which includes a **tags** field which is an array includes ids for tag in **tags** table. Everything is fine if the id in tags array is one of the tag id. But it shows error message instead of return empty if the tag id is not one of the tag id.

**What happened instead:**

Got an error message if the referenced id can't find:

[TypeError: Cannot read property 'filter' of undefined

    in ReferenceArrayField (at post_list.js:17)
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by DatagridCell)
    in DatagridCell (created by DatagridRow)
    in tr (created by ForwardRef(TableRow))](url)

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
   <ReferenceArrayField label="Tags" reference="tags" source="tags">
        <SingleFieldList>
          <ChipField source="name" />
        </SingleFieldList>
    </ReferenceArrayField>      

```

**Other information:**

**Environment**

* React-admin version: 3.0.0.beta-2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment] 2019-10-25 10:08
Thanks for reporting this. If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/next/examples/simple)
* A sample application via GitHub

**Comment by fzaninotto** [comment] 2019-11-15 06:11
I  can't reproduce the bug in the `next` branch by altering the data in the simple example with non existent tag ids. Either it's been fixed since beta.2, or you're missing some details in the bug description. I'm closing this bug, but will reopen if you manage to provide a sample app that shows the issue.

**Closed by fzaninotto** 2019-11-15 06:11 UTC
Labels: needs more info, v3-beta
