### ISSUE TITLE
Documentation about Custom App does not allow to integrate react-admin into another app

### ISSUE THREAD

**Issue by ric-kin** [marmelab/react-admin#2025] opened 2018-07-17 17:51 UTC
**What you were expecting:**
Include react-admin into existing project. Followed instructions on: https://marmelab.com/react-admin/CustomApp.html

**What happened instead:**
When loading a simple List component, output is:
TypeError: resourceState is undefined
mapStateToProps
node_modules/ra-core/lib/controller/ListController.js:413

  410 | 
  411 | return {
  412 |     query: getQuery(props),
> 413 |     params: resourceState.list.params,
  414 |     ids: resourceState.list.ids,
  415 |     selectedIds: resourceState.list.selectedIds,
  416 |     total: resourceState.list.total

**Other information:**
I passed the "admin", "form" and "i18n" props to the List component. However, admin prop contains no resources. In other words, how can I bootstrap resources to my store's 'admin' state manually?

**Environment**

* React-admin version: 2.1.2
* React version: 16.4.0
* Browser: Firefox 61
* Stack trace (in case of a JS error):
 [Show/hide message details.] TypeError: resourceState is undefined[Learn More] ListController.js:413
mapStateToProps
ListController.js:413
mapToPropsProxy
wrapMapToProps.js:43
detectFactoryAndVerify
wrapMapToProps.js:52
mapToPropsProxy
wrapMapToProps.js:43
handleFirstCall
selectorFactory.js:26
pureFinalPropsSelector
selectorFactory.js:74
runComponentSelector
connectAdvanced.js:26
initSelector
connectAdvanced.js:178
Connect
connectAdvanced.js:119
constructClassInstance
react-dom.development.js:11447
updateClassComponent
react-dom.development.js:13144
beginWork
react-dom.development.js:13824
performUnitOfWork
react-dom.development.js:15863
workLoop
react-dom.development.js:15902
renderRoot
react-dom.development.js:15942
performWorkOnRoot
react-dom.development.js:16560
performWork
react-dom.development.js:16482
performSyncWork
react-dom.development.js:16454
requestWork
react-dom.development.js:16354
scheduleWork$1
react-dom.development.js:16218
scheduleRootUpdate
react-dom.development.js:16785
updateContainerAtExpirationTime
react-dom.development.js:16812
updateContainer
react-dom.development.js:16839
./node_modules/react-dom/cjs/react-dom.development.js/ReactRoot.prototype.render
react-dom.development.js:17122
legacyRenderSubtreeIntoContainer/<
react-dom.development.js:17262
unbatchedUpdates
react-dom.development.js:16679
legacyRenderSubtreeIntoContainer
react-dom.development.js:17258
render
react-dom.development.js:17317
./src/index.js
index.js:7
__webpack_require__
bootstrap e2d2a275ba0ef9153073:678
fn
bootstrap e2d2a275ba0ef9153073:88
0
http://localhost:3000/static/js/bundle.js:220612:18
__webpack_require__
bootstrap e2d2a275ba0ef9153073:678
<anonymous>
bootstrap e2d2a275ba0ef9153073:724
<anonymous>
http://localhost:3000/static/js/bundle.js:1:11

**Comment by djhi** [comment] 2018-07-17 18:52
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by tomkis** [comment] 2018-07-19 10:52
Apologies but blindly redirecting someone to SO without even having a look at the problem is strong ignorance.

This is problem of the documentation, definitely not something which should be handled on SO side.

So here's the solution:

You need to manually register resource because you don't use `Resource` component which does that.

So right after you create the store call `registerResource` action manually.

```javascript
import * as reactAdmin from "ra-core";
...
...
const store = createStore....


store.dispatch(reactAdmin.registerResource({
  name: "myStuff",
  hasList: true,
  hasEdit: false,
  hasShow: false,
  hasCreate: false
}));
```

For 90%  of people this is a showstopper when they want to integrate react-admin. Because finding this out will require some source code digging.

**Comment by djhi** [comment] 2018-07-19 11:52
Apologies but we might simply have missed this while actively working on this **open-source** project. Putting all this negativity in a comment instead of simply opening a pull request fixing the documentation is a strong waste of time. I'll gladly accept a pull request though

**Comment by ric-kin** [comment] 2018-07-19 13:54
Thank you very much for your help. I was about to ditch using 
react-admin since I could not get it running properly. Your apology is 
welcome, I would suggest to keep the github issue public so other users 
can benefit from your response.

**Comment by tomkis** [comment] 2018-07-19 14:22
@djhi I never meant to offend you, seriously. I really appreciate all the effort that you've put into this project. However, open sourcing this kind of library is a huge commitment. Especially for the project like this which is likely a foundation block.

I am just a bit tired of fixing a lot of issues caused by the decision to use react-admin as foundation for our app. I don't simply feel like it's stable enough. Which is fine - I do understand it's non-trivial effort to build something like react-admin.

However, I would really appreciate to slow down and focus on improving quality - meaning tickets like these should have highest priority. Thank you for your time anyway.

**Comment by christiaanwesterbeek** [comment] 2018-07-19 14:40
> blindly redirecting someone to SO without even having a look at the problem

You don't know that.

> open sourcing this kind of library is a huge commitment

Using open source software implies an invitation to improve it yourself.

> I would really appreciate to slow down and focus on improving quality

They would really appreciate you contributing.

> I am just a bit tired of fixing a lot of issues

The more I use react-admin, the more I like it.

**Comment by djhi** [comment] 2018-07-19 14:54
@tomkis No problem. Can you be more specific about what you think isnt' stable enough? We are currently focusing on fixing bugs and adding some features with breaking changes. 

I would really appreciate more detailed feedbacks. By the way, we use react-admin on almost all our client projects and many have really huge admins ;)

**Comment by fzaninotto** [comment] 2018-07-19 15:13
Reopening the issue and marking it as a documentation problem

**Comment by djhi** [comment] 2018-07-20 06:27
@ric-kin Would you mind explaining why you need to it like this ? Is it because of the redux store?

**Comment by djhi** [comment] 2018-07-20 14:47
@ric-kin Thanks! I'm investigating a way to make this use case easier :)

**Comment by tomkis** [comment] 2018-07-24 07:42
@djhi I kinda had the same use case.

Basically provide our own store. How about it would be possible to pass store down through the props optionally?

IMO this would be most comfortable for the users.

Also another problem with this approach is that users that want / have to use different router than react-router (I use router5) are basically screwed. Application heavily relies on the presence of the router. React-admin could definitely leverage from more abstraction on this front.

Unfortunately, I do not have time to do any rewrite of our app so I can't share concrete obstacles. But once I free myself up a bit, I will definitely share my two cents.

**Comment by djhi** [comment] 2018-07-24 08:58
> Basically provide our own store. How about it would be possible to pass store down through the props optionally?

It first requires that we rewrite all our state reading operations using selectors (which is a good thing anyway). Then we could follow the [redux-form approach](https://redux-form.com/7.4.2/docs/api/reducer.md/). This would be great but will take some time to implement so don't expect it soon

**Comment by djhi** [comment] 2018-07-24 09:03
> Also another problem with this approach is that users that want / have to use different router than react-router (I use router5) are basically screwed. Application heavily relies on the presence of the router. React-admin could definitely leverage from more abstraction on this front.

Not screwed but they'll have to rewrite significant parts of the library. The good news is those parts should not be too hard to implement: (The `Resource` component, the `mapDispatchToProps` of some components, mostly Controllers from 'ra-core` and the `auth` and `redirection` side effects.

I'll think about how we could make this easier though

**Comment by fzaninotto** [comment] 2018-07-24 15:31
@djhi Shouldn't we just add `<Resource context="registration" ... />` lines in the Custom app documentation snippet?

**Comment by fzaninotto** [comment] 2018-07-24 15:33
or, since we explain how to create a custom store in CustomApp, I guess we can even accept an external store and skip the creation of our own if it's provided.

**Comment by tomkis** [comment] 2018-07-27 12:36
> I'm -1 about making the router configurable. This is one of the fundamental building blocks for react-admin (together with Redux, saga, and redux-form).

What if someone has a running application that they either want gradually rewrite to RA or just add it on top of that? They would either be forced to use react-router (which may not always be an option) or they may need to use two collocated routers - which is really impractical.

**Comment by djhi** [comment] 2018-07-27 13:04
> Not screwed but they'll have to rewrite significant parts of the library. The good news is those parts should not be too hard to implement: (The Resource component, the mapDispatchToProps of some components, mostly Controllers from ra-core and the auth and redirection side effects.

**Comment by djhi** [comment] 2018-07-27 13:04
> or, since we explain how to create a custom store in CustomApp, I guess we can even accept an external store and skip the creation of our own if it's provided.

Not that simple but yes, I'll try to tackle this asap

**Comment by fzaninotto** [comment] 2018-08-24 15:37
Fixed by #2141

**Closed by fzaninotto** 2018-08-24 15:37 UTC
Labels: bug

**Comment by dgkmurthy** [comment] 2019-06-03 08:04
Is there a demo or example application to show the integration with custom react app please?

**Comment by btoro** [comment] 2020-06-06 18:56
Does anyone have an example to show the integration with custom react app?

**Comment by fzaninotto** [comment] 2020-06-08 06:55
@btoro What's wrong with https://marmelab.com/react-admin/CustomApp.html?
