### ISSUE TITLE
Infinite loop on checkAuth Promise.reject()

### ISSUE THREAD

**Issue by kevinmamaqi** [marmelab/react-admin#6755] opened 2021-11-07 19:35 UTC
**What you were expecting:**

Redirect to the default /login page provided by react-admin.

**What happened instead:**

There is an infinite loop.

**Steps to reproduce:**

Use the following code:
```
const authProvider = {
  login: ({ email, password }: UserLoginI) => {
    firebase
      .auth()
      .signInWithEmailAndPassword(email, password)
      .then((userCredential) => {
        userCredential.user?.getIdToken().then((token) => {
          localStorage.setItem('auth', token)
          return Promise.resolve(token)
        })
      })
      .catch((error) => {
        const errorCode = error.code
        const errorMessage = error.message
        console.error('errorCode', errorCode)
        console.error('errorMessage', errorMessage)
        throw new Error(errorMessage)
      })
  },
  logout: () => {
    logOut()
  },
  checkAuth: () =>
    localStorage.getItem('auth') ? Promise.resolve() : Promise.reject(),
  checkError: (error: Error) => {
    throw new Error(error.message)
  },
  getPermissions: () => {
    return Promise.resolve('admin')
  },
}
```
**Related code:**

```
<Admin
        title="Robbie Admin Dashboard"
        disableTelemetry
        dataProvider={dataProvider}
        // @ts-ignore <------ login function is void()
        authProvider={authProvider}
        layout={Layout}
      >
```

**Environment**

* React-admin version: 3.19.0
* React version: 17.0.2
* Browser: Google Chrome

**Comment by fzaninotto** [comment] 2021-11-08 10:53
This is likely linked to your layout, or to the fact that your Login page requires authentication.

Please share a reproducible test case.

**Comment by kevinmamaqi** [comment] 2021-11-08 11:02
Hi @fzaninotto I am not using a login page, I thought react-admin provides a default one. Moreover I am using the Layout imported from react admin:

`import { Admin, Resource, Layout } from "react-admin";
`

**Comment by fzaninotto** [comment] 2021-11-08 11:05
So you can easily provide a test case base on the simple example codesandbox, right?

**Comment by jashwant** [comment] 2021-11-15 10:41
@kevinmamaqi , I think you need to return a `Promise` from login function, but you are returning undefined.

Default login page waits for a Promise and since your login function does not reject or resolve,  that waiting may look like infinite loop.

Does adding return before firebase help?

```` javascript
const authProvider = {
  login: ({ email, password }: UserLoginI) => {
    return firebase
      .auth()
      .signInWithEmailAndPassword(email, password)
      .then((userCredential) => {
        userCredential.user?.getIdToken().then((token) => {
          localStorage.setItem('auth', token)
          return Promise.resolve(token)
        })
      })
      .catch((error) => {
        const errorCode = error.code
        const errorMessage = error.message
        console.error('errorCode', errorCode)
        console.error('errorMessage', errorMessage)
        throw new Error(errorMessage)
      })
  },
  logout: () => {
    logOut()
  },
  checkAuth: () =>
    localStorage.getItem('auth') ? Promise.resolve() : Promise.reject(),
  checkError: (error: Error) => {
    throw new Error(error.message)
  },
  getPermissions: () => {
    return Promise.resolve('admin')
  },
}

**Comment by fzaninotto** [comment] 2021-12-22 09:36
No news for some time, closing.

**Closed by fzaninotto** 2021-12-22 09:36 UTC
Labels: needs more info
