### ISSUE TITLE
Hide loader in Reference Fields when the REST client call fails

### ISSUE THREAD

**Issue by natrim** [marmelab/react-admin#854] opened 2017-07-11 13:11 UTC
Sometimes when i return to resource list, the ReferenceArrayField is not updated and is stuck in loading state.

There is no request seen in network panel in Chrome.
And the only message is console is many of: finalize has been cancelled

I have not managed to reproduce it reliably, so i guess its some timeout thingie.

It would probably be nice if there was some timeout on the reference request?
And displaying some error icon with retry on click?

**Comment by fzaninotto** [comment] 2017-07-25 07:00
If you can't give us a reliable way to reproduce it, there is no way we can fix it...

Feel free to reopen when you have a reliable failing test case.

**Comment by natrim** [comment] 2017-07-25 07:04
well the only way i can reproduce it is to simulate network failure during fetching of the references

ie. i set slow network in chrome, and then set it to offline after fetching the list, but before the referenced fields are fetched

**Comment by fzaninotto** [comment] 2017-07-25 07:27
Just to rephrase: when your server doesn't return the response to a ReferenceArrayField request,  it lets the field in loading state. It's probably true for every Reference field (not only ReferenceArrayField).

There is currently no way the ReferenceArrayField can detect a failure in the REST client call. All it does is update when the referenced data changes. But I can see why it's a problem.

I'm reopening and marking it as an enhancement request.

**Comment by fzaninotto** [comment] 2017-07-25 07:29
As a side note, this is probably VERY difficult. For instance, some REST clients make n requests to fetch references. If only one of those requests fails, how can the concerned Reference field know about it?

**Comment by natrim** [comment] 2017-07-25 07:47
well the simplest fix would be to add one more prop named timeout (and set timeout based on it) and if it elapses and the field is still in loading state, then mark it as failed

**Comment by fzaninotto** [comment] 2017-07-25 16:18
No, handling timeout is your rest client's business. For aor, a timeout isn't different from another REST failure. And aor components don't send REST requests directly anyway, so there is no way to determine if a REST failure is related to a given component.

**Comment by llioor** [comment] 2018-02-08 14:53
@fzaninotto I think that the issue is "Too Many Attempts" (error code 429).
For example:
I have Country model and I have State model. When I edit the Country "United States" I use `<ReferenceArrayField>`  to load the States (50). In the network console I can see many requests to load all chosen States (50 requests). This can be an issue if you are using "throttling" in your API. If I go back to the list or refresh the page I got "429" error code and the `<ReferenceArrayField>` is stuck in loading status.

**Comment by djhi** [comment] 2018-02-09 10:38
This particular case depends on your `restClient`: the `ReferenceArrayField` actually make a `CRUD_GET_MANY_ACCUMULATE` action (accumulating all requested ids) and ends up with a final `CRUD_GET_MANY`.

Depending on your restClient, this final `CRUD_GET_MANY` may end up with multiple get requests but an optimized one should make only one request and retrieve all specified resources

**Comment by llioor** [comment] 2018-02-10 08:59
@djhi Got it!

**Comment by curtisolson** [comment] 2018-08-29 17:44
I had a case where the server was responding with data, but I didn't include the Content Range header in my response. So the data was returned, but the progress spinner just stayed on. Very confusing to troubleshoot. I added it as a question+answer on stackoverflow in case it helps someone else.

[https://stackoverflow.com/questions/52083078/referenceinput-field-shows-progress-bar-but-never-resolves/52083079#52083079](https://stackoverflow.com/questions/52083078/referenceinput-field-shows-progress-bar-but-never-resolves/52083079#52083079)

**Comment by fzaninotto** [comment] 2019-08-22 08:08
fixed by #3550

**Closed by fzaninotto** 2019-08-22 08:08 UTC
Labels: enhancement
