### ISSUE TITLE
Warning: Invalid value for prop `refetch` on <div> tag.

### ISSUE THREAD

**Issue by ryanmstokes** [marmelab/react-admin#6455] opened 2021-07-21 07:06 UTC
**What you were expecting:**
To run the simplest implementation of the application without any warnings. 

**What happened instead:**
The app runs but a warning occurs:

Warning: Invalid value for prop `refetch` on <div> tag (See below for more details)

**Steps to reproduce:**
```
git clone https://github.com/ryanmstokes/react-admin-typescript.git
yarn
yarn start
```
then check web dev console to see warning.

**Environment**

* React-admin version: ^3.17.0
* Last version that did not exhibit the issue (if applicable):
* React version: ^17.0.2
* Browser: All
* Stack trace (in case of a JS error):
```
index.js:1 Warning: Invalid value for prop `refetch` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at div
    at ListView (http://localhost:3002/static/js/vendors~main.chunk.js:127608:23)
    at ListViewGuesser (http://localhost:3002/static/js/vendors~main.chunk.js:127416:19)
    at ListContextProvider (http://localhost:3002/static/js/vendors~main.chunk.js:82814:18)
    at ListGuesser (http://localhost:3002/static/js/vendors~main.chunk.js:127409:90)
    at WithPermissions (http://localhost:3002/static/js/vendors~main.chunk.js:81151:23)
    at Route (http://localhost:3002/static/js/vendors~main.chunk.js:167183:29)
    at Switch (http://localhost:3002/static/js/vendors~main.chunk.js:167385:29)
    at ResourceContextProvider (http://localhost:3002/static/js/vendors~main.chunk.js:90074:21)
    at ResourceRoutes (http://localhost:3002/static/js/vendors~main.chunk.js:89940:17)
    at Resource (http://localhost:3002/static/js/vendors~main.chunk.js:90012:15)
    at Route (http://localhost:3002/static/js/vendors~main.chunk.js:167183:29)
    at Switch (http://localhost:3002/static/js/vendors~main.chunk.js:167385:29)
    at RoutesWithLayout (http://localhost:3002/static/js/vendors~main.chunk.js:90201:21)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3002/static/js/vendors~main.chunk.js:125025:24)
    at WithStyles (http://localhost:3002/static/js/vendors~main.chunk.js:41284:31)
    at C (http://localhost:3002/static/js/vendors~main.chunk.js:167440:37)
    at ConnectFunction (http://localhost:3002/static/js/vendors~main.chunk.js:164290:75)
    at ThemeProvider (http://localhost:3002/static/js/vendors~main.chunk.js:39986:24)
    at Layout (http://localhost:3002/static/js/vendors~main.chunk.js:125143:26)
    at Route (http://localhost:3002/static/js/vendors~main.chunk.js:167183:29)
    at Switch (http://localhost:3002/static/js/vendors~main.chunk.js:167385:29)
    at div
    at CoreAdminRouter (http://localhost:3002/static/js/vendors~main.chunk.js:89576:87)
    at Route (http://localhost:3002/static/js/vendors~main.chunk.js:167183:29)
    at Switch (http://localhost:3002/static/js/vendors~main.chunk.js:167385:29)
    at CoreAdminUI (http://localhost:3002/static/js/vendors~main.chunk.js:89792:15)
    at AdminUI
    at Router (http://localhost:3002/static/js/vendors~main.chunk.js:166818:30)
    at ConnectedRouter (http://localhost:3002/static/js/vendors~main.chunk.js:49277:7)
    at ConnectedRouterWithContext (http://localhost:3002/static/js/vendors~main.chunk.js:49400:25)
    at ConnectFunction (http://localhost:3002/static/js/vendors~main.chunk.js:164290:75)
    at TranslationProvider (http://localhost:3002/static/js/vendors~main.chunk.js:98582:28)
    at Provider (http://localhost:3002/static/js/vendors~main.chunk.js:164003:20)
    at CoreAdminContext (http://localhost:3002/static/js/vendors~main.chunk.js:89339:25)
    at AdminContext
    at Admin (http://localhost:3002/static/js/vendors~main.chunk.js:131776:22)
    at App
```

**Comment by djhi** [comment] 2021-07-22 08:01
Thanks for reporting this. I can't reproduce anymore so I'm closing this issue

**Closed by djhi** 2021-07-22 08:01 UTC
