### ISSUE TITLE
Linked inputs error: Cannot update a component from inside the function body of a different component

### ISSUE THREAD

**Issue by manuelamaria** [marmelab/react-admin#4606] opened 2020-03-30 19:12 UTC
**What you were expecting:**
I have two linked inputs on a form - a SelectInput and a CheckboxGroupInput. I expect to be able to change the options of the group input depending on the selection in the select. For this, I use the FormDataConsumer.

**What happened instead:**
This works, so the options update in the group, but whenever I change the selection, I have a warning in the console:

```
Warning: Cannot update a component from inside the function body of a different component.
    in CheckboxGroupInput (at EditFormAlt.js:26)
    in FormDataConsumerView (created by FormDataConsumer)
    in FormDataConsumer (at EditFormAlt.js:23)

```
**Related code:**

```
<SimpleForm {...props}>
    <SelectInput source='provider' choices={providerChoices} />
    <FormDataConsumer>
        {({ formData, ...rest }) =>
            formData.provider && (
                        <CheckboxGroupInput
                            source='correlations'
                            choices={getByProvider(formData.provider)}
                        />
            )
         }
    </FormDataConsumer>
</SimpleForm>
```

**Other information:**

**Environment**

* React-admin version: 3.2.1
* React version: 16.13.0
* Stack trace (in case of a JS error):
```
index.js:1437 Warning: Cannot update a component from inside the function body of a different component.
    in CheckboxGroupInput (at EditFormAlt.js:26)
    in FormDataConsumerView (created by FormDataConsumer)
    in FormDataConsumer (at EditFormAlt.js:23)
    in div (created by FormInput)
    in FormInput (created by SimpleFormView)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by CardContentInner)
    in CardContentInner (created by SimpleFormView)
    in form (created by SimpleFormView)
    in SimpleFormView (created by FormView)
    in FormView (created by ReactFinalForm)
    in ReactFinalForm (created by FormWithRedirect)
    in FormWithRedirect (created by SimpleForm)
    in SimpleForm (at EditFormAlt.js:20)
```

**Comment by fzaninotto** [comment] 2020-03-30 19:57
Duplicate of #4572

**Closed by fzaninotto** 2020-03-30 19:57 UTC
