### ISSUE TITLE
Allow usage of BulkDeleteButton with undoable=false in non-list pages

### ISSUE THREAD

**Issue by sebitoelcheater** [marmelab/react-admin#4943] opened 2020-06-15 05:27 UTC
**What you were expecting:**
In List component of a resource, when I select one element to delete with a BulkDeleteButton with `undoable` prop set to false, a confirmation dialog is open. When I click confirm, the dialog should disappear after the deletion.

**What happened instead:**
The dialog remains open.
![error-bulk-delete-ra](https://user-images.githubusercontent.com/2347536/84620994-7097f600-aea7-11ea-8959-3b6001e46009.gif)

**Steps to reproduce:**
```
const AssetBulkActionButtons = props => (
    <Fragment>
      <BulkDeleteButton {...props} undoable={false}/>
    </Fragment>
);

<List {...props} bulkActionButtons={<AssetBulkActionButtons/>}>
...
```

**Environment**
* React-admin version: 3.5.5
* Last version that did not exhibit the issue (if applicable): 2.x.x
* React version: 16.13.1
* Browser: Chrome
* Stack trace (in case of a JS error): -

**Comment by djhi** [comment] 2020-06-15 06:21
I can't reproduce this issue on our simple example. Please provide a sample application based on this [CodeSandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by a-pavlov-parc** [comment] 2020-07-16 17:10
I have the same issue with the undoable DeleteButton component. I checked the sources and I don't see it is supposed to be closed on success
![image](https://user-images.githubusercontent.com/8544449/87701276-6025b480-c7a0-11ea-83d9-6f4219913c02.png)

**Comment by Luwangel** [comment] 2020-07-22 13:34
Hello @sebitoelcheater and @a-pavlov-parc 

Just like @djhi, I cannot reproduce the described bug on the Simple Example. See my [Code Sandbox](https://codesandbox.io/s/young-sunset-p7k0x?file=/src/posts/PostList.js).

Maybe it comes from your code or from an old version of React-Admin.

I'm closing this issue for the moment. Don't hesitate to reopen it if you can reproduce it on CodeSandbox.

Regards,
Adrien

**Comment by a-pavlov-parc** [comment] 2020-07-22 13:38
@Luwangel in order to reproduce this you must perform editing on the list page, you're doing this on another one. In your case, it does redirection after successful deleting, in our case it does not because the page it's going to redirect to is the same page where we are staying at the moment

**Comment by fzaninotto** [comment] 2020-07-28 17:01
I suppose we could reopen this one. It would make the BulkDeleteButton usable when the Datagrid is embedded in other pages - at the price of an additional render. Not that bug a deal.

**Closed** 2020-08-03 11:37 UTC
Labels: enhancement, good first issue
