### ISSUE TITLE
RichTextInput doesn't accept defaultValue prop

### ISSUE THREAD

**Issue by manolisan** [marmelab/react-admin#2465] opened 2018-10-24 09:49 UTC
**What you were expecting:**
Using a component like that `<RichTextInput defaultValue="<p>Hello</p>" />` should result in a RichTextInput component having a prefiled value.

**What happened instead:**
The component renders without the default value.

**Related code:**
 `<RichTextInput defaultValue="Initial Value" />`

**Environment**

 - React-admin version: 2.3.3
 - React version: 16.3.2
 - Browser: Chrome 69.0

**Comment by fzaninotto** [comment] 2018-10-25 16:11
Confirmed and reproduced

**Comment by fzaninotto** [comment] 2018-10-25 16:13
in fact, it's a duplicate of #2464

**Comment by manolisan** [comment] 2018-10-26 17:20
I am not sure if accepting defaultValue prop will fix #2464 

#2464 is not about the default value of the RichTextInput  component. 

**Behavior of Input components on redux-change actions**
In general, on an Input component, when a redux-state change happens, the Input component should re-render it's value on React.

**Behavior of RichTextInput on redux-change actions caused by other components**
However if the componet is a RichTextInput and the redux-state change is caused by an action other than writing in that specific component _(e.g. writing on another RichTextInput component with the same source)_, it doesn't re-render it in React.

Let me know if it's clear or not, to provide you a code example in the next days.

**Closed** 2019-02-26 07:07 UTC
Labels: bug
