### ISSUE TITLE
SelectArrayInput component required validation not working

### ISSUE THREAD

**Issue by mithoska** [marmelab/react-admin#3185] opened 2019-05-01 19:35 UTC
**What you were expecting:**
My SelectArrayInput statement is:

```jsx
<SelectArrayInput 
    source="categories" 
    choices={choices} 
    optionText="name" 
    optionValue="id" 
    label="Uj Kategoriak (Kerjuk az OSSZES kategoriat ujra bejelolni!)" 
    allowEmpty={false} 
    validate={ required() }
    {...rest}
/>
```

I expected it will not allow empty arrays to be sent to the API back. Despite I got empty array back, when I do not fill in the  categories:

```
=============> $VAR1 = {
          'user' => 25,
          'spec_5' => '',
          'spec_3' => 'xcfjbfkl',
          'click_type' => 0,
          'data_6' => '',
          'spec_1' => 'bfbsbvs',
          'description' => '<p>fb xbxf</p>',
          'target_id' => 0,
          'data_1' => '30-90 nap',
          'promo_start' => '0000-00-00 00:00:00',
          'spec_2' => 'fdbrgkslgnvedbn ',
          'data_2' => "Tetsz\x{151}leges alkalommal hosszabb\x{ed}that\x{f3}",
          'title' => 'Dynamically created array length in reactJS',
          'conditions' => '',
          'status' => 0,
          'specification' => '',
          'type' => 38,
          'data_4' => '',
          **'categories' => [],**
          'start_time' => '0000-00-00 00:00:00',
          'spec_4' => '',
          'id' => '96',
          'data_3' => '',
          'image' => '',
          'time' => '2019-04-08 17:01:58',
          'data' => ''
        };
```

**What happened instead:**
it allowed empty arrays to be send back to the API

**Environment**

* React-admin version: 2.8.6
* Last version that did not exhibit the issue (if applicable):
* React version: 16.8.6
* Browser: Chrome (73.0.3683.103)
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment] 2019-06-12 06:19
I'm not able to reproduce witth the latest version. Can you fork this [Code Sandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple) with a reproducible issue?

**Comment by fzaninotto** [comment] 2019-07-08 13:59
No news for some time, closing

**Closed by fzaninotto** 2019-07-08 13:59 UTC
Labels: awaiting more info

**Comment by guilleironhack** [comment] 2019-08-20 09:05
I think I'm experiencing a similar issue, where even if validation fails, the call is made.

I reproduced it [here](https://codesandbox.io/s/simple-wf51r) (See test filter in posts list)

**Comment by djhi** [comment] 2019-08-20 09:15
That's because `required` does not validate arrays yet. I had a fix in a PR I closed without merging for v3. I'll add it back when I'll work on this component again

**Comment by guilleironhack** [comment] 2019-08-20 09:29
Shouldn't it work with a custom validate function then?

**Comment by djhi** [comment] 2019-08-20 10:38
This is an entirely different issue. We don't support validation inside filters. Otherwise, a custom validate would work
