### ISSUE TITLE
Getting URI malformed when trying to edit record with percentage (%) symbol in.

### ISSUE THREAD

**Issue by vforvaios** [marmelab/react-admin#10158] opened 2024-08-26 10:21 UTC
Hi everyone,

Using react-admin (tried both 4.16.0 and 5.1.2 version).

I have a form that tries to save a form with 2 fields: name and profession using simple TextInputs.

When I pass the following data (name: 'Test' and profession: 'Surgeon%'), the backend creates a record with the following id: Test__Surgeon%

When trying to access the edit page it goes to http://localhost/......../Test__Surgeon%25 (which is the auto encoded by the react-admin) and it says "Error: URI malformed."

What exactly is the issue here? 

Thanks in advance.

p.s.
I've the line that crashes in useEditController: `const id = propsId ?? decodeURIComponent(routeId!);`
but when I use a plain editor playground I get no error:

![image](https://github.com/user-attachments/assets/959fe245-08cc-4188-9266-4af4e5a132b8)

**Comment by fzaninotto** [comment] 2024-08-26 13:38
I managed to reproduce the problem in this Stackblitz: https://stackblitz.com/edit/github-ifstjz (click on the first post in the list to trigger the error-. 

This is probably a bug in react-admin, marking it as such.

**Comment by fzaninotto** [comment] 2024-08-26 13:50
May be caused by a recent update in react-router (6.22), see https://github.com/remix-run/react-router/pull/11199

**Comment by vforvaios** [comment] 2024-08-26 14:30
Thank you very much for your quick response. Maybe, one solution is for the backend to not create ids based on concatenation of fields, but base64 unique ids with no special characters inside.

**Comment by fzaninotto** [comment] 2024-08-26 14:55
yes, that's a good idea! But there still seems to be a double encoding issue on the react-admin side that we must fix.

**Comment by djhi** [comment] 2024-09-16 10:26
I can't reproduce this issue anymore in the provided stackblitz

**Closed** 2024-10-24 08:12 UTC
