### ISSUE TITLE
ReferenceInput with AutocompleteInput re-render with optionText function

### ISSUE THREAD

**Issue by Oupsla** [marmelab/react-admin#6422] opened 2021-07-08 08:55 UTC
**What you were expecting:**
Type something in autocompleteInput and the list is correctly filtered 

**What happened instead:**
Copy/paste something (or write it) into the autocomplete input make it re-render and the list is not correctly filtered (it goes back to the initial list, with the initial graphql query)

**Steps to reproduce:**
Create an referenceInput with an autocompleteInput that has an optionText function (like 

```js
<AutocompleteInput
   optionText={(record) => `${record.title} - ${record.id}`}
/>

```

Note : 
optionText without a function seems to works : 
```js
<AutocompleteInput
   optionText="id"
/>
```

**Related code:**

Codesandox : https://codesandbox.io/s/romantic-dubinsky-79175?file=/src/comments/CommentEdit.tsx

Go to https://79175.sse.codesandbox.io/#/comments/2  and write 'veritatis' for example, list re-render and is not filtered

Video : 

https://user-images.githubusercontent.com/15279620/124893344-eef79680-dfda-11eb-826b-8b83ea5dacef.mov

**Environment**

* React-admin version: 3.16.6

**Comment by mahdijirofti** [comment] 2021-07-11 15:09
Did you try pass memoized function to Component like this:
```
const optionText = useMemo(()=> { 
  return ((record) => `${record.title} - ${record.id}`)
 }, [])

<AutocompleteInput
   optionText={optionText}
/>
```

**Comment by djhi** [comment] 2021-07-21 15:11
> Did you try pass memoized function to Component like this:

You don't even need to memoize it, just extract it outside the component.

I can't reproduce this issue using the provided codesandbox with or without extracting the function so I'll close it. Feel free to comment if you think it still exists.

**Closed by djhi** 2021-07-21 15:11 UTC

**Comment by wmwart** [comment] 2022-12-07 05:55
I also encountered this problem in "react-admin": "3.19.10"
such a component erases the search text entered in the field after receiving the results
When optionText is not used everything works fine

```
import React, { Fragment } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core//Typography';
import { AutocompleteInput } from 'react-admin';
import { matchTrue } from '../../utils';

const useStyles = makeStyles(theme => ({
    text: { flex: "1 1 auto" },
    textSecondary: { marginLeft: theme.spacing(2) }
}), { name: "ProfileAutocompleteInputOption" });

const ProfileAutocompleteInputOption = props => {
    const { record } = props
    const classes = useStyles();
    return (
        <Fragment>
            <Typography className={classes.text}>{record.name}</Typography>
            <Typography variant='caption' color='textSecondary' className={classes.textSecondary}>{record.application?.name}</Typography>
        </Fragment>
    )
};

const inputText = choice => `${choice.name} (${choice.application.name})`;

const ProfileAutocompleteInput = (props) => {
    return (
        <AutocompleteInput
            {...props}
            optionText={<ProfileAutocompleteInputOption />}
            inputText={inputText}
            matchSuggestion={matchTrue}
        />
    );
};

export default ProfileAutocompleteInput;
```

I also note that the description of the optionText properties as a component in the documentation is incorrect

**Comment by slax57** [comment] 2022-12-08 14:44
@wmwart could you open a new issue to start fresh, and provide a repro?
Thanks
