### ISSUE TITLE
Running dist code on production not working as expected

### ISSUE THREAD

**Issue by edernucci** [marmelab/react-admin#10093] opened 2024-07-26 12:28 UTC
**What you were expecting:**
I'm trying to make a production ready distribution of react-admin example code.

**What happened instead:**
No CSS exported. Only a white screen and no errors on console.

**Steps to reproduce:**
```
npm init react-admin
cd example-admin
npm run dev # open the URL and everything is working
npm run build
serve dist/ # open the URL and now I have just a white screen
```

**Comment by adguernier** [comment] 2024-07-31 09:09
This doesn't seem to be an issue regarding react-admin, as serving a front-end application depends on your bundler and your application architecture. 

If you need assistance with this issue, you can ask for help on [stackoverflow](https://stackoverflow.com/questions/tagged/react-admin) or on our [Discord server](https://discord.gg/GeZF9sqh3N).

Closing

**Comment by lucaferri** [comment] 2024-07-31 13:08
I add the same issue a couple of days ago but now it seems to be resolved (at least for me)

**Comment by djhi** [comment] 2024-08-02 10:23
I can't reproduce this using the exact command posted by @edernucci. Closing this issue. Feel free to reopen if you provide a reproduction

**Closed by djhi** 2024-08-02 10:23 UTC
