### ISSUE TITLE
Autocomplete instantly closes when use it with useFormState

### ISSUE THREAD

**Issue by NookieNoo** [marmelab/react-admin#6883] opened 2021-11-18 20:27 UTC
**Description:**
When I try to use useFormState together with AutocompleteInput and property optionText = React.component, then when I first click on AutocompleteInput, it instantly closes, or does not open at all.

**Steps to reproduce:**
* Create AutocompleteInput with custom optionText Renderer
* Try to get values using useFormState from react-final-form
* Click on Autocomplete
* Or go to [this sandbox](https://codesandbox.io/s/react-admin-bug-fswue?file=/src/UserCreate.js), then click on "Create" button and click on AutoComplete to create user.

My form with bug:
```
import { Create, AutocompleteInput, SimpleForm } from "react-admin";
import { useFormState } from "react-final-form";
import { parthners } from "./parthners";

const OptionRenderer = ({ record, ...rest }) => {
  return <div>{record.full_name}</div>;
};

const MyAutocompleteInput = (props) => {
  const { values } = useFormState();
  // console.log(values);
  return (
    <AutocompleteInput
      label="Parthner"
      source="parthner_id"
      optionText={<OptionRenderer />}
      inputText={(record) => record.full_name}
      matchSuggestion={(filter, choice) => true}
      choices={parthners}
      optionValue={"id"}
      // suggestionLimit={10}
      resettable={true}
      emptyValue={null}
    />
  );
};

export default function UserCreate(props) {
  return (
    <Create {...props}>
      <SimpleForm>
        <MyAutocompleteInput label="Parthner" source="parthner_id" />
        <MyAutocompleteInput label="Parthner" source="parthner_id1" />
        <MyAutocompleteInput label="Parthner" source="parthner_id2" />
        <MyAutocompleteInput label="Parthner" source="parthner_id3" />
        <MyAutocompleteInput label="Parthner" source="parthner_id4" />
        <MyAutocompleteInput label="Parthner" source="parthner_id5" />
      </SimpleForm>
    </Create>
  );
}

```
![Peek 2021-11-18 22-55](https://user-images.githubusercontent.com/52598716/142490722-840cc1a6-3b16-40b4-8512-7d5f1466152e.gif)

**Environment**
* react-admin: 3.19.1
* react: 17.0.2
* Browser: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by WiXSL** [comment] 2021-11-23 13:26
I couldn't reproduce the issue you describe in the proposed sandbox. Plus, the sandbox is too simplified, and I get not related errors.
Try modifying over the original sandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)

**Comment by bacabange** [comment] 2021-11-26 16:35
@WiXSL I have same issue, I tried to reproduce it in sandbox but ReferenceInput/AutocompleteInput doesn't work. Please see PostEdit file https://codesandbox.io/s/priceless-brown-jmq8k?file=/src/posts/PostEdit.tsx

**Comment by WiXSL** [comment] 2021-11-29 19:23
@NookieNoo, this looks like a problem in the underlying Downshift component, I don't know if we could do something about it.

**Comment by WiXSL** [comment] 2021-11-29 19:24
> @WiXSL I have same issue, I tried to reproduce it in sandbox but ReferenceInput/AutocompleteInput doesn't work. Please see PostEdit file https://codesandbox.io/s/priceless-brown-jmq8k?file=/src/posts/PostEdit.tsx

@bacabange,
I don't see anything wrong with your codesandbox
Please, describe with steps how to reproduce your issue, and if it's related to a different component, open a new issue

**Comment by andrico1234** [comment] 2021-12-14 12:03
The same issue as described in here:
https://github.com/marmelab/react-admin/issues/6715

I've added a repro case in there too

**Comment by fzaninotto** [comment] 2021-12-22 09:26
I'm closing this issue as a ducpliate. Feel free to comment if you think it's a different issue.

**Closed by fzaninotto** 2021-12-22 09:26 UTC
Labels: needs more info
