### ISSUE TITLE
Do not fetch if there are invalid filter inputs

### ISSUE THREAD

**Issue by alfredorevilla** [marmelab/react-admin#6283] opened 2021-05-16 03:36 UTC
**Is your feature request related to a problem? Please describe.**
Currently fetch will be done regardless of filters inputs validation state

**Describe the solution you'd like**
Fetch should not be done if a filter input validation fails

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fzaninotto** [comment] 2021-06-08 16:47
Duplicate of #1207

**Closed by fzaninotto** 2021-06-08 16:47 UTC
Labels: bug
