### ISSUE TITLE
[v4 typescript] `<MenuItemLink>` seems now have missing placeholder prop

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#9507] opened 2023-12-11 00:29 UTC
**What you were expecting:**
I expect when I follow the tutorial there would be no type error https://marmelab.com/react-admin/Buttons.html#menuitemlink

**What happened instead:**
There is a type related error

```
Property 'placeholder' is missing in type '{ to: string; primaryText: string; }' but required in type 'Pick<MenuItemLinkProps, "replace" | "slot" | "style" | "title" | "children" | "role" | "action" | "about" | "security" | "primaryText" | "id" | "type" | "key" | ... 275 more ... | "tooltipProps">'.(2741)
```

**Steps to reproduce:**
Go to the example below
Run $ yarn type-check and look for errors in the src/Layout.tsx file

**Related code:**
https://stackblitz.com/edit/github-cubnvw?file=src%2FLayout.tsx

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 4.16.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: Safari
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2023-12-11 12:05
Thanks for the feedback. I can't reproduce the problem locally.

Can you give more information about how you built the repro in Stackblitz?

I noticed that your stackblitz uses React 17 but ` "@types/react"` version 18.2.43. I wonder if this may be the cause.

**Comment by panfiva** [comment] 2023-12-12 03:14
@fzaninotto , I noticed the same issue in my project as soon as I updated "@types/react": "^18.2.42" -> "@types/react": "^18.2.43"

After I added `"@types/react": "18.2.42"` to `resolutions` in `package.json`, my build worked properly

**Comment by fzaninotto** [comment] 2023-12-12 19:01
So this seems to be a react types error. I invite you to open an issue in their repository.

**Comment by panfiva** [comment] 2023-12-13 03:23
it appears the issue is resolved in "@types/react": "18.2.45"

**Comment by smeng9** [comment] 2024-01-02 06:06
Hi @fzaninotto 

Adding a backlink to the PR that causes this issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170

Shall we consider a quick fix by omitting the `placeholder` prop here https://github.com/marmelab/react-admin/blob/ab2e448a6746081ea6c387484754a68cd9464f15/packages/ra-ui-materialui/src/layout/MenuItemLink.tsx#L143

**Comment by fzaninotto** [comment] 2024-01-03 09:53
@smeng9 Seems a sensible solution. Would you like to open a PR about it?

**Closed** 2024-01-04 10:45 UTC
Labels: bug
