### ISSUE TITLE
Incorrect payload is passed when Edit is submitted twice with different records

### ISSUE THREAD

**Issue by lckj210** [marmelab/react-admin#2036] opened 2018-07-19 05:29 UTC
I have a json backend that returns the following records:

```
[  
   {  
      "id":"1",
      "field": "value1",
      ...
   },
   {  
      "id":"2",
      "field": "value2",
      ...
   },
]
```

I have a simple List and Edit View, with Edit that has the following fields.
```
  <Edit>
    <SimpleForm>
      <TextInput source="field" />
    // Other inputs that is not id
    </SimpleForm>
  </Edit>
```

When I edit and save the first record, everything works as expected.
If I edit the second record immediately after saving the first record, the payload is passed with "id" as "1", instead of "2".

This doesn't happen if I have `<TextInput source="id" />` in the simple form.

The bug only appeared in v2.1.2. v2.1.0 was working fine for me.
I suspect that is related to the addition of `keepDirtyOnReinitialize: true` in SimpleForm in #1997, although I am not 100% sure.

Appreciate if anyone can help, thanks!

**Comment by djhi** [comment] 2018-07-19 06:59
Duplicate of #2021. Thanks for the detailed report though

**Closed by djhi** 2018-07-19 06:59 UTC
