### ISSUE TITLE
display validation errors for <ImageInput>

### ISSUE THREAD

**Issue by jamesjwarren** [marmelab/react-admin#1611] opened 2018-03-05 17:50 UTC
**What you were expecting:**
ImageInput to display validation errors eg. "Required" as per the other input fields.

**What happened instead:**
No validation error messages displayed.

**Steps to reproduce:**
Use the ImageInput component in a create or edit form, either with a validation function or `maxSize` property. Submit the form. The form is not submitted but not validation errors are displayed.

**Related code:**

```jsx
<ImageInput
  source="image"
  label="Image"
  accept="image/*"
  maxSize={1}
  validate={[required]}
>
  <ImageField source="src" />
</ImageInput>
```

**Environment**

* Admin-on-rest version: 1.3.4
* React version: 15.6.2
* Browser: Chrome 64

**Comment by fzaninotto** [comment] 2018-12-13 19:53
Fixed by #2660

**Closed by fzaninotto** 2018-12-13 19:53 UTC
Labels: enhancement, hacktoberfest

**Comment by jasonlimantoro** [comment] 2021-04-07 04:00
What about the `maxSize` property?
I see `required()` is displayed, but it would be nice to tell a user something when a file is rejected for whatever reason (e.g. File is too large).
Is there anyway to get this behavior?

**Comment by fzaninotto** [comment] 2021-04-09 23:41
For File and ImageInput, there is already a minSize and a maxSize property, see https://marmelab.com/react-admin/Inputs.html#imageinput

**Comment by jasonlimantoro** [comment] 2021-04-10 08:48
I’m aware of those two properties. But it does not display any error or messages after the file was rejected, at least not by default.

**Comment by fzaninotto** [comment] 2021-04-12 05:21
Can you please open a new issue then? don't forget to include a link to a CodeSandbox reproducing the problem (the simple CodeSandbox already has a FileInput in the CreatePost page).

**Comment by nosequeldeebee** [comment] 2022-09-05 22:31
Duplicate of #6441
