### ISSUE TITLE
Console warnings about "history" package

### ISSUE THREAD

**Issue by handreistoicescu** [marmelab/react-admin#3140] opened 2019-04-18 13:53 UTC
**What you were expecting:**
I'd expect no console warnings.

**What happened instead:**
Four console warnings about require("history").createBrowserHistory, createHashHistory, createMemoryHistory and .PathUtils.

**Steps to reproduce:**
Follow the [Official Tutorial](https://marmelab.com/react-admin/Tutorial.html) until and including the step "Making Contact With The API Using a Data Provider".

**CodeSandbox:**
https://codesandbox.io/s/4xnw6ow6q4

**Other information:**
I really hope this issue won't be closed in the same arrogant, non-explanatory way the other issues regarding the same problem were closed before by the react-admin team. I mean, collaboration is the crux of open-source, otherwise I don't see why this isn't a private repo.

**Comment by fzaninotto** [comment] 2019-04-18 15:12
Dear @handreistoicescu, thanks for bringing that to our attention a second time, this time following the Issue template.

More than half of the bug reports opened by react-admin users (that means about 1,500 issues so far) concern problems with their code, not the react-admin code. That's why we consider that there is no bug until someone can give us a way to reproduce it. Sometimes we close a real bug like #3138 because it's not properly described. I'm sorry for that. Note that this bug didn't show up in our local tests.

I understand your frustration, but please refrain from showing your anger. The software you're using required years of hard work from the core team and outside collaborators, for which none gets paid. Finally, calling us names is probably the worst way to make us listen to you. Don't do that again or you'll be banned, no further warning.

I'm closing this one as a duplicate of your previous issue #3138, that I've reopened. The (gentle) discussion can continue over there.

**Closed by fzaninotto** 2019-04-18 15:12 UTC
