### ISSUE TITLE
AutocompleteArrayInput makes an empty chip when you click tab key, on blur action

### ISSUE THREAD

**Issue by sgonzaloc** [marmelab/react-admin#4801] opened 2020-05-13 02:48 UTC
**What you were expecting:**
When I use _AutocompleteArrayInput_ if I wrote an option that is not in the choices, and then I click on _tab key_, an empty chip is added to the input. For example if I wrote the label _someOptionNotIncludedInChoices_, I would expect to have a chip with this label.

**What happened instead:**
An empty chip is added.

**Steps to reproduce:**
Just add _AutocompleteArrayInput_ and write a choice not included in all choices

**Here the snapshots:**

1. All choices
![allChoices](https://user-images.githubusercontent.com/6353386/81764996-289d4200-94a9-11ea-8866-34ba368e1e49.png)

2. The label that I wrote
![NotIncludedInChoices](https://user-images.githubusercontent.com/6353386/81765143-744feb80-94a9-11ea-8084-db64b6b1a801.png)

3. The empty field results after click on tab key
![emptyChipAfterTabKey](https://user-images.githubusercontent.com/6353386/81765187-8762bb80-94a9-11ea-98dc-86e94eebd860.png)

**Environment**

* React-admin version: 2.9.9
* React version: 16.8.4
* Browser: 81.0.4044.138

**Comment by fzaninotto** [comment] 2020-05-13 05:07
I can't reproduce it on 3.x, this was probably fixed long ago.

React-admin 2.9 is no longer maintained by the core team, so a fix for this will come from the community. We recommend that you upgrade to react-admin v3.

**Comment by WiXSL** [comment] 2022-03-24 19:06
This was fixed in version 3 years ago. I don't think it makes sense to maintain this one open for version 2.
If you think  this could still be helpful, please ask us to re-open it

**Closed by WiXSL** 2022-03-24 19:06 UTC
Labels: bug, v2
