### ISSUE TITLE
BulkActionButtons not showing after selecting rows

### ISSUE THREAD

**Issue by pnwk112** [marmelab/react-admin#8288] opened 2022-10-21 08:55 UTC
BulkActionButtons doesn't show up when I select rows in a list that is inside Tab. I have many Lists in my app and it works fine  but not when it is inside Tab. I tried adding BulkActionButtons as component but still no luck. Any ideals?

**Related code:**

```
    <TabbedShowLayout>
      <Tab label="Tab1">
       .....
      </Tab>
      <Tab label="Tab2">
        <List>
          <ReferenceArrayField source="users" reference="forms" target="id">
            <Datagrid>
             ......
            </Datagrid>
          </ReferenceArrayField>
          </List>
        </Tab>
  </TabbedShowLayout>
```

**Environment**

* React-admin version: 3.19.11
* React version: 17.0.2
* Stack trace (in case of a JS error): no errors in console

**Comment by slax57** [comment] 2022-10-21 09:56
Not sure you're supposed to add a `<List>` inside your `<Tab>`. Can you try to remove it?

Also, it would greatly help us if you could provide a reproduction sandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/3.x/examples/simple

Thanks

**Comment by pnwk112** [comment] 2022-11-08 09:15
I removed List component and added hasBulkActions={true} to Datagrid but it didn't fix the issue. Any ideas if there is any way to select rows inside Tab? Thanks for any help.

**Comment by fzaninotto** [comment] 2022-11-08 09:17
No, we can't reproduce the issue. Please provide a reproduction so we can understand in which particular case the problem occurs.

**Comment by fzaninotto** [comment] 2022-12-01 17:45
No news for some time, closing.

**Closed by fzaninotto** 2022-12-01 17:45 UTC
Labels: needs more info, v3
