### ISSUE TITLE
Pagination resets to page 1

### ISSUE THREAD

**Issue by devcodeash** [marmelab/react-admin#6474] opened 2021-07-28 16:44 UTC
If we use a custom label for a resource pagination is reset to page 1 if we click page 2,3,4 or next button.
If i remove the options pagination works perfectly.

"react-admin": "^3.17.0"

```JSX
<Resource
      name="inviteCodes"
      options={{ label: 'Invite Codes' }}
      list={InviteCodeList}
      create={InviteCodeCreate}
      icon={InviteCodeIcon}
      show={InviteCodeShow}
      edit={InviteCodeEdit}
/>
```

**Comment by fzaninotto** [comment] 2021-07-28 19:00
Duplicate of #6442 
Duplicate of #6421

**Closed by fzaninotto** 2021-07-28 19:00 UTC
