### ISSUE TITLE
Not registering a field can cause the record context and form context to get out of sync after updating.

### ISSUE THREAD

**Issue by nathan-britten** [marmelab/react-admin#7004] opened 2021-12-16 12:54 UTC
Not registering a field can cause the record context and form context to get out of sync after updating.

**What you were expecting:**

When we create a new entry in an array input then click save it is added to the record on the server. Then we return it as part of the response to the update. The data in the form state is in sync with the retrieved record.

**What happened instead:**

At the moment the data in the form state is out of sync with the data retrieved in the record.  After saving, any additional information we get back from the server will be made available via the record context, but won't be part of the form context.  That means then when we save, any new fields will not be sent over to the data provider (or they will, but set to null, which could cause problems when updating the record

**Steps to reproduce:**

1. Create a new backlink
2. Save
3. View the formstate and record which are logging in the console, you can see the ID is not reapplied back to the form.
 
**Related code:**
https://codesandbox.io/s/sweet-water-3plur?file=/src/dataProvider.tsx

**Other information:**
To fix the issue we patched one of the changes made in 3.19.3: https://github.com/marmelab/react-admin/pull/6932/commits/2d15eb52ddb6959269dfb135c0b6d76a40a42279

Reverting the change in useInput.ts file causes everything to work as expected:

initialValue,
initialValue: get(record, source, initialValue),

**Environment**

* React-admin version: 3.19.3
* Last version that did not exhibit the issue (if applicable): 3.19.2
* React version: 17.0.2
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2021-12-16 18:10
Is this what you are talking about:

![2021-12-16 150751](https://user-images.githubusercontent.com/8268610/146425679-18835140-59b9-4a24-bf02-4193fe443fd9.gif)

I'm really not sure if this is a bug

**Comment by andrico1234** [comment] 2021-12-16 19:42
I guess this is a tricky area. 

My gut reaction is that the form state should sync with record on update. I can't think of any scenario of when we wouldn't want that to happen.

While this specific scenario may seem like an edge case, there are common cases where this would cause problems. One is when uploading a file using the FileInput. If we follow the similar repro steps above, the FileInput would still hold a reference to the file we just uploaded, meaning if we press save again we'll try and upload the file again.

I'm recreated this locally and will move it to the codesandbox and share.

**Comment by andrico1234** [comment] 2021-12-17 09:13
Here's the repro case for uploading files.

https://codesandbox.io/s/long-moon-mwe7z?file=/src/dataProvider.tsx

**Comment by WiXSL** [comment] 2021-12-29 11:37
@nathan-britten,
I can't reproduce it anymore by creating, see attached image. 
Can you explain how to reproduce it.

You say the `id` field is not in the formState, but the form doesn't have a `id` field, I don't know if it should be there to start with

![2021-12-29 083512](https://user-images.githubusercontent.com/8268610/147658306-069a837b-e94f-4d3d-a15f-017734ecfaec.png)

**Comment by fzaninotto** [comment] 2022-07-21 16:56
No news for some time, closing.

**Closed by fzaninotto** 2022-07-21 16:56 UTC
Labels: needs more info
