### ISSUE TITLE
<submitOnEnter> in props of SaveButton is not working

### ISSUE THREAD

**Issue by sbyeol3** [marmelab/react-admin#4672] opened 2020-04-10 06:40 UTC
**What you were expecting:**
I customized <Toolbar> component including 'SaveButton'.
And I added props 'submitOnEnter' as 'true' in 'SaveButton'
But it isn't working. I have to directly click to work Button click event.

**What happened instead:**
I want to make click event just pressing enter

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
      <SaveButton
        submitOnEnter={true}
        redirect={() => (props.record.readyIds.length > 0 ? `${props.record.readyIds[0]}` : '/receipts')}
        undoable={false}
      />
```

**Other information:**

the other 'Button' in 'Toolbar' is clicked using pressing enter

**Environment**

* React-admin version: 3.1.2
* Last version that did not exhibit the issue (if applicable): i don't know
* React version: 16.10.2
* Browser: Chrome
* Stack trace (in case of a JS error): none

**Comment by djhi** [comment] 2020-04-10 06:46
Please provide a codesandbox showing the issue

**Comment by sbyeol3** [comment] 2020-04-10 07:02
sorry.  https://codesandbox.io/s/ecstatic-mcnulty-w040g?file=/src/Receipts/ReceiptEdit.js
my codes are in Receipts Directory.

**Comment by jdemangeon** [comment] 2020-04-14 07:15
Hello @sbyeol3 ! I'm not able to reproduce our error in codesandbox because of a 404 error. Can you fix it ?

**Comment by fzaninotto** [comment] 2020-06-02 21:54
No news for some time, closing. 

Note that `submitOnEnter` seems to work fine in the [simple example](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple): In the Post Create toolbar, I can submit the form by pressing Enter.

**Closed by fzaninotto** 2020-06-02 21:54 UTC
Labels: needs more info
