### ISSUE TITLE
Add loading property to List component which does not fetch data until set to false

### ISSUE THREAD

**Issue by wattry** [marmelab/react-admin#5514] opened 2020-11-11 09:57 UTC
**Is your feature request related to a problem? Please describe.**
We wanted to filter a list based on the input received from a referenceInput filter however the data is not available until the referenceInput's request is resolved. We'd like to be able to pass a loading prop to the list component and only once the props is set to false then fetch the list data. This will allow use to set the defaultFilterValues before the list is populated and provide the filterValues context object throughout our application. Making client will be aware of the filters set on the backend before the list is populated.

**Describe the solution you'd like**
Add an optional loading prop to a lists props and if set to true then do not fetch list data otherwise if not provided or false then fetch the data. This should also be applied to the lists context provider.

**Comment by fzaninotto** [comment] 2020-11-12 13:01
Since v3.10, the `<ReferenceInput>` implements a `ListContext`, so you can grab the loading state in children components as follows:

```jsx
const { loading } = useListContext();
```

Does that solve your problem? 

As we're switching between injecting props to using context in children, we won't be injecting a loading prop to the ReferenceInput children. Also, the loading state of the ReferenceInput is a combination between the loading state of the current selection, and the loading state of the possible choices. Not sure which one you're interested in.

**Comment by wattry** [comment] 2020-11-12 16:04
Thanks for your response. We aren't looking to change or modify the behavior of the ReferenceInput but rather the List component. We'd like to delay fetching the List data until the reference input has fetched the ids of the entries a user is allowed to view. Here is any example.

```
const Filter = props => {
  return <Filter>
      <ReferenceInput source="groups" alwaysOn reference="user-groups" resettable={true} >
        <SelectInput optionText={({ name, can }) => `${name} - ${can}`} />
      </ReferenceInput>
    </Filter>
}


const DeviceList = props => {
  const groupStore = useSelector(state => state.admin.resources['user-groups'].data);
  const [defaultFilters, setDefaultFilters] = useState({ service_type: 'org' });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const groups = Object.keys(Object.assign({}, groupStore)).filter(group => group !== 'fetchedAt');

    if (groups.length > 0) {
      setDefaultFilters(prevFilters => ({ ...prevFilters, service_group: groups }));
      setLoading(false);
    }
  }, [groupStore])

  return (<List
    {...props}
    filterDefaultValues={defaultFilters}
    filters={<Filter />}
    loading={loading}
  >
    ...
  </List>)
}
```
The list will then only be able to able to get entries from groups the user is not in. This will allow us to have the users groups throughout the application using the lists useListContext() to get all the filters and not just the service_type. This also helps us from making a request until we we have the actual filtered request we need to make.

**Comment by fzaninotto** [comment] 2020-11-12 17:52
Well, this is a corner case that react-admin components don't currently handle, and I'm not sure we want to handle it in the future. It seems really specific, and delaying the fetching of options would cause perf regressions if enabled by default. 

I suggest you implement your own ReferenceInput logic using the hooks provided by react-admin, or by hand. 

So I'm closing this issue as we won't address it in the core.

**Closed by fzaninotto** 2020-11-12 17:52 UTC
Labels: needs more info
