### ISSUE TITLE
arning: Failed prop type: The prop `onExited` of `ForwardRef(Snackbar)` is deprecated

### ISSUE THREAD

**Issue by kulame** [marmelab/react-admin#6580] opened 2021-09-12 11:50 UTC
**What you were expecting:**

```javascript
index.js:1 Warning: Failed prop type: The prop `onExited` of `ForwardRef(Snackbar)` is deprecated. Use the `TransitionProps` prop instead.
    at Snackbar (http://localhost:3000/static/js/vendors~main.chunk.js:25489:22)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:42464:31)
    at Notification (http://localhost:3000/static/js/vendors~main.chunk.js:131915:31)
    at div
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:41166:24)
    at Login (http://localhost:3000/static/js/vendors~main.chunk.js:111866:21)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:173414:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:173616:29)
    at CoreAdminUI (http://localhost:3000/static/js/vendors~main.chunk.js:94865:18)
    at AdminUI
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:173045:30)
    at ConnectedRouter (http://localhost:3000/static/js/vendors~main.chunk.js:52635:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/vendors~main.chunk.js:52758:25)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:170463:75)
    at TranslationProvider (http://localhost:3000/static/js/vendors~main.chunk.js:103659:28)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:170174:20)
    at CoreAdminContext (http://localhost:3000/static/js/vendors~main.chunk.js:94412:28)
    at AdminContext
    at Admin (http://localhost:3000/static/js/vendors~main.chunk.js:137927:25)
    at App
```
**What happened instead:**

clean output 

**Environment**

    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "axios": "^0.21.4",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "^3.18.0",
    "react": "^17.0.2",
    "react-admin": "^3.18.1",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"

**Comment by davidhenley** [comment] 2021-09-13 20:14
I get the same errors now with 3.18.1

**Comment by fzaninotto** [comment] 2021-09-14 09:37
Duplicate of #6451

**Closed by fzaninotto** 2021-09-14 09:38 UTC
