### ISSUE TITLE
Filter not clearing on menu button click

### ISSUE THREAD

**Issue by slhawkins** [marmelab/react-admin#1823] opened 2018-05-12 05:08 UTC
**What you were expecting:**
If I'm looking at a list that is filtered via the URL such as (decoded) `?filter={"id":1}`, I expect to easily clear the filter by pressing the menu button of that same resource.

This is perhaps a duplicate to #1747. I applied the filter via a link from elsewhere, with no filtering normally present on this page. That is why I expected it to remove the filter.

**What happened instead:**
When I clicked on the menu button, the query/filter is removed from the URL but the same GET request with the filter is made to the API as when the filter was in the URL. So the same data is fetched and nothing changes.

**Steps to reproduce:**
This can be reproduced by adding the filter such as the one above - `?filter=%7B%22id%22%3A1%7D` - to any given resource with a list.

**Other information:**
The problem can be traced back to [ListController.js#L103](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.js#L103). The lines are:

```
            this.updateData(
                Object.keys(nextProps.query).length > 0
                    ? nextProps.query
                    : nextProps.params
            );
```

Because there is no longer a query in the URL, it uses `nextProps.params` for the update. That value is pulled from the redux state. So somewhere I believe the action `CRUD_CHANGE_LIST_PARAMS` is not being dispatched.

**Environment**

* React-admin version: 2.0.0-RC3
* React version: 16.3.2
* Browser: Chrome

**Comment by fzaninotto** [comment] 2018-05-13 17:06
Yes, it's a duplicate of #1747

**Closed by fzaninotto** 2018-05-13 17:06 UTC
