### ISSUE TITLE
No rule to make target 'watch'

### ISSUE THREAD

**Issue by batbyR** [marmelab/react-admin#2977] opened 2019-03-08 16:27 UTC
**What you were expecting:**
I am using react-admin as a dependency and I want to link my project to my local sources.
After linking the two folders, I tried to watch the files with the command line `make watch` as explained in the readme file.

**What happened instead:**
There are no rule `watch`in the react-admin makefile

![image](https://user-images.githubusercontent.com/13064661/54040417-9a06a400-41c5-11e9-9991-e38f0af96c51.png)

**Steps to reproduce:**
Follow the documentation :
```sh
# in myapp
# install react-admin from GitHub in another directory
$ cd ..
$ git clone git@github.com:marmelab/react-admin.git && cd react-admin && make install
# replace your node_modules/react-admin by a symbolic link to the github checkout
$ cd ../myapp
$ npm link ../react-admin/packages/react-admin
# go back to the checkout, and replace the version of react by the one in your app
$ cd ../react-admin
$ npm link ../myapp/node_modules/react
$ make watch
# in another terminal, go back to your app, and start it as usual
$ cd ../myapp
$ npm run
```

**Environment**

* React-admin version: 2.7.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

Thank you for your help!

**Comment by fzaninotto** [comment] 2019-03-08 17:13
Duplicate of #2880

**Closed by fzaninotto** 2019-03-08 17:13 UTC
