### ISSUE TITLE
Next button not working in Pagination

### ISSUE THREAD

**Issue by techmodule** [marmelab/react-admin#6442] opened 2021-07-17 03:05 UTC
I have use "react-admin": "^3.17.0",
But i have problem for Next button in Pagination, it is not working.
![bug next button](https://user-images.githubusercontent.com/372715/126023422-4cb1b681-9da6-4aa5-a3f1-4839cd00da23.png)
**I check my API server by change url in browers.**
`http://localhost:3000/#/events?displayedFilters=%7B%7D&filter=%7B%7D&order=ASC&page=1&perPage=10&sort=id`
**Change the page=1 to page=2**
`http://localhost:3000/#/events?displayedFilters=%7B%7D&filter=%7B%7D&order=ASC&**page=2**&perPage=10&sort=id`
**it is worked well.**
![change url](https://user-images.githubusercontent.com/372715/126023501-b7254cf1-e2b3-4126-9fa7-d17f9ae4f3d9.png)

**But Next button same disable.**
P/S: I try to change by use "ra-data-json-server": "^3.17.0", with the tutorial [https://marmelab.com/react-admin/Tutorial.html](url), it is still not working

**Comment by chadfaurie** [comment] 2021-07-19 10:03
I think this is related to a change in material UI as I had similar issues with table components

**Comment by scheiblr** [comment] 2021-07-19 16:07
Might be this issue: https://stackoverflow.com/questions/67077267/react-material-ui-tablepagination-onchangepage-is-not-a-function ?
I have the same problems with paginations. An error is thrown, though: `Uncaught TypeError: onChangePage is not a function`

**Comment by fzaninotto** [comment] 2021-07-20 15:28
Yes, I believe it's a duplicate of #6421. Material-ui has published a breaking change in a minor version, there is nothing we can do on our side, we have to wait for them to fix it on their side and publish the fix in a new minor release. You can add your vote to https://github.com/mui-org/material-ui/issues/27192#issuecomment-877117148, or contribute a patch there, to get this fixed faster.

**Closed by fzaninotto** 2021-07-20 15:28 UTC
