### ISSUE TITLE
RichTextInput text does not reorder in SimpleFormIterator

### ISSUE THREAD

**Issue by chloelangston** [marmelab/react-admin#7118] opened 2022-01-20 17:26 UTC
**What you were expecting:**
RichTextInput text to reorder with the rest of the SimpleFormIteratorItem inputs. Other inputs, like TextInput reorder fine.

**What happened instead:**
The RichTextInput text stays in its place while the other inputs reorder properly. (If I switch the RichTextInput to a TextInput, it reorders fine.)
![rich_text_reorder_bug](https://user-images.githubusercontent.com/12164376/150389806-f13b189c-ddcd-468c-b828-edd446154c24.gif)

**Steps to reproduce:**
Here is a link to a CodeSandbox where you can reproduce the issue: https://codesandbox.io/s/immutable-sea-x1fyi?file=/src/posts/PostEdit.tsx:4758-5217
* Navigate into a post
* Navigate to the "Body" tab
* Create two new items
* Reorder them
* Notice how the TextInput reorders fine, but the RichTextInput does not

**Related code:**
Link to CodeSandbox: https://codesandbox.io/s/immutable-sea-x1fyi?file=/src/posts/PostEdit.tsx:4758-5217

```
<FormTab label="post.form.body">
  <ArrayInput label="Content sections" source="content.sections">
    <SimpleFormIterator>
      <TextInput source="description" label="TEXT" />
      <RichTextInput
        source="body"
        label="A"
        validate={required()}
      />
    </SimpleFormIterator>
  </ArrayInput>
</FormTab>
```

**Other information:**
The input itself seems to be moving correctly and its ID changes accordingly to match the proper new index. Only the text does not move accordingly.

**Environment**

* React-admin version: 3.19.0
* ra-input-rich-text version: 3.2.2
* Last version that did not exhibit the issue (if applicable):
* React version: 16.14.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2022-01-20 17:32
Thanks for the report. 
But this is a duplicate of #6722

**Closed by WiXSL** 2022-01-20 17:32 UTC

**Comment by chloelangston** [comment] 2022-01-20 17:35
Oh ok, thank you. Is there an update on if this will be fixed?

**Comment by WiXSL** [comment] 2022-01-20 17:36
I'll try to take a look at it tomorrow
