### ISSUE TITLE
The AutoCompleteInput Form always reloaded when type some string

### ISSUE THREAD

**Issue by oktarama96** [marmelab/react-admin#6214] opened 2021-04-27 04:06 UTC
**What you were expecting:**
The AutoCompleteInput doesnt reloaded the input form when type some string

**What happened instead:**
The AutoCompleteInput reloaded the input form when type some string and make us to repeat type

**Related code:**

```
<Filter {...props}>
      <ReferenceInput label="Consultant" source="consultant_id" reference="consultants" sort={{ field: 'full_name', order: 'ASC' }}>
        <AutocompleteInput optionText="full_name"
          shouldRenderSuggestions={(val: string) => {
            return val.trim().length > 2;
          }} />
      </ReferenceInput>
    </Filter>
```

**Other information:**
This the video https://drive.google.com/file/d/1me268LGar3wg17F8Xh0b-3eV5R7aIOfY/view?usp=sharing
**Environment**

* React-admin version: 3.11.2
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.1
* Browser: Chrome Version 90.0.4430.85 (Official Build) (64-bit)
* Stack trace (in case of a JS error):

**Comment by fzaninotto** [comment] 2021-04-29 17:23
I can't reproduce the problem on the simple example. Please fork the Codesandbox and modify the code to reproduce your bug, e.g. in the Comment List, which uses a ReferenceInput for its filters.

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by kuuneko** [comment] 2021-05-10 07:42
I have this same issue as described by the OP. It occurs as soon as I upgrade from 3.9.4 to anything.

**Comment by fzaninotto** [comment] 2021-05-10 07:43
@kuuneko then please provide a way to reproduce it.

**Comment by ngnclht1102** [comment] 2021-05-19 10:54
Same here, I also encountered the same problem.
It is successfully filtered, but after that, it is reloading.

It only happened on edit mode, on create mode, it works perfectly

https://user-images.githubusercontent.com/6987730/118801403-2abf8b00-b8cb-11eb-9be4-e56e152b5797.mov

**Comment by WiXSL** [comment] 2022-02-02 13:34
> My repo is here: https://github.com/ngnclht1102/ancestor-tree-admin-dashboard/blob/master/src/components/people/form.js

I can`t login to that project when I run it, is password protected

**Comment by WiXSL** [comment] 2022-02-02 13:41
> My repo is here: https://github.com/ngnclht1102/ancestor-tree-admin-dashboard/blob/master/src/components/people/form.js

It's not easy to run your project, It throws all sort of errors.
Could you provide a simple codesandbox reproducing the problem?

**Comment by WiXSL** [comment] 2022-02-11 15:13
@oktarama96, @ngnclht1102, could you try version 3.19.8 and see if you still have this problem?

**Comment by macrozone** [comment] 2022-03-13 14:59
i had a similar problem, reason was that i used an anonymous function for `optionText`, which was a new object on each rerender, which resulted in the autocomplete input to call handleFilterChange("") and thus empty the input. 

Maybe you have a similar problem with  `shouldRenderSuggestions` ? so use `useCallback` or a global variable for that function

**Comment by cdwhitt** [comment] 2022-04-11 17:50
I am having a similar problem for the edit page, but for me, the input *sometimes* clears when I select one of the rendered options. Running on 3.19.10

**Comment by Jules-DG** [comment] 2022-05-04 15:28
> I am having a similar problem for the edit page, but for me, the input _sometimes_ clears when I select one of the rendered options. Running on 3.19.10

Same problem on 4.0.2, everything is fine when i type some text matching options that are not selected yet, but if my text match an option already selected it's erased

**Comment by slax57** [comment] 2022-05-05 08:24
Again, we fail to reproduce this issue on our examples, so we can't work on it.
Can you try to reproduce in this codesandbox, and/or try to add some of your code in it in order to reproduce the issue?
https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
Thanks

**Comment by fzaninotto** [comment] 2022-07-21 16:52
No news for some time, closing.

**Closed by fzaninotto** 2022-07-21 16:52 UTC
Labels: needs more info
