### ISSUE TITLE
Notification crashes when messageInfo.message is an array instead of string

### ISSUE THREAD

**Issue by thdk** [marmelab/react-admin#8300] opened 2022-10-24 22:20 UTC
**What you were expecting:**
When a javascript error happens, I should get a notification at the bottom of my screen with the error message.

**What happened instead:**
The viewport of my browser is completely white. 

```

```

**Steps to reproduce:**
I got this error when using a nestjs rest api that does not allow unknown fields to be send in the requests.
![image](https://user-images.githubusercontent.com/4201102/197639417-9063699c-c5e3-4b30-9a0b-a5e881646bd2.png)

**Other information:**

See also duplicate issue #7178 where the screenshot also shows that the property `message` is an array instead of the expected string.

Other possible related issues: #5727 #5978

**Environment**

* React-admin version: 4.4.4
* Last version that did not exhibit the issue (if applicable):
* React version: 18.2.0
* Browser: chrome Version 106.0.5249.119
* Stack trace (in case of a JS error):
```
index.js:203 Uncaught TypeError: Polyglot.transformPhrase expects argument #1 to be string
    at transformPhrase (index.js:203:11)
    at Polyglot2.t (index.js:406:14)
    at Object.translate (index.ts:60:56)
    at useTranslate.ts:29:26
    at Notification (Notification.tsx:95:79)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
```

**Comment by WiXSL** [comment] 2022-10-25 13:31
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).
Stackblitz: https://stackblitz.com/github/marmelab/react-admin/tree/master/examples/simple?file=src%2Findex.tsx

**Comment by fzaninotto** [comment] 2022-10-27 12:42
did you call `useNotify()` with an array of strings instead of a string?

**Comment by thdk** [comment] 2022-10-27 13:21
> did you call `useNotify()` with an array of strings instead of a string?

No. But I just found the issue:
https://github.com/marmelab/react-admin/blob/105c14c7575b78b7c0e547a898e4b51e7eafcd43/packages/ra-core/src/form/setSubmissionErrors.ts#L44

`typeof [] === 'object'` 😮‍💨  I'll submit a PR

**Comment by thdk** [comment] 2022-10-27 15:30
![image](https://user-images.githubusercontent.com/4201102/198333007-375260fd-79a0-451d-a833-da08e2803bbf.png)

**Comment by fzaninotto** [comment] 2022-12-01 17:44
Did you find a reproduction for this issue?

**Comment by thdk** [comment] 2022-12-01 20:32
> Did you find a reproduction for this issue?

Hi, thanks for following up. I did some investigation after logging this issue but didn't find how to clearly reproduce this.

Feel free to close this issue.

Just note that there is a code path that will not work as intended: 
```javascript
var error = [] //empty array
console.log(typeof error) // prints: 'object'

if (typeof error === "object") {
    // true for both arrays and objects
    return;
}
if (Array.isArray(error)) {
     // this path won't be taken since the first 'if' statement already catches it for arrays.
     return;
}
```

So when you do:

**Comment by slax57** [comment] 2022-12-08 13:40
@thdk You are 100% correct.

However, I added the following test and it passed with no change to the code:

```ts
    it('calls setError for form schema containing nested arrays', () => {
        const setError = jest.fn();

        setSubmissionErrors(
            {
                user: {
                    friends: [
                        {
                            name: 'invalid name',
                        },
                    ],
                },
            },
            setError
        );

        expect(setError).toHaveBeenCalledWith('user.friends.0.name', {
            message: 'invalid name',
            type: 'server',
        });
    });
```

Turns out, `Object.entries(errors)` actually works fine for arrays too, and returns exactly what we need.

So in the end I just cleaned the useless code in https://github.com/marmelab/react-admin/pull/8482

Thanks for pointing this out!
Now I'm closing this issue, as requested.

**Closed by slax57** 2022-12-08 13:40 UTC
Labels: needs more info
