### ISSUE TITLE
Support for other than Material-UI

### ISSUE THREAD

**Issue by geeklisted** [marmelab/react-admin#5231] opened 2020-09-04 15:34 UTC
**Is your feature request related to a problem? Please describe.**

Not a problem per se, React Admin is a terrific product. However, when customizing a React-Admin application, in my opinion, Material-UI has its drawbacks and limitations.   

Are there any plans or discussions around offering support for other UI frameworks?

**Describe the solution you'd like**

A more full-featured React UI library like Semantic UI would be beneficial as an optional plugin to replace Material-UI.

**Describe alternatives you've considered**
None at the moment; there would be a lot of work involved to swap in Semantic UI into React-Admin.

**Additional context**
N/A

**Comment by fzaninotto** [comment] 2020-09-04 15:50
Duplicate of #249 (one of the early requests made about react-admin!).

**Closed by fzaninotto** 2020-09-04 15:50 UTC
