### ISSUE TITLE
Module not found: Can't resolve 'graphql-ast-types'

### ISSUE THREAD

**Issue by ben-eb** [marmelab/react-admin#2494] opened 2018-11-02 09:22 UTC
**What you were expecting:**

React Admin should compile.

**What happened instead:**

React Admin failed to compile.

**Steps to reproduce:**

1. Create a react-admin project with a graphql adapter.
2. Build the project.
3. Error outputted.

**Other information:**

I think this is because React Admin is relying on https://github.com/Kmaschta/graphql-ast-types at `master` which has since changed its name to `graphql-ast-types-browser` and therefore won't be installed by npm as `graphql-ast-types`.

**Environment**

* React-admin version: 2.4.1
* Last version that did not exhibit the issue (if applicable):
* React version: 16.5.0
* Browser: Chrome
* Stack trace (in case of a JS error):

```js
./node_modules/ra-data-graphql-simple/esm/buildGqlQuery.js
Module not found: Can't resolve 'graphql-ast-types' in '/projects/app/node_modules/ra-data-graphql-simple/esm'
```

**Comment by djhi** [comment] 2018-11-02 09:51
Duplicate of #2398. Fixed by #2486

**Closed by djhi** 2018-11-02 09:51 UTC
