### ISSUE TITLE
Richtext dosen't clean value after form submit

### ISSUE THREAD

**Issue by ggarcia92** [marmelab/react-admin#2889] opened 2019-02-15 16:33 UTC
**What you were expecting:**

When user press save, richtext input value is set to empty or default value

**What happened instead:**

When i create a bulk create action all react-admin components get value empty or default after submit, but richtext input doesn't

**Environment**

* React-admin version: 2.7.0

**Comment by ggarcia92** [comment] 2019-02-15 16:39
I solve this problem by adding to the RichTextInput component

```
    componentWillReceiveProps(nextProps){
        this.editor.innerHTML = nextProps.input.value
    }
```

**Comment by afilp** [comment] 2019-02-16 11:35
Should this be a default behavior you believe? If yes, may I assume that it needs a PR? Thanks!

**Comment by ggarcia92** [comment] 2019-02-16 17:59
Hi @afilp , yes this should be the default behavior, just like other react-admin components. Regards

**Comment by ggarcia92** [comment] 2019-02-16 18:11
Added to PR #2868 Regards

**Comment by fzaninotto** [comment] 2019-02-21 16:47
> What you were expecting:
>
> When user press save, richtext input value is set to empty or default value

Well, I'm not expecting that. Why should the save action reset the rich text input?

**Comment by ggarcia92** [comment] 2019-02-21 18:57
Hi @fzaninotto , we omitted the after save redirect to accomplish a Bulk Create Action, by doing that we observe that all inputs in our forms reset its values, except rich text input. Regards

**Comment by fzaninotto** [comment] 2019-02-22 18:04
I don't understand what a Bulk Create action is. It's not part of react-admin. Did you stack several Create forms in a single page? If so, it's not supported by react-admin - use your own Create component for that.

**Comment by ggarcia92** [comment] 2019-02-25 16:04
I did not stack several Create forms, just set `redirect` prop of SaveButton to `false`.

**Comment by fzaninotto** [comment] 2019-02-26 03:28
OK then your issue is a duplicate of #2464

**Closed by fzaninotto** 2019-02-26 03:28 UTC
