### ISSUE TITLE
Edit Form Submission does not send any request to server

### ISSUE THREAD

**Issue by benoj** [marmelab/react-admin#4699] opened 2020-04-17 14:10 UTC
**What you were expecting:**
Submit edit form would send a PUT request to my server

**What happened instead:**
Redirects to the list page with no network request

**Steps to reproduce:**
```
import React from 'react';
import { render } from 'react-dom';
import { Admin as AdminUnderlying, Resource } from 'react-admin';
import simpleRestProvider from 'ra-data-simple-rest';
import {
    List,
    Datagrid, 
    Edit, 
    Create,
    SimpleForm,
    DateField, TextField, NumberField, EditButton,
    DateInput, TextInput, NumberInput,
} from 'react-admin';


export const PostList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="owner" />
            <DateField source="starttime" />
            <NumberField source="duration" />
            <TextField source="provider" />
            <TextField source="location" />
            <TextField source="type" />
            <EditButton basePath="/experiences" />
        </Datagrid>
    </List>
);

export const PostEdit = (props) => (
    <Edit title="Edit" {...props}>
        <SimpleForm>
            <TextInput disabled source="id" />
            <TextInput source="owner" />
            <DateInput source="starttime" />
            <NumberInput source="duration" />
            <TextInput source="provider" />
            <TextInput source="location" />
            <TextInput source="type" />
        </SimpleForm>
    </Edit>
);

export const PostCreate = (props) => (
    <Create title="Create a Post" {...props}>
        <SimpleForm>
            <TextInput source="owner" />
            <DateInput source="starttime" />
            <NumberInput source="duration" />
            <TextInput source="provider" />
            <TextInput source="location" />
            <TextInput source="type" />
        </SimpleForm>
    </Create>
);


export const Admin = () => {
    return (
        <AdminUnderlying dataProvider={simpleRestProvider('http://localhost:5000')}>
            <Resource name="experiences" list={PostList} edit={PostEdit} create={PostCreate}/>
        </AdminUnderlying>
    )
}

```

The create form works perfectly, however the Edit form doesnt seem to do anything other than redirect back. I can see in my browser console tools there are no network requests ?

**Comment by JulienMattiussi** [comment] 2020-04-17 14:33
Can you explain wich versions you are using ?

**Comment by benoj** [comment] 2020-04-17 14:40
3.4.1

I just downgraded to 3.4.0 but same issue

**Comment by benoj** [comment] 2020-04-17 15:10
When i updated my code to:

```
 <Edit save={() => console.log("savvvving")} />
``` 

I get no console log - it's like the save action is being skipped?>

**Comment by benoj** [comment] 2020-04-17 17:33
I put a break-point in the simple `ra-data-simple-rest` - it appears as though the submit triggers a getOne action - rather than an update?

**Comment by benoj** [comment] 2020-04-17 18:00
Okay - 

After further digging it seems there is something strange happening when the events are triggered. I've recorded a video (see below).

It appears as though the requests only happen when i click the listing selection checkbox on the for the items _after_ an action (e.g. delete) has occurred and all the requests are buffered up ready to go but not yet being executed?

(Right hand side you can see the network requests and left hand side you can see the example app i have built)

https://drive.google.com/file/d/1BmB0pSaCqccEWKSSQgpEfc0f5ZSSixvJ/view?usp=sharing

**Comment by benoj** [comment] 2020-04-22 08:02
Hey @JulienMattiussi just wondering if you had enough information now?

**Comment by benoj** [comment] 2020-04-29 14:50
ping?

**Comment by fzaninotto** [comment] 2020-05-04 09:25
Are you using a custom layout? That would explain the problem you're seeing. 

React-admin deletes are *optimistic*, meaning the user sees the change on the client side, but has a grace period of a few seconds to cancel it before the change is sent to the server. The logic for this "Undo" action lies in the `<Notification>`  component - the one that shows the toast message after editing/deleting an item.

I don't see any toast message in your example, so I suppose you've used a custom layout, and forgot to include the `<Notification>` component in it. 

Finally, the problem you describe can't be reproduced with just the code you've pasted, so I imagine the problem is elsewhere - on your side. So I'm closing this issue. feel free to reopen it if you can provide a way to reproduce the issue - a CodeSandbox or a GitHub repository.

**Closed by fzaninotto** 2020-05-04 09:25 UTC
Labels: needs more info

**Comment by rromikas** [comment] 2022-02-01 20:12
Notification component shouldn't complete the requests.

**Comment by An88ton** [comment] 2024-12-13 14:20
I've had the same bug, for me helped delete package-lock.json and node modules folder. Then run npm install
