### ISSUE TITLE
Create button on wide resource list not fixed on right bottom corner of screen but content (mobile device only)

### ISSUE THREAD

**Issue by apapacy** [marmelab/react-admin#6427] opened 2021-07-12 10:44 UTC
**What you were expecting:**
See Create button on resource list with wide content in fixed position on right bottom corner of screen on mobile browser

**What happened instead:**
Create button positioned on right bottom corner of content and scroll with content. As result on wide content Create button invisible. You need to scroll content to see Create button/

**Steps to reproduce:**
Open resource list with wide content.

**Other information:**
Bug is reproduced on real mobile device only (non on mobile browser emulator inside desktop browser)
![image](https://user-images.githubusercontent.com/4279840/125274523-b7f4ee00-e316-11eb-8d8c-c7982d5004b2.png)

**Environment**

* React-admin version: 3.11.1, 3.17.0
* React version: 17.0.2
* Browser:   Chrome 86.0.4240.110 (on mobile device)

**Comment by djhi** [comment] 2021-07-21 15:41
I can't reproduce this issue on a real mobile device with a chromium 91 based browser. I'll close this issue but feel free to comment on it if you still have the problem.

**Closed by djhi** 2021-07-21 15:41 UTC
