### ISSUE TITLE
SimpleForm with defaultValue cannot be submitted without altering an input.

### ISSUE THREAD

**Issue by waynebloss** [marmelab/react-admin#3203] opened 2019-05-08 16:08 UTC
**What you were expecting:**
When a `SimpleForm` with a `defaultValue` prop fills out the entire form, I can't submit the form without altering at least one of the inputs. I expected to be able to just submit the default values.

**What happened instead:**
I wasn't able to submit the default values.

**Steps to reproduce:**

1. Make a resource that contains a `<SimpleForm defaultValue={defaultValue}>` which applies defaults to all of the form fields.
2. Visit the resource, try to submit the form without altering any inputs.
3. There is no warning, the `Save` button is not disabled and no other indication of why the form cannot be submitted.

**Related code:**
None

**Other information:**
None

**Environment**

* React-admin version: 2.9.0
* Last version that did not exhibit the issue (if applicable): Not sure.
* React version: 16.8.6
* Browser: Chrome 72
* Stack trace (in case of a JS error): no.

**Comment by waynebloss** [comment] 2019-05-08 16:16
Not a huge deal, probably doesn't affect a lot of people. Just pointing it out. Thanks!

**Comment by djhi** [comment] 2019-05-09 07:22
Thanks for reporting. It would help a lot if you could setup a codesandbox :)

**Comment by fzaninotto** [comment] 2019-05-13 08:44
I cannot reproduce the bug on the simple example. Please add a CodeSandbox demonstring the problem.

**Comment by fzaninotto** [comment] 2019-09-17 15:06
No news for some time, closing.

**Closed by fzaninotto** 2019-09-17 15:06 UTC
Labels: awaiting more info
