### ISSUE TITLE
CSS bug in production build 

### ISSUE THREAD

**Issue by pilacoepouco** [marmelab/react-admin#3741] opened 2019-09-26 11:54 UTC
When trying to build in production or CSS gets misconfigured, which doesn't happen in development.

Run the following commands:
```npm run build```
```yarn global add serve```
```serve -s build```
production :
![bug](https://user-images.githubusercontent.com/53221609/65686415-bae7f700-e03a-11e9-8459-7d28e2ba29af.PNG)
development:
![dev](https://user-images.githubusercontent.com/53221609/65686417-bae7f700-e03a-11e9-9e5c-53ec190c3949.PNG)

![Capturar](https://user-images.githubusercontent.com/53221609/65686506-14e8bc80-e03b-11e9-9460-bea921cd1543.PNG)

**Environment**

* React-admin version: "^2.9.6"
* Last version that did not exhibit the issue (if applicable):
* React version: "^16.9.0"
* Browser:
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment] 2019-09-26 12:33
React Admin v2 doesn't support a version of Material UI > 1.x
Material UI v4 will be supported by React Admin v3, [here is the roadmap](https://github.com/marmelab/react-admin/issues/3194).

Duplicate of https://github.com/marmelab/react-admin/issues/1782

**Closed by Kmaschta** 2019-09-26 12:33 UTC
Labels: duplicate
