### ISSUE TITLE
Module not found: Can't resolve 

### ISSUE THREAD

**Issue by darkiron** [marmelab/react-admin#2491] opened 2018-10-31 16:17 UTC
Using with api-platform/admin

**What you were expecting:**
Load react-admin

**What happened instead:**
> ./src/App.js
> Module not found: Can't resolve 'ra-input-rich-text' in '/usr/src/admin/src'

**Steps to reproduce:**
[apiplatform doc](https://api-platform.com/docs/admin/getting-started/#customizing-the-admin)

`yarn add ra-input-rich-text` run normaly (expeted some warn with react-dom)

**Related code:**

```
import { FunctionField, ImageField, ImageInput, RichTextField } from 'react-admin';
import RichTextInput from 'ra-input-rich-text';
```

**Environment**

*  "@api-platform/admin": "^0.5.0",
* "@babel/runtime": "7.0.0-beta.55",
* "ra-input-rich-text": "^2.4.0",
* "react": "^16.6.0",
* "react-dom": "^16.6.0"

**Comment by fzaninotto** [comment] 2018-11-05 22:16
Hi darkiron, and thanks for your report. 

If the first React element can't load a module, it means that it's not installed. You probably didn't install it in the right place. I don't know how API Platform works, but this is definitely not a bug with the rich text input (which works on other projects).

So I'm closing this issue as I can't reproduce it. Feel free to reopen it if you can provide a CodeSandbox showing a bug using react-admin directly.

**Closed by fzaninotto** 2018-11-05 22:16 UTC

**Comment by darkiron** [comment] 2018-11-06 13:36
Thanks, is not bug... is a docker issue ;)
