### ISSUE TITLE
Square brackets in filter's "source" attribute prevent the deletion of filters

### ISSUE THREAD

**Issue by ltcmdrkeen** [marmelab/react-admin#5944] opened 2021-02-22 18:13 UTC
**What you were expecting:**

In a filter source, I want to use square brackets like `createdAt[before]`. Deleting the filter should work as without having the brackets in the source name.
```jsx
const UserFilter: FC<Omit<FilterProps, 'children'>> = props => (
  <Filter {...props}>
      <DateInput source="createdAt[after]"  />
 </Filter>
)
```

**What happened instead:**

When I click on the remove button, the URL search string changes from:

`?displayedFilters=%7B%22createdAt%5Bafter%5D%22%3Atrue%7D&filter=%7B%22createdAt%22%3A%7B%22after%22%3A%222021-02-23%22%7D%7D`

(which decodes to `displayedFilters={"createdAt[after]":true}&filter={"createdAt":{"after":"2021-02-23"}}`)

to 

`?displayedFilters=%7B%7D&filter=%7B%22createdAt%22%3A%7B%22after%22%3A%222021-02-23%22%7D%7D` (which decodes to `?displayedFilters={}&filter={"createdAt":{"after":"2021-02-23"}}`)

The filter still remains. Clicking the remove button again results in  the following console error message:
`Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack`

**Steps to reproduce:**
- Add a resource with square brackets to a filter, e.g.
```jsx
  <Filter {...props}>
      <DateInput source="createdAt[after]"  />
 </Filter>
```
- Add the filter in the compiled react app
- Set a value for the date
- Try to remove the filter again

**Environment**

- Docker, MacOs, node 14
- api platform 2.6.0

* React-admin version: 3.12.0.
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.1
* Browser: Chrome/Firefox

**Comment by djhi** [comment] 2021-02-23 07:28
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment] 2021-02-23 07:55
I think it's a duplicate of #4885.

**Comment by ltcmdrkeen** [comment] 2021-02-23 08:05
@fzaninotto Okay, I think you are right that this is a duplicate of #4855. 
As you stated that react-admin is just not designed to have brackets in filter-queries, I think this can be closed.

However, here's a dirty fix to achieve that if anybody else is using API Platform/Hydra with react-admin:

1. Encode the filter's source:
```jsx
<DateInput source={encodeURI("createdAt[after]")} />
```
2. Wrap the fetch function, replacing the double-encoding:

```js
global.fetch = (req, init): Promise<Response> => {
  var urlStr = req.toString();
  if(urlStr.includes("%255B")){
    req=urlStr.replace("%255B", "%5B").replace("%255D", "%5D");
  }
  return fetch(req, init);
}
```

**Closed** 2021-02-23 08:14 UTC
Labels: needs more info

**Comment by Hakihiro** [comment] 2021-02-26 14:09
@ltcmdrkeen Api platform seems to be able to manage filter with a dot. It's simpler to just switch your source:
```html
<Filter {...props}>
      <DateInput source="createdAt[after]"  />
 </Filter>
```
To
```html
<Filter {...props}>
      <DateInput source="createdAt.after"  />
 </Filter>
```

It should work.
