### ISSUE TITLE
RadioButtonGroupInput does not use the `defaultValue`

### ISSUE THREAD

**Issue by afilp** [marmelab/react-admin#3374] opened 2019-06-29 00:17 UTC
**What you were expecting:**

`defaultValue` to be applied to the `RadioButtonGroupInput`

**What happened instead:**

I tried to add the `defaultValue` prop using as value one of the "ids" that exist in `choices` but nothing happened. I looked at your code implementation and could not see how the `defaultValue` could affect the `input.value`. I believe this is a bug, but not 100% sure.

**Steps to reproduce:**

**Related code:**

```jsx
<RadioButtonGroupInput
          label=""
          source="departmentField"
          defaultValue="id1"
          choices={[
             {id: 'id1', name: 'name1'},
             {id: 'id2', name: 'name2'},
          ]}
          onChange={this.handleOnChangeRadio}
          options={{
              row: true,
          }}
        />
```

**Other information:**

**Environment**

* React-admin version: v2.9.3
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by Kmaschta** [comment] 2019-07-01 14:25
Mind you provide a CodeSandbox fork with the issue?

**Comment by fzaninotto** [comment] 2019-07-02 09:54
I can't reproduce the issue in a fresh CodeSandbox (test "create post")

https://codesandbox.io/s/simple-dgptf

Can you modify that CodeSandbox until you can reproduce the bug?

Also, the code for setting default values is outside of the input components. It's mutualized and uses Redux.

**Comment by afilp** [comment] 2019-07-03 11:23
Thanks, now I got it what it was wrong. 

I was using it inside a custom filter component (a `div`).

See a *working* sandbox here (add the "Foo2" filter):

https://ckn6h.codesandbox.io/#/posts?filter={}&order=DESC&page=1&perPage=10&sort=published_at

I was using the `defaultValue="id2"` inside the custom filter (at the actual `RadioButtonGroupInput`, not outside. I think I did not find something in the documentation on what is needed in that case.

SIDE NOTE:
Please also add the `commentable` filter, you will see that it cannot be clicked (not selectable). Is this a bug?

**Comment by fzaninotto** [comment] 2019-07-07 20:59
The fact that the `defaultValue` must be added to direct children of the `Filter` component is due to a limitation of redux-form, and we hope it will be removed by switching to react-final-form, which is planned for react-admin v3. Consider it a limitation of `Filter`, and please use a custom Filter component if you want a different logic.

The commentable filter is a "quick filter", which means that it directly adds a filter *value*. It is normal that its value cannot be modified. 

So I don't see a real bug in react-admin here - just a gotcha that can be overcome and that will be fixed in the next version. I'm closing the issue, thanks anyway for taking the time to describe it.

**Closed by fzaninotto** 2019-07-07 20:59 UTC
Labels: awaiting more info
