### ISSUE TITLE
mutationOptions onError not getting called in <Create>

### ISSUE THREAD

**Issue by vaizki** [marmelab/react-admin#8428] opened 2022-11-23 21:40 UTC
**What you were expecting:**
When defining a create view like:
```
  <Create mutationOptions={{ onError, onSuccess }} >
```
I expect my onError to be called when server returns 422 and onSuccess to be called when it returns 200. 

**What happened instead:**
The onSuccess handler works ok but the onError is never called.

If I define an edit view similarly:

```
  <Edit title=" " mutationMode="pessimistic" mutationOptions={{ onError }} >
```
... this works fine, onError is called on 422 and connect errors for example.
**Other information:**
**Environment**

* React-admin version: 4.5.2
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.2
* Browser: Chrome latest
* Stack trace (in case of a JS error):

**Comment by WiXSL** [comment] 2022-11-24 16:16
I cannot reproduce this issue in the simple project.
Please follow the issue template

**Comment by tauqeer-trailfive** [comment] 2022-12-15 14:48
is it any way to pass `mutationMode `in Create?

**Comment by fzaninotto** [comment] 2023-01-03 17:34
No news for some time, closing.

**Closed by fzaninotto** 2023-01-03 17:34 UTC
Labels: needs more info
