### ISSUE TITLE
[4.0.0-alpha.1] Tutorial: Filter component appears too narrow 

### ISSUE THREAD

**Issue by WiXSL** [marmelab/react-admin#6700] opened 2021-10-18 13:50 UTC
![filter](https://user-images.githubusercontent.com/8268610/137744419-ac998b92-1de4-4fd0-807c-4680dcba995c.png)

**Comment by panna-ahmed** [comment] 2021-10-31 12:20
@djhi I was able to reproduce it. I wanna try to fix it. Any ideas?

**Comment by CoreyB26** [comment] 2021-11-17 21:05
I am new to this project, it's my first day trying to help out the open source community so please bear with me.
I have been unable to reproduce this issue, though admittedly I am a little confused as I can't find a branch for 4.0.0-alpha.1 but did try the origin of 4.0.0-alpha.0 and didn't see this issue there. I also tried the latest branch off of the origin which is a travis-ci bot branch called react-hooks-form and I tried the next branch. If this is still a real issue and if anyone could help me out in reproducing it and pointing me to the correct source code I would appreciate it, thank you.
<img width="1437" alt="Screen Shot 2021-11-17 at 3 16 21 PM" src="https://user-images.githubusercontent.com/43451029/142282247-86f25377-dda4-4fc3-9f9a-2c08d9333a22.png">

**Comment by WiXSL** [comment] 2021-11-17 21:26
> @djhi I was able to reproduce it. I wanna try to fix it. Any ideas?

Probably a styling issue, but can't be sure without looking into it

**Comment by WiXSL** [comment] 2021-11-17 21:30
> I am new to this project, it's my first day trying to help out the open source community so please bear with me. I have been unable to reproduce this issue, though admittedly I am a little confused as I can't find a branch for 4.0.0-alpha.1 but did try the origin of 4.0.0-alpha.0 and didn't see this issue there. I also tried the latest branch off of the origin which is a travis-ci bot branch called react-hooks-form and I tried the next branch. If this is still a real issue and if anyone could help me out in reproducing it and pointing me to the correct source code I would appreciate it, thank you.

Version 4 is the `next` branch, 4.0.0.alpha1 is the next milestone which will come out of the `next` branch.

In order to reproduce the problem, you have to add a filter clicking in the `Add Filter` action button

**Comment by CoreyB26** [comment] 2021-11-17 21:47
@WiXSL Perfect! Now I can reproduce it. I will take a swing at fixing it.

**Comment by CoreyB26** [comment] 2021-11-19 19:49
This is fixed in my PR above, please let me know if the fix is acceptable or not. I couldn't figure out how to link the PR to this issue...

**Comment by fzaninotto** [comment] 2022-01-28 08:21
Fixed by #7152

**Closed by fzaninotto** 2022-01-28 08:21 UTC
Labels: bug, good first issue
