### ISSUE TITLE
Unable to render ReferenceField inside ArrayInput

### ISSUE THREAD

**Issue by ashim-k-saha** [marmelab/react-admin#1933] opened 2018-06-20 05:55 UTC
I was trying to pass ReferenceField inside ArrayInput, got an error
```
  110 |     resource = _props.resource,
  111 |     source = _props.source;
  112 | 
> 113 | var rootPath = basePath.replace(resource, reference);
  114 | var resourceLinkPath = !linkType ? false : (0, _util.linkToRecord)(rootPath, (0, _get2.default)(record, source), linkType);
  115 | return children({
  116 |     isLoading: !referenceRecord && !allowEmpty,
```

Sample code is

```
<ArrayInput source="fees" >
	<SimpleFormIterator >
		<ReferenceField
			label="Select fee type"
			source="misc_fee_id"
			reference="fee_types"
		>
			<TextField optionText="fee_name" />
		</ReferenceField>
		<DisabledInput source="due_amount" />
		<DisabledInput source="due_date" />
		<DisabledInput source="fine_after_due_date"/>
		<BooleanInput source="is_paid"/>
	</SimpleFormIterator>
</ArrayInput>
```

Dependencies are
```json
{
    "ra-data-json-server": "^2.0.3",
    "react": "^16.3.2",
    "react-admin": "^2.0.3",
    "react-dom": "^16.3.2",
    "react-scripts": "1.1.4",
    "@material-ui/icons": "1.1.0"
}
```

**Comment by fzaninotto** [comment] 2018-06-20 06:46
I think it's a duplicate of #1871. Feel free to reopen if you disagree.

Next time you open an issue, please paste your error message in the issue description - it makes our work easier. It's even better if you follow the issue template.

**Closed by fzaninotto** 2018-06-20 06:46 UTC
