### ISSUE TITLE
Add a 'target' field to <ReferenceField>

### ISSUE THREAD

**Issue by nickgrealy** [marmelab/react-admin#5581] opened 2020-11-24 02:32 UTC
**Is your feature request related to a problem? Please describe.**
I want to use a `ReferenceField`, to lookup a (single) resource based on a foreign field name (e.g. `voucherCode` not `id`). However [`ReferenceField`](https://marmelab.com/react-admin/Fields.html#reference-fields) only allows me to use the default foreign field `id`.

I imagine this is a pretty common use case, especially in existing databases.

Please correct me if I'm using the wrong component (or wrongly using the right component!).

**Describe the solution you'd like**
I'd like `ReferenceField` to behave similarly to `ReferenceManyField`, in that I can supply a foreign field name to match against (i.e. `target={...}`).

e.g. 

I'd like a `ReferenceField` to support a `target` attribute...
```js
<ReferenceField
  source={field}
  reference={collection}
  target={matchForeignField}
>
  ...
</ReferenceField>
```

... similar to how `ReferenceManyField` already behaves.
```js
<ReferenceManyField
  source={field}
  reference={collection}
  target={matchForeignField}
>
  ...
</ReferenceManyField>
```

**Describe alternatives you've considered**
I've tried using `ReferenceManyField` - which can lookup the field successfully, but throws an error when I return to list view after updating an object (screenshot attached)

![attempt-error](https://user-images.githubusercontent.com/1669373/100039366-2ef97700-2e59-11eb-9211-bfb5c2c38bb1.png)

**Comment by MicroJackson** [comment] 2020-11-24 07:29
Might totally misunderstand your question but you can just put `voucherCode` in your `source` if you received it from your backend.
```
                    <ReferenceField
                        source="voucherCode"
                        reference="your_resource_in_app"
                    >
                        <TextField source="name" />
                    </ReferenceField>
```
Creates a request like: /your_resource_in_app/voucherCode/
Then you need to capture that in your backend and deal with it accordingly.

As far as the error goes: https://github.com/marmelab/react-admin/issues/5054 should have fixed it I think. Maybe update your React Admin?

**Comment by nickgrealy** [comment] 2020-11-24 07:41
Thanks @MicroJackson.

You're right, one workaround could be to modify the backend. If I was going to do that, I'd simply create a custom mapping (`id` => `voucherCode`) when retrieving the data.

Another workaround to keep the "link" behaviour, would be to use `<Link ... />` to filter the target data to just the requested resource. Downside is, I can't "lookup" target fields to display, AND the Field doesn't know whether the target resource exists or not (so it's always displayed).

I'd prefer to continue to investigate adding a `target` attribute - because it seems intuitive and logical. (I was looking for it in the documentation, before realising it didn't exist).

re: #5054 - I'm not sure that `ReferenceManyField` is the correct component I should be using, as I'm currently only looking for a 1-to-1 mapping.

I'm already on the latest - `"react-admin": "3.10.2"`.

**Comment by nickgrealy** [comment] 2020-11-26 13:32
Looking for some guidance on how to proceed (@fzaninotto)) - happy to get my hands dirty if there's interest in including this feature.

My initial investigation...

**ReferenceField** - currently calls `useGetMany` with an array of (one) id. I imagine we could do something similar, but call `useGetManyReference` instead.

Two options:

1. (my prefereence) we could extend `ReferenceField` to modify it's underlying call (`useGetMany` vs `useGetManyReference`) based on the presence of a `target` attribute.
2. Or we could create a separate component specifically for handling "get by reference" (although I don't know what you'd call it - `ReferenceField` sums it up nicely).

**Call Chain**

ReferenceField calls -> _useReference({ reference, id })_
https://github.com/marmelab/react-admin/blob/1e2e57554b45067a06c4e678b437213d269d25b0/packages/ra-ui-materialui/src/field/ReferenceField.tsx#L87-L96

which calls -> _useGetMany(reference, [id])_
https://github.com/marmelab/react-admin/blob/89ac783fd9f961401d1c2e8d4ca4965053ed1d21/packages/ra-core/src/controller/useReference.ts#L43-L51

proposed? -> _useGetManyReference(resource, target, id, pagination, sort, fiter, referencingResource, options)_
https://github.com/marmelab/react-admin/blob/89ac783fd9f961401d1c2e8d4ca4965053ed1d21/packages/ra-core/src/dataProvider/useGetManyReference.ts#L58-L67

**Comment by djhi** [comment] 2020-11-26 14:10
Duplicate of #2022. Please see @fzaninotto [answer](https://github.com/marmelab/react-admin/issues/2022#issuecomment-406206759)

**Closed by djhi** 2020-11-26 14:10 UTC

**Comment by nickgrealy** [comment] 2020-11-26 15:59
Hi @djhi - thanks for the response. Just one question if you'll humour me.

First - agree it's a duplicate.

> React-admin requires that the records it manipulates have an id attribute. If your backend doesn't provide one, it's the job of the dataProvider to do the translation.

👍  - No problem. All my records have my records have an `id` field.

> Adding the target prop that you ask would imply leaking this "adapter" logic outside of the dataProvider. We won't do it.

Then why does `ReferenceManyField` have a `target` field?

https://github.com/marmelab/react-admin/blob/1e2e57554b45067a06c4e678b437213d269d25b0/packages/ra-ui-materialui/src/field/ReferenceManyField.tsx#L61-L74
