### ISSUE TITLE
Optimize REST calls for ArrayInput > ReferenceInput

### ISSUE THREAD

**Issue by sliterok** [marmelab/react-admin#5379] opened 2020-10-11 03:22 UTC
**Is your feature request related to a problem? Please describe.**
Problem is that when you have ReferenceInput (SelectInput) inside your ArrayInput react-admin will call REST api for SelectInput variants as many times as there are elements in ArrayInput. I guess it should be optimized because in my case you could have really many elements in array.

**Describe the solution you'd like**
Instead of N calls make only 1 and somehow share result between SelectInputs

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
Somehow related to #2585 and #3205.
You can visit [CodeSandbox](https://codesandbox.io/s/react-admin-21-advanced-recipes-create-a-record-related-to-the-current-one-forked-jzz5v?file=/src/posts/PostEdit.js:508-522) open console and click on the post. Right after that you could see that there was 3 calls to REST api. If you add more items to that post count of requests will increase accordingly.

**Comment by sliterok** [comment] 2020-10-11 13:52
I guess problem originates not from the SelectInput, but from the ReferenceInput itself somehow? This [CodeSandbox](https://codesandbox.io/s/react-admin-21-advanced-recipes-create-a-record-related-to-the-current-one-forked-bx64k?file=/src/posts/PostEdit.js) clearly shows that if you replace SelectInput with TextInput problem remains. Also i've added more items to post.

**Comment by sliterok** [comment] 2020-10-11 13:55
Also, if you replace all "Input" elements inside second FormTab with "Field" elements problem somehow resolves, so i guess it's really specific about caching ReferenceInput result?

**Comment by fzaninotto** [comment] 2020-10-11 19:25
duplicate of #4531

**Closed by fzaninotto** 2020-10-11 19:25 UTC
