### ISSUE TITLE
Support warnings on form inputs

### ISSUE THREAD

**Issue by ngoldenberg** [marmelab/react-admin#2919] opened 2019-02-22 16:09 UTC
I tried using the `warn` prop to validate/warn a form as stated on `react-admin` docs in [this section](https://marmelab.com/react-admin/CreateEdit.html#validation):
> Tip: The props of your Input components are passed to a redux-form <Field> component. So in addition to validate, you can also use warn.

Tried both `Global Validation` and `Per Input Validation` but none of them are raising any warnings. 
Even more, when i try `Global Validation` as warning like this:    
```js
 <TabbedForm validate={validateUserCreation} warn={warnUserCreation}>
```
It throws console errors:
```js
index.js:1452 Warning: Invalid value for prop `warn` on <form> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. 
(...)
````

Is there a way to actually notify the user (even a popup would work for me) about some fields warnings?
For example, i want the user to know that a `regionId` is not required for creating a `user` object, but the new `user` won't be able to login until a `region` is associated to it. I'm open to suggestions.

### Full code example
```js
const validateUserCreation = values => {
  const errors = {};
  if (!values.name) {
    errors.name = ["Name is required"];
  }
  if (!values.user) {
    errors.user = ["User is required"];
  }
  if (!values.pass) {
    errors.pass = ["Pass is required"];
  }
  if (!values.email) {
    errors.email = ["Email is required"];
  } else if (!utils.validateEmailFormat(values.email)) {
    errors.email = ["Invalid email syntax"];
  }
  if (!values.organization) {
    errors.organization = ["Organization is required"];
  }
  return errors;
};

const warnUserCreation = values => {
  const warnings = {};
  if (!values.regionId) {
    warnings.regionId = [
      "User won't be active until it is associated to a Region"
    ];
  }
  if (!values.groupId) {
    warnings.groupId = [
      "User won't be active until it is associated to a Account Limits"
    ];
  }
  return warnings;
};

export const UserCreate = props => (
  <Create {...props}>
    <TabbedForm validate={validateUserCreation} warn={warnUserCreation}>
      <FormTab label="General">
        <TextInput source="name" />
        <TextInput source="user" />
        <TextInput source="pass" type="password" />
        <TextInput source="email" type="email" />
        <TextInput source="organization" />
      </FormTab>
      <FormTab label="Region">
        <ReferenceInput
          label="Region"
          source="regionId"
          reference="regions"
        >
          <SelectInput
            optionText="name"
            optionValue="id"
            options={{ fullWidth: true }}
          />
        </ReferenceInput>
      </FormTab>
      <FormTab label="Account Limits">
        <ReferenceInput
          label="Account Limits"
          source="groupId"
          reference="groups"
        >
          <SelectInput
            optionText="name"
            optionValue="id"
            options={{ fullWidth: true }}
          />
        </ReferenceInput>
      </FormTab>
    </TabbedForm>
  </Create>
);
```

Also tried single input validation like this:
```js
        <TextInput source="organization" warn={[required(), minLength(2), maxLength(15)]} />
```
But no warning is raised at all.

### Environment

* React-admin version: `2.4.3`
* Dependencies: 
  ```json
    "dependencies": {
      "axios": "^0.18.0",
      "prop-types": "^15.6.2",
      "ra-data-json-server": "^2.4.3",
      "ra-data-simple-rest": "^2.4.3",
      "react": "^16.6.3",
      "react-admin": "^2.4.3",
      "react-dom": "^16.6.3",
      "react-scripts": "2.1.1"
    },
  ```
* Last version that did not exhibit the issue (if applicable): None
* React version: `16.6.3`
* Browser: Google chrome `Version 71.0.3578.80 (Official Build) (64-bit)`
* OS:  Manjaro-Arch-Linux `v18.0.2`
* Stack trace (in case of a JS error):
  ```js
    index.js:1452 Warning: Invalid value for prop `warn` on <form> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
        in form (created by TabbedForm)
        in TabbedForm (created by WithStyles(TabbedForm))
        in WithStyles(TabbedForm) (created by Form(WithStyles(TabbedForm)))
        in Form(WithStyles(TabbedForm)) (created by Connect(Form(WithStyles(TabbedForm))))
        in Connect(Form(WithStyles(TabbedForm))) (created by ReduxForm)
        in ReduxForm (created by Context.Consumer)
        in translate(ReduxForm) (created by Connect(translate(ReduxForm)))
        in Connect(translate(ReduxForm)) (created by Route)
        in Route (created by withRouter(Connect(translate(ReduxForm))))
        in withRouter(Connect(translate(ReduxForm))) (at users.js:246)
        in div (created by Paper)
        in Paper (created by WithStyles(Paper))
        in WithStyles(Paper) (created by Card)
        in Card (created by WithStyles(Card))
        in WithStyles(Card) (created by CreateView)
        in div (created by CreateView)
        in CreateView (created by CreateController)
        in CreateController (created by Context.Consumer)
        in translate(CreateController) (created by Connect(translate(CreateController)))
        in Connect(translate(CreateController)) (created by Create)
        in Create (created by WithStyles(Create))
        in WithStyles(Create) (at users.js:245)
        in UserCreate (created by WithPermissions)
        in WithPermissions (created by Connect(WithPermissions))
        in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
        in getContext(Connect(WithPermissions)) (created by Route)
        in Route (created by Resource)
        in Switch (created by Resource)
        in Resource (created by Connect(Resource))
        in Connect(Resource) (at App.js:40)
        in Route (created by RoutesWithLayout)
        in Switch (created by RoutesWithLayout)
        in RoutesWithLayout (created by Route)
        in div (created by Layout)
        in main (created by Layout)
        in div (created by Layout)
        in div (created by Layout)
        in Layout (created by WithStyles(Layout))
        in WithStyles(Layout) (created by Route)
        in Route (created by withRouter(WithStyles(Layout)))
        in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
        in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
        in MuiThemeProvider (created by LayoutWithTheme)
        in LayoutWithTheme (created by Route)
        in Route (created by CoreAdminRouter)
        in Switch (created by CoreAdminRouter)
        in div (created by CoreAdminRouter)
        in CoreAdminRouter (created by Connect(CoreAdminRouter))
        in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
        in getContext(Connect(CoreAdminRouter)) (created by Route)
        in Route (created by CoreAdmin)
        in Switch (created by CoreAdmin)
        in Router (created by ConnectedRouter)
        in ConnectedRouter (created by CoreAdmin)
        in TranslationProviderView (created by Connect(TranslationProviderView))
        in Connect(TranslationProviderView) (created by CoreAdmin)
        in Provider (created by CoreAdmin)
        in CoreAdmin (created by withContext(CoreAdmin))
        in withContext(CoreAdmin) (at App.js:35)
        in App (at src/index.js:7)
    ```

**Comment by fzaninotto** [comment] 2019-02-22 18:53
Hiding the warning isn't a big deal (it's just a matter of adding the `warn` key in the `sanitizeRestProps()` function in both `SimpleForm` and `TabbedForm`). But that won't be enough to display the warnings under each field.

Currently, the react-admin Inputs components don't show the warnings, only the errors. Displaying warnings requires that we add that functionality to all inputs.

I'm marking this as an enhancement. As we don't need it for our own projects, the core team won't implement it ourselves. A PR from the community is welcome!

**Comment by deksden** [comment] 2019-05-07 18:01
Will be cool to mark it as “help wanted”!

**Comment by fzaninotto** [comment] 2019-05-07 18:20
Every issue in this issue tracker is "help wanted". Feel free to give a hand.

**Comment by fzaninotto** [comment] 2019-07-26 12:01
Duplicate of #1000

**Closed by fzaninotto** 2019-07-26 12:01 UTC
Labels: enhancement, good first issue
