### ISSUE TITLE
Issue Description: DataGrid Hides Header When No Results Match Filters

### ISSUE THREAD

**Issue by Louay24** [marmelab/react-admin#10354] opened 2024-11-15 13:25 UTC
## Is your feature request related to a problem? Please describe.
When using the DataGrid component in a React-Admin application, applying filters that result in no matching data causes the entire grid, including the header, the custom search input, and filters, to disappear. Instead, the grid is replaced by a single "No results" message. This behavior is confusing for users as it removes the visual structure of the list, including column headers and active filters.

This makes it difficult for users to adjust or remove filters because the context provided by the column headers and visible filters is lost.

## Describe the solution you'd like
When no data matches the filters:

* Keep the DataGrid header (column names) visible.
* Maintain the custom search input and filter components in their usual positions.
* Display a placeholder row (e.g., "No data available") within the grid itself to indicate that there are no results while preserving the overall structure.
* This approach provides a better user experience by showing the grid's context and making it easier to adjust filters to display results.

## Describe alternatives you've considered
* Injecting Placeholder Data
Pass a dummy object (e.g., { id: 'no-data', isPlaceholder: true }) into the data array when data.length === 0. However, this requires additional logic to manage placeholder rows and might feel like a workaround rather than a proper solution.

* Customizing the ListContextProvider
Override the ListContextProvider to modify the data passed to DataGrid. While this is more robust, it introduces extra complexity in managing the context.

* Building a Custom DataGrid Component
Develop a custom implementation of DataGrid to handle empty states. Although this provides full control, it requires significant effort and reduces the benefit of using React-Admin’s pre-built components.

**Comment by fzaninotto** [comment] 2024-11-15 13:30
The Datagrid headers contain no details about the filters. A assume you've customized the Datagrid Header to add filtering capabilities there, which isn't something that we support. 

That being said, you can customize the "No results" component using the [`<Datagrid empty>`](https://marmelab.com/react-admin/Datagrid.html#empty) prop, e.g., to pass a custom datagrid header. 

So I'm closing this issue as it's not a bug and there is a workaround.

**Closed by fzaninotto** 2024-11-15 13:30 UTC

**Comment by djhi** [comment] 2024-11-15 13:32
We could also support passing `false` to `empty` like we do for many props, no?

**Comment by fzaninotto** [comment] 2024-11-15 15:23
So, just reuse the same custom headers in your custom datagrid and the empty component? 

Anyway, as I said we don't support adding filtering capabilities to the datagrid headers, so you'll have to figure out a solution on your own.

**Comment by Louay24** [comment] 2024-11-15 16:01
the custom headers have inputs and the inputs have values in it so when i reuse the custom headers im empty the values of inputs in custom datagrid will be removed

**Comment by Louay24** [comment] 2024-11-21 08:40
@slax57 this won't help in my case because Empty is rendering another component instead of the actual header. This causes it to remove the values of custom filters in the headers, making it useless to keep the header in this case. We are essentially returning to the same problem of deleting filter values.

but i found another solution . i created a hook called useNoDataGridProps this checks if the list has noDate it overrides the data by one null element  and i render custom field is case row has no id 

`import { FunctionField, ListNoResults, useListController } from "react-admin";
import { dataGridWithNoDataStyles } from "../components/sharedStyles/dataGridStyles";

export const useNoDataGridProps = () => {
  const { data } = useListController();

  return data?.length === 0
    ? {
        total: 1,
        data: [{ id: null }],
        isRowSelectable: (record) => !!record.id,
        rowSx: dataGridWithNoDataStyles,
      }
    : {};
};
export const noDataGridDataRender = (
  <FunctionField
    render={(row) => {
      return !row.id ? <ListNoResults /> : undefined;
    }}
  />
);
`

` <Datagrid
      sort={{ field: "createdAt", order: "DESC" }}
      {...props}
      header={<CustomDatagridHeader />}
      {...useNoDataGridProps()}
    >
      {noDataGridDataRender}

      <TextField
        source="reference"
        label={
          <FilterableHeaderField
            label={t("ra.app.tournament_name")}
            source="reference"
            filterType="simple"
          />
        }
      />
      <TextField
        source="description"
        label={
          <FilterableHeaderField
            label={t("ra.app.description")}
            source="description"
            filterType="simple"
          />
        }
      />
      <FunctionField
        source="startDate"
        render={(record) => {
          return convertUTCtoUAE(record.startDate);
        }}
        label={
          <FilterableHeaderField
            label={t("ra.app.startDate")}
            source="startDate"
            type="date"
          />
        }
      />
      <FunctionField
        source="endDate"
        render={(record) => {
          return convertUTCtoUAE(record.endDate);
        }}
        label={
          <FilterableHeaderField
            label={t("ra.app.endDate")}
            source="endDate"
            type="date"
          />
        }
      />
      <DeleteButton />
    </Datagrid>`

![Image](https://github.com/user-attachments/assets/d014312e-2c34-4063-a00c-ca43b61d0551)
this is the final result
