### ISSUE TITLE
"Using a Function As <Admin> Child" gives "not assignable to type 'ReactNode'.ts(2322)" with @types/react 18

### ISSUE THREAD

**Issue by psam44** [marmelab/react-admin#9642] opened 2024-02-05 16:58 UTC
A typescript error appears on:
```
<Admin ...>
  {fetchResources}
</Admin>
```
```
Type '(permissions: Permissions) => JSX.Element[]' is not assignable to type 'ReactNode'.ts(2322)
App.tsx(119, 9): Did you mean to call this expression?
const fetchResources: (permissions: Permissions) => JSX.Element[]
```
 This happens with an upgrade to `@types/react@18.2.51`

It was fine before, with `@types/react@17.0.43`

**Workaround:**

* (more to prouve the origin of the problem):
Add into `node_modules\@types\react\index.d.ts`, for `type ReactNode =`:
```
        | {}
```
This option was removed in v18, as stated in [Remove {} from ReactFragment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56026) 
* Mute the error:
```
<Admin ...>
  {
    // @ts-expect-error
    fetchResources}
</Admin>
```

**Environment**

* React-admin version: 4.16.9
* React version: 18.2.0
* typescript@5.3.3

**Comment by slax57** [comment] 2024-02-06 10:33
Thanks for the report.
Can you please provide a [reproduction sandbox](https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by psam44** [comment] 2024-02-06 16:41
I did nothing, just clicked on your link and opened the index.tsx file:
![image](https://github.com/marmelab/react-admin/assets/537094/99fce07d-821f-4c50-ad29-ac5e04e1ea3c)

**Comment by psam44** [comment] 2024-02-06 17:08
May be a hint, with what is usually `children: AdminChildren`, in ra-ui-materialui\src\theme\ThemeProvider.tsx:
```
export interface ThemeProviderProps {
    children: ReactNode;
```
and so on, deeper in @mui/material/styles.

**Comment by slax57** [comment] 2024-02-06 17:43
Indeed, it can be reproduced straight from the sandbox! :sweat_smile: 
We'll look into it, thanks!

It's also worth mentioning that this may have been fixed already on the `next` branch, since we upgraded our monorepo to use React 18 for the upcoming v5.

We need to check whether this fix could be applied to the `master` branch too, or if it requires a breaking change.

**Comment by djhi** [comment] 2024-07-23 13:48
I don't see this issue in v5 so I'm closing this issue. Feel free to reopen if needed

**Closed by djhi** 2024-07-23 13:48 UTC
Labels: bug
