### ISSUE TITLE
index.js:1406 Total from response is not a number. Please check your dataProvider or the API.

### ISSUE THREAD

**Issue by kylinai** [marmelab/react-admin#4519] opened 2020-03-13 02:56 UTC
if (
        action.meta.fetchResponse === CREATE ||
        action.meta.fetchResponse === DELETE ||
        action.meta.fetchResponse === DELETE_MANY ||
        action.meta.fetchResponse === UPDATE ||
        action.meta.fetchResponse === UPDATE_MANY
    ) {
        // force refresh of all lists because we don't know where the
        // new/deleted/updated record(s) will appear in the list
        return initialState;
    }

the console reported the following error after cachedRequests is cleaned from store:
Total from response is not a number. Please check your dataProvider or the API.

**Comment by fzaninotto** [comment] 2020-03-13 08:47
Can you please describe the actions that lead to this error, and even better, provide a CodeSandbox, ax explained in the issue template?

**Comment by meastp** [comment] 2020-03-13 09:37
This might be a duplicate of #4337 which has been reproduced in a sandbox.

**Comment by JulienMattiussi** [comment] 2020-03-23 09:18
Thanks for rteporting this.
As pointed, it's a dupplicate of #4337

The bug was introduced in 3.3.0
It's happens only if undoable={true]
We're working on it

As a dupplicate, I close this one.

**Closed by JulienMattiussi** 2020-03-23 09:18 UTC
Labels: needs more info
