### ISSUE TITLE
CRM demo unable to clear filter form when clicking ⦻ in Firefox

### ISSUE THREAD

**Issue by smeng9** [marmelab/react-admin#7559] opened 2022-04-15 18:27 UTC
**What you were expecting:**

I expect clicking the cross button in filter form should clear the filter

**What happened instead:**

Clicking on the cross button in filter form does not clear the filter
Only clicking on the filter item text clears the filter
This only happens in Firefox (Chrome and Edge seems work fine)

**Steps to reproduce:**

Go to https://marmelab.com/react-admin-crm/#/contacts?filter=%7B%22sales_id%22%3A0%2C%22status%22%3A%22cold%22%2C%22last_seen_lte%22%3A%222022-04-01T05%3A00%3A00.000Z%22%7D&order=DESC&page=1&perPage=25&sort=last_seen
Click on the cross button next to `Before this moth` and the filter cannot be cleared. (Only Firefox has this issue)
Click on the `Before this moth` text clears the filter.

**Other information:**

**Environment**

* React-admin version: 4.0.0
* Last version that did not exhibit the issue (if applicable):
* React version: 
* Browser: Firefox 99
* Stack trace (in case of a JS error):

**Comment by slax57** [comment] 2022-04-19 09:10
Hi!
I'm unable to reproduce with Firefox version 99.0.1 (64 bits) on Windows.
What OS do you use?
Also note that copy pasting the full URL you provided does not enable the `Before this moth` filter when I arrive on the page, I have to enable it manually. I don't know if this is linked.

**Comment by smeng9** [comment] 2022-04-19 16:44
I will attach with a video


https://user-images.githubusercontent.com/38666763/164053957-6e2fb190-11ca-4e6e-b7a9-d1c16d249177.mp4

**Comment by smeng9** [comment] 2022-04-19 20:03
> Also note that copy pasting the full URL you provided does not enable the Before this moth filter when I arrive on the page, I have to enable it manually. I don't know if this is linked.

This is indeed a very weird problem. I cannot reproduce it locally on my computer (any setup either Firefox, Chrome, Edge), when I click the link the filter will always be applied. However, I can reproduce it here using Linux and Firefox 81.0
https://front.comparium.app/livetesting

**Comment by slax57** [comment] 2022-04-20 09:49
I asked a colleague of mine using Ubuntu with Firefox 99 and he doesn't reproduce either.
Can you try clearing you local storage? Might have a residual value in there.

**Comment by smeng9** [comment] 2022-04-20 16:19
I tried to use private browsing mode and the issues seems disappeared.

**Comment by smeng9** [comment] 2022-04-20 16:28
Hi @slax57, This may be likely a race condition just happened on my computer, and may be hard to trigger somewhere else?

I noticed in the code there are two toggle filters 
https://github.com/marmelab/react-admin/blob/bfa79a541b6f60be346c9b9895158de3c0a26750/packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx#L193
and 
https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/filter/FilterListItem.tsx#L173

Is possible that the filter is toggled twice using a different filter state? e.g. filter on -> filter off -> filter on?

**Comment by smeng9** [comment] 2022-04-20 18:38
![oie_wEuwVL03eoTM](https://user-images.githubusercontent.com/38666763/164298948-3cb18a3b-0f22-48bb-8eaa-c0ac2a748318.png)

![imageedit_1_2250438296](https://user-images.githubusercontent.com/38666763/164298963-ae93287b-36ee-4d97-820a-39eddd7f2037.png)

Click on red or blue region will clear the filter.
Click on green region does not clear the filter. This should be a race condition. The onClick seems need to stop propagation during bubbling.

**Comment by slax57** [comment] 2022-04-21 07:04
I still can't figure out why I can't reproduce on my end, even knowing where to click.
Anyway, your analysis makes sense to me, so I approved your PR. Let's just wait for @djhi to approve it as well 🙂

**Comment by djhi** [comment] 2022-04-21 08:54
Fixed by #7574

**Closed by djhi** 2022-04-21 08:54 UTC
Labels: bug

**Comment by smeng9** [comment] 2022-04-21 16:24
Hi @slax57 Did you figure out the other issue you mentioned? 

> Also note that copy pasting the full URL you provided does not enable the Before this moth filter when I arrive on the page, I have to enable it manually.

The filter is automatically enabled on my side as it is coded in url state.

**Comment by slax57** [comment] 2022-04-25 08:58
@smeng9 I believe this might be linked to the localstorage as well. The problem might come from the fact that this filter implies today's date. The quick filter is only marked active if the filter currently applied is exactly the same. In your url, the date was a few days early, that's why I think it is normal for the filter to be marked as inactive. The fact that is was active on your end might come from matching residual data.
If you clear localstorage, refresh the webpage, and try pasting your original link again, I believe you will notice the same behaviour as me.
