### ISSUE TITLE
[Typescript - DatagridCell]: Type '"height"' is not assignable to....

### ISSUE THREAD

**Issue by ValentinH** [marmelab/react-admin#5783] opened 2021-01-15 11:11 UTC
**What you were expecting:**
No compilation error.

**What happened instead:**
I get a compilation error on a `react-admin` internal type:
```
Type '"height"' is not assignable to type '"color" | "translate" | "padding"...
```

This is on the `node_modules/react-admin/node_modules/ra-ui-materialui/lib/list/datagrid/DatagridCell.d.ts` file.

![image](https://user-images.githubusercontent.com/2678610/104718203-d0e76280-572a-11eb-8dbd-d3b02f4599a7.png)

**Environment**

* React-admin version: 3.11.2
* Last version that did not exhibit the issue (if applicable): I was using 3.8 before so no TS definitions were available
* React version: 16.14 (also tested with 17)
* Browser: N/A
* Stack trace (in case of a JS error): N/A

**Comment by djhi** [comment] 2021-01-20 08:51
There is no `height` prop indeed. Can you please check your material-ui packages versions? It would also help us debug this if you could provide a codesandbox showing the issue

**Comment by ValentinH** [comment] 2021-01-20 09:23
I'm using `@material-ui/core@4.11.2` and `typescript@4.1.3`.

As far as I understand, the `height` (and `width`) props are coming from the `HTMLTableCellElement` used [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/list/datagrid/DatagridCell.tsx#L7). This interface does contain `width` and `height` but they are deprecated:
![image](https://user-images.githubusercontent.com/2678610/105153488-c9e49980-5b08-11eb-8126-fcc4665ff00e.png)

I created this sandbox where you can CMD+click on `DatagridCell` to see the issue (wait for the types to be installed): https://codesandbox.io/s/gallant-rgb-gz1uh?file=/src/App.tsx

**Comment by fzaninotto** [comment] 2021-04-13 21:00
The codesandbox link is dead, and we still can't reproduce the bug, so I'm closing this issue. Feel free to reopen it if you can provide another link to a Codesandbox showing the issue on a recent version of react-admin.

**Closed by fzaninotto** 2021-04-13 21:00 UTC
Labels: needs more info
