### ISSUE TITLE
After create

### ISSUE THREAD

**Issue by bgnq** [marmelab/react-admin#2236] opened 2018-08-28 16:22 UTC
Hello

**What you were expecting:**
After create a ressource, edit page displayed but without informations

**What happened instead:**
I have no data, after a reload I see my data, but the title form is correctly display

After create : 
![screen shot 2018-08-28 at 18 19 37](https://user-images.githubusercontent.com/13726591/44736300-25a0c900-aaef-11e8-909a-c65a7f59c0a1.png)

After reload : 
![screen shot 2018-08-28 at 18 19 48](https://user-images.githubusercontent.com/13726591/44738003-e032ca80-aaf3-11e8-9f07-013569c3c7f4.png)

**Related code:**

```
import React from 'react';
import {
    translate,
    Datagrid,
    Edit,
    EditButton,
    List,
    SimpleForm,
    TextField,
    TextInput,
    CreateButton,
    CardActions,
    Create,

    required
} from 'react-admin';
import withStyles from '@material-ui/core/styles/withStyles';
import Icon from '@material-ui/icons/LocalParking';


export const ParkingIcon = Icon;

const listStyles = {
    name: { padding: '0 12px 0 25px' },
};

const editStyles = {
    first_name: { display: 'inline-block' },
    last_name: { display: 'inline-block', marginLeft: 32 },
    email: { width: 544 },
    address: { maxWidth: 544 },
    zipcode: { display: 'inline-block' },
    city: { display: 'inline-block', marginLeft: 32 },
    comment: {
        maxWidth: '20em',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
};


const ParkingActions = ({
    basePath,
    currentSort,
    displayedFilters,
    exporter,
    filters,
    filterValues,
    resource,
    showFilter,
    bulkActions,
    selectedIds,
    onUnselectItems,
}) => {
    return (
        <CardActions>
            {bulkActions && React.cloneElement(bulkActions, {
                basePath,
                filterValues,
                resource,
                selectedIds,
                onUnselectItems,
            })}
            <CreateButton basePath={basePath} />
        </CardActions>
    );
}



export const ParkingList = withStyles(listStyles)(({ classes, ...props }) => (
    <List
        {...props}
        sort={{ field: 'name', order: 'ASC' }}
        actions={<ParkingActions />}
    >
        <Datagrid>
            <TextField source="name" className={classes.name} />
            <EditButton />
        </Datagrid>
    </List>
));

const ParkingTitle = translate(({ record, translate }) => (
    <span>
        {translate('resources.parkings.name', { smart_count: 1 })} &quot;{
        record.name
    }&quot;
    </span>
));

export const ParkingEdit = props => (
    <Edit title={<ParkingTitle />} {...props}>
        <SimpleForm>
            <TextInput source="name" validate={required()}/>
        </SimpleForm>
    </Edit>
);

export const ParkingCreate = withStyles(editStyles)(({ classes, ...props }) => (
    <Create {...props}>
        <SimpleForm>
            <TextInput source="name" validate={required()}/>
        </SimpleForm>
    </Create>
));
```

**Environment**

* React-admin version: last
* React version: last
* Browser: Chrome

Thanks !!

**Comment by RWOverdijk** [comment] 2018-09-12 19:52
@bgnq Did you ever figure it out? I'm facing the same.

**Comment by bgnq** [comment] 2018-09-13 05:04
> @bgnq Did you ever figure it out? I'm facing the same.

=> no, I make a redirection to the list after create :(

**Comment by RWOverdijk** [comment] 2018-09-13 08:20
That's not good... I'll try to figure it out and if I do post the solution here.

**Comment by Dragonqos** [comment] 2018-09-17 14:52
I see the same behavior on version 2.3.1

**Comment by fzaninotto** [comment] 2018-09-19 21:06
Thanks for reporting.

Even though #2324, which is a duplicate of this one, was opened later, we've started tracking the changes there, so I'm closing this one.

**Closed by fzaninotto** 2018-09-19 21:06 UTC
