### ISSUE TITLE
Save in localstorage

### ISSUE THREAD

**Issue by jgabriele** [marmelab/react-admin#6068] opened 2021-03-19 16:44 UTC
**Is your feature request related to a problem? Please describe.**
When navigating through different list views and after refresh, the list state is lost (rows per page, current page).

For example:
- Go to the users resource list. Default rows per page is 10.
- Set rows per page to 25. (side note: the url gets updated with `?perPage=25`)
- Go to the books resource list (actually anywhere else)
- Go back to the users resource list. The settings are kept and we can still see 25 results. (side note: the urls lost the list state)
- Refresh the page. The list shows 10 results and not 25.

**Describe the solution you'd like**
We could keep, per resource, the list settings in localStorage. We would then use those settings as defaults when the list view of that resource is displayed and there is no query parameter in the url (we would merge url query params with those defaults).

**Describe alternatives you've considered**
Rebuilding the list pagination myself to include this feature would work but seems overkill.

**Comment by fzaninotto** [comment] 2021-03-19 17:12
This can be achieved in userland via a custom Redux middleware. So anyone can create an extension for react-admin to offer that feature. Not sure we want to address it in core, though.

**Comment by jgabriele** [comment] 2021-03-19 17:25
Oh, I see. Do you have an example of such middleware that was created for react-admin?

**Comment by fzaninotto** [comment] 2021-03-19 17:38
also, duplicate of #3521

**Closed** 2021-03-22 07:42 UTC
Labels: enhancement
