### ISSUE TITLE
AutocompleteInput not recognising prop optionText

### ISSUE THREAD

**Issue by ghidoras** [marmelab/react-admin#6257] opened 2021-05-07 10:47 UTC
**What you were expecting:**
AutocompleteInput `optionText` prop type should be recognised.

**What happened instead:**
`optionText` type not recognised which is documented here https://marmelab.com/react-admin/doc/3.12/Inputs.html .

**Steps to reproduce:**
Just use it as below:
```
    <ReferenceInput
      label="Label"
      perPage={12}
      source={"source"}
      reference={resources.archives}
      filterToQuery={q => ({ name: q })}
    >
      <AutocompleteInput
        optionText={choice => choice.id ? `${choice.name}` : ''}
      />
    </ReferenceInput>
```

**Related code:**
See above.

Some more details here https://stackoverflow.com/questions/67372039/react-admin-autocompleteinput-not-recognising-prop-optiontext?noredirect=1#comment119098229_67372039 

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.12
* Last version that did not exhibit the issue (if applicable): NA
* React version: 16.8.5
* Browser: NA
* Stack trace (in case of a JS error): NA

**Comment by djhi** [comment] 2021-05-12 07:41
Thanks for the report. I can't reproduce it on the simple example though after modifying the `TagReferenceInput` so that it has a function for `optionText`. 
Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment] 2021-06-17 20:23
No news for some time, closing.

**Closed by fzaninotto** 2021-06-17 20:23 UTC
Labels: needs more info
