### ISSUE TITLE
import error when updating from 3.0.0-beta.0 to 3.0.0-beta.2

### ISSUE THREAD

**Issue by js-chris** [marmelab/react-admin#3850] opened 2019-10-21 10:15 UTC
**What you were expecting:**
Normal starting of react-admin 3.0.0-beta.2 after npm update from 3.0.0-beta.0

**What happened instead:**
Got the error:
./node_modules/ra-ui-materialui/esm/form/TabbedForm.js
Attempted import error: 'sanitizeEmptyValues' is not exported from 'ra-core'.

**Steps to reproduce:**
Update from 3.0.0-beta.0 to 3.0.0-beta.2

**Environment**

* React-admin version: 3.0.0-beta.2
* React version: 16.10.2

**Comment by fzaninotto** [comment] 2019-10-21 12:40
Hi, `ra-core` 3.0.0-beta.2 does export `sanitizeEmptyValues`, so your error is weird. Would you, by any chance, have *another* ra- package (like `ra-language-french`, `ra-data-jsonserver`, etc) not upgraded to beta-1?

**Comment by fzaninotto** [comment] 2019-10-21 12:57
Note that I can't reproduce your issue with a simple `EditGuesser`, so I really suspect a problem on your side with multiple versions of ra-core.

**Comment by js-chris** [comment] 2019-10-21 19:20
Thanks for your reply! 
I will recheck that and get back to you.

**Comment by js-chris** [comment] 2019-10-22 12:14
Donno, I was somewhere trapped in dependency hell. 
I managed to make it work, after installing everything step-by.step, starting with react-admin.

But after all, I still had an error that "@testing-library/react" somewhere in ra-core is not installed. After installing it, everything works now. 

Thanks for supporting me
Chris

**Comment by fzaninotto** [comment] 2019-10-22 13:47
Thanks for the feedback. The @testing-library/react bug has been solved elsewhere (#3851), so I'm closing this bug.

**Closed by fzaninotto** 2019-10-22 13:47 UTC
Labels: awaiting more info
